# API Last fm

In [21]:
import requests
import json

In [22]:
cliente = "73b20cda4ec1a72f5360723b9f3be682"
secreto = "058ba5ffb6b9faa3ae5fd9a395402793"

In [23]:
url_api = "http://ws.audioscrobbler.com/2.0/"

## Hacemos una función para llamar a la api

In [24]:
def llamar_lastfm_api(method, artist_name, cliente):

        params = {'method': method,'artist': artist_name,'api_key': cliente,'format': 'json'}

        response = requests.get(url_api, params=params)


        if response.status_code == 200:
            return response.json()
        else:
            print(f"Error {response.status_code}: No se pudo obtener la información para el método {method}")
            return

## Hacemos un bucle for para iterar por cada artista -- en esta prueba lo hacemos con prints de control porque son solo cuatro artistas

In [25]:
artistas_a_consultar_prueba = ["Radiohead", "Pink Floyd", "Led Zeppelin", "Queen",  "The Beatles"]
lista_artistas_prueba = []


for nombre_artista in artistas_a_consultar_prueba:
    print(f"--- Consultando: {nombre_artista} ---")
    
    datos_artista = llamar_lastfm_api('artist.getinfo', nombre_artista, cliente)  
    
    
    if datos_artista and 'artist' in datos_artista:
        
        artista_data = datos_artista['artist']
        
        
        oyentes = artista_data.get('stats', {}).get('listeners', 'arista no encontrado') 
        reproducciones = artista_data.get('stats', {}).get('playcount', 'N/D')
        
        bio_content = artista_data.get('bio', {}).get('content', '')
        
        if not bio_content or bio_content.strip() == "":
            bio_resumen = 'biografia no encontrada'
        else:
            bio_resumen = artista_data.get('bio', {}).get('summary')
        
        lista_artistas_dict = {'artista': artista_data.get('name', nombre_artista),'oyentes': oyentes, 'reproducciones': reproducciones, 'bio_resumen': bio_resumen}
        lista_artistas_prueba.append(lista_artistas_dict)
        
        print(f"Datos de {nombre_artista} procesados y guardados.")
           
    else:
        print(f"No se pudo obtener información de {nombre_artista}")

--- Consultando: Radiohead ---
Datos de Radiohead procesados y guardados.
--- Consultando: Pink Floyd ---
Datos de Pink Floyd procesados y guardados.
--- Consultando: Led Zeppelin ---
Datos de Led Zeppelin procesados y guardados.
--- Consultando: Queen ---
Datos de Queen procesados y guardados.
--- Consultando: The Beatles ---
Datos de The Beatles procesados y guardados.

In [26]:
lista_artistas_prueba

[{'artista': 'Radiohead',
  'oyentes': '7923689',
  'reproducciones': '1271778153',
  'bio_resumen': 'Radiohead is an English rock band formed in Abingdon, Oxfordshire, in 1985. The band consists of Thom Yorke (vocals, guitar, piano, keyboards); brothers Jonny Greenwood (guitar, keyboards, other instruments) and Colin Greenwood (bass); Ed O\'Brien (guitar, backing vocals); and Philip Selway (drums, percussion). Since 1994, they have frequently collaborated with producer Nigel Godrich and cover artist Stanley Donwood. Radiohead are noted for their experimental approach, which has influenced the development of alternative rock. <a href="https://www.last.fm/music/Radiohead">Read more on Last.fm</a>'},
 {'artista': 'Pink Floyd',
  'oyentes': '5342099',
  'reproducciones': '583090578',
  'bio_resumen': 'Pink Floyd was an English rock band formed in London in 1965. Gaining an early following as one of the first British psychedelic groups, they were distinguished by their extended compositions, sonic experimentation, philosophical lyrics and elaborate live shows. They became a leading band of the progressive rock genre, cited by some as the greatest progressive rock band of all time.\n\nPink Floyd were founded in 1965 by Syd Barrett (guitar, lead vocals) <a href="https://www.last.fm/music/Pink+Floyd">Read more on Last.fm</a>'},
 {'artista': 'Led Zeppelin',
  'oyentes': '4794943',
  'reproducciones': '330352025',
  'bio_resumen': 'Led Zeppelin was a hard rock band formed in London in 1968. The group comprised vocalist Robert Plant, guitarist Jimmy Page, bassist and keyboardist John Paul Jones, and drummer John Bonham. With a heavy, guitar-driven sound, they are cited as one of the progenitors of hard rock and heavy metal, although their style drew from a variety of influences, including blues and folk music. Led Zeppelin have been credited as significantly impacting the nature of the music industry <a href="https://www.last.fm/music/Led+Zeppelin">Read more on Last.fm</a>'},
 {'artista': 'Queen',
  'oyentes': '6981572',
  'reproducciones': '406171817',
  'bio_resumen': 'Queen is a British rock band formed in London in 1970 by Freddie Mercury (lead vocals, piano), Brian May (guitar, vocals), and Roger Taylor (drums, vocals), later joined by John Deacon (bass). Their earliest works were influenced by progressive rock, hard rock, and heavy metal, but the band gradually ventured into more conventional and radio-friendly styles by incorporating elements of arena rock and pop rock.\n\nBefore forming Queen, May and Taylor had played together in the band Smile. <a href="https://www.last.fm/music/Queen">Read more on Last.fm</a>'},
 {'artista': 'The Beatles',
  'oyentes': '6291060',
  'reproducciones': '1045532298',
  'bio_resumen': 'The Beatles was an English rock band formed in Liverpool, Lancashire in 1960. With the line-up comprising John Lennon, Paul McCartney,  George Harrison, and Ringo Starr, they are regarded as the most popular and influential band of all time. The group were integral to the development of 1960s counterculture and popular music\'s recognition as an art form. Rooted in skiffle, beat and 1950s rock and roll, their sound incorporated elements of classical <a href="https://www.last.fm/music/The+Beatles">Read more on Last.fm</a>'}]

In [45]:

""" datos_artista = llamar_lastfm_api('artist.getinfo', nombre_artista, cliente)  
    
if datos_artista and 'artist' in datos_artista:
        
    artista = datos_artista['artist']
    oyentes = artista.get('stats', {}).get('listeners')
    reproducciones = artista.get('stats', {}).get('playcount')
        
    print(f"--- Detalles de {nombre_artista} ---")
    print(f"Oyentes (Last.fm): {oyentes}")
    print(f"Reproducciones (Last.fm): {reproducciones}")

    if datos_artista['artist']['bio']['content'] == "":
        print('biografia no encontrada')
    
    else:
        bio_resumen = artista.get('bio', {}).get('summary')
        print(f"Resumen de Biografía:\n{bio_resumen}...")

    # lista_artistas_dict = {'artista': artista, 'oyentes': oyentes, 'reproducciones': reproducciones, 'bio_resumen': bio_resumen}
    # lista_artistas.append(lista_artistas_dict)
           
else:
    print("No se pudo obtener información del artista.")"""

' datos_artista = llamar_lastfm_api(\'artist.getinfo\', nombre_artista, cliente)  \n    \nif datos_artista and \'artist\' in datos_artista:\n        \n    artista = datos_artista[\'artist\']\n    oyentes = artista.get(\'stats\', {}).get(\'listeners\')\n    reproducciones = artista.get(\'stats\', {}).get(\'playcount\')\n        \n    print(f"--- Detalles de {nombre_artista} ---")\n    print(f"Oyentes (Last.fm): {oyentes}")\n    print(f"Reproducciones (Last.fm): {reproducciones}")\n\n    if datos_artista[\'artist\'][\'bio\'][\'content\'] == "":\n        print(\'biografia no encontrada\')\n    \n    else:\n        bio_resumen = artista.get(\'bio\', {}).get(\'summary\')\n        print(f"Resumen de Biografía:\n{bio_resumen}...")\n\n    # lista_artistas_dict = {\'artista\': artista, \'oyentes\': oyentes, \'reproducciones\': reproducciones, \'bio_resumen\': bio_resumen}\n    # lista_artistas.append(lista_artistas_dict)\n           \nelse:\n    print("No se pudo obtener información del artista.")'

In [27]:
datos_artista.keys()

dict_keys(['artist'])

In [28]:
datos_artista['artist'].keys()

dict_keys(['name', 'mbid', 'url', 'image', 'streamable', 'ontour', 'stats', 'similar', 'tags', 'bio'])

In [29]:
datos_artista['artist']['bio']

{'links': {'link': {'#text': '',
   'rel': 'original',
   'href': 'https://last.fm/music/The+Beatles/+wiki'}},
 'published': '03 Feb 2006, 06:05',
 'summary': 'The Beatles was an English rock band formed in Liverpool, Lancashire in 1960. With the line-up comprising John Lennon, Paul McCartney,  George Harrison, and Ringo Starr, they are regarded as the most popular and influential band of all time. The group were integral to the development of 1960s counterculture and popular music\'s recognition as an art form. Rooted in skiffle, beat and 1950s rock and roll, their sound incorporated elements of classical <a href="https://www.last.fm/music/The+Beatles">Read more on Last.fm</a>',
 'content': 'The Beatles was an English rock band formed in Liverpool, Lancashire in 1960. With the line-up comprising John Lennon, Paul McCartney,  George Harrison, and Ringo Starr, they are regarded as the most popular and influential band of all time. The group were integral to the development of 1960s counterculture and popular music\'s recognition as an art form. Rooted in skiffle, beat and 1950s rock and roll, their sound incorporated elements of classical music and traditional pop in innovative ways; the band later explored music styles ranging from ballads and Indian music to psychedelia and hard rock. As pioneers in recording, songwriting and artistic presentation, the group revolutionized many aspects of the music industry and were often publicized as leaders of the era\'s youth and socio-cultural movements. \n\nLed by primary songwriters Lennon and McCartney, the Beatles built their reputation playing clubs in Liverpool and Hamburg over three years from 1960, initially with Stuart Sutcliffe playing bass. The core trio of Lennon, McCartney and Harrison, together since 1958, went through a succession of drummers, eventually settling with Pete Best in 1960, who played with them for two years before being replaced with then Rory Storm & The Hurricanes drummer Ringo Starr in 1962. Manager Brian Epstein molded them into a professional act and producer George Martin guided and developed their recordings, greatly expanding their domestic success after their first hit, "Love Me Do", in late 1962. As their popularity grew into the intense fan frenzy dubbed "Beatlemania", the band acquired the nickname "the Fab Four", with Epstein, Martin and other members of the band\'s entourage sometimes given the informal title of "fifth Beatle".\n\nBy early 1964, the Beatles were international stars, leading the "British Invasion" of the United States pop market and breaking numerous sales records. They soon made their film debut with A Hard Day\'s Night (1964). From 1965 onwards, they produced increasingly innovative recordings, including the albums Rubber Soul (1965), Revolver (1966) and Sgt. Pepper\'s Lonely Hearts Club Band (1967), and enjoyed further commercial success with The Beatles (also known as "the White Album", 1968) and Abbey Road (1969). In 1968, they founded Apple Corps, a multi-armed multimedia corporation that continues to oversee projects related to the band\'s legacy. After the group\'s break-up in 1970, all four members enjoyed success as solo artists. Lennon was shot and killed in December 1980, and Harrison died of lung cancer in November 2001. McCartney and Starr remain musically active.\n\nThe Beatles are the best-selling music act of all time, with estimated sales of 600 million units worldwide. They hold the record for most number-one albums on the UK Albums Chart, most number-one hits on the Billboard Hot 100 chart, and most singles sold in the UK. The group were inducted into the Rock and Roll Hall of Fame in 1988, and all four main members were inducted individually between 1994 and 2015. In 2008, the group topped Billboard\'s list of the all-time most successful artists on the Billboard Hot 100. The band received seven Grammy Awards, four Brit Awards, an Academy Award (for Best Original Song Score for the 1970 film Let It Be) and fifteen Ivor Novello Awards. Time magazine named them among the 20th century\'s 100 most important people.\n\nFormer Rolling Stone associate editor Robert Greenfield compared the Beatles to Picasso, as "artists who broke through the constraints of their time period to come up with something that was unique and original "... In the form of popular music, no one will ever be more revolutionary, more creative and more distinctive ..." The British poet Philip Larkin described their work as "an enchanting and intoxicating hybrid of African-American rock-and-roll with their own adolescent romanticism", and "the first advance in popular music since the War".\n\nThey not only sparked the British Invasion of the US, they became a globally influential phenomenon as well. From the 1920s, the US had dominated popular entertainment culture throughout much of the world, via Hollywood films, jazz, the music of Broadway and Tin Pan Alley and, later, the rock and roll that first emerged in Memphis, Tennessee. The Beatles are regarded as British cultural icons, with young adults from abroad naming the band among a group of people that they most associated with UK culture.\n\nTheir musical innovations and commercial success inspired musicians worldwide. Many artists have acknowledged the Beatles\' influence and enjoyed chart success with covers of their songs. On radio, their arrival marked the beginning of a new era; in 1968 the programme director of New York\'s WABC radio station forbade his DJs from playing any "pre-Beatles" music, marking the defining line of what would be considered oldies on American radio. They helped to redefine the album as something more than just a few hits padded out with "filler", and they were primary innovators of the modern music video. The Shea Stadium show with which they opened their 1965 North American tour attracted an estimated 55,600 people, then the largest audience in concert history; Spitz describes the event as a "major breakthrough ... a giant step toward reshaping the concert business". Emulation of their clothing and especially their hairstyles, which became a mark of rebellion, had a global impact on fashion.\n\nAccording to Gould, the Beatles changed the way people listened to popular music and experienced its role in their lives. From what began as the Beatlemania fad, the group\'s popularity grew into what was seen as an embodiment of socio-cultural movements of the decade. As icons of the 1960s counterculture, Gould continues, they became a catalyst for bohemianism and activism in various social and political arenas, fuelling movements such as women\'s liberation, gay liberation and environmentalism. According to Peter Lavezzoli, after the "more popular than Jesus" controversy in 1966, the Beatles felt considerable pressure to say the right things and "began a concerted effort to spread a message of wisdom and higher consciousness".\n\n\nOther commentators such as Mikal Gilmore and Todd Leopold have traced the inception of their socio-cultural impact earlier, interpreting even the Beatlemania period, particularly on their first visit to the US, as a key moment in the development of generational awareness. Referring to their appearance on the Ed Sullivan Show Leopold states: "In many ways, the Sullivan appearance marked the beginning of a cultural revolution ... The Beatles were like aliens dropped into the United States of 1964."\n\nIn 1965, Queen Elizabeth II appointed Lennon, McCartney, Harrison and Starr Members of the Order of the British Empire (MBE). The Beatles won the 1971 Academy Award for Best Original Song Score for the film Let It Be (1970). The recipients of seven Grammy Awards and fifteen Ivor Novello Awards, the Beatles have six Diamond albums, as well as 20 Multi-Platinum albums, 16 Platinum albums and six Gold albums in the US. In the UK, the Beatles have four Multi-Platinum albums, four Platinum albums, eight Gold albums and one Silver album. They were inducted into the Rock and Roll Hall of Fame in 1988.\n\nThe best-selling band in history, the Beatles have sold more than 800 million physical and digital albums as of 2013. They have had more number-one albums on the UK charts, fifteen, and sold more singles in the UK, 21.9 million, than any other act. In 2004, Rolling Stone ranked the Beatles as the most significant and influential rock music artists of the last 50 years. They ranked number one on Billboard magazine\'s list of the all-time most successful Hot 100 artists, released in 2008 to celebrate the US singles chart\'s 50th anniversary. As of 2017, they hold the record for most number-one hits on the Billboard Hot 100, with twenty. The Recording Industry Association of America certifies that the Beatles have sold 178 million units in the US, more than any other artist. They were collectively included in Time magazine\'s compilation of the 20th century\'s 100 most influential people. In 2014, they received the Grammy Lifetime Achievement Award.\n\nThere are two holidays celebrated for the Beatles: Global Beatles Day on 25 June each year. On that date in 1967, the band performed "All You Need Is Love" on television. In 2001, UNESCO created World Beatles Day on 16 January each year. This date has direct relation to the opening of The Cavern Club in 1957.\n\nFive asteroids, 4147 Lennon, 4148 McCartney, 4149 Harrison, 4150 Starr and 8749 Beatles are named after the Beatles. <a href="https://www.last.fm/music/The+Beatles">Read more on Last.fm</a>. User-contributed text is available under the Creative Commons By-SA License; additional terms may apply.'}

In [30]:
datos_artista['artist']['bio']['content']

'The Beatles was an English rock band formed in Liverpool, Lancashire in 1960. With the line-up comprising John Lennon, Paul McCartney,  George Harrison, and Ringo Starr, they are regarded as the most popular and influential band of all time. The group were integral to the development of 1960s counterculture and popular music\'s recognition as an art form. Rooted in skiffle, beat and 1950s rock and roll, their sound incorporated elements of classical music and traditional pop in innovative ways; the band later explored music styles ranging from ballads and Indian music to psychedelia and hard rock. As pioneers in recording, songwriting and artistic presentation, the group revolutionized many aspects of the music industry and were often publicized as leaders of the era\'s youth and socio-cultural movements. \n\nLed by primary songwriters Lennon and McCartney, the Beatles built their reputation playing clubs in Liverpool and Hamburg over three years from 1960, initially with Stuart Sutcliffe playing bass. The core trio of Lennon, McCartney and Harrison, together since 1958, went through a succession of drummers, eventually settling with Pete Best in 1960, who played with them for two years before being replaced with then Rory Storm & The Hurricanes drummer Ringo Starr in 1962. Manager Brian Epstein molded them into a professional act and producer George Martin guided and developed their recordings, greatly expanding their domestic success after their first hit, "Love Me Do", in late 1962. As their popularity grew into the intense fan frenzy dubbed "Beatlemania", the band acquired the nickname "the Fab Four", with Epstein, Martin and other members of the band\'s entourage sometimes given the informal title of "fifth Beatle".\n\nBy early 1964, the Beatles were international stars, leading the "British Invasion" of the United States pop market and breaking numerous sales records. They soon made their film debut with A Hard Day\'s Night (1964). From 1965 onwards, they produced increasingly innovative recordings, including the albums Rubber Soul (1965), Revolver (1966) and Sgt. Pepper\'s Lonely Hearts Club Band (1967), and enjoyed further commercial success with The Beatles (also known as "the White Album", 1968) and Abbey Road (1969). In 1968, they founded Apple Corps, a multi-armed multimedia corporation that continues to oversee projects related to the band\'s legacy. After the group\'s break-up in 1970, all four members enjoyed success as solo artists. Lennon was shot and killed in December 1980, and Harrison died of lung cancer in November 2001. McCartney and Starr remain musically active.\n\nThe Beatles are the best-selling music act of all time, with estimated sales of 600 million units worldwide. They hold the record for most number-one albums on the UK Albums Chart, most number-one hits on the Billboard Hot 100 chart, and most singles sold in the UK. The group were inducted into the Rock and Roll Hall of Fame in 1988, and all four main members were inducted individually between 1994 and 2015. In 2008, the group topped Billboard\'s list of the all-time most successful artists on the Billboard Hot 100. The band received seven Grammy Awards, four Brit Awards, an Academy Award (for Best Original Song Score for the 1970 film Let It Be) and fifteen Ivor Novello Awards. Time magazine named them among the 20th century\'s 100 most important people.\n\nFormer Rolling Stone associate editor Robert Greenfield compared the Beatles to Picasso, as "artists who broke through the constraints of their time period to come up with something that was unique and original "... In the form of popular music, no one will ever be more revolutionary, more creative and more distinctive ..." The British poet Philip Larkin described their work as "an enchanting and intoxicating hybrid of African-American rock-and-roll with their own adolescent romanticism", and "the first advance in popular music since the War".\n\nThey not only sparked the British Invasion of the US, they became a globally influential phenomenon as well. From the 1920s, the US had dominated popular entertainment culture throughout much of the world, via Hollywood films, jazz, the music of Broadway and Tin Pan Alley and, later, the rock and roll that first emerged in Memphis, Tennessee. The Beatles are regarded as British cultural icons, with young adults from abroad naming the band among a group of people that they most associated with UK culture.\n\nTheir musical innovations and commercial success inspired musicians worldwide. Many artists have acknowledged the Beatles\' influence and enjoyed chart success with covers of their songs. On radio, their arrival marked the beginning of a new era; in 1968 the programme director of New York\'s WABC radio station forbade his DJs from playing any "pre-Beatles" music, marking the defining line of what would be considered oldies on American radio. They helped to redefine the album as something more than just a few hits padded out with "filler", and they were primary innovators of the modern music video. The Shea Stadium show with which they opened their 1965 North American tour attracted an estimated 55,600 people, then the largest audience in concert history; Spitz describes the event as a "major breakthrough ... a giant step toward reshaping the concert business". Emulation of their clothing and especially their hairstyles, which became a mark of rebellion, had a global impact on fashion.\n\nAccording to Gould, the Beatles changed the way people listened to popular music and experienced its role in their lives. From what began as the Beatlemania fad, the group\'s popularity grew into what was seen as an embodiment of socio-cultural movements of the decade. As icons of the 1960s counterculture, Gould continues, they became a catalyst for bohemianism and activism in various social and political arenas, fuelling movements such as women\'s liberation, gay liberation and environmentalism. According to Peter Lavezzoli, after the "more popular than Jesus" controversy in 1966, the Beatles felt considerable pressure to say the right things and "began a concerted effort to spread a message of wisdom and higher consciousness".\n\n\nOther commentators such as Mikal Gilmore and Todd Leopold have traced the inception of their socio-cultural impact earlier, interpreting even the Beatlemania period, particularly on their first visit to the US, as a key moment in the development of generational awareness. Referring to their appearance on the Ed Sullivan Show Leopold states: "In many ways, the Sullivan appearance marked the beginning of a cultural revolution ... The Beatles were like aliens dropped into the United States of 1964."\n\nIn 1965, Queen Elizabeth II appointed Lennon, McCartney, Harrison and Starr Members of the Order of the British Empire (MBE). The Beatles won the 1971 Academy Award for Best Original Song Score for the film Let It Be (1970). The recipients of seven Grammy Awards and fifteen Ivor Novello Awards, the Beatles have six Diamond albums, as well as 20 Multi-Platinum albums, 16 Platinum albums and six Gold albums in the US. In the UK, the Beatles have four Multi-Platinum albums, four Platinum albums, eight Gold albums and one Silver album. They were inducted into the Rock and Roll Hall of Fame in 1988.\n\nThe best-selling band in history, the Beatles have sold more than 800 million physical and digital albums as of 2013. They have had more number-one albums on the UK charts, fifteen, and sold more singles in the UK, 21.9 million, than any other act. In 2004, Rolling Stone ranked the Beatles as the most significant and influential rock music artists of the last 50 years. They ranked number one on Billboard magazine\'s list of the all-time most successful Hot 100 artists, released in 2008 to celebrate the US singles chart\'s 50th anniversary. As of 2017, they hold the record for most number-one hits on the Billboard Hot 100, with twenty. The Recording Industry Association of America certifies that the Beatles have sold 178 million units in the US, more than any other artist. They were collectively included in Time magazine\'s compilation of the 20th century\'s 100 most influential people. In 2014, they received the Grammy Lifetime Achievement Award.\n\nThere are two holidays celebrated for the Beatles: Global Beatles Day on 25 June each year. On that date in 1967, the band performed "All You Need Is Love" on television. In 2001, UNESCO created World Beatles Day on 16 January each year. This date has direct relation to the opening of The Cavern Club in 1957.\n\nFive asteroids, 4147 Lennon, 4148 McCartney, 4149 Harrison, 4150 Starr and 8749 Beatles are named after the Beatles. <a href="https://www.last.fm/music/The+Beatles">Read more on Last.fm</a>. User-contributed text is available under the Creative Commons By-SA License; additional terms may apply.'

## Convertimos el CSV de rock en una lista de tuplas para poder trabajarlo

In [31]:
import pandas as pd

In [32]:
df = pd.read_csv("df_rock.csv", index_col=0)

In [33]:
df

,Artista,Género,Tipo,Nombre,Año_Lanzamiento,ID_Spotify
0,Five For Fighting,rock,track,Superman (It's Not Easy),2000,3TwtrR1yNLY1PMPsrGQpOp
1,The Smashing Pumpkins,rock,track,Stand Inside Your Love,2000,3RciEQxS7PxtLqMs7OwRsU
2,The Beatles,rock,track,Day Tripper - Remastered 2015,2000,29b2b96jozyD9GPCkOrVLs
3,Deftones,rock,track,Passenger,2000,7IoK6jZBxY7NMoQPoPXZCF
4,Panchiko,rock,track,D>E>A>T>H>M>E>T>A>L,2000,4sIFi8LpJWPvI5xviWFyA6
...,...,...,...,...,...,...
745,Hombres G,rock,track,Qué soy yo para ti,2004,2vnMY0A72GKY9DJey7bzMd
746,Keane,rock,track,Somewhere Only We Know,2004,2slll7iPbwCD4IwdgcZN69
747,Bunbury,rock,track,Canto... el mismo dolor,2004,1boxzAIByOzRhopCsD6PhG
748,Michael McDonald,rock,track,"Stop, Look, Listen (To Your Heart)",2004,6eKRQdKMtSWnlApt4x2aIX
749,Nek,rock,track,Laura no està,2004,5jbG38paHIeVJc57uXUNYt

In [34]:
df['Artista']

0          Five For Fighting
1      The Smashing Pumpkins
2                The Beatles
3                   Deftones
4                   Panchiko
               ...
745                Hombres G
746                    Keane
747                  Bunbury
748         Michael McDonald
749                      Nek
Name: Artista, Length: 750, dtype: object

In [35]:
artista = df['Artista']

In [41]:
artista_unico = set(artista)

In [42]:
artista_unico

{'10cc',
 '3 Doors Down',
 'A Perfect Circle',
 'AC/DC',
 'ASIAN KUNG-FU GENERATION',
 'Aerosmith',
 'Air Supply',
 'Airbag',
 'Al Stewart',
 'Alaska Y Dinarama',
 'Alfredo Pardo- Spanish Pop',
 'Alter Bridge',
 'Alvin Lee',
 'Andrés Calamaro',
 'Arcade Fire',
 'Aterciopelados',
 'Attaque 77',
 'Audioslave',
 'Avenged Sevenfold',
 'Babasonicos',
 'Ben Harper',
 'Benito Kamelas',
 'Bersuit Vergarabat',
 'Billy Joel',
 'Black Rebel Motorcycle Club',
 'Blur',
 'Bon Jovi',
 'Breaking Benjamin',
 'Bruce Springsteen',
 'Bunbury',
 'Bushido',
 'CAKE',
 'Café Tacvba',
 'Callejeros',
 'Calvin Russell',
 'Catupecu Machu',
 'Celso Piña',
 'Charlie Brown Jr.',
 'Charly García',
 'Cheap Trick',
 'Chris de Burgh',
 'Citizen Cope',
 'Cock Robin',
 'Coti',
 'Counting Crows',
 'Crazy Town',
 'Creed',
 'Crossfade',
 'Cypress Hill',
 'Cómplices',
 'Daryl Hall & John Oates',
 'David Bowie',
 'Deftones',
 'Desert Sessions',
 'Design19',
 'Divididos',
 'Dobie Gray',
 'Donavon Frankenreiter',
 'Dover',
 'Drowning Pool',
 'Duncan Dhu',
 'Eagle-Eye Cherry',
 'Electric Six',
 'Elefante',
 'Elvis Presley',
 'Embrace',
 'Engenheiros Do Hawaii',
 'Eric Clapton',
 'Evanescence',
 'Explosions In The Sky',
 'Five For Fighting',
 'Fleetwood Mac',
 'Foo Fighters',
 'Franz Ferdinand',
 'Gary Moore',
 'Green Day',
 'Gustavo Cerati',
 'HALCALI',
 'HIM',
 'Hombres G',
 'Illya Kuryaki & The Valderramas',
 'Incubus',
 'Indio Solari',
 'Inspector',
 'Interpol',
 'Intoxicados',
 'JAY-Z',
 'Jack Johnson',
 'Jaguares',
 'Jarabe De Palo',
 'Jet',
 'Joe Bonamassa',
 'Journey',
 'Juanes',
 'Jóvenes Pordioseros',
 'Keane',
 'Kula Shaker',
 'La Ley',
 'La Mosca',
 'La Renga',
 'La Unión',
 'La Vela Puerca',
 'La-33',
 'Lamp',
 'Las Pelotas',
 'Lenny Kravitz',
 'Libido',
 'Lifehouse',
 'Limp Bizkit',
 'Linkin Park',
 'Lionel Richie',
 'Lordi',
 'Los Abuelos De La Nada',
 'Los Amantes De Lola',
 'Los Animalitos',
 'Los Auténticos Decadentes',
 'Los Caballeros De La Quema',
 'Los Enanitos Verdes',
 'Los Inhumanos',
 'Los Piojos',
 'Los Rodriguez',
 'Los Tipitos',
 'Madrugada',
 'Mancha De Rolando',
 'Manic Street Preachers',
 'Maná',
 'Maria De Los Angeles',
 'Marilyn Manson',
 'Mark Knopfler',
 'Matchbox Twenty',
 'Memphis La Blusera',
 'Metallica',
 'Michael McDonald',
 'Mick Jagger',
 'Miguel Ríos',
 'Modest Mouse',
 'Mogwai',
 'Molotov',
 'Muse',
 'Mägo de Oz',
 'Neil Young',
 'Nek',
 'Nickelback',
 'Nirvana',
 'No Te Va Gustar',
 "O'Funk'illo",
 'Oasis',
 'Orleans',
 'Orquesta Mondragon',
 'Os Paralamas Do Sucesso',
 'Ozzy Osbourne',
 'P.O.D.',
 'PJ Harvey',
 'Panchiko',
 'Papa Roach',
 'Pappo',
 'Patricio Rey y sus Redonditos de Ricota',
 'Pearl Jam',
 'Pedro Suárez-Vértiz',
 'Pepper',
 'Peter Frampton',
 'Phil Collins',
 'Pink Floyd',
 'Pixies',
 'Placebo',
 'Porcupine Tree',
 'Puddle Of Mudd',
 'Queen',
 'Queens of the Stone Age',
 'R.E.M.',
 'Radiohead',
 'Rage Against The Machine',
 'Rata Blanca',
 'Red Hot Chili Peppers',
 'Richard Ashcroft',
 'Robbie Williams',
 'Robert Palmer',
 'Roger Hodgson',
 'Santana',
 'Seether',
 'Semisonic',
 'Serani Poji',
 'Shinedown',
 'Sigur Rós',
 'Silver Mt. Zion',
 'Simon & Garfunkel',
 'Skank',
 'Skay Beilinson',
 'Soda Stereo',
 'Spandau Ballet',
 'Staind',
 'Starsailor',
 'Stone Sour',
 'System Of A Down',
 'TOOL',
 'Talk Talk',
 'Thanya Paredes Aymara',
 'The Arrows and Friends',
 'The Beatles',
 'The Beautiful Girls',
 'The Black Keys',
 'The Cranberries',
 'The Cult',
 'The Cure',
 'The Dandy Warhols',
 'The Darkness',
 'The Goo Goo Dolls',
 'The Greenhornes',
 'The Hellacopters',
 'The Hives',
 'The Killers',
 'The Rolling Stones',
 'The Smashing Pumpkins',
 'The Strokes',
 'The The',
 'The Verve',
 'The Vines',
 'The White Stripes',
 'Thousand Foot Krutch',
 'Three Days Grace',
 'Titãs',
 'Tommy february6',
 'Train',
 'Travis',
 'Turf',
 'U2',
 'Velvet Revolver',
 'Vicentico',
 'Viejas Locas',
 'Vilma Palma e Vampiros',
 'Weezer',
 'Wilco',
 'Zoé'}

In [19]:
len(artista_unico)

233

In [38]:
artistas_a_consultar = artista_unico
lista_artistas = []


for nombre_artista in artistas_a_consultar:
    
    datos_artista = llamar_lastfm_api('artist.getinfo', nombre_artista, cliente)  
    
    
    if datos_artista and 'artist' in datos_artista:
        
        artista_data = datos_artista['artist']
        
        
        oyentes = artista_data.get('stats', {}).get('listeners', 'arista no encontrado') 
        reproducciones = artista_data.get('stats', {}).get('playcount', 'N/D')
        
        bio_content = artista_data.get('bio', {}).get('content', '')
        
        if not bio_content or bio_content.strip() == "":
            bio_resumen = 'biografia no encontrada'
        else:
            bio_resumen = artista_data.get('bio', {}).get('summary')
        
        lista_artistas_dict = {'artista': artista_data.get('name', nombre_artista),'oyentes': oyentes, 'reproducciones': reproducciones, 'bio_resumen': bio_resumen}
        lista_artistas.append(lista_artistas_dict)
        
    
           
    else:
        print(f"No se pudo obtener información de {nombre_artista}")

In [87]:
import pandas as pd

In [39]:
df_rock_bio = pd.DataFrame(lista_artistas)

In [40]:
df_rock_bio

,artista,oyentes,reproducciones,bio_resumen
0,Green Day,6352266,420765442,Green Day is an American punk rock band formed...
1,Billy Joel,3857530,118256341,"Billy Joel (born William Martin Joel on May 9,..."
2,Attaque 77,148479,3823845,Formed in 1987 as a group of friends that join...
3,Eric Clapton,3342651,79783469,Eric Patrick Clapton CBE (born 30 March 1945) ...
4,Los Abuelos de la Nada,311185,4474292,Los Abuelos de la Nada is a band from Buenos A...
...,...,...,...,...
228,Maná,804429,18343982,There is more than one artist with this name:\...
229,Cheap Trick,1358770,16390386,Cheap Trick is an American power pop/rock n ro...
230,Skank,641574,21592543,Skank is a pop/rock/reggae band in Brazil. The...
231,Café Tacvba,385629,13432352,Café Tacvba is a band from the Lomas de Sotelo...
232,Elvis Presley,4306234,144587977,"Elvis Aaron Presley (January 8, 1935 – August ..."

In [43]:
df_rock_bio.to_csv("df_rock_bio.csv")