Tareas: Extraer canciones y álbumes lanzados entre 2000 y 2005.

Extraer la siguiente información:

[ ] Artista.

[ ] Género musical.

[ ] Tipo (canción o álbum).

[ ] Nombre.

[ ] Año de lanzamiento.

[ ] ID.

In [ ]:
#pip install spotipy

Collecting spotipy
  Using cached spotipy-2.25.1-py3-none-any.whl.metadata (5.1 kB)
Collecting redis>=3.5.3 (from spotipy)
  Downloading redis-7.0.1-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: requests>=2.25.0 in c:\users\romin\miniconda3\lib\site-packages (from spotipy) (2.32.5)
Requirement already satisfied: urllib3>=1.26.0 in c:\users\romin\miniconda3\lib\site-packages (from spotipy) (2.5.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\romin\miniconda3\lib\site-packages (from requests>=2.25.0->spotipy) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\romin\miniconda3\lib\site-packages (from requests>=2.25.0->spotipy) (3.7)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\romin\miniconda3\lib\site-packages (from requests>=2.25.0->spotipy) (2025.10.5)
Using cached spotipy-2.25.1-py3-none-any.whl (31 kB)
Downloading redis-7.0.1-py3-none-any.whl (339 kB)
Installing collected packages: redis, spotipy

   ---------------------------------------- 0/2 [redis]
   -------------------- ------------------- 1/2 [spotipy]
   ---------------------------------------- 2/2 [spotipy]

Successfully installed redis-7.0.1 spotipy-2.25.1
Note: you may need to restart the kernel to use updated packages.

In [5]:
import spotipy #importo, una vez quiero usarla en c/nb

from spotipy.oauth2 import SpotifyClientCredentials

In [6]:
import pandas as pd
pd.set_option('display.max_columns', None) # para poder visualizar todas las columnas de los DataFrames

In [ ]:
secreto= "numero_secreto"
cliente= "cliente_secreto"

In [8]:
# Autenticación
auth_manager = SpotifyClientCredentials(cliente, secreto)
sp = spotipy.Spotify(auth_manager=auth_manager)

In [9]:
query = sp.search(q="genre:blues, year:2005", type="track", limit=50, offset=0) #usamos offset=0 para obtener los primeros 50

In [10]:
lista_artistas = query['tracks']['items'][0]['album']['artists'] #analizamos los len que contiene el diccionario y los puntos de acceso a la info
lista_artistas

[{'external_urls': {'spotify': 'https://open.spotify.com/artist/2gCsNOpiBaMNh20jQ5prf0'},
  'href': 'https://api.spotify.com/v1/artists/2gCsNOpiBaMNh20jQ5prf0',
  'id': '2gCsNOpiBaMNh20jQ5prf0',
  'name': 'Buddy Guy',
  'type': 'artist',
  'uri': 'spotify:artist:2gCsNOpiBaMNh20jQ5prf0'}]

In [11]:
for artista in lista_artistas:
    print(artista['name'])

Buddy Guy

In [12]:
for track in query['tracks']['items']: ###para acceder a la popularidad del tema
    print(track['name'], track['popularity'])

What Kind Of Woman Is This? 44
Crazy 34
Watermelon Man 29
Tired Of Your Jive 29
T-Bone Shuffle 33
House Of The Rising Sun 32
You Don't Love Me 32
Days Like This 34
I'm A Bluesman - Live 31
Mean Town Blues - 2004 Digital Remaster 30
Stormy Monday - Live 38
Call It Stormy Monday 35
Supernatural - Studio 33
If I Don't Get Home 30
Statesboro Blues 33
Life By The Drop 35
Freight Train to Ride 37
Doodlin' 24
Sweet Baby of Mine 31
Givin' Up On Love 36
Honey Hush 35
On The Road Again - Remastered 2005 33
Just Got Back From Baby's 39
Somebody Ease My Troublin' Mind 38
Rockabilly Rebel 39
How Long Has This Been Going On 32
Falling 37
You Got The Silver 43
Mean Old World 41
Papa Ain't Salty 40
I Believe to My Soul - 2005 Remaster 49
Let Me Down Easy 35
Early In The Morning 35
Ain't No Sunshine 49
Fa-Fa-Fa 41
Need Your Love So Bad 38
Down into Mexico 45
Humankind 39
Hummingbird 45
Cocaine 42
I Don't Need No Doctor 42
Working Man 47
What'd I Say, Pt. 1 & 2 44
The Thrill Is Gone 53
All Over Again 46
Seven Nation Army 45
Recado Bossa Nova - Remastered 2005/Rudy Van Gelder Edition 44
Baby What You Want Me To Do 49
T-Bone Blues 52
Rulando 29

In [13]:
for dato in query['tracks']['items']: #iteramos en los elementos que componen items
    artista = dato['artists'][0]['name']
    genero = 'blues'
    nombre = dato['name']
    tipo = dato['type']
    ano = dato['album']['release_date']
    spotify_id = dato['id']
    print({'Artista': artista,'Género': 'blues','Tipo': tipo,'Nombre': nombre,'Año': ano,'ID': spotify_id})
    break ##detiene la lista despues del primer elemento, por lo que solo guardarías uno

{'Artista': 'Buddy Guy', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'What Kind Of Woman Is This?', 'Año': '2005-09-01', 'ID': '0BrmbJnPYcd7gnvLYqxw0r'}

In [14]:
lista_blues = [] #lista vacia antes del bucle

for dato in query['tracks']['items']: #recorremos los elementos
    artista = dato['artists'][0]['name']
    genero = 'blues'
    nombre = dato['name']
    tipo = dato['type']
    ano = dato['album']['release_date']
    spotify_id = dato['id']

    informacion_artista= {'Artista': artista, 'Género': 'blues', 'Tipo': tipo, 'Nombre': nombre, 'Año': ano,'ID': spotify_id} #creamos un diccionario con la info que queremos recopila de cada truck. nota: genero str

    lista_blues.append(informacion_artista)
    #elimino brake para que me salgan todos los elementos de query

In [15]:
# IMPRESIÓN POR FILAS SEPARADAS

for diccionario in lista_blues:
    print(diccionario)

{'Artista': 'Buddy Guy', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'What Kind Of Woman Is This?', 'Año': '2005-09-01', 'ID': '0BrmbJnPYcd7gnvLYqxw0r'}
{'Artista': 'Lara Price Band', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'Crazy', 'Año': '2005-07-27', 'ID': '0pmS7QvJs6i2ENKjYpS52I'}
{'Artista': 'Big Mama Thornton', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'Watermelon Man', 'Año': '2005-08-23', 'ID': '0GGUZVkxnuYn7sNSa2OkNQ'}
{'Artista': 'B.B. King', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'Tired Of Your Jive', 'Año': '2005-01-01', 'ID': '2FFLsJDnc7eEsxjTIEcsSI'}
{'Artista': 'T-Bone Walker', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'T-Bone Shuffle', 'Año': '2005-03-29', 'ID': '6bl7UHHcx1OY9tbvvnSssc'}
{'Artista': 'Roxy Perry', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'House Of The Rising Sun', 'Año': '2005-05-05', 'ID': '5mv7gXwH5qYChfwISnOx94'}
{'Artista': 'Maria Daines', 'Género': 'blues', 'Tipo': 'track', 'Nombre': "You Don't Love Me", 'Año': '2005-01-01', 'ID': '2QFSymCLADUjN4mK81RG0m'}
{'Artista': "Danny Bryant's Redeyeband", 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'Days Like This', 'Año': '2005', 'ID': '3BPgGORjhUhc9lplQyni4j'}
{'Artista': 'Magic Slim & The Teardrops', 'Género': 'blues', 'Tipo': 'track', 'Nombre': "I'm A Bluesman - Live", 'Año': '2005-08-16', 'ID': '5UkxPWonTl7c034dEWmmCD'}
{'Artista': 'Johnny Winter', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'Mean Town Blues - 2004 Digital Remaster', 'Año': '2005-01-01', 'ID': '4uwZKQ2lxIJDYgY2MbKoNX'}
{'Artista': 'Cream', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'Stormy Monday - Live', 'Año': '2005-09-30', 'ID': '7EhLes7NMh9LJg2yQIaHFe'}
{'Artista': 'T-Bone Walker', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'Call It Stormy Monday', 'Año': '2005-03-29', 'ID': '1i7nQGgwloILcp6ZftH2Qa'}
{'Artista': 'Peter Green', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'Supernatural - Studio', 'Año': '2005-06-07', 'ID': '1xbeQpHwgIIIjwIwY9jYpx'}
{'Artista': 'John Mayall', 'Género': 'blues', 'Tipo': 'track', 'Nombre': "If I Don't Get Home", 'Año': '2005-11-06', 'ID': '6y7hd61hR6hHD3HKZ6dkNj'}
{'Artista': 'Blind Willie McTell', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'Statesboro Blues', 'Año': '2005-08-30', 'ID': '05Fqtv0hpBriJj803R6x8i'}
{'Artista': "Pickin' On Series", 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'Life By The Drop', 'Año': '2005-10-20', 'ID': '53KZrDPXBYKUoCONaHFQ1n'}
{'Artista': 'Louisiana Red', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'Freight Train to Ride', 'Año': '2005-12-20', 'ID': '2T6QJ7Ax9evXGxvGXBC8le'}
{'Artista': 'Ray Charles', 'Género': 'blues', 'Tipo': 'track', 'Nombre': "Doodlin'", 'Año': '2005-01-18', 'ID': '2TCeLqICaM0pasmlqguYUq'}
{'Artista': 'Ruth Brown', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'Sweet Baby of Mine', 'Año': '2005-03-29', 'ID': '3343d5GDSYKsli0L8W61Gc'}
{'Artista': 'Byther Smith', 'Género': 'blues', 'Tipo': 'track', 'Nombre': "Givin' Up On Love", 'Año': '2005', 'ID': '0z996lfA5XGfC9uwVaBIUW'}
{'Artista': 'Big Joe Turner', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'Honey Hush', 'Año': '2005-04-19', 'ID': '5ssXU6u9HqUW87W2gglY7F'}
{'Artista': 'Canned Heat', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'On The Road Again - Remastered 2005', 'Año': '2005-01-01', 'ID': '1R45EyWM83EVqPOrDWtZTG'}
{'Artista': 'Hard Bargain', 'Género': 'blues', 'Tipo': 'track', 'Nombre': "Just Got Back From Baby's", 'Año': '2005-12-02', 'ID': '3NVFEmcKDxsN9ieHLJbnr7'}
{'Artista': 'Eric Clapton', 'Género': 'blues', 'Tipo': 'track', 'Nombre': "Somebody Ease My Troublin' Mind", 'Año': '2005-01-01', 'ID': '0cvIYPJ3KaGZLiOxZZXSAR'}
{'Artista': 'Matchbox', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'Rockabilly Rebel', 'Año': '2005-12-05', 'ID': '47fBL9Hqjq2kFIrg8c1wQi'}
{'Artista': 'Carly Simon', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'How Long Has This Been Going On', 'Año': '2005-07-01', 'ID': '67b2LBKIzjo0yqdWgFxShN'}
{'Artista': 'Snowy White', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'Falling', 'Año': '2005-04-11', 'ID': '1HYuzQ4I1KJV1BTctLIZvz'}
{'Artista': 'Susan Tedeschi', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'You Got The Silver', 'Año': '2005-01-01', 'ID': '5jQPaMjSWpFOMx8BVUOtpM'}
{'Artista': 'T-Bone Walker', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'Mean Old World', 'Año': '2005-03-29', 'ID': '3gg0xEc2b4eEbYySLmfFU1'}
{'Artista': 'T-Bone Walker', 'Género': 'blues', 'Tipo': 'track', 'Nombre': "Papa Ain't Salty", 'Año': '2005-03-29', 'ID': '1OGh5aeiGiNvuD37LiNN99'}
{'Artista': 'Ray Charles', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'I Believe to My Soul - 2005 Remaster', 'Año': '2005-09-20', 'ID': '2iRnG73mX0ZyEbRTWp3Nt2'}
{'Artista': 'Bettye LaVette', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'Let Me Down Easy', 'Año': '2005-03-25', 'ID': '0MvsfFXD0XkeOcPUOO5XaH'}
{'Artista': 'B.B. King', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'Early In The Morning', 'Año': '2005-01-01', 'ID': '3QP9B2esvPxLlbxaiNGQVK'}
{'Artista': 'Buddy Guy', 'Género': 'blues', 'Tipo': 'track', 'Nombre': "Ain't No Sunshine", 'Año': '2005-09-01', 'ID': '1amH1FjaNDAaZVpHWzcztW'}
{'Artista': 'Datarock', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'Fa-Fa-Fa', 'Año': '2005-04-04', 'ID': '69jJtkqDBuF3n6yPnAvRjK'}
{'Artista': 'B.B. King', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'Need Your Love So Bad', 'Año': '2005-01-01', 'ID': '0dQu291pxTuFzs1RaZu4uY'}
{'Artista': 'Delbert McClinton', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'Down into Mexico', 'Año': '2005-08-23', 'ID': '2JXEgeW3DXVDsjfQNHtRuV'}
{'Artista': 'Alice Russell', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'Humankind', 'Año': '2005-09-26', 'ID': '6jf2LNT3ob0LLMz2BxvyeP'}
{'Artista': 'B.B. King', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'Hummingbird', 'Año': '2005-01-01', 'ID': '0CF1X2oxbHWyFNPG2CPeNX'}
{'Artista': 'Eric Clapton', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'Cocaine', 'Año': '2005-01-01', 'ID': '6hDegaGv8VwBoMhGqoPfxR'}
{'Artista': 'John Scofield', 'Género': 'blues', 'Tipo': 'track', 'Nombre': "I Don't Need No Doctor", 'Año': '2005-01-01', 'ID': '3VgYGwa03GGyYwKjHtJqrQ'}
{'Artista': 'Otis Rush', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'Working Man', 'Año': '2005-02-08', 'ID': '4Gia17DzXBhYFbYiJj6SyW'}
{'Artista': 'Ray Charles', 'Género': 'blues', 'Tipo': 'track', 'Nombre': "What'd I Say, Pt. 1 & 2", 'Año': '2005-01-18', 'ID': '3JvDEbXLKUxaNv0D0txup5'}
{'Artista': 'B.B. King', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'The Thrill Is Gone', 'Año': '2005-01-01', 'ID': '4kyKnNbxFe86MMeV4xpDL8'}
{'Artista': 'B.B. King', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'All Over Again', 'Año': '2005-01-01', 'ID': '1jPBDpK4MKwUVgtE3LuCae'}
{'Artista': 'Nostalgia 77', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'Seven Nation Army', 'Año': '2005-03-21', 'ID': '5Bbj2kKDkUaoiyuD3nC0xh'}
{'Artista': 'Hank Mobley', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'Recado Bossa Nova - Remastered 2005/Rudy Van Gelder Edition', 'Año': '2005-01-01', 'ID': '5K5NOAnF7DwQATrEumi6dS'}
{'Artista': 'Jimmy Reed', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'Baby What You Want Me To Do', 'Año': '2005-03-22', 'ID': '05oMNN5Rbv6rVqyFFG9uTl'}
{'Artista': 'T-Bone Walker', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'T-Bone Blues', 'Año': '2005-03-29', 'ID': '3DjwjAUPT4zvIu6ZzcgLGJ'}
{'Artista': "O'Funk'illo", 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'Rulando', 'Año': '2005-03-22', 'ID': '5zjkZoJ3yVDqzv1lyHvh3G'}

In [16]:
# CREACIÓN DEL DATAFRAME
df_blues = pd.DataFrame(lista_blues)

df_blues #en print o cvs añadir (index=False) para eliminar ese primer indice

,Artista,Género,Tipo,Nombre,Año,ID
0,Buddy Guy,blues,track,What Kind Of Woman Is This?,2005-09-01,0BrmbJnPYcd7gnvLYqxw0r
1,Lara Price Band,blues,track,Crazy,2005-07-27,0pmS7QvJs6i2ENKjYpS52I
2,Big Mama Thornton,blues,track,Watermelon Man,2005-08-23,0GGUZVkxnuYn7sNSa2OkNQ
3,B.B. King,blues,track,Tired Of Your Jive,2005-01-01,2FFLsJDnc7eEsxjTIEcsSI
4,T-Bone Walker,blues,track,T-Bone Shuffle,2005-03-29,6bl7UHHcx1OY9tbvvnSssc
5,Roxy Perry,blues,track,House Of The Rising Sun,2005-05-05,5mv7gXwH5qYChfwISnOx94
6,Maria Daines,blues,track,You Don't Love Me,2005-01-01,2QFSymCLADUjN4mK81RG0m
7,Danny Bryant's Redeyeband,blues,track,Days Like This,2005,3BPgGORjhUhc9lplQyni4j
8,Magic Slim & The Teardrops,blues,track,I'm A Bluesman - Live,2005-08-16,5UkxPWonTl7c034dEWmmCD
9,Johnny Winter,blues,track,Mean Town Blues - 2004 Digital Remaster,2005-01-01,4uwZKQ2lxIJDYgY2MbKoNX
10,Cream,blues,track,Stormy Monday - Live,2005-09-30,7EhLes7NMh9LJg2yQIaHFe
11,T-Bone Walker,blues,track,Call It Stormy Monday,2005-03-29,1i7nQGgwloILcp6ZftH2Qa
12,Peter Green,blues,track,Supernatural - Studio,2005-06-07,1xbeQpHwgIIIjwIwY9jYpx
13,John Mayall,blues,track,If I Don't Get Home,2005-11-06,6y7hd61hR6hHD3HKZ6dkNj
14,Blind Willie McTell,blues,track,Statesboro Blues,2005-08-30,05Fqtv0hpBriJj803R6x8i
15,Pickin' On Series,blues,track,Life By The Drop,2005-10-20,53KZrDPXBYKUoCONaHFQ1n
16,Louisiana Red,blues,track,Freight Train to Ride,2005-12-20,2T6QJ7Ax9evXGxvGXBC8le
17,Ray Charles,blues,track,Doodlin',2005-01-18,2TCeLqICaM0pasmlqguYUq
18,Ruth Brown,blues,track,Sweet Baby of Mine,2005-03-29,3343d5GDSYKsli0L8W61Gc
19,Byther Smith,blues,track,Givin' Up On Love,2005,0z996lfA5XGfC9uwVaBIUW
20,Big Joe Turner,blues,track,Honey Hush,2005-04-19,5ssXU6u9HqUW87W2gglY7F
21,Canned Heat,blues,track,On The Road Again - Remastered 2005,2005-01-01,1R45EyWM83EVqPOrDWtZTG
22,Hard Bargain,blues,track,Just Got Back From Baby's,2005-12-02,3NVFEmcKDxsN9ieHLJbnr7
23,Eric Clapton,blues,track,Somebody Ease My Troublin' Mind,2005-01-01,0cvIYPJ3KaGZLiOxZZXSAR
24,Matchbox,blues,track,Rockabilly Rebel,2005-12-05,47fBL9Hqjq2kFIrg8c1wQi
25,Carly Simon,blues,track,How Long Has This Been Going On,2005-07-01,67b2LBKIzjo0yqdWgFxShN
26,Snowy White,blues,track,Falling,2005-04-11,1HYuzQ4I1KJV1BTctLIZvz
27,Susan Tedeschi,blues,track,You Got The Silver,2005-01-01,5jQPaMjSWpFOMx8BVUOtpM
28,T-Bone Walker,blues,track,Mean Old World,2005-03-29,3gg0xEc2b4eEbYySLmfFU1
29,T-Bone Walker,blues,track,Papa Ain't Salty,2005-03-29,1OGh5aeiGiNvuD37LiNN99
30,Ray Charles,blues,track,I Believe to My Soul - 2005 Remaster,2005-09-20,2iRnG73mX0ZyEbRTWp3Nt2
31,Bettye LaVette,blues,track,Let Me Down Easy,2005-03-25,0MvsfFXD0XkeOcPUOO5XaH
32,B.B. King,blues,track,Early In The Morning,2005-01-01,3QP9B2esvPxLlbxaiNGQVK
33,Buddy Guy,blues,track,Ain't No Sunshine,2005-09-01,1amH1FjaNDAaZVpHWzcztW
34,Datarock,blues,track,Fa-Fa-Fa,2005-04-04,69jJtkqDBuF3n6yPnAvRjK
35,B.B. King,blues,track,Need Your Love So Bad,2005-01-01,0dQu291pxTuFzs1RaZu4uY
36,Delbert McClinton,blues,track,Down into Mexico,2005-08-23,2JXEgeW3DXVDsjfQNHtRuV
37,Alice Russell,blues,track,Humankind,2005-09-26,6jf2LNT3ob0LLMz2BxvyeP
38,B.B. King,blues,track,Hummingbird,2005-01-01,0CF1X2oxbHWyFNPG2CPeNX
39,Eric Clapton,blues,track,Cocaine,2005-01-01,6hDegaGv8VwBoMhGqoPfxR
40,John Scofield,blues,track,I Don't Need No Doctor,2005-01-01,3VgYGwa03GGyYwKjHtJqrQ
41,Otis Rush,blues,track,Working Man,2005-02-08,4Gia17DzXBhYFbYiJj6SyW
42,Ray Charles,blues,track,"What'd I Say, Pt. 1 & 2",2005-01-18,3JvDEbXLKUxaNv0D0txup5
43,B.B. King,blues,track,The Thrill Is Gone,2005-01-01,4kyKnNbxFe86MMeV4xpDL8
44,B.B. King,blues,track,All Over Again,2005-01-01,1jPBDpK4MKwUVgtE3LuCae
45,Nostalgia 77,blues,track,Seven Nation Army,2005-03-21,5Bbj2kKDkUaoiyuD3nC0xh
46,Hank Mobley,blues,track,Recado Bossa Nova - Remastered 2005/Rudy Van G...,2005-01-01,5K5NOAnF7DwQATrEumi6dS
47,Jimmy Reed,blues,track,Baby What You Want Me To Do,2005-03-22,05oMNN5Rbv6rVqyFFG9uTl
48,T-Bone Walker,blues,track,T-Bone Blues,2005-03-29,3DjwjAUPT4zvIu6ZzcgLGJ
49,O'Funk'illo,blues,track,Rulando,2005-03-22,5zjkZoJ3yVDqzv1lyHvh3G

In [17]:
for año in range(2000, 2005):
    for cancion in range (0,150,50):
        q=f"genre:blues, year:{año}"
    print(q)

genre:blues, year:2000
genre:blues, year:2001
genre:blues, year:2002
genre:blues, year:2003
genre:blues, year:2004

In [18]:
lista_blues = [] #lista vacia antes del bucle

for ano in range(2000, 2005):
    for offset in range (0,150,50):
        
        query = sp.search(q=f"genre:blues, year:{ano}", type="track", limit=50, offset=offset)

        for dato in query['tracks']['items']:
            artista = dato['artists'][0]['name']
            genero = 'blues'
            nombre = dato['name']
            tipo = dato['type']
            ano = dato['album']['release_date'][:4]
            spotify_id = dato['id']

            informacion_artista= {'Artista': artista, 'Género': 'blues', 'Tipo': tipo, 'Nombre': nombre, 'Año': ano,'ID': spotify_id} #creamos un diccionario con la info que queremos recopila de cada truck. nota: genero str

            lista_blues.append(informacion_artista)

print(lista_blues)

[{'Artista': 'Greg Brown', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'Blue Car', 'Año': '2000', 'ID': '3gIRDIOGmLc1WBhlcv35O5'}, {'Artista': 'James Intveld', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'Love Calls', 'Año': '2000', 'ID': '3x5EuJxLpjk0vIV5iMpd1i'}, {'Artista': 'Murali Coryell', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'Softly Let Me Kiss Your Lips', 'Año': '2000', 'ID': '5cDIbJtehjhImG8eytKwGw'}, {'Artista': 'Joe Bonamassa', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'Miss You, Hate You', 'Año': '2000', 'ID': '270fcAQl6cPF3S3ZQiPNon'}, {'Artista': 'Sean Costello', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'Double Trouble', 'Año': '2000', 'ID': '0DeGKiRiCK6Hv8ivuojSdH'}, {'Artista': 'The White Stripes', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'Death Letter', 'Año': '2000', 'ID': '78ZPgT0agDUG95ByxpTNBP'}, {'Artista': 'Freddie King', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'Five Long Years - Remastered', 'Año': '2000', 'ID': '56cQKq9cveZtNl2c284ttH'}, {'Artista': 'Freddie King', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'Me And My Guitar', 'Año': '2000', 'ID': '0QpxUzXEI3ZjJeo6dDFgV7'}, {'Artista': 'Joe Bonamassa', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'A New Day Yesterday', 'Año': '2000', 'ID': '1vm3dobPEhe6ZVhhbtiaWO'}, {'Artista': 'Johnny & The Jailbirds', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'Roll On (Clickety Clack)', 'Año': '2000', 'ID': '3Lez3vHWLiqZkfUZjbstXz'}, {'Artista': 'Peter Green Splinter Group', 'Género': 'blues', 'Tipo': 'track', 'Nombre': "I'm A Steady Rollin' Man - Studio", 'Año': '2000', 'ID': '2695otTpDzVxoWa0BDZmoD'}, {'Artista': 'Chris Smither', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'Link Of Chain', 'Año': '2000', 'ID': '16N2lpCidTNYdNq2YZhE98'}, {'Artista': 'Mark Selby', 'Género': 'blues', 'Tipo': 'track', 'Nombre': "You're Gonna Miss My Love", 'Año': '2000', 'ID': '0jZJc4oCRBBHvzK3cd4342'}, {'Artista': 'Chris Smither', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'I Am The Ride', 'Año': '2000', 'ID': '5DFNZIBtwTmcEjZNuovJQ9'}, {'Artista': 'Jimmy Rogers', 'Género': 'blues', 'Tipo': 'track', 'Nombre': "You're Sweet", 'Año': '2000', 'ID': '1yvTGo5neAri7tdlc0zhOf'}, {'Artista': 'Coco Montoya', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'Good Days, Bad Days', 'Año': '2000', 'ID': '66YScT9ixRBmW6wFoYjQJj'}, {'Artista': 'Blue Stew', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'Bringing Home The Blues', 'Año': '2000', 'ID': '3DmVpgHrFO7VNAC3RHXe6Y'}, {'Artista': 'Lonnie Brooks', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'Two Guitars Shuffle - Take 2', 'Año': '2000', 'ID': '46uYtQlZwFZ1RdJYRblEwM'}, {'Artista': 'Lucky Lloyd', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'I Feel The Pain', 'Año': '2000', 'ID': '2xO8Qjuf11PmyDG367E7qC'}, {'Artista': 'Eric Clapton', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'Days of Old', 'Año': '2000', 'ID': '0FSYTwx4rU8zXbDotK08MN'}, {'Artista': 'The White Stripes', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'Little Bird', 'Año': '2000', 'ID': '7uYoO8Jt7BUib2teUpLFLZ'}, {'Artista': 'Eddy Wilsons Blues Band', 'Género': 'blues', 'Tipo': 'track', 'Nombre': "I Just Can't Wait No More", 'Año': '2000', 'ID': '2xLbcLVaPhswWtf8rkBa51'}, {'Artista': 'Gomez', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'Machismo', 'Año': '2000', 'ID': '53YV9igWx2KDJDaByNru3S'}, {'Artista': 'Eric Clapton', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'I Wanna Be', 'Año': '2000', 'ID': '2JfEpNSiHz7X0lT3RlcUuL'}, {'Artista': 'Calvin Russell', 'Género': 'blues', 'Tipo': 'track', 'Nombre': "That Woudn't Be Enough", 'Año': '2000', 'ID': '546IGaq08nvVxVSMUQta82'}, {'Artista': 'George Thorogood & The Destroyers', 'Género': 'blues', 'Tipo': 'track', 'Nombre': "If You Don't Start Drinkin' (I'm Gonna Leave)", 'Año': '2000', 'ID': '1XV97m6mzheMHFbF9XlnMP'}, {'Artista': 'R.L. Burnside', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'Bad Luck City', 'Año': '2000', 'ID': '1n9PUTUa3NkYqkUHQ11rwm'}, {'Artista': 'Mark Selby', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'Kink In The Chain', 'Año': '2000', 'ID': '0FSwHcnyYV4MQeJNGLWqn9'}, {'Artista': 'Blues Company', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'My Little Angel', 'Año': '2000', 'ID': '7pl3bhnRrfYEcw0kg5cHjv'}, {'Artista': 'Chris Thomas King', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'Hard Time Killing Floor Blues', 'Año': '2000', 'ID': '3rlPaBlRjyNKHzJsvKV6dP'}, {'Artista': 'Solomon Burke', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'Proud Mary', 'Año': '2000', 'ID': '1DoB9qQAEHwV9s5BWofgUm'}, {'Artista': 'Deborah Coleman', 'Género': 'blues', 'Tipo': 'track', 'Nombre': "I'm A Woman", 'Año': '2000', 'ID': '0HPazJXESVCimRyMggplg5'}, {'Artista': 'Julian Sas', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'Blues for J', 'Año': '2000', 'ID': '7ATNFqcr0pTZuFendjxtpk'}, {'Artista': 'B.B. King', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'How Blue Can You Get?', 'Año': '2000', 'ID': '1zuVsc5gf2S2Fp5achygUi'}, {'Artista': 'Solomon Burke', 'Género': 'blues', 'Tipo': 'track', 'Nombre': "I'll Be Doggone", 'Año': '2000', 'ID': '50v0EN7BuMhNTyYqA41adj'}, {'Artista': 'Guru', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'Plenty', 'Año': '2000', 'ID': '6zSe7ZKNjb6Zl5AP78y5QN'}, {'Artista': 'The White Stripes', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'Hello Operator', 'Año': '2000', 'ID': '7zPxIh1c3kJaNwmjdZ3GQX'}, {'Artista': 'Calvin Russell', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'Crossroads', 'Año': '2000', 'ID': '06jV48CGewrRuHeVIUA4ze'}, {'Artista': 'Eric Clapton', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'Marry You', 'Año': '2000', 'ID': '3izCarsX6zxJ216lnid5qR'}, {'Artista': 'Eric Clapton', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'Worried Life Blues', 'Año': '2000', 'ID': '2fdhU7kBO3WVYkWJnYAlO3'}, {'Artista': 'Eric Clapton', 'Género': 'blues', 'Tipo': 'track', 'Nombre': "Hold On I'm Coming", 'Año': '2000', 'ID': '0XFJaXsCH4sSni128GpPls'}, {'Artista': 'Eric Clapton', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'Come Rain or Come Shine', 'Año': '2000', 'ID': '2Z7U506Agti2s9uxP564LE'}, {'Artista': 'Eric Clapton', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'Help the Poor', 'Año': '2000', 'ID': '1zdJVsBmTNavn5u2GSqWkW'}, {'Artista': 'Eric Clapton', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'When My Heart Beats Like a Hammer', 'Año': '2000', 'ID': '7cBSTKsHmyjqp5euTS5yCM'}, {'Artista': 'Mark Selby', 'Género': 'blues', 'Tipo': 'track', 'Nombre': "Don't You Throw That Mojo On Me", 'Año': '2000', 'ID': '54KR62xO0Z7OF77FpcjGGo'}, {'Artista': 'Eric Clapton', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'Ten Long Years', 'Año': '2000', 'ID': '2bykT1h4Tb2Scaw0QcqYBA'}, {'Artista': 'Etta James', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'Miss You', 'Año': '2000', 'ID': '4JVeqfE2tpi7Pv63LJZtPh'}, {'Artista': 'Eric Clapton', 'Género': 'blues', 'Tipo': 'track', 'Nombre': "Three O'Clock Blues", 'Año': '2000', 'ID': '6lWxIJH0CyUtmFaIAeVmTQ'}, {'Artista': 'Eric Clapton', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'Key to the Highway', 'Año': '2000', 'ID': '1a0CDu5jpwW2arT34HbwUP'}, {'Artista': 'Eric Clapton', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'Riding With the King', 'Año': '2000', 'ID': '0U6wNkZaQUTBrCLbhbbRgS'}, {'Artista': 'Rascal Flatts', 'Género': 'blues', 'Tipo': 'track', 'Nombre': "I'm Movin' On", 'Año': '2000', 'ID': '7gpuC3rLKkI7PoJcEnSIO6'}, {'Artista': 'Johnny & The Jailbirds', 'Género': 'blues', 'Tipo': 'track', 'Nombre': "Rockin' the Blues Away", 'Año': '2000', 'ID': '1myqk2BTZIfAvGJY8C0Lrl'}, {'Artista': 'Mojo Blues Band', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'Wee Baby Blues', 'Año': '2000', 'ID': '0VziYoppHx4lOJQUDOqDl1'}, {'Artista': 'R.L. Burnside', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'Got Messed Up', 'Año': '2000', 'ID': '3J8D4mxkDl7YBJu0cCVbNI'}, {'Artista': 'Nappy Brown', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'Love Locks', 'Año': '2000', 'ID': '0uE00jXki2CKFcIZRfCZ53'}, {'Artista': 'Coco Montoya', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'Nothing But Love', 'Año': '2000', 'ID': '3uU9xb3RmfQEwbnlikdKJM'}, {'Artista': 'Mississippi John Hurt', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'Coffee Blues', 'Año': '2000', 'ID': '16GdiwewBf99MhUSVsxUBe'}, {'Artista': 'Joe Bonamassa', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'Colour and Shape', 'Año': '2000', 'ID': '4vWeqYSux6JHbcRDBknsRa'}, {'Artista': 'Sonny Rollins', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'Sonnymoon For Two', 'Año': '2000', 'ID': '58auzrd6rwCLuWleG4bCAy'}, {'Artista': 'James Intveld', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'Modern Don Juan', 'Año': '2000', 'ID': '1iufJsYASeY1I57AosUBhC'}, {'Artista': 'Wes Montgomery', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'D-Natural Blues', 'Año': '2000', 'ID': '5fxPh44pYzAR5M5KW5SdMk'}, {'Artista': 'John Littlejohn', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'Sweet Little Angel', 'Año': '2000', 'ID': '0eNlLMGiQcQRcUClHYiicl'}, {'Artista': 'Tadg Galleran', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'Stagger Lee', 'Año': '2000', 'ID': '0pZHA4QJjCl1n4EFkpuepb'}, {'Artista': 'Chris Smither', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'No Love Today', 'Año': '2000', 'ID': '6KmJfZCd5f4P11vuglbIrN'}, {'Artista': 'Chris Smither', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'Slow Surprise', 'Año': '2000', 'ID': '4AVuDNWohEaQQZJ3fSt9M8'}, {'Artista': 'Mississippi John Hurt', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'Pay Day', 'Año': '2000', 'ID': '29Q6NQ4WsPYTsZ8nhdAhfo'}, {'Artista': 'Steve Vaus', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'Everybody Told Me', 'Año': '2000', 'ID': '3vAU4lGghbyWGYqFQFPxCB'}, {'Artista': 'Joe Bonamassa', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'If Heartaches Were Nickels', 'Año': '2000', 'ID': '017d9sEiXW5QsPhlFOE7TG'}, {'Artista': 'La Mississippi', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'Un Poco Mas', 'Año': '2000', 'ID': '3nM4VFUnGA9rT3Smk1WFJ0'}, {'Artista': 'Jools Holland', 'Género': 'blues', 'Tipo': 'track', 'Nombre': "I'm In The Mood For Love", 'Año': '2000', 'ID': '1K2mskoYmN2Z05e6colFcr'}, {'Artista': 'Joe Bonamassa', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'Head Aches to Heart Breaks', 'Año': '2000', 'ID': '20XTWISYlgsJ0b35cKB1TO'}, {'Artista': 'B.B. King', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'I Like To Live The Love', 'Año': '2000', 'ID': '65k1tfjXmOYbc3aLB3wliS'}, {'Artista': 'Dr. John', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'Solitude', 'Año': '2000', 'ID': '1ViGgioq3zeIkA9B95j0Wo'}, {'Artista': 'Walter Trout and The Free Radicals', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'Let Me Know - Live', 'Año': '2000', 'ID': '6VfK8MlwXtfKZEGCpE1OLk'}, {'Artista': 'Mark Selby', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'Smoked', 'Año': '2000', 'ID': '4syOaApfBfZeTIv5XcP584'}, {'Artista': 'Johnny & The Jailbirds', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'Too Much', 'Año': '2000', 'ID': '6REZePiAWXdIk1sYvUChal'}, {'Artista': 'Jimmy Thackery And The Drivers', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'Chained To The Blues Line', 'Año': '2000', 'ID': '4Bv1m8dBj1E94sxBfPlN7x'}, {'Artista': 'Johnny & The Jailbirds', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'Shake It Up', 'Año': '2000', 'ID': '4xYkTCChNbbNigOSSSc9vt'}, {'Artista': 'Julian Sas', 'Género': 'blues', 'Tipo': 'track', 'Nombre': "Working Man's Blues", 'Año': '2000', 'ID': '7hDksuyOEN9trOQm7QyU0T'}, {'Artista': 'Lonnie Brooks', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'Sweet Home Chicago', 'Año': '2000', 'ID': '6IIngEBJRQQumwt1MA3Y6y'}, {'Artista': 'Peter Green Splinter Group', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'Sweet Home Chicago - Studio', 'Año': '2000', 'ID': '0znXZlsMDXLiTeK1IoG0XD'}, {'Artista': 'Mark Selby', 'Género': 'blues', 'Tipo': 'track', 'Nombre': "What Am I Doin'", 'Año': '2000', 'ID': '6CDjI2pTAxgGe7GSfppPi1'}, {'Artista': 'Denise LaSalle', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'Trapped By a Thing Called Love', 'Año': '2000', 'ID': '6T3TfV8M5drXuQ35TgdGVL'}, {'Artista': 'The Robert Cray Band', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'Love Gone to Waste', 'Año': '2000', 'ID': '0tMr3kcYlbktwHdfpBZmL0'}, {'Artista': 'Blues Company', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'Run Your Finger Through My Hair', 'Año': '2000', 'ID': '0TEsHUsXothgvoHyZlx6wO'}, {'Artista': 'Calvin Russell', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'Where the Blues Get Born', 'Año': '2000', 'ID': '1auCKIkY3Doo3me3WRI36z'}, {'Artista': 'Chris Smither', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'Killing the Blues', 'Año': '2000', 'ID': '76CtO0Xm5paZVEVRxoG9rz'}, {'Artista': 'Freddie King', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'Going Down - Remastered 2000', 'Año': '2000', 'ID': '0JmzkCi9xu32A1idZ6ROBX'}, {'Artista': 'Joe Dassin', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'Si Tu Me Extranas (Si Tu Penses A Moi)-(Now Woman No Cry) - Version Espagnole', 'Año': '2000', 'ID': '6gzjxUXZ1LW82onjWwzlEI'}, {'Artista': 'Nappy Brown', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'Well, Well, Well Baby LA', 'Año': '2000', 'ID': '26wbI9PC17C8AszrgaaxJi'}, {'Artista': 'Johnny & The Jailbirds', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'Real Gone Rocker', 'Año': '2000', 'ID': '2N3xtEsA1CX7cst2zqVqlY'}, {'Artista': 'Big Mama Thornton', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'Gonna Leave You', 'Año': '2000', 'ID': '1dEkRQ2ASVMTLF7Ig5Mud7'}, {'Artista': 'B.B. King', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'I Know', 'Año': '2000', 'ID': '1LSC4TKKoJCbpAEsyvRmkQ'}, {'Artista': 'Wes Montgomery', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'Four On Six', 'Año': '2000', 'ID': '2Mq2Fzc9HBgvsijVFdSXUl'}, {'Artista': 'Solomon Burke', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'Uptight Good Woman', 'Año': '2000', 'ID': '13AUYiz7PWyjeWdJQW21wD'}, {'Artista': 'Ellis Hall', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'Flip Flop and Fly', 'Año': '2000', 'ID': '4Oh9rODvqWz9kfT5FeXZqy'}, {'Artista': 'Julian Sas', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'Blues for the Lost and Found', 'Año': '2000', 'ID': '2MLkhRevYCibfPpHxlIAq6'}, {'Artista': 'Dr. Feelgood', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'You Gotta Help Me', 'Año': '2000', 'ID': '24LEsorak3E3tyIW0LLFpX'}, {'Artista': 'The White Stripes', 'Género': 'blues', 'Tipo': 'track', 'Nombre': "Truth Doesn't Make a Noise", 'Año': '2000', 'ID': '4cuKwDw7T3JELdePWwa3hZ'}, {'Artista': 'Jimmy Thackery And The Drivers', 'Género': 'blues', 'Tipo': 'track', 'Nombre': "Blues 'Fore Dawn - Instrumental", 'Año': '2000', 'ID': '0ddS9gxgh8EECW1wemruyi'}, {'Artista': 'R.L. Burnside', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'Too Many Ups', 'Año': '2000', 'ID': '1uPvVSSe0u55thfPeNMdBI'}, {'Artista': 'Chris Smither', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'Cave Man', 'Año': '2000', 'ID': '7Ev2BC5iwtLVqOFEOxkaWg'}, {'Artista': "Keb' Mo'", 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'Gimme What You Got', 'Año': '2000', 'ID': '0jwAYxpZTG7i7b0kJwncwQ'}, {'Artista': 'Wes Montgomery', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'West Coast Blues', 'Año': '2000', 'ID': '5vooXq1F3SrYJl8TGtMsHA'}, {'Artista': 'Nappy Brown', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'Skidy Woe', 'Año': '2000', 'ID': '7dQAOrvHztTE0ONRKeVr1W'}, {'Artista': 'The White Stripes', 'Género': 'blues', 'Tipo': 'track', 'Nombre': "Why Can't You Be Nicer to Me?", 'Año': '2000', 'ID': '2mcIqH8wKpaRr554Tj4tFM'}, {'Artista': 'Patrick Yandall', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'Blues On 5th Avenue', 'Año': '2000', 'ID': '2AmEPE041ByXKpMuNGlfPf'}, {'Artista': 'Jimmy Rogers', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'Gold Tailed Bird', 'Año': '2000', 'ID': '1SgQhS2rBcpPM41hABnSap'}, {'Artista': 'R.L. Burnside', 'Género': 'blues', 'Tipo': 'track', 'Nombre': "Nothin' Man", 'Año': '2000', 'ID': '4jiYgkhW4duSaylPxCWrLS'}, {'Artista': 'Freddie King', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'Big Legged Woman - Remastered', 'Año': '2000', 'ID': '2DQNcMIYVQwpShcFU9GZfV'}, {'Artista': 'Sam Cooke', 'Género': 'blues', 'Tipo': 'track', 'Nombre': "Movin' and Groovin'", 'Año': '2000', 'ID': '4jaLgfNiPUQKpMfdTUG00J'}, {'Artista': 'Calvin Russell', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'Rats and Roaches', 'Año': '2000', 'ID': '04jcKEKasC0Za3Lwij8Qs3'}, {'Artista': 'Johnny & The Jailbirds', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'Pretending', 'Año': '2000', 'ID': '2MfCuw9W2aBtamGmCCcNtE'}, {'Artista': 'Ten Years After', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'Good Morning Little Schoolgirl - Live', 'Año': '2000', 'ID': '3mqtOBDCacrTc5wwpvaqIn'}, {'Artista': 'The White Stripes', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'Sister, Do You Know My Name?', 'Año': '2000', 'ID': '1h1CncaFyTssQ9zGiHy1Ez'}, {'Artista': 'Sista Monica', 'Género': 'blues', 'Tipo': 'track', 'Nombre': "Honey It's Your Fault", 'Año': '2000', 'ID': '5YpqRyGuBn5etkcVncz6fv'}, {'Artista': 'B.B. King', 'Género': 'blues', 'Tipo': 'track', 'Nombre': "I Got Some Help I Don't Need", 'Año': '2000', 'ID': '3hOhranovtYFweLwF5UHaU'}, {'Artista': 'Freddie King', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'Reconsider Baby - Remastered', 'Año': '2000', 'ID': '5Avx6u0cFb5P0fL4qzijGC'}, {'Artista': 'Blues Company', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'Invitation to the Blues', 'Año': '2000', 'ID': '6KgCVYAl7OUOlsKy3k7Ajj'}, {'Artista': 'B.B. King', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'Never Trust A Woman', 'Año': '2000', 'ID': '4IISGbUpoUAXqDdZews1ve'}, {'Artista': 'Johnny & The Jailbirds', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'She Can Blow It', 'Año': '2000', 'ID': '0PBUMWVAhjcAWmCVD0nCVh'}, {'Artista': 'Calvin Russell', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'I Gave My Soul to You', 'Año': '2000', 'ID': '11aV4H2ByFqHmeqptCRfed'}, {'Artista': 'Shemekia Copeland', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'Beat Up Guitar', 'Año': '2000', 'ID': '5MXGqDBmhnHELueZgK6ypP'}, {'Artista': 'Mississippi John Hurt', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'Spike Driver Blues', 'Año': '2000', 'ID': '0QcYseQfUmZpjXGoXDT9z4'}, {'Artista': "Gov't Mule", 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'Bad Little Doggie', 'Año': '2000', 'ID': '0J7W6f3S8CienuTyjZOGzh'}, {'Artista': 'Status Quo', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'Sweet Home Chicago', 'Año': '2000', 'ID': '4PH13VJJov8vDEvtZXmMO1'}, {'Artista': 'Mark Selby', 'Género': 'blues', 'Tipo': 'track', 'Nombre': "More Storms Comin'", 'Año': '2000', 'ID': '1jX7dfgIhSxeKN0tsF4Qd5'}, {'Artista': 'Sista Monica', 'Género': 'blues', 'Tipo': 'track', 'Nombre': "You're Only Good For One Thang Baby", 'Año': '2000', 'ID': '0CLPTSldV2Dp016RKyBUqi'}, {'Artista': 'Son House', 'Género': 'blues', 'Tipo': 'track', 'Nombre': "Grinnin' In Your Face", 'Año': '2000', 'ID': '1JIIvzT8aX6v7LmZ1FolCM'}, {'Artista': 'Chris Smither', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'Hold On I', 'Año': '2000', 'ID': '5hN4Rb80cAYgzl48f0r8ED'}, {'Artista': 'R.L. Burnside', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'Wish I Was in Heaven Sitting Down', 'Año': '2000', 'ID': '23Ry7IvrU6JBcxkpdqsPaw'}, {'Artista': 'Joe Bonamassa', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'Walk In My Shadow', 'Año': '2000', 'ID': '6d9qqpoy4h5jaxLqtXTPp5'}, {'Artista': 'James Intveld', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'One Sweet Letter', 'Año': '2000', 'ID': '6MAk3v3dnzC4PefLYb2Khk'}, {'Artista': 'Rusty Zinn', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'Just Like A Fish', 'Año': '2000', 'ID': '70ip0BmVSrmwxhWHOj58uf'}, {'Artista': 'Etta James', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'Hound Dog', 'Año': '2000', 'ID': '52auP9OuR9q0qR2OQxM5l0'}, {'Artista': 'Tommy Johnson', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'Canned Heat Blues', 'Año': '2000', 'ID': '1Uk2MppskA0wnHUj8JwYfC'}, {'Artista': 'R.L. Burnside', 'Género': 'blues', 'Tipo': 'track', 'Nombre': 'Chain of Fools', 

In [19]:
df_blues = pd.DataFrame(lista_blues)

df_blues

,Artista,Género,Tipo,Nombre,Año,ID
0,Greg Brown,blues,track,Blue Car,2000,3gIRDIOGmLc1WBhlcv35O5
1,James Intveld,blues,track,Love Calls,2000,3x5EuJxLpjk0vIV5iMpd1i
2,Murali Coryell,blues,track,Softly Let Me Kiss Your Lips,2000,5cDIbJtehjhImG8eytKwGw
3,Joe Bonamassa,blues,track,"Miss You, Hate You",2000,270fcAQl6cPF3S3ZQiPNon
4,Sean Costello,blues,track,Double Trouble,2000,0DeGKiRiCK6Hv8ivuojSdH
...,...,...,...,...,...,...
745,Mark Knopfler,blues,track,Song For Sonny Liston,2004,7CEB9EWKgL5kC1HTO8Oru7
746,Muddy Waters Blues Band,blues,track,Everything Gonna Be Alright,2004,5VK783FVcaNdsx5iN0O7dN
747,Carl Weathersby,blues,track,Hold On,2004,6hvJliJvOMHiKSXjPyUoZf
748,Albert Cummings,blues,track,Blues Makes Me Feel So Good,2004,5T1sj4W2NIUlbmZMdZmAI3
749,Jools Holland,blues,track,St. James' Infirmary Blues,2004,6TSgebnc69Ndnw52rffHJV

In [20]:
df_blues.to_csv('df_blues.csv', index=False)