Tareas: Extraer canciones y álbumes lanzados entre 2000 y 2005.

Extraer la siguiente información:

[ ] Artista.

[ ] Género musical.

[ ] Tipo (canción o álbum).

[ ] Nombre.

[ ] Año de lanzamiento.

[ ] ID.

In [1]:
import spotipy #importo, una vez quiero usarla en c/nb

from spotipy.oauth2 import SpotifyClientCredentials

In [2]:
import json

In [3]:
import pandas as pd
pd.set_option('display.max_columns', None) # para poder visualizar todas las columnas de los DataFrames

In [ ]:
secreto = "#####"
cliente = "#####"

In [5]:
# Autenticación
auth_manager = SpotifyClientCredentials(cliente, secreto)
sp = spotipy.Spotify(auth_manager=auth_manager)

In [6]:
query = sp.search(q="genre:latin pop, year:2005", type="track", limit=50, offset=0) #usamos offset=0 para obtener los primeros 50

In [7]:
lista_artistas = query['tracks']['items'][0]['album']['artists'] #analizamos los len que contiene el diccionario y los puntos de acceso a la info
lista_artistas

[{'external_urls': {'spotify': 'https://open.spotify.com/artist/0h1zs4CTlU9D2QtgPxptUD'},
  'href': 'https://api.spotify.com/v1/artists/0h1zs4CTlU9D2QtgPxptUD',
  'id': '0h1zs4CTlU9D2QtgPxptUD',
  'name': 'Ricardo Arjona',
  'type': 'artist',
  'uri': 'spotify:artist:0h1zs4CTlU9D2QtgPxptUD'}]

In [8]:
for artista in lista_artistas:
    print(artista['name'])

Ricardo Arjona

In [9]:
for track in query['tracks']['items']: ###para acceder a la popularidad del tema
    print(track['name'], track['popularity'])

Iluso 49
Popurri 40
テ・キエロ・ディヒステ 53
Dia Especial (feat. Gustavo Cerati) 50
En Tus Pupilas 48
Sway 52
La Pared 53
Te Doy Mi Amor 51
Mojado 55
Seduccion 54
遠く離れても 52
No te apartes de mí 54
Fuera 50
Qué Hay Detrás 56
Quiero 41
La Cabaña 59
No Me Canso - Inedito 27
De Vez en Mes 49
Obtener un Si 45
A Ti 51
No Te Preocupes por Mi 47
¿Qué Hago Yo? 66
キエンセラ 52
Las de la Intuición 77
Popurri Kchaka Piru (Bailando Guararé / Anhelos / La Rosita / Mi Negra) 22
La Tortura (feat. Alejandro Sanz) 80
Como Me Mira 55
Te Echo de Menos 48
No (feat. Gustavo Cerati) 65
No Te Pido Flores 58
Te necesito 54
Aún Hay Algo 61
Tras De Mí 65
Hace Tiempo 60
Nuestro Amor 59
Qué Vida la Mía 66
Pingüinos en la Cama 69
Este Corazón 66
Noviembre Sin Ti 74
Suelta Mi Mano 66
Te Mando Flores 72
Popurrí Juan Gabriel / Ya Lo Sé Que Tú Te Vas / La Diferencia / Te Sigo Amando - En Vivo 47
Día de Enero 76
Pídeme 53
Nada Fue Un Error - Live In Spain / 2005 63
A Ti 66
Acompáñame a Estar Solo 69
ベサメ・ムーチョ 64
Nada Fue Un Error - Live In Spain / 2005 48
Yo Quisiera 76

In [10]:
for dato in query['tracks']['items']: #iteramos en los elementos que componen items
    artista = dato['artists'][0]['name']
    genero = 'latin pop'
    nombre = dato['name']
    tipo = dato['type']
    ano = dato['album']['release_date']
    spotify_id = dato['id']
    print({'Artista': artista,'Género': 'latin pop','Tipo': tipo,'Nombre': nombre,'Año': ano,'ID': spotify_id})
    break ##detiene la lista despues del primer elemento, por lo que solo guardarías uno

{'Artista': 'Ricardo Arjona', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Iluso', 'Año': '2005-12-06', 'ID': '39FeHqemDNAlWn3C0VMowR'}

In [11]:
lista_latin_pop = [] #lista vacia antes del bucle

for dato in query['tracks']['items']: #recorremos los elementos
    artista = dato['artists'][0]['name']
    genero = 'latin pop'
    nombre = dato['name']
    tipo = dato['type']
    ano = dato['album']['release_date']
    spotify_id = dato['id']

    informacion_artista= {'Artista': artista, 'Género': 'latin pop', 'Tipo': tipo, 'Nombre': nombre, 'Año': ano,'ID': spotify_id} #creamos un diccionario con la info que queremos recopila de cada truck. nota: genero str

    lista_latin_pop.append(informacion_artista)
    #elimino brake para que me salgan todos los elementos de query

print(lista_latin_pop)

[{'Artista': 'Ricardo Arjona', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Iluso', 'Año': '2005-12-06', 'ID': '39FeHqemDNAlWn3C0VMowR'}, {'Artista': 'Aniceto Molina', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Popurri', 'Año': '2005-03-01', 'ID': '5ndbUsAt6oyeBhZZ4U1NH4'}, {'Artista': 'Lisa Ono', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'テ・キエロ・ディヒステ', 'Año': '2005-06-29', 'ID': '1xjGMWxSfbo7Eyjeb3mzNs'}, {'Artista': 'Shakira', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Dia Especial (feat. Gustavo Cerati)', 'Año': '2005-06-03', 'ID': '2EZ4NSQtoKdiWK8JDMY7NT'}, {'Artista': 'Shakira', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'En Tus Pupilas', 'Año': '2005-06-03', 'ID': '7046NJqL0E7v5THigdTOyE'}, {'Artista': 'The Pussycat Dolls', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Sway', 'Año': '2005-01-01', 'ID': '01xXQbDsWMJVBKOoKWXE8h'}, {'Artista': 'Shakira', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'La Pared', 'Año': '2005-06-03', 'ID': '35idKzsNHvyALKIZ9JHw47'}, {'Artista': 'Bacanos', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Te Doy Mi Amor', 'Año': '2005-05-05', 'ID': '5cgwBlY1oNdnuNsy4PaXAz'}, {'Artista': 'Ricardo Arjona', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Mojado', 'Año': '2005-12-06', 'ID': '5Qchpm6oOiHytt5dIk69Ij'}, {'Artista': 'Thalia', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Seduccion', 'Año': '2005-01-01', 'ID': '1YMr1YzK04rKlN8vt03nPP'}, {'Artista': 'Lisa Ono', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': '遠く離れても', 'Año': '2005-08-19', 'ID': '35i2XFc60eKVIu9SlRIRCH'}, {'Artista': 'Yahir', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'No te apartes de mí', 'Año': '2005-09-20', 'ID': '7EC5RB8EDJOWXcYlk9HLwr'}, {'Artista': 'RBD', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Fuera', 'Año': '2005-01-01', 'ID': '4haBiYrYQ7AbvQxlt1QahV'}, {'Artista': 'RBD', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Qué Hay Detrás', 'Año': '2005-01-01', 'ID': '5Ya2WSoqPdAkmohiRZgZGl'}, {'Artista': 'Calle Ciega', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Quiero', 'Año': '2005-01-01', 'ID': '3b11hXQgd8rXcROT2qRcJp'}, {'Artista': "La K'onga", 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'La Cabaña', 'Año': '2005-11-04', 'ID': '5TpGT4K34mBP6JcJfIgRqF'}, {'Artista': 'Ana Torroja', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'No Me Canso - Inedito', 'Año': '2005', 'ID': '2apIAlbkN6IgvucbM5PCdo'}, {'Artista': 'Ricardo Arjona', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'De Vez en Mes', 'Año': '2005-12-06', 'ID': '7dkw2lSgDwyhHZYoVgMclt'}, {'Artista': 'Shakira', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Obtener un Si', 'Año': '2005-06-03', 'ID': '0OUVKbGfxGA6rdvqwxwyWV'}, {'Artista': 'Sin Bandera', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'A Ti', 'Año': '2005-11-18', 'ID': '1EtN1I3hbkuIl6zka9XhJ3'}, {'Artista': 'Chayanne', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'No Te Preocupes por Mi', 'Año': '2005', 'ID': '0NN9TRTvceycUm8wq30yk8'}, {'Artista': 'Ha*Ash', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': '¿Qué Hago Yo?', 'Año': '2005', 'ID': '5fISatRSvu52jsmsnKwNfY'}, {'Artista': 'Lisa Ono', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'キエンセラ', 'Año': '2005-08-19', 'ID': '6pTh0DeJkVDvv1ytHlwDiA'}, {'Artista': 'Shakira', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Las de la Intuición', 'Año': '2005-06-03', 'ID': '7DnMd3BxVOedyOyR7K3F8L'}, {'Artista': 'Frecuencia Trio', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Popurri Kchaka Piru (Bailando Guararé / Anhelos / La Rosita / Mi Negra)', 'Año': '2005', 'ID': '64HTYIDH9Y6vW53FV6AoLg'}, {'Artista': 'Shakira', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'La Tortura (feat. Alejandro Sanz)', 'Año': '2005-06-03', 'ID': '53AafWSzYsiJKnAtJTUB5f'}, {'Artista': 'Fonseca', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Como Me Mira', 'Año': '2005-05-01', 'ID': '1OwZtvGw2BNYjmLHoGfrY4'}, {'Artista': 'Chayanne', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Te Echo de Menos', 'Año': '2005', 'ID': '5OkWLb3GzvjYUrhSpQFbvn'}, {'Artista': 'Shakira', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'No (feat. Gustavo Cerati)', 'Año': '2005-06-03', 'ID': '7CZkVQ8LsfDsu8STKAQfWY'}, {'Artista': 'Fanny Lu', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'No Te Pido Flores', 'Año': '2005-01-01', 'ID': '2ctc9nwRgXeeIFaFWTRrRl'}, {'Artista': 'Luis Miguel', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Te necesito', 'Año': '2005-12-02', 'ID': '6fM4uVlC2brb5Di9O1vvry'}, {'Artista': 'RBD', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Aún Hay Algo', 'Año': '2005-01-01', 'ID': '6fqpsCQ7jF7OgQolXgYovX'}, {'Artista': 'RBD', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Tras De Mí', 'Año': '2005-01-01', 'ID': '1AO5MeGsWdPLejY47pnYYy'}, {'Artista': 'Fonseca', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Hace Tiempo', 'Año': '2005-05-01', 'ID': '7G0Z77RdBTdf4bt45AL6yS'}, {'Artista': 'RBD', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Nuestro Amor', 'Año': '2005-01-01', 'ID': '7F7qwp7VZRVwZsNoddRRgX'}, {'Artista': 'Reik', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Qué Vida la Mía', 'Año': '2005-03-02', 'ID': '0M6KY0x5u65ybXHZ3IAega'}, {'Artista': 'Ricardo Arjona', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Pingüinos en la Cama', 'Año': '2005-12-06', 'ID': '73X4fA2RX6ycvEsFvDIUs4'}, {'Artista': 'RBD', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Este Corazón', 'Año': '2005-01-01', 'ID': '0bMVCO35RJiUhAfvFsLjIF'}, {'Artista': 'Reik', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Noviembre Sin Ti', 'Año': '2005-03-02', 'ID': '2vCHDrXVN0k1GPTjSIZ69E'}, {'Artista': 'Sin Bandera', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Suelta Mi Mano', 'Año': '2005-11-18', 'ID': '50xvGsnNmO3k5EtaUBXRRr'}, {'Artista': 'Fonseca', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Te Mando Flores', 'Año': '2005-05-01', 'ID': '2in1gSZtv2lRbcZUmN9aAl'}, {'Artista': 'Alejandro Fernández', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Popurrí Juan Gabriel / Ya Lo Sé Que Tú Te Vas / La Diferencia / Te Sigo Amando - En Vivo', 'Año': '2005-10-20', 'ID': '2APE7KXnCG2IFP66BVdZis'}, {'Artista': 'Shakira', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Día de Enero', 'Año': '2005-06-03', 'ID': '2u24GtkbktY3HB3souJdNY'}, {'Artista': 'Guaco', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Pídeme', 'Año': '2005-07-01', 'ID': '3dqgHG4Rksh3B04Dt3cVHu'}, {'Artista': 'Coti', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Nada Fue Un Error - Live In Spain / 2005', 'Año': '2005-01-01', 'ID': '7GO6pBFbieZ30NjGIp2LP5'}, {'Artista': 'Ricardo Arjona', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'A Ti', 'Año': '2005-12-06', 'ID': '5CcBo88PRHzJeQdiE5mBNi'}, {'Artista': 'Ricardo Arjona', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Acompáñame a Estar Solo', 'Año': '2005-12-06', 'ID': '5rwl9TKyjbAVSCUOBZz77Y'}, {'Artista': 'Lisa Ono', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'ベサメ・ムーチョ', 'Año': '2005-08-19', 'ID': '26nkboSGZauLZQJo2Ni1vA'}, {'Artista': 'Coti', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Nada Fue Un Error - Live In Spain / 2005', 'Año': '2005-01-01', 'ID': '15RAXEkBCh62ZB6xddv0wO'}, {'Artista': 'Reik', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Yo Quisiera', 'Año': '2005-03-02', 'ID': '2GSr8anleCXKLNjjjijoMZ'}]

In [12]:
# IMPRESIÓN POR FILAS SEPARADAS

for diccionario in lista_latin_pop:
    print(diccionario)

{'Artista': 'Ricardo Arjona', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Iluso', 'Año': '2005-12-06', 'ID': '39FeHqemDNAlWn3C0VMowR'}
{'Artista': 'Aniceto Molina', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Popurri', 'Año': '2005-03-01', 'ID': '5ndbUsAt6oyeBhZZ4U1NH4'}
{'Artista': 'Lisa Ono', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'テ・キエロ・ディヒステ', 'Año': '2005-06-29', 'ID': '1xjGMWxSfbo7Eyjeb3mzNs'}
{'Artista': 'Shakira', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Dia Especial (feat. Gustavo Cerati)', 'Año': '2005-06-03', 'ID': '2EZ4NSQtoKdiWK8JDMY7NT'}
{'Artista': 'Shakira', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'En Tus Pupilas', 'Año': '2005-06-03', 'ID': '7046NJqL0E7v5THigdTOyE'}
{'Artista': 'The Pussycat Dolls', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Sway', 'Año': '2005-01-01', 'ID': '01xXQbDsWMJVBKOoKWXE8h'}
{'Artista': 'Shakira', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'La Pared', 'Año': '2005-06-03', 'ID': '35idKzsNHvyALKIZ9JHw47'}
{'Artista': 'Bacanos', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Te Doy Mi Amor', 'Año': '2005-05-05', 'ID': '5cgwBlY1oNdnuNsy4PaXAz'}
{'Artista': 'Ricardo Arjona', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Mojado', 'Año': '2005-12-06', 'ID': '5Qchpm6oOiHytt5dIk69Ij'}
{'Artista': 'Thalia', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Seduccion', 'Año': '2005-01-01', 'ID': '1YMr1YzK04rKlN8vt03nPP'}
{'Artista': 'Lisa Ono', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': '遠く離れても', 'Año': '2005-08-19', 'ID': '35i2XFc60eKVIu9SlRIRCH'}
{'Artista': 'Yahir', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'No te apartes de mí', 'Año': '2005-09-20', 'ID': '7EC5RB8EDJOWXcYlk9HLwr'}
{'Artista': 'RBD', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Fuera', 'Año': '2005-01-01', 'ID': '4haBiYrYQ7AbvQxlt1QahV'}
{'Artista': 'RBD', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Qué Hay Detrás', 'Año': '2005-01-01', 'ID': '5Ya2WSoqPdAkmohiRZgZGl'}
{'Artista': 'Calle Ciega', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Quiero', 'Año': '2005-01-01', 'ID': '3b11hXQgd8rXcROT2qRcJp'}
{'Artista': "La K'onga", 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'La Cabaña', 'Año': '2005-11-04', 'ID': '5TpGT4K34mBP6JcJfIgRqF'}
{'Artista': 'Ana Torroja', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'No Me Canso - Inedito', 'Año': '2005', 'ID': '2apIAlbkN6IgvucbM5PCdo'}
{'Artista': 'Ricardo Arjona', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'De Vez en Mes', 'Año': '2005-12-06', 'ID': '7dkw2lSgDwyhHZYoVgMclt'}
{'Artista': 'Shakira', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Obtener un Si', 'Año': '2005-06-03', 'ID': '0OUVKbGfxGA6rdvqwxwyWV'}
{'Artista': 'Sin Bandera', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'A Ti', 'Año': '2005-11-18', 'ID': '1EtN1I3hbkuIl6zka9XhJ3'}
{'Artista': 'Chayanne', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'No Te Preocupes por Mi', 'Año': '2005', 'ID': '0NN9TRTvceycUm8wq30yk8'}
{'Artista': 'Ha*Ash', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': '¿Qué Hago Yo?', 'Año': '2005', 'ID': '5fISatRSvu52jsmsnKwNfY'}
{'Artista': 'Lisa Ono', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'キエンセラ', 'Año': '2005-08-19', 'ID': '6pTh0DeJkVDvv1ytHlwDiA'}
{'Artista': 'Shakira', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Las de la Intuición', 'Año': '2005-06-03', 'ID': '7DnMd3BxVOedyOyR7K3F8L'}
{'Artista': 'Frecuencia Trio', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Popurri Kchaka Piru (Bailando Guararé / Anhelos / La Rosita / Mi Negra)', 'Año': '2005', 'ID': '64HTYIDH9Y6vW53FV6AoLg'}
{'Artista': 'Shakira', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'La Tortura (feat. Alejandro Sanz)', 'Año': '2005-06-03', 'ID': '53AafWSzYsiJKnAtJTUB5f'}
{'Artista': 'Fonseca', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Como Me Mira', 'Año': '2005-05-01', 'ID': '1OwZtvGw2BNYjmLHoGfrY4'}
{'Artista': 'Chayanne', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Te Echo de Menos', 'Año': '2005', 'ID': '5OkWLb3GzvjYUrhSpQFbvn'}
{'Artista': 'Shakira', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'No (feat. Gustavo Cerati)', 'Año': '2005-06-03', 'ID': '7CZkVQ8LsfDsu8STKAQfWY'}
{'Artista': 'Fanny Lu', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'No Te Pido Flores', 'Año': '2005-01-01', 'ID': '2ctc9nwRgXeeIFaFWTRrRl'}
{'Artista': 'Luis Miguel', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Te necesito', 'Año': '2005-12-02', 'ID': '6fM4uVlC2brb5Di9O1vvry'}
{'Artista': 'RBD', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Aún Hay Algo', 'Año': '2005-01-01', 'ID': '6fqpsCQ7jF7OgQolXgYovX'}
{'Artista': 'RBD', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Tras De Mí', 'Año': '2005-01-01', 'ID': '1AO5MeGsWdPLejY47pnYYy'}
{'Artista': 'Fonseca', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Hace Tiempo', 'Año': '2005-05-01', 'ID': '7G0Z77RdBTdf4bt45AL6yS'}
{'Artista': 'RBD', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Nuestro Amor', 'Año': '2005-01-01', 'ID': '7F7qwp7VZRVwZsNoddRRgX'}
{'Artista': 'Reik', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Qué Vida la Mía', 'Año': '2005-03-02', 'ID': '0M6KY0x5u65ybXHZ3IAega'}
{'Artista': 'Ricardo Arjona', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Pingüinos en la Cama', 'Año': '2005-12-06', 'ID': '73X4fA2RX6ycvEsFvDIUs4'}
{'Artista': 'RBD', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Este Corazón', 'Año': '2005-01-01', 'ID': '0bMVCO35RJiUhAfvFsLjIF'}
{'Artista': 'Reik', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Noviembre Sin Ti', 'Año': '2005-03-02', 'ID': '2vCHDrXVN0k1GPTjSIZ69E'}
{'Artista': 'Sin Bandera', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Suelta Mi Mano', 'Año': '2005-11-18', 'ID': '50xvGsnNmO3k5EtaUBXRRr'}
{'Artista': 'Fonseca', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Te Mando Flores', 'Año': '2005-05-01', 'ID': '2in1gSZtv2lRbcZUmN9aAl'}
{'Artista': 'Alejandro Fernández', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Popurrí Juan Gabriel / Ya Lo Sé Que Tú Te Vas / La Diferencia / Te Sigo Amando - En Vivo', 'Año': '2005-10-20', 'ID': '2APE7KXnCG2IFP66BVdZis'}
{'Artista': 'Shakira', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Día de Enero', 'Año': '2005-06-03', 'ID': '2u24GtkbktY3HB3souJdNY'}
{'Artista': 'Guaco', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Pídeme', 'Año': '2005-07-01', 'ID': '3dqgHG4Rksh3B04Dt3cVHu'}
{'Artista': 'Coti', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Nada Fue Un Error - Live In Spain / 2005', 'Año': '2005-01-01', 'ID': '7GO6pBFbieZ30NjGIp2LP5'}
{'Artista': 'Ricardo Arjona', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'A Ti', 'Año': '2005-12-06', 'ID': '5CcBo88PRHzJeQdiE5mBNi'}
{'Artista': 'Ricardo Arjona', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Acompáñame a Estar Solo', 'Año': '2005-12-06', 'ID': '5rwl9TKyjbAVSCUOBZz77Y'}
{'Artista': 'Lisa Ono', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'ベサメ・ムーチョ', 'Año': '2005-08-19', 'ID': '26nkboSGZauLZQJo2Ni1vA'}
{'Artista': 'Coti', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Nada Fue Un Error - Live In Spain / 2005', 'Año': '2005-01-01', 'ID': '15RAXEkBCh62ZB6xddv0wO'}
{'Artista': 'Reik', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Yo Quisiera', 'Año': '2005-03-02', 'ID': '2GSr8anleCXKLNjjjijoMZ'}

In [13]:
# CREACIÓN DEL DATAFRAME
df_latin_pop = pd.DataFrame(lista_latin_pop)

df_latin_pop #en print o cvs añadir (index=False) para eliminar ese primer indice

,Artista,Género,Tipo,Nombre,Año,ID
0,Ricardo Arjona,latin pop,track,Iluso,2005-12-06,39FeHqemDNAlWn3C0VMowR
1,Aniceto Molina,latin pop,track,Popurri,2005-03-01,5ndbUsAt6oyeBhZZ4U1NH4
2,Lisa Ono,latin pop,track,テ・キエロ・ディヒステ,2005-06-29,1xjGMWxSfbo7Eyjeb3mzNs
3,Shakira,latin pop,track,Dia Especial (feat. Gustavo Cerati),2005-06-03,2EZ4NSQtoKdiWK8JDMY7NT
4,Shakira,latin pop,track,En Tus Pupilas,2005-06-03,7046NJqL0E7v5THigdTOyE
5,The Pussycat Dolls,latin pop,track,Sway,2005-01-01,01xXQbDsWMJVBKOoKWXE8h
6,Shakira,latin pop,track,La Pared,2005-06-03,35idKzsNHvyALKIZ9JHw47
7,Bacanos,latin pop,track,Te Doy Mi Amor,2005-05-05,5cgwBlY1oNdnuNsy4PaXAz
8,Ricardo Arjona,latin pop,track,Mojado,2005-12-06,5Qchpm6oOiHytt5dIk69Ij
9,Thalia,latin pop,track,Seduccion,2005-01-01,1YMr1YzK04rKlN8vt03nPP
10,Lisa Ono,latin pop,track,遠く離れても,2005-08-19,35i2XFc60eKVIu9SlRIRCH
11,Yahir,latin pop,track,No te apartes de mí,2005-09-20,7EC5RB8EDJOWXcYlk9HLwr
12,RBD,latin pop,track,Fuera,2005-01-01,4haBiYrYQ7AbvQxlt1QahV
13,RBD,latin pop,track,Qué Hay Detrás,2005-01-01,5Ya2WSoqPdAkmohiRZgZGl
14,Calle Ciega,latin pop,track,Quiero,2005-01-01,3b11hXQgd8rXcROT2qRcJp
15,La K'onga,latin pop,track,La Cabaña,2005-11-04,5TpGT4K34mBP6JcJfIgRqF
16,Ana Torroja,latin pop,track,No Me Canso - Inedito,2005,2apIAlbkN6IgvucbM5PCdo
17,Ricardo Arjona,latin pop,track,De Vez en Mes,2005-12-06,7dkw2lSgDwyhHZYoVgMclt
18,Shakira,latin pop,track,Obtener un Si,2005-06-03,0OUVKbGfxGA6rdvqwxwyWV
19,Sin Bandera,latin pop,track,A Ti,2005-11-18,1EtN1I3hbkuIl6zka9XhJ3
20,Chayanne,latin pop,track,No Te Preocupes por Mi,2005,0NN9TRTvceycUm8wq30yk8
21,Ha*Ash,latin pop,track,¿Qué Hago Yo?,2005,5fISatRSvu52jsmsnKwNfY
22,Lisa Ono,latin pop,track,キエンセラ,2005-08-19,6pTh0DeJkVDvv1ytHlwDiA
23,Shakira,latin pop,track,Las de la Intuición,2005-06-03,7DnMd3BxVOedyOyR7K3F8L
24,Frecuencia Trio,latin pop,track,Popurri Kchaka Piru (Bailando Guararé / Anhelo...,2005,64HTYIDH9Y6vW53FV6AoLg
25,Shakira,latin pop,track,La Tortura (feat. Alejandro Sanz),2005-06-03,53AafWSzYsiJKnAtJTUB5f
26,Fonseca,latin pop,track,Como Me Mira,2005-05-01,1OwZtvGw2BNYjmLHoGfrY4
27,Chayanne,latin pop,track,Te Echo de Menos,2005,5OkWLb3GzvjYUrhSpQFbvn
28,Shakira,latin pop,track,No (feat. Gustavo Cerati),2005-06-03,7CZkVQ8LsfDsu8STKAQfWY
29,Fanny Lu,latin pop,track,No Te Pido Flores,2005-01-01,2ctc9nwRgXeeIFaFWTRrRl
30,Luis Miguel,latin pop,track,Te necesito,2005-12-02,6fM4uVlC2brb5Di9O1vvry
31,RBD,latin pop,track,Aún Hay Algo,2005-01-01,6fqpsCQ7jF7OgQolXgYovX
32,RBD,latin pop,track,Tras De Mí,2005-01-01,1AO5MeGsWdPLejY47pnYYy
33,Fonseca,latin pop,track,Hace Tiempo,2005-05-01,7G0Z77RdBTdf4bt45AL6yS
34,RBD,latin pop,track,Nuestro Amor,2005-01-01,7F7qwp7VZRVwZsNoddRRgX
35,Reik,latin pop,track,Qué Vida la Mía,2005-03-02,0M6KY0x5u65ybXHZ3IAega
36,Ricardo Arjona,latin pop,track,Pingüinos en la Cama,2005-12-06,73X4fA2RX6ycvEsFvDIUs4
37,RBD,latin pop,track,Este Corazón,2005-01-01,0bMVCO35RJiUhAfvFsLjIF
38,Reik,latin pop,track,Noviembre Sin Ti,2005-03-02,2vCHDrXVN0k1GPTjSIZ69E
39,Sin Bandera,latin pop,track,Suelta Mi Mano,2005-11-18,50xvGsnNmO3k5EtaUBXRRr
40,Fonseca,latin pop,track,Te Mando Flores,2005-05-01,2in1gSZtv2lRbcZUmN9aAl
41,Alejandro Fernández,latin pop,track,Popurrí Juan Gabriel / Ya Lo Sé Que Tú Te Vas ...,2005-10-20,2APE7KXnCG2IFP66BVdZis
42,Shakira,latin pop,track,Día de Enero,2005-06-03,2u24GtkbktY3HB3souJdNY
43,Guaco,latin pop,track,Pídeme,2005-07-01,3dqgHG4Rksh3B04Dt3cVHu
44,Coti,latin pop,track,Nada Fue Un Error - Live In Spain / 2005,2005-01-01,7GO6pBFbieZ30NjGIp2LP5
45,Ricardo Arjona,latin pop,track,A Ti,2005-12-06,5CcBo88PRHzJeQdiE5mBNi
46,Ricardo Arjona,latin pop,track,Acompáñame a Estar Solo,2005-12-06,5rwl9TKyjbAVSCUOBZz77Y
47,Lisa Ono,latin pop,track,ベサメ・ムーチョ,2005-08-19,26nkboSGZauLZQJo2Ni1vA
48,Coti,latin pop,track,Nada Fue Un Error - Live In Spain / 2005,2005-01-01,15RAXEkBCh62ZB6xddv0wO
49,Reik,latin pop,track,Yo Quisiera,2005-03-02,2GSr8anleCXKLNjjjijoMZ

In [ ]:
# establecemos un rango

In [14]:
for año in range (2000,2005):
    for o in range (0,150,50):
        q=f"genre:rock, year:{año}"
        print(q)

        print(año, "-", o)

genre:rock, year:2000
2000 - 0
genre:rock, year:2000
2000 - 50
genre:rock, year:2000
2000 - 100
genre:rock, year:2001
2001 - 0
genre:rock, year:2001
2001 - 50
genre:rock, year:2001
2001 - 100
genre:rock, year:2002
2002 - 0
genre:rock, year:2002
2002 - 50
genre:rock, year:2002
2002 - 100
genre:rock, year:2003
2003 - 0
genre:rock, year:2003
2003 - 50
genre:rock, year:2003
2003 - 100
genre:rock, year:2004
2004 - 0
genre:rock, year:2004
2004 - 50
genre:rock, year:2004
2004 - 100

In [15]:
lista_latin_pop = [] #lista vacia antes del bucle

for dato in query['tracks']['items']: #recorremos los elementos
    artista = dato['artists'][0]['name']
    genero = 'latin pop'
    nombre = dato['name']
    tipo = dato['type']
    ano = dato['album']['release_date']
    spotify_id = dato['id']

    informacion_artista= {'Artista': artista, 'Género': 'latin pop', 'Tipo': tipo, 'Nombre': nombre, 'Año': ano,'ID': spotify_id} #creamos un diccionario con la info que queremos recopila de cada truck. nota: genero str

    lista_latin_pop.append(informacion_artista)
    #elimino brake para que me salgan todos los elementos de query

print(lista_latin_pop)

[{'Artista': 'Ricardo Arjona', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Iluso', 'Año': '2005-12-06', 'ID': '39FeHqemDNAlWn3C0VMowR'}, {'Artista': 'Aniceto Molina', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Popurri', 'Año': '2005-03-01', 'ID': '5ndbUsAt6oyeBhZZ4U1NH4'}, {'Artista': 'Lisa Ono', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'テ・キエロ・ディヒステ', 'Año': '2005-06-29', 'ID': '1xjGMWxSfbo7Eyjeb3mzNs'}, {'Artista': 'Shakira', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Dia Especial (feat. Gustavo Cerati)', 'Año': '2005-06-03', 'ID': '2EZ4NSQtoKdiWK8JDMY7NT'}, {'Artista': 'Shakira', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'En Tus Pupilas', 'Año': '2005-06-03', 'ID': '7046NJqL0E7v5THigdTOyE'}, {'Artista': 'The Pussycat Dolls', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Sway', 'Año': '2005-01-01', 'ID': '01xXQbDsWMJVBKOoKWXE8h'}, {'Artista': 'Shakira', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'La Pared', 'Año': '2005-06-03', 'ID': '35idKzsNHvyALKIZ9JHw47'}, {'Artista': 'Bacanos', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Te Doy Mi Amor', 'Año': '2005-05-05', 'ID': '5cgwBlY1oNdnuNsy4PaXAz'}, {'Artista': 'Ricardo Arjona', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Mojado', 'Año': '2005-12-06', 'ID': '5Qchpm6oOiHytt5dIk69Ij'}, {'Artista': 'Thalia', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Seduccion', 'Año': '2005-01-01', 'ID': '1YMr1YzK04rKlN8vt03nPP'}, {'Artista': 'Lisa Ono', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': '遠く離れても', 'Año': '2005-08-19', 'ID': '35i2XFc60eKVIu9SlRIRCH'}, {'Artista': 'Yahir', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'No te apartes de mí', 'Año': '2005-09-20', 'ID': '7EC5RB8EDJOWXcYlk9HLwr'}, {'Artista': 'RBD', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Fuera', 'Año': '2005-01-01', 'ID': '4haBiYrYQ7AbvQxlt1QahV'}, {'Artista': 'RBD', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Qué Hay Detrás', 'Año': '2005-01-01', 'ID': '5Ya2WSoqPdAkmohiRZgZGl'}, {'Artista': 'Calle Ciega', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Quiero', 'Año': '2005-01-01', 'ID': '3b11hXQgd8rXcROT2qRcJp'}, {'Artista': "La K'onga", 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'La Cabaña', 'Año': '2005-11-04', 'ID': '5TpGT4K34mBP6JcJfIgRqF'}, {'Artista': 'Ana Torroja', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'No Me Canso - Inedito', 'Año': '2005', 'ID': '2apIAlbkN6IgvucbM5PCdo'}, {'Artista': 'Ricardo Arjona', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'De Vez en Mes', 'Año': '2005-12-06', 'ID': '7dkw2lSgDwyhHZYoVgMclt'}, {'Artista': 'Shakira', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Obtener un Si', 'Año': '2005-06-03', 'ID': '0OUVKbGfxGA6rdvqwxwyWV'}, {'Artista': 'Sin Bandera', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'A Ti', 'Año': '2005-11-18', 'ID': '1EtN1I3hbkuIl6zka9XhJ3'}, {'Artista': 'Chayanne', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'No Te Preocupes por Mi', 'Año': '2005', 'ID': '0NN9TRTvceycUm8wq30yk8'}, {'Artista': 'Ha*Ash', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': '¿Qué Hago Yo?', 'Año': '2005', 'ID': '5fISatRSvu52jsmsnKwNfY'}, {'Artista': 'Lisa Ono', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'キエンセラ', 'Año': '2005-08-19', 'ID': '6pTh0DeJkVDvv1ytHlwDiA'}, {'Artista': 'Shakira', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Las de la Intuición', 'Año': '2005-06-03', 'ID': '7DnMd3BxVOedyOyR7K3F8L'}, {'Artista': 'Frecuencia Trio', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Popurri Kchaka Piru (Bailando Guararé / Anhelos / La Rosita / Mi Negra)', 'Año': '2005', 'ID': '64HTYIDH9Y6vW53FV6AoLg'}, {'Artista': 'Shakira', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'La Tortura (feat. Alejandro Sanz)', 'Año': '2005-06-03', 'ID': '53AafWSzYsiJKnAtJTUB5f'}, {'Artista': 'Fonseca', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Como Me Mira', 'Año': '2005-05-01', 'ID': '1OwZtvGw2BNYjmLHoGfrY4'}, {'Artista': 'Chayanne', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Te Echo de Menos', 'Año': '2005', 'ID': '5OkWLb3GzvjYUrhSpQFbvn'}, {'Artista': 'Shakira', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'No (feat. Gustavo Cerati)', 'Año': '2005-06-03', 'ID': '7CZkVQ8LsfDsu8STKAQfWY'}, {'Artista': 'Fanny Lu', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'No Te Pido Flores', 'Año': '2005-01-01', 'ID': '2ctc9nwRgXeeIFaFWTRrRl'}, {'Artista': 'Luis Miguel', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Te necesito', 'Año': '2005-12-02', 'ID': '6fM4uVlC2brb5Di9O1vvry'}, {'Artista': 'RBD', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Aún Hay Algo', 'Año': '2005-01-01', 'ID': '6fqpsCQ7jF7OgQolXgYovX'}, {'Artista': 'RBD', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Tras De Mí', 'Año': '2005-01-01', 'ID': '1AO5MeGsWdPLejY47pnYYy'}, {'Artista': 'Fonseca', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Hace Tiempo', 'Año': '2005-05-01', 'ID': '7G0Z77RdBTdf4bt45AL6yS'}, {'Artista': 'RBD', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Nuestro Amor', 'Año': '2005-01-01', 'ID': '7F7qwp7VZRVwZsNoddRRgX'}, {'Artista': 'Reik', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Qué Vida la Mía', 'Año': '2005-03-02', 'ID': '0M6KY0x5u65ybXHZ3IAega'}, {'Artista': 'Ricardo Arjona', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Pingüinos en la Cama', 'Año': '2005-12-06', 'ID': '73X4fA2RX6ycvEsFvDIUs4'}, {'Artista': 'RBD', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Este Corazón', 'Año': '2005-01-01', 'ID': '0bMVCO35RJiUhAfvFsLjIF'}, {'Artista': 'Reik', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Noviembre Sin Ti', 'Año': '2005-03-02', 'ID': '2vCHDrXVN0k1GPTjSIZ69E'}, {'Artista': 'Sin Bandera', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Suelta Mi Mano', 'Año': '2005-11-18', 'ID': '50xvGsnNmO3k5EtaUBXRRr'}, {'Artista': 'Fonseca', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Te Mando Flores', 'Año': '2005-05-01', 'ID': '2in1gSZtv2lRbcZUmN9aAl'}, {'Artista': 'Alejandro Fernández', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Popurrí Juan Gabriel / Ya Lo Sé Que Tú Te Vas / La Diferencia / Te Sigo Amando - En Vivo', 'Año': '2005-10-20', 'ID': '2APE7KXnCG2IFP66BVdZis'}, {'Artista': 'Shakira', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Día de Enero', 'Año': '2005-06-03', 'ID': '2u24GtkbktY3HB3souJdNY'}, {'Artista': 'Guaco', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Pídeme', 'Año': '2005-07-01', 'ID': '3dqgHG4Rksh3B04Dt3cVHu'}, {'Artista': 'Coti', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Nada Fue Un Error - Live In Spain / 2005', 'Año': '2005-01-01', 'ID': '7GO6pBFbieZ30NjGIp2LP5'}, {'Artista': 'Ricardo Arjona', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'A Ti', 'Año': '2005-12-06', 'ID': '5CcBo88PRHzJeQdiE5mBNi'}, {'Artista': 'Ricardo Arjona', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Acompáñame a Estar Solo', 'Año': '2005-12-06', 'ID': '5rwl9TKyjbAVSCUOBZz77Y'}, {'Artista': 'Lisa Ono', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'ベサメ・ムーチョ', 'Año': '2005-08-19', 'ID': '26nkboSGZauLZQJo2Ni1vA'}, {'Artista': 'Coti', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Nada Fue Un Error - Live In Spain / 2005', 'Año': '2005-01-01', 'ID': '15RAXEkBCh62ZB6xddv0wO'}, {'Artista': 'Reik', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Yo Quisiera', 'Año': '2005-03-02', 'ID': '2GSr8anleCXKLNjjjijoMZ'}]

In [16]:
lista_latin_pop = [] #lista vacia antes del bucle

for año in range (2000,2005):
    for o in range (0,150,50):
        q=f"genre:latin_pop, year:{año}"
        print(q)

        print(año, "-", o)

        for dato in query['tracks']['items']: #recorremos los elementos
            artista = dato['artists'][0]['name']
            genero = 'latin pop'
            nombre = dato['name']
            tipo = dato['type']
            ano = dato['album']['release_date']
            spotify_id = dato['id']

            informacion_artista= {'Artista': artista, 'Género': 'latin pop', 'Tipo': tipo, 'Nombre': nombre, 'Año': ano,'ID': spotify_id} #creamos un diccionario con la info que queremos recopila de cada truck. nota: genero str

            lista_latin_pop.append(informacion_artista)
            #elimino brake para que me salgan todos los elementos de query

        print(lista_latin_pop)

genre:latin_pop, year:2000
2000 - 0
[{'Artista': 'Ricardo Arjona', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Iluso', 'Año': '2005-12-06', 'ID': '39FeHqemDNAlWn3C0VMowR'}, {'Artista': 'Aniceto Molina', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Popurri', 'Año': '2005-03-01', 'ID': '5ndbUsAt6oyeBhZZ4U1NH4'}, {'Artista': 'Lisa Ono', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'テ・キエロ・ディヒステ', 'Año': '2005-06-29', 'ID': '1xjGMWxSfbo7Eyjeb3mzNs'}, {'Artista': 'Shakira', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Dia Especial (feat. Gustavo Cerati)', 'Año': '2005-06-03', 'ID': '2EZ4NSQtoKdiWK8JDMY7NT'}, {'Artista': 'Shakira', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'En Tus Pupilas', 'Año': '2005-06-03', 'ID': '7046NJqL0E7v5THigdTOyE'}, {'Artista': 'The Pussycat Dolls', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Sway', 'Año': '2005-01-01', 'ID': '01xXQbDsWMJVBKOoKWXE8h'}, {'Artista': 'Shakira', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'La Pared', 'Año': '2005-06-03', 'ID': '35idKzsNHvyALKIZ9JHw47'}, {'Artista': 'Bacanos', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Te Doy Mi Amor', 'Año': '2005-05-05', 'ID': '5cgwBlY1oNdnuNsy4PaXAz'}, {'Artista': 'Ricardo Arjona', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Mojado', 'Año': '2005-12-06', 'ID': '5Qchpm6oOiHytt5dIk69Ij'}, {'Artista': 'Thalia', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Seduccion', 'Año': '2005-01-01', 'ID': '1YMr1YzK04rKlN8vt03nPP'}, {'Artista': 'Lisa Ono', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': '遠く離れても', 'Año': '2005-08-19', 'ID': '35i2XFc60eKVIu9SlRIRCH'}, {'Artista': 'Yahir', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'No te apartes de mí', 'Año': '2005-09-20', 'ID': '7EC5RB8EDJOWXcYlk9HLwr'}, {'Artista': 'RBD', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Fuera', 'Año': '2005-01-01', 'ID': '4haBiYrYQ7AbvQxlt1QahV'}, {'Artista': 'RBD', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Qué Hay Detrás', 'Año': '2005-01-01', 'ID': '5Ya2WSoqPdAkmohiRZgZGl'}, {'Artista': 'Calle Ciega', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Quiero', 'Año': '2005-01-01', 'ID': '3b11hXQgd8rXcROT2qRcJp'}, {'Artista': "La K'onga", 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'La Cabaña', 'Año': '2005-11-04', 'ID': '5TpGT4K34mBP6JcJfIgRqF'}, {'Artista': 'Ana Torroja', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'No Me Canso - Inedito', 'Año': '2005', 'ID': '2apIAlbkN6IgvucbM5PCdo'}, {'Artista': 'Ricardo Arjona', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'De Vez en Mes', 'Año': '2005-12-06', 'ID': '7dkw2lSgDwyhHZYoVgMclt'}, {'Artista': 'Shakira', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Obtener un Si', 'Año': '2005-06-03', 'ID': '0OUVKbGfxGA6rdvqwxwyWV'}, {'Artista': 'Sin Bandera', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'A Ti', 'Año': '2005-11-18', 'ID': '1EtN1I3hbkuIl6zka9XhJ3'}, {'Artista': 'Chayanne', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'No Te Preocupes por Mi', 'Año': '2005', 'ID': '0NN9TRTvceycUm8wq30yk8'}, {'Artista': 'Ha*Ash', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': '¿Qué Hago Yo?', 'Año': '2005', 'ID': '5fISatRSvu52jsmsnKwNfY'}, {'Artista': 'Lisa Ono', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'キエンセラ', 'Año': '2005-08-19', 'ID': '6pTh0DeJkVDvv1ytHlwDiA'}, {'Artista': 'Shakira', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Las de la Intuición', 'Año': '2005-06-03', 'ID': '7DnMd3BxVOedyOyR7K3F8L'}, {'Artista': 'Frecuencia Trio', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Popurri Kchaka Piru (Bailando Guararé / Anhelos / La Rosita / Mi Negra)', 'Año': '2005', 'ID': '64HTYIDH9Y6vW53FV6AoLg'}, {'Artista': 'Shakira', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'La Tortura (feat. Alejandro Sanz)', 'Año': '2005-06-03', 'ID': '53AafWSzYsiJKnAtJTUB5f'}, {'Artista': 'Fonseca', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Como Me Mira', 'Año': '2005-05-01', 'ID': '1OwZtvGw2BNYjmLHoGfrY4'}, {'Artista': 'Chayanne', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Te Echo de Menos', 'Año': '2005', 'ID': '5OkWLb3GzvjYUrhSpQFbvn'}, {'Artista': 'Shakira', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'No (feat. Gustavo Cerati)', 'Año': '2005-06-03', 'ID': '7CZkVQ8LsfDsu8STKAQfWY'}, {'Artista': 'Fanny Lu', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'No Te Pido Flores', 'Año': '2005-01-01', 'ID': '2ctc9nwRgXeeIFaFWTRrRl'}, {'Artista': 'Luis Miguel', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Te necesito', 'Año': '2005-12-02', 'ID': '6fM4uVlC2brb5Di9O1vvry'}, {'Artista': 'RBD', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Aún Hay Algo', 'Año': '2005-01-01', 'ID': '6fqpsCQ7jF7OgQolXgYovX'}, {'Artista': 'RBD', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Tras De Mí', 'Año': '2005-01-01', 'ID': '1AO5MeGsWdPLejY47pnYYy'}, {'Artista': 'Fonseca', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Hace Tiempo', 'Año': '2005-05-01', 'ID': '7G0Z77RdBTdf4bt45AL6yS'}, {'Artista': 'RBD', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Nuestro Amor', 'Año': '2005-01-01', 'ID': '7F7qwp7VZRVwZsNoddRRgX'}, {'Artista': 'Reik', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Qué Vida la Mía', 'Año': '2005-03-02', 'ID': '0M6KY0x5u65ybXHZ3IAega'}, {'Artista': 'Ricardo Arjona', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Pingüinos en la Cama', 'Año': '2005-12-06', 'ID': '73X4fA2RX6ycvEsFvDIUs4'}, {'Artista': 'RBD', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Este Corazón', 'Año': '2005-01-01', 'ID': '0bMVCO35RJiUhAfvFsLjIF'}, {'Artista': 'Reik', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Noviembre Sin Ti', 'Año': '2005-03-02', 'ID': '2vCHDrXVN0k1GPTjSIZ69E'}, {'Artista': 'Sin Bandera', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Suelta Mi Mano', 'Año': '2005-11-18', 'ID': '50xvGsnNmO3k5EtaUBXRRr'}, {'Artista': 'Fonseca', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Te Mando Flores', 'Año': '2005-05-01', 'ID': '2in1gSZtv2lRbcZUmN9aAl'}, {'Artista': 'Alejandro Fernández', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Popurrí Juan Gabriel / Ya Lo Sé Que Tú Te Vas / La Diferencia / Te Sigo Amando - En Vivo', 'Año': '2005-10-20', 'ID': '2APE7KXnCG2IFP66BVdZis'}, {'Artista': 'Shakira', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Día de Enero', 'Año': '2005-06-03', 'ID': '2u24GtkbktY3HB3souJdNY'}, {'Artista': 'Guaco', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Pídeme', 'Año': '2005-07-01', 'ID': '3dqgHG4Rksh3B04Dt3cVHu'}, {'Artista': 'Coti', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Nada Fue Un Error - Live In Spain / 2005', 'Año': '2005-01-01', 'ID': '7GO6pBFbieZ30NjGIp2LP5'}, {'Artista': 'Ricardo Arjona', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'A Ti', 'Año': '2005-12-06', 'ID': '5CcBo88PRHzJeQdiE5mBNi'}, {'Artista': 'Ricardo Arjona', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Acompáñame a Estar Solo', 'Año': '2005-12-06', 'ID': '5rwl9TKyjbAVSCUOBZz77Y'}, {'Artista': 'Lisa Ono', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'ベサメ・ムーチョ', 'Año': '2005-08-19', 'ID': '26nkboSGZauLZQJo2Ni1vA'}, {'Artista': 'Coti', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Nada Fue Un Error - Live In Spain / 2005', 'Año': '2005-01-01', 'ID': '15RAXEkBCh62ZB6xddv0wO'}, {'Artista': 'Reik', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Yo Quisiera', 'Año': '2005-03-02', 'ID': '2GSr8anleCXKLNjjjijoMZ'}]
genre:latin_pop, year:2000
2000 - 50

In [17]:
lista_latin_pop = [] #lista vacia antes del bucle

for ano in range(2000, 2005):
    for offset in range (0,150,50):
        
        query = sp.search(q=f"genre:latin pop, year:{ano}", type="track", limit=50, offset=offset)

        for dato in query['tracks']['items']:
            artista = dato['artists'][0]['name']
            genero = 'latin pop'
            nombre = dato['name']
            tipo = dato['type']
            ano = dato['album']['release_date'][:4]
            spotify_id = dato['id']

            informacion_artista= {'Artista': artista, 'Género': 'latin pop', 'Tipo': tipo, 'Nombre': nombre, 'Año': ano,'ID': spotify_id} #creamos un diccionario con la info que queremos recopila de cada truck. nota: genero str

            lista_latin_pop.append(informacion_artista)

print(lista_latin_pop)

[{'Artista': 'La Oreja de Van Gogh', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Pop', 'Año': '2000', 'ID': '4FXSEdmbbeGmPIQltH27C8'}, {'Artista': 'Ricky Martin', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'She Bangs - Spanish Version', 'Año': '2000', 'ID': '4ti5pZ0zs1PDf1eQswskFB'}, {'Artista': 'Thalia', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Entre El Mar Y Una Estrella', 'Año': '2000', 'ID': '2KNtKG2X0jpOIgVunVbAkQ'}, {'Artista': 'Rodrigo', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Fuego y Pasion', 'Año': '2000', 'ID': '0SBHkYiZh8ih1RHoOcDtHl'}, {'Artista': 'Rodrigo', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Como Le Digo', 'Año': '2000', 'ID': '4nH1lpWkgzQPpTYPPjWKaI'}, {'Artista': 'Paulina Rubio', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Tal Vez Quizas', 'Año': '2000', 'ID': '4Ft4AbNwk1acKagaBOmvHb'}, {'Artista': 'Los Tucanes De Tijuana', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Mis Tres Viejas', 'Año': '2000', 'ID': '1yxJIFPhP2EqnQ6oWJKbmP'}, {'Artista': 'Rodrigo', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Soy Cordobes', 'Año': '2000', 'ID': '5wG4J1UECH0c42YhMhSkcS'}, {'Artista': 'Rodrigo', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Amor Clasificado', 'Año': '2000', 'ID': '5MK642wCaNr9hRDZ3kWyDX'}, {'Artista': 'Alejandro Sanz', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Cuando nadie me ve - Maqueta', 'Año': '2000', 'ID': '7IxcEDXDSefpahEg6zmDs5'}, {'Artista': 'Thalia', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Regresa A Mi', 'Año': '2000', 'ID': '36GbwUTkCSQ18aysIFYEPF'}, {'Artista': 'Chayanne', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Candela', 'Año': '2000', 'ID': '6aZVaIudGaHm88ydUe9k4i'}, {'Artista': 'Celia Cruz', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': "Celia's Oye Como Va (Oye Como Va)", 'Año': '2000', 'ID': '7fhCXXF7V5jsU06bOgVBqJ'}, {'Artista': 'Juanes', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Fijate Bien', 'Año': '2000', 'ID': '3wE4fvPhhScUAhY37TDc1D'}, {'Artista': 'Chayanne', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Boom Boom', 'Año': '2000', 'ID': '4zkOTmiamebLJ39Sqbp7sb'}, {'Artista': 'Chayanne', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Salomé', 'Año': '2000', 'ID': '4l8i9h5PNoJte95Es3HftJ'}, {'Artista': 'Rodrigo', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Que Ironia', 'Año': '2000', 'ID': '0E9YlthbJZ6WOPKi3LTBJc'}, {'Artista': 'Ana Torroja', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Duende', 'Año': '2000', 'ID': '3WX2KhnJq3QdRTfPgHWgZU'}, {'Artista': 'Laura Pausini', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Un error de los grandes', 'Año': '2000', 'ID': '0cZRvN0JNRbkmhJK90x4cH'}, {'Artista': 'Alejandro Sanz', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Me iré', 'Año': '2000', 'ID': '42t0ZnBaS3dYFcs3xyQF2Y'}, {'Artista': 'La Oreja de Van Gogh', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Tantas Cosas Que Contar', 'Año': '2000', 'ID': '09oZXunRcHWgNc4jYxDeue'}, {'Artista': 'Chayanne', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Mariana Mambo', 'Año': '2000', 'ID': '3ppKW2voPfRuCtdWhF1R9z'}, {'Artista': 'Armando Manzanero', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Esperaré (feat. Café Quijano)', 'Año': '2000', 'ID': '4RclcYWxQMRsdmT25OK9ic'}, {'Artista': 'Paulina Rubio', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'El Ultimo Adios', 'Año': '2000', 'ID': '7lnun6viJADQCvZnE0w9q8'}, {'Artista': 'Donato Y Estefano', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Sin Ti', 'Año': '2000', 'ID': '3c9KuwSygZBPj6gbXLxRc7'}, {'Artista': 'Ana Torroja', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Corazones', 'Año': '2000', 'ID': '6cbvo1vIHJZfIXrGxOzza9'}, {'Artista': 'Alejandro Sanz', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Hay un universo de pequeñas cosas', 'Año': '2000', 'ID': '5JA04DokXsoCNcVPI9NRmD'}, {'Artista': 'Paulina Rubio', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Lo Haré Por Ti', 'Año': '2000', 'ID': '2j0vCRV8XySsYHDYasQwbi'}, {'Artista': 'Alejandro Sanz', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Para que me quieras', 'Año': '2000', 'ID': '3QYWYwpcCdf5f5DQW52oaz'}, {'Artista': 'Christina Aguilera', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Ven Conmigo (Solamente Tú)', 'Año': '2000', 'ID': '2PYJnUWEPPP8C6b79UiwIl'}, {'Artista': 'Gloria Estefan', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Como Me Duele Perderte', 'Año': '2000', 'ID': '7deJdnhCWumMOBJtXeIVyN'}, {'Artista': 'Chayanne', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Yo Te Amo', 'Año': '2000', 'ID': '2sKo5u6IppUEudIz265wYa'}, {'Artista': 'Celia Cruz', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Rie y Llora', 'Año': '2000', 'ID': '63knvuoSPpfzIwdDuWRSoV'}, {'Artista': 'Alejandro Sanz', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'El alma al aire', 'Año': '2000', 'ID': '0Bs7Y5vCIzuvFTS9SLBPn8'}, {'Artista': 'La Oreja de Van Gogh', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Tu Pelo', 'Año': '2000', 'ID': '36wsPM9GCrgt9pxS95PYr2'}, {'Artista': 'Christina Aguilera', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Genio Atrapado', 'Año': '2000', 'ID': '3ne8ipFCs7RUr2K6QoD6BQ'}, {'Artista': 'La Oreja de Van Gogh', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Paris', 'Año': '2000', 'ID': '5ByvJeBlrYISiwy7AVEAmP'}, {'Artista': 'Eros Ramazzotti', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Fuego en el Fuego', 'Año': '2000', 'ID': '3P8ruszvU7rSrL6rrGbLUQ'}, {'Artista': 'Paulina Rubio', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Y Yo Sigo Aqui - Spanglish', 'Año': '2000', 'ID': '2Ma2f8jV8VKMJoAcnCvZ8h'}, {'Artista': 'Paulina Rubio', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Yo No Soy Esa Mujer', 'Año': '2000', 'ID': '0JAGODD5w6MeYQzA9lV6Zm'}, {'Artista': 'Thalia', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Arrasando', 'Año': '2000', 'ID': '1EhDeCHd34jt7dMDqkGQBC'}, {'Artista': 'La Oreja de Van Gogh', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Cuídate', 'Año': '2000', 'ID': '7gqIqyeCaV2xNtfZWxEphD'}, {'Artista': 'La Oreja de Van Gogh', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'La Chica del Gorro Azul', 'Año': '2000', 'ID': '3MtGBLot4sqvpT0cDyWTC8'}, {'Artista': 'La Oreja de Van Gogh', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'La Playa', 'Año': '2000', 'ID': '2DNyZP4Py6f4zMASLBnIu6'}, {'Artista': 'La Oreja de Van Gogh', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Dicen Que Dicen', 'Año': '2000', 'ID': '69sZqRBNGrcRHZBFkvlRGW'}, {'Artista': 'La Oreja de Van Gogh', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Mariposa', 'Año': '2000', 'ID': '50CFzmM2N9wxobKcURrZdw'}, {'Artista': 'Eros Ramazzotti', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Fuego en el Fuego', 'Año': '2000', 'ID': '5zGJT3TTShcNHeJeDrjPvs'}, {'Artista': 'La Oreja de Van Gogh', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Soledad', 'Año': '2000', 'ID': '4NLpfB52hwDPLn7bphgjgD'}, {'Artista': 'Alejandro Sanz', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Cuando nadie me ve', 'Año': '2000', 'ID': '7sNpt6AvOvXXZVaqTCFVCu'}, {'Artista': 'Alejandro Sanz', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Quisiera ser', 'Año': '2000', 'ID': '2MnNZIetVS8IVfy9PtpLeb'}, {'Artista': 'El Cuarteto De Nos', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Cristo Te Odia', 'Año': '2000', 'ID': '6nGheW6QepWxeMuwkPLDfS'}, {'Artista': 'Los Tucanes De Tijuana', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Gripa Colombiana', 'Año': '2000', 'ID': '33Kxt0fCaltxIuIOzM7hfs'}, {'Artista': 'El Cuarteto De Nos', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'La Pequeña Leti', 'Año': '2000', 'ID': '1NisqP9RbbUN7IR3rw83EE'}, {'Artista': 'Ricardo Arjona', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Sólo Quería un Café', 'Año': '2000', 'ID': '2kWYn9WboACIhmjQWRwMMX'}, {'Artista': 'Paulina Rubio', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Sexi Dance', 'Año': '2000', 'ID': '2HUMe9s1Sn8ZrpsbmDjEAH'}, {'Artista': 'Celia Cruz', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': "Celia's Oye Como Va (Oye Como Va)", 'Año': '2000', 'ID': '21pnPg1UFfvVpLInYio1sR'}, {'Artista': 'Jean Carlos', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Tu Vas a Volar', 'Año': '2000', 'ID': '5aarNSF6jcTWgC8L25kpYi'}, {'Artista': 'Banda XXI', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Quiero Saber De Ti', 'Año': '2000', 'ID': '68mzTYsp45l51K37Tv3V8r'}, {'Artista': 'Nek', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'La vida es', 'Año': '2000', 'ID': '2KV7Z8NrqJTSq206nKiGGf'}, {'Artista': 'Los Tucanes De Tijuana', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Cien Por Uno', 'Año': '2000', 'ID': '64VeKDD6z3P2UnDl8nphc4'}, {'Artista': 'Walter Olmos', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Amor Fugitivo', 'Año': '2000', 'ID': '5inaJ88bGKl7HkA9S7ktmV'}, {'Artista': 'Walter Olmos', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Adicto A Ti', 'Año': '2000', 'ID': '53p8lIxLmoCoBINK0zuQ4G'}, {'Artista': 'Rodrigo', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Por Lo Que Yo Te Quiero', 'Año': '2000', 'ID': '5i9yLs9LPercK6BJgj87gj'}, {'Artista': 'Beto Quintanilla', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Escolta Suicida', 'Año': '2000', 'ID': '4P26HKA1ijPe4o7NQqkHlP'}, {'Artista': 'Alejandro Sanz', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Una noche (feat. The Corrs)', 'Año': '2000', 'ID': '1QHK82whaHGYWfARl21hUs'}, {'Artista': 'Rodrigo', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'El Viaje', 'Año': '2000', 'ID': '6yBiLjtUHxkO5OJFuSRIeK'}, {'Artista': 'Rodrigo', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Yerba Mala', 'Año': '2000', 'ID': '6DAZuerCWNL5TtgKo8M2jl'}, {'Artista': 'Luis Alberto Posada', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Corazón Partido', 'Año': '2000', 'ID': '2XjKVBc0FnVE2IQNYusZg5'}, {'Artista': 'Rodrigo', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Aprendiz', 'Año': '2000', 'ID': '3zOKIMB5FOUtlhYB3nqEJY'}, {'Artista': 'Rodrigo', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'La mano de Dios (Homenaje a Diego Maradona)', 'Año': '2000', 'ID': '6bQkinbnTaWeLtMObzIxf0'}, {'Artista': 'El Cuarteto De Nos', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Necesito Una Mujer', 'Año': '2000', 'ID': '7d6hieV5hQnqZNYnrYfjob'}, {'Artista': 'Alejandro Sanz', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Llega, llegó soledad', 'Año': '2000', 'ID': '7e7ojN0bPRY4b9y7yuE40Y'}, {'Artista': 'Thalia', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Rosalinda', 'Año': '2000', 'ID': '4KufWaE6epxrctKlrfVsQh'}, {'Artista': 'Ana Torroja', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Hacer por hacer', 'Año': '2000', 'ID': '3bJMFkv8AhKbE9CDJYp5G8'}, {'Artista': 'Ana Torroja', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Nada particular', 'Año': '2000', 'ID': '3EL9ISVp1tp06Euqc8492e'}, {'Artista': 'El Cuarteto De Nos', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Pegame Y Decime Shirley', 'Año': '2000', 'ID': '5OPEU3148saJYZplRlZn8U'}, {'Artista': 'Ana Torroja', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Siete de septiembre', 'Año': '2000', 'ID': '6fzT2ceqglZpffBISnqM7w'}, {'Artista': 'Fey', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Azúcar Amargo', 'Año': '2000', 'ID': '2arXuCWrLfgcELqYogQDbt'}, {'Artista': 'Celia Cruz', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Por Si Acaso No Regreso', 'Año': '2000', 'ID': '1n52ulXSj7E3GOjcpw1EKF'}, {'Artista': 'Debelah Morgan', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Dance with Me', 'Año': '2000', 'ID': '1C2Q3AymKS17bw7T5gfq6p'}, {'Artista': 'Ana Torroja', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Amante bandido', 'Año': '2000', 'ID': '2lMAx2mhNdHdgw0qDZ2PSB'}, {'Artista': 'Ana Torroja', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Mujer contra mujer', 'Año': '2000', 'ID': '68RZ0w4gdgXVWKpooGcYWl'}, {'Artista': 'Paulina Rubio', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Vive El Verano', 'Año': '2000', 'ID': '13hnZOARWepu30E9lhn4jO'}, {'Artista': 'Rey Ruiz', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Muevelo', 'Año': '2000', 'ID': '2z7qJyoZCeNUyyt7z0Ha1U'}, {'Artista': 'Ana Torroja', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'A contratiempo', 'Año': '2000', 'ID': '7zDsplBsyc0cyZoR9AJYWt'}, {'Artista': 'Thalia', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Reencarnacion', 'Año': '2000', 'ID': '1iT6VaEqoBLCQcAYH75jOC'}, {'Artista': 'Walter Olmos', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'No Me Mientas', 'Año': '2000', 'ID': '0mYPt9hLmZZvqWAbR9SdNj'}, {'Artista': 'Ana Torroja', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Si tú no vuelves', 'Año': '2000', 'ID': '07HhvYazaf4LyXNKpmDb5J'}, {'Artista': 'Bertin Osborne', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Popurrí Mexicano', 'Año': '2000', 'ID': '6vV6BhzqwsuFFRBh1L0mOq'}, {'Artista': 'Alejandro Sanz', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'El alma al aire - Maqueta', 'Año': '2000', 'ID': '0J1X8DvOXj0GD07UN3kyci'}, {'Artista': 'Chayanne', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Ay Mama', 'Año': '2000', 'ID': '3x7w1y7WLU7lpCSh39VSrZ'}, {'Artista': 'Alejandro Sanz', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Hicimos un trato', 'Año': '2000', 'ID': '6AF3xHHs3tmL7JN8lkNkgR'}, {'Artista': 'La Retrocumbia', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Popurri - Cartagenera - El orangutan - No te vayas - La Piragua - Cumbia sobre el mar', 'Año': '2000', 'ID': '0PDd6bNpNQdJXQhvNWSC3O'}, {'Artista': 'La Retrocumbia', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Popurri - Alejate de mi - Mentiras, mientras - Muchacha ojos de miel', 'Año': '2000', 'ID': '3vWUFIYGhO5AH4jvgVouPv'}, {'Artista': 'La Gran Banda', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Popurri Romantico', 'Año': '2000', 'ID': '312V3J3wZS2wv53UsD97oy'}, {'Artista': 'Luis Alberto Posada', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Cruz de Dolor', 'Año': '2000', 'ID': '5GODB1nafsfms7LyFymC4V'}, {'Artista': 'Luis Alberto Posada', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'No Soy un Juguete', 'Año': '2000', 'ID': '7JoZyPwW1w1TjoO5yrzks0'}, {'Artista': 'La Retrocumbia', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Popurri - La Negra Salome - Juana la Cubana', 'Año': '2000', 'ID': '3MqI7CgT8Y57MbbcvbT5pX'}, {'Artista': 'La Retrocumbia', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Popurri - Las chiquillas - La Revoltosa - El Parrandero - Pajaro del monte', 'Año': '2000', 'ID': '5oWiYUPBnKii0nuqfzr30o'}, {'Artista': 'La Retrocumbia', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Popurri - El pescador - Todos los domingos - Atrevete a mirarme de frente - Santa Martha - Se va el caiman - La Burrita - Quiero un sombrero - Para que', 'Año': '2000', 'ID': '52b25x2jxiV9Iapiq2ni6s'}, {'Artista': 'Los Razos', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Chingon De Chingones', 'Año': '2000', 'ID': '5lduUBDO2K74wlWcReMTJ8'}, {'Artista': 'Walter Olmos', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Chico De La Calle', 'Año': '2000', 'ID': '4zmK84b3QtttgoP5mNZpse'}, {'Artista': 'Beto Quintanilla', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'El Plebe y el Cholo', 'Año': '2000', 'ID': '2jR8SDgmlxxxsiJ2iwd6Ms'}, {'Artista': 'Walter Olmos', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Extrañándote', 'Año': '2000', 'ID': '0zXjhiCo3x42xLcxK0GoFf'}, {'Artista': 'Walter Olmos', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Por Lo Que Yo Te Quiero', 'Año': '2000', 'ID': '3dKjmF3Yjl79hybcSkE9M5'}, {'Artista': 'Beto Quintanilla', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Raquenel Villanueva', 'Año': '2000', 'ID': '71rQncW9uGaAg4QplpEbeL'}, {'Artista': 'Alejandro Sanz', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'El alma al aire', 'Año': '2000', 'ID': '0JDTLHMnltIIVnXi72RTom'}, {'Artista': 'Chayanne', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Simplemente', 'Año': '2000', 'ID': '1bMQ3pR8fxeAAVg4TwXPrM'}, {'Artista': 'Alejandro Sanz', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Cuando nadie me ve', 'Año': '2000', 'ID': '0bfPmBR6iN2cyJQJUUQOG0'}, {'Artista': 'Donato Y Estefano', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Toma Tu Tiempo Y Suena', 'Año': '2000', 'ID': '3ANzgIoMEW7KobbWrA6crP'}, {'Artista': 'El Cuarteto De Nos', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Me Amo', 'Año': '2000', 'ID': '5aRef1fGbwM1t0MqXSrwzV'}, {'Artista': 'Ana Torroja', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Un año más', 'Año': '2000', 'ID': '58dwFuu8GK2Gnab1ucCSlj'}, {'Artista': 'Jean Carlos', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'A Puro Dolor', 'Año': '2000', 'ID': '2K5ureC8z6V2dAtj0B8ASW'}, {'Artista': 'La Oreja de Van Gogh', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Rosas', 'Año': '2000', 'ID': '0iCTZBrskLb7xIZBuGcNrn'}, {'Artista': 'Julio Iglesias', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'No Es Amor Ni Es Amar (Gone Too Far)', 'Año': '2000', 'ID': '3yggjuzrpJ9qNnVuz6va83'}, {'Artista': 'Chayanne', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Hasta Que El Alma Resista', 'Año': '2000', 'ID': '24roOHa0bnZSohbWE7Ligd'}, {'Artista': 'Donato Y Estefano', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Naturaleza', 'Año': '2000', 'ID': '6oGgP96pCoPGVH9WhFZus0'}, {'Artista': 'Juanes', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Podemos Hacernos Daño', 'Año': '2000', 'ID': '4dK3GtjIEt42iVHo3qjMss'}, {'Artista': 'Ana Torroja', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Bambú', 'Año': '2000', 'ID': '1TuvKksFlFgn6D3VkGUhPs'}, {'Artista': 'Jimmy Bosch', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': "Pa' Mantener Tradición", 'Año': '2000', 'ID': '5m9rNQ7CqWffaZGBXTF98n'}, {'Artista': 'Ana Torroja', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Muro', 'Año': '2000', 'ID': '4KYnziYaVyyM2KHT2hZfZI'}, {'Artista': 'Banda XXI', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Y Te Amo Solo', 'Año': '2000', 'ID': '78Of4ie3Av5b8BKSf8CG6H'}, {'Artista': 'Shakira', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'No Creo - En Vivo', 'Año': '2000', 'ID': '1GM2ouHHKW3tuCzjSZKIyr'}, {'Artista': 'Ricky Martin', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Dame Más (Loaded) - Spanish Edit', 'Año': '2000', 'ID': '3zBP6rvzlBtcn1gEsgzeBI'}, {'Artista': 'Ana Torroja', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Salamandra', 'Año': '2000', 'ID': '6dLlU2XOMZLWoXrKA9baY8'}, {'Artista': 'Donato Y Estefano', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Entre La Linea Del Bien Y La Linea Del Mal', 'Año': '2000', 'ID': '4iKnaiZ1Rb1emdpboOte67'}, {'Artista': 'Luis Alberto Posada', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Negros Recuerdos', 'Año': '2000', 'ID': '2eaqczOTq5cAAZxIdbkYr9'}, {'Artista': 'Donato Y Estefano', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Y Bailo', 'Año': '2000', 'ID': '4qrhU545tqm3RHvNrql1YA'}, {'Artista': 'Ana Torroja', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Nena', 'Año': '2000', 'ID': '05lfAUHuoiSTGESSyLbiZ4'}, {'Artista': 'Alejandro Sanz', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Silencio (Ghost Track)', 'Año': '2000', 'ID': '41IpfXrlcy5uVYLHSD4hw1'}, {'Artista': 'Issac Delgado', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': "Popourri Pa'l Sonero", 'Año': '2000', 'ID': '13ViPREtq0llZeSbArTKno'}, {'Artista': 'Nek', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Llegas tu', 'Año': '2000', 'ID': '3YX0QfZP4EhzAc4PmlUlTS'}, {'Artista': 'Juanes', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Nada', 'Año': '2000', 'ID': '0fxLW78I51KMo6SNMm7Fcg'}, {'Artista': 'La Mosca', 'Género': 'latin pop', 'Tipo': 'track', 'Nombre': 'Cha Cha Cha', 'Año': '2000', 'ID': '36in1jDriTe1PQhU4iTKkv'}, {'Artista': 'Ana Torroja', 'Género': 'latin pop', 'Tipo': 't

In [18]:
df_latin_pop = pd.DataFrame(lista_latin_pop) 

df_latin_pop

,Artista,Género,Tipo,Nombre,Año,ID
0,La Oreja de Van Gogh,latin pop,track,Pop,2000,4FXSEdmbbeGmPIQltH27C8
1,Ricky Martin,latin pop,track,She Bangs - Spanish Version,2000,4ti5pZ0zs1PDf1eQswskFB
2,Thalia,latin pop,track,Entre El Mar Y Una Estrella,2000,2KNtKG2X0jpOIgVunVbAkQ
3,Rodrigo,latin pop,track,Fuego y Pasion,2000,0SBHkYiZh8ih1RHoOcDtHl
4,Rodrigo,latin pop,track,Como Le Digo,2000,4nH1lpWkgzQPpTYPPjWKaI
...,...,...,...,...,...,...
745,Alejandro Sanz,latin pop,track,El alma al aire,2004,7s4ggtq4icIPCo9wLk5vss
746,Carlos Vives,latin pop,track,La Maravilla,2004,5Jivv7trOtgHlnaNAiPEnN
747,Franco De Vita,latin pop,track,Ay Dios,2004,0Sd0bKypMwcUTUgHH9TCov
748,Yahir,latin pop,track,La Locura,2004,5HSoliYp4FmKDilRXndbc4
749,Alejandro Sanz,latin pop,track,Y sólo se me ocurre amarte,2004,3zvnloMEkCiIFRsZDUJPaW

In [ ]:
## convierto en json para poder exportarlo

In [19]:
lista_latin_pop

json_lista_latin_pop = json.dumps(lista_latin_pop)

In [20]:
json_lista_latin_pop

'[{"Artista": "La Oreja de Van Gogh", "G\\u00e9nero": "latin pop", "Tipo": "track", "Nombre": "Pop", "A\\u00f1o": "2000", "ID": "4FXSEdmbbeGmPIQltH27C8"}, {"Artista": "Ricky Martin", "G\\u00e9nero": "latin pop", "Tipo": "track", "Nombre": "She Bangs - Spanish Version", "A\\u00f1o": "2000", "ID": "4ti5pZ0zs1PDf1eQswskFB"}, {"Artista": "Thalia", "G\\u00e9nero": "latin pop", "Tipo": "track", "Nombre": "Entre El Mar Y Una Estrella", "A\\u00f1o": "2000", "ID": "2KNtKG2X0jpOIgVunVbAkQ"}, {"Artista": "Rodrigo", "G\\u00e9nero": "latin pop", "Tipo": "track", "Nombre": "Fuego y Pasion", "A\\u00f1o": "2000", "ID": "0SBHkYiZh8ih1RHoOcDtHl"}, {"Artista": "Rodrigo", "G\\u00e9nero": "latin pop", "Tipo": "track", "Nombre": "Como Le Digo", "A\\u00f1o": "2000", "ID": "4nH1lpWkgzQPpTYPPjWKaI"}, {"Artista": "Paulina Rubio", "G\\u00e9nero": "latin pop", "Tipo": "track", "Nombre": "Tal Vez Quizas", "A\\u00f1o": "2000", "ID": "4Ft4AbNwk1acKagaBOmvHb"}, {"Artista": "Los Tucanes De Tijuana", "G\\u00e9nero": "latin pop", "Tipo": "track", "Nombre": "Mis Tres Viejas", "A\\u00f1o": "2000", "ID": "1yxJIFPhP2EqnQ6oWJKbmP"}, {"Artista": "Rodrigo", "G\\u00e9nero": "latin pop", "Tipo": "track", "Nombre": "Soy Cordobes", "A\\u00f1o": "2000", "ID": "5wG4J1UECH0c42YhMhSkcS"}, {"Artista": "Rodrigo", "G\\u00e9nero": "latin pop", "Tipo": "track", "Nombre": "Amor Clasificado", "A\\u00f1o": "2000", "ID": "5MK642wCaNr9hRDZ3kWyDX"}, {"Artista": "Alejandro Sanz", "G\\u00e9nero": "latin pop", "Tipo": "track", "Nombre": "Cuando nadie me ve - Maqueta", "A\\u00f1o": "2000", "ID": "7IxcEDXDSefpahEg6zmDs5"}, {"Artista": "Thalia", "G\\u00e9nero": "latin pop", "Tipo": "track", "Nombre": "Regresa A Mi", "A\\u00f1o": "2000", "ID": "36GbwUTkCSQ18aysIFYEPF"}, {"Artista": "Chayanne", "G\\u00e9nero": "latin pop", "Tipo": "track", "Nombre": "Candela", "A\\u00f1o": "2000", "ID": "6aZVaIudGaHm88ydUe9k4i"}, {"Artista": "Celia Cruz", "G\\u00e9nero": "latin pop", "Tipo": "track", "Nombre": "Celia\'s Oye Como Va (Oye Como Va)", "A\\u00f1o": "2000", "ID": "7fhCXXF7V5jsU06bOgVBqJ"}, {"Artista": "Juanes", "G\\u00e9nero": "latin pop", "Tipo": "track", "Nombre": "Fijate Bien", "A\\u00f1o": "2000", "ID": "3wE4fvPhhScUAhY37TDc1D"}, {"Artista": "Chayanne", "G\\u00e9nero": "latin pop", "Tipo": "track", "Nombre": "Boom Boom", "A\\u00f1o": "2000", "ID": "4zkOTmiamebLJ39Sqbp7sb"}, {"Artista": "Chayanne", "G\\u00e9nero": "latin pop", "Tipo": "track", "Nombre": "Salom\\u00e9", "A\\u00f1o": "2000", "ID": "4l8i9h5PNoJte95Es3HftJ"}, {"Artista": "Rodrigo", "G\\u00e9nero": "latin pop", "Tipo": "track", "Nombre": "Que Ironia", "A\\u00f1o": "2000", "ID": "0E9YlthbJZ6WOPKi3LTBJc"}, {"Artista": "Ana Torroja", "G\\u00e9nero": "latin pop", "Tipo": "track", "Nombre": "Duende", "A\\u00f1o": "2000", "ID": "3WX2KhnJq3QdRTfPgHWgZU"}, {"Artista": "Laura Pausini", "G\\u00e9nero": "latin pop", "Tipo": "track", "Nombre": "Un error de los grandes", "A\\u00f1o": "2000", "ID": "0cZRvN0JNRbkmhJK90x4cH"}, {"Artista": "Alejandro Sanz", "G\\u00e9nero": "latin pop", "Tipo": "track", "Nombre": "Me ir\\u00e9", "A\\u00f1o": "2000", "ID": "42t0ZnBaS3dYFcs3xyQF2Y"}, {"Artista": "La Oreja de Van Gogh", "G\\u00e9nero": "latin pop", "Tipo": "track", "Nombre": "Tantas Cosas Que Contar", "A\\u00f1o": "2000", "ID": "09oZXunRcHWgNc4jYxDeue"}, {"Artista": "Chayanne", "G\\u00e9nero": "latin pop", "Tipo": "track", "Nombre": "Mariana Mambo", "A\\u00f1o": "2000", "ID": "3ppKW2voPfRuCtdWhF1R9z"}, {"Artista": "Armando Manzanero", "G\\u00e9nero": "latin pop", "Tipo": "track", "Nombre": "Esperar\\u00e9 (feat. Caf\\u00e9 Quijano)", "A\\u00f1o": "2000", "ID": "4RclcYWxQMRsdmT25OK9ic"}, {"Artista": "Paulina Rubio", "G\\u00e9nero": "latin pop", "Tipo": "track", "Nombre": "El Ultimo Adios", "A\\u00f1o": "2000", "ID": "7lnun6viJADQCvZnE0w9q8"}, {"Artista": "Donato Y Estefano", "G\\u00e9nero": "latin pop", "Tipo": "track", "Nombre": "Sin Ti", "A\\u00f1o": "2000", "ID": "3c9KuwSygZBPj6gbXLxRc7"}, {"Artista": "Ana Torroja", "G\\u00e9nero": "latin pop", "Tipo": "track", "Nombre": "Corazones", "A\\u00f1o": "2000", "ID": "6cbvo1vIHJZfIXrGxOzza9"}, {"Artista": "Alejandro Sanz", "G\\u00e9nero": "latin pop", "Tipo": "track", "Nombre": "Hay un universo de peque\\u00f1as cosas", "A\\u00f1o": "2000", "ID": "5JA04DokXsoCNcVPI9NRmD"}, {"Artista": "Paulina Rubio", "G\\u00e9nero": "latin pop", "Tipo": "track", "Nombre": "Lo Har\\u00e9 Por Ti", "A\\u00f1o": "2000", "ID": "2j0vCRV8XySsYHDYasQwbi"}, {"Artista": "Alejandro Sanz", "G\\u00e9nero": "latin pop", "Tipo": "track", "Nombre": "Para que me quieras", "A\\u00f1o": "2000", "ID": "3QYWYwpcCdf5f5DQW52oaz"}, {"Artista": "Christina Aguilera", "G\\u00e9nero": "latin pop", "Tipo": "track", "Nombre": "Ven Conmigo (Solamente T\\u00fa)", "A\\u00f1o": "2000", "ID": "2PYJnUWEPPP8C6b79UiwIl"}, {"Artista": "Gloria Estefan", "G\\u00e9nero": "latin pop", "Tipo": "track", "Nombre": "Como Me Duele Perderte", "A\\u00f1o": "2000", "ID": "7deJdnhCWumMOBJtXeIVyN"}, {"Artista": "Chayanne", "G\\u00e9nero": "latin pop", "Tipo": "track", "Nombre": "Yo Te Amo", "A\\u00f1o": "2000", "ID": "2sKo5u6IppUEudIz265wYa"}, {"Artista": "Celia Cruz", "G\\u00e9nero": "latin pop", "Tipo": "track", "Nombre": "Rie y Llora", "A\\u00f1o": "2000", "ID": "63knvuoSPpfzIwdDuWRSoV"}, {"Artista": "Alejandro Sanz", "G\\u00e9nero": "latin pop", "Tipo": "track", "Nombre": "El alma al aire", "A\\u00f1o": "2000", "ID": "0Bs7Y5vCIzuvFTS9SLBPn8"}, {"Artista": "La Oreja de Van Gogh", "G\\u00e9nero": "latin pop", "Tipo": "track", "Nombre": "Tu Pelo", "A\\u00f1o": "2000", "ID": "36wsPM9GCrgt9pxS95PYr2"}, {"Artista": "Christina Aguilera", "G\\u00e9nero": "latin pop", "Tipo": "track", "Nombre": "Genio Atrapado", "A\\u00f1o": "2000", "ID": "3ne8ipFCs7RUr2K6QoD6BQ"}, {"Artista": "La Oreja de Van Gogh", "G\\u00e9nero": "latin pop", "Tipo": "track", "Nombre": "Paris", "A\\u00f1o": "2000", "ID": "5ByvJeBlrYISiwy7AVEAmP"}, {"Artista": "Eros Ramazzotti", "G\\u00e9nero": "latin pop", "Tipo": "track", "Nombre": "Fuego en el Fuego", "A\\u00f1o": "2000", "ID": "3P8ruszvU7rSrL6rrGbLUQ"}, {"Artista": "Paulina Rubio", "G\\u00e9nero": "latin pop", "Tipo": "track", "Nombre": "Y Yo Sigo Aqui - Spanglish", "A\\u00f1o": "2000", "ID": "2Ma2f8jV8VKMJoAcnCvZ8h"}, {"Artista": "Paulina Rubio", "G\\u00e9nero": "latin pop", "Tipo": "track", "Nombre": "Yo No Soy Esa Mujer", "A\\u00f1o": "2000", "ID": "0JAGODD5w6MeYQzA9lV6Zm"}, {"Artista": "Thalia", "G\\u00e9nero": "latin pop", "Tipo": "track", "Nombre": "Arrasando", "A\\u00f1o": "2000", "ID": "1EhDeCHd34jt7dMDqkGQBC"}, {"Artista": "La Oreja de Van Gogh", "G\\u00e9nero": "latin pop", "Tipo": "track", "Nombre": "Cu\\u00eddate", "A\\u00f1o": "2000", "ID": "7gqIqyeCaV2xNtfZWxEphD"}, {"Artista": "La Oreja de Van Gogh", "G\\u00e9nero": "latin pop", "Tipo": "track", "Nombre": "La Chica del Gorro Azul", "A\\u00f1o": "2000", "ID": "3MtGBLot4sqvpT0cDyWTC8"}, {"Artista": "La Oreja de Van Gogh", "G\\u00e9nero": "latin pop", "Tipo": "track", "Nombre": "La Playa", "A\\u00f1o": "2000", "ID": "2DNyZP4Py6f4zMASLBnIu6"}, {"Artista": "La Oreja de Van Gogh", "G\\u00e9nero": "latin pop", "Tipo": "track", "Nombre": "Dicen Que Dicen", "A\\u00f1o": "2000", "ID": "69sZqRBNGrcRHZBFkvlRGW"}, {"Artista": "La Oreja de Van Gogh", "G\\u00e9nero": "latin pop", "Tipo": "track", "Nombre": "Mariposa", "A\\u00f1o": "2000", "ID": "50CFzmM2N9wxobKcURrZdw"}, {"Artista": "Eros Ramazzotti", "G\\u00e9nero": "latin pop", "Tipo": "track", "Nombre": "Fuego en el Fuego", "A\\u00f1o": "2000", "ID": "5zGJT3TTShcNHeJeDrjPvs"}, {"Artista": "La Oreja de Van Gogh", "G\\u00e9nero": "latin pop", "Tipo": "track", "Nombre": "Soledad", "A\\u00f1o": "2000", "ID": "4NLpfB52hwDPLn7bphgjgD"}, {"Artista": "Alejandro Sanz", "G\\u00e9nero": "latin pop", "Tipo": "track", "Nombre": "Cuando nadie me ve", "A\\u00f1o": "2000", "ID": "7sNpt6AvOvXXZVaqTCFVCu"}, {"Artista": "Alejandro Sanz", "G\\u00e9nero": "latin pop", "Tipo": "track", "Nombre": "Quisiera ser", "A\\u00f1o": "2000", "ID": "2MnNZIetVS8IVfy9PtpLeb"}, {"Artista": "El Cuarteto De Nos", "G\\u00e9nero": "latin pop", "Tipo": "track", "Nombre": "Cristo Te Odia", "A\\u00f1o": "2000", "ID": "6nGheW6QepWxeMuwkPLDfS"}, {"Artista": "Los Tucanes De Tijuana", "G\\u00e9nero": "latin pop", "Tipo": "track", "Nombre": "Gripa Colombiana", "A\\u00f1o": "2000", "ID": "33Kxt0fCaltxIuIOzM7hfs"}, {"Artista": "El Cuarteto De Nos", "G\\u00e9nero": "latin pop", "Tipo": "track", "Nombre": "La Peque\\u00f1a Leti", "A\\u00f1o": "2000", "ID": "1NisqP9RbbUN7IR3rw83EE"}, {"Artista": "Ricardo Arjona", "G\\u00e9nero": "latin pop", "Tipo": "track", "Nombre": "S\\u00f3lo Quer\\u00eda un Caf\\u00e9", "A\\u00f1o": "2000", "ID": "2kWYn9WboACIhmjQWRwMMX"}, {"Artista": "Paulina Rubio", "G\\u00e9nero": "latin pop", "Tipo": "track", "Nombre": "Sexi Dance", "A\\u00f1o": "2000", "ID": "2HUMe9s1Sn8ZrpsbmDjEAH"}, {"Artista": "Celia Cruz", "G\\u00e9nero": "latin pop", "Tipo": "track", "Nombre": "Celia\'s Oye Como Va (Oye Como Va)", "A\\u00f1o": "2000", "ID": "21pnPg1UFfvVpLInYio1sR"}, {"Artista": "Jean Carlos", "G\\u00e9nero": "latin pop", "Tipo": "track", "Nombre": "Tu Vas a Volar", "A\\u00f1o": "2000", "ID": "5aarNSF6jcTWgC8L25kpYi"}, {"Artista": "Banda XXI", "G\\u00e9nero": "latin pop", "Tipo": "track", "Nombre": "Quiero Saber De Ti", "A\\u00f1o": "2000", "ID": "68mzTYsp45l51K37Tv3V8r"}, {"Artista": "Nek", "G\\u00e9nero": "latin pop", "Tipo": "track", "Nombre": "La vida es", "A\\u00f1o": "2000", "ID": "2KV7Z8NrqJTSq206nKiGGf"}, {"Artista": "Los Tucanes De Tijuana", "G\\u00e9nero": "latin pop", "Tipo": "track", "Nombre": "Cien Por Uno", "A\\u00f1o": "2000", "ID": "64VeKDD6z3P2UnDl8nphc4"}, {"Artista": "Walter Olmos", "G\\u00e9nero": "latin pop", "Tipo": "track", "Nombre": "Amor Fugitivo", "A\\u00f1o": "2000", "ID": "5inaJ88bGKl7HkA9S7ktmV"}, {"Artista": "Walter Olmos", "G\\u00e9nero": "latin pop", "Tipo": "track", "Nombre": "Adicto A Ti", "A\\u00f1o": "2000", "ID": "53p8lIxLmoCoBINK0zuQ4G"}, {"Artista": "Rodrigo", "G\\u00e9nero": "latin pop", "Tipo": "track", "Nombre": "Por Lo Que Yo Te Quiero", "A\\u00f1o": "2000", "ID": "5i9yLs9LPercK6BJgj87gj"}, {"Artista": "Beto Quintanilla", "G\\u00e9nero": "latin pop", "Tipo": "track", "Nombre": "Escolta Suicida", "A\\u00f1o": "2000", "ID": "4P26HKA1ijPe4o7NQqkHlP"}, {"Artista": "Alejandro Sanz", "G\\u00e9nero": "latin pop", "Tipo": "track", "Nombre": "Una noche (feat. The Corrs)", "A\\u00f1o": "2000", "ID": "1QHK82whaHGYWfARl21hUs"}, {"Artista": "Rodrigo", "G\\u00e9nero": "latin pop", "Tipo": "track", "Nombre": "El Viaje", "A\\u00f1o": "2000", "ID": "6yBiLjtUHxkO5OJFuSRIeK"}, {"Artista": "Rodrigo", "G\\u00e9nero": "latin pop", "Tipo": "track", "Nombre": "Yerba Mala", "A\\u00f1o": "2000", "ID": "6DAZuerCWNL5TtgKo8M2jl"}, {"Artista": "Luis Alberto Posada", "G\\u00e9nero": "latin pop", "Tipo": "track", "Nombre": "Coraz\\u00f3n Partido", "A\\u00f1o": "2000", "ID": "2XjKVBc0FnVE2IQNYusZg5"}, {"Artista": "Rodrigo", "G\\u00e9nero": "latin pop", "Tipo": "track", "Nombre": "Aprendiz", "A\\u00f1o": "2000", "ID": "3zOKIMB5FOUtlhYB3nqEJY"}, {"Artista": "Rodrigo", "G\\u00e9nero": "latin pop", "Tipo": "track", "Nombre": "La mano de Dios (Homenaje a Diego Maradona)", "A\\u00f1o": "2000", "ID": "6bQkinbnTaWeLtMObzIxf0"}, {"Artista": "El Cuarteto De Nos", "G\\u00e9nero": "latin pop", "Tipo": "track", "Nombre": "Necesito Una Mujer", "A\\u00f1o": "2000", "ID": "7d6hieV5hQnqZNYnrYfjob"}, {"Artista": "Alejandro Sanz", "G\\u00e9nero": "latin pop", "Tipo": "track", "Nombre": "Llega, lleg\\u00f3 soledad", "A\\u00f1o": "2000", "ID": "7e7ojN0bPRY4b9y7yuE40Y"}, {"Artista": "Thalia", "G\\u00e9nero": "latin pop", "Tipo": "track", "Nombre": "Rosalinda", "A\\u00f1o": "2000", "ID": "4KufWaE6epxrctKlrfVsQh"}, {"Artista": "Ana Torroja", "G\\u00e9nero": "latin pop", "Tipo": "track", "Nombre": "Hacer por hacer", "A\\u00f1o": "2000", "ID": "3bJMFkv8AhKbE9CDJYp5G8"}, {"Artista": "Ana Torroja", "G\\u00e9nero": "latin pop", "Tipo": "track", "Nombre": "Nada particular", "A\\u00f1o": "2000", "ID": "3EL9ISVp1tp06Euqc8492e"}, {"Artista": "El Cuarteto De Nos", "G\\u00e9nero": "latin pop", "Tipo": "track", "Nombre": "Pegame Y Decime Shirley", "A\\u00f1o": "2000", "ID": "5OPEU3148saJYZplRlZn8U"}, {"Artista": "Ana Torroja", "G\\u00e9nero": "latin pop", "Tipo": "track", "Nombre": "Siete de septiembre", "A\\u00f1o": "2000", "ID": "6fzT2ceqglZpffBISnqM7w"}, {"Artista": "Fey", "G\\u00e9nero": "latin pop", "Tipo": "track", "Nombre": "Az\\u00facar Amargo", "A\\u00f1o": "2000", "ID": "2arXuCWrLfgcELqYogQDbt"}, {"Artista": "Celia Cruz", "G\\u00e9nero": "latin pop", "Tipo": "track", "Nombre": "Por Si Acaso No Regreso", "A\\u00f1o": "2000", "ID": "1n52ulXSj7E3GOjcpw1EKF"}, {"Artista": "Debelah Morgan", "G\\u00e9nero": "latin pop", "Tipo": "track", "Nombre": "Dance with Me", "A\\u00f1o": "2000", "ID": "1C2Q3AymKS17bw7T5gfq6p"}, {"Artista": "Ana Torroja", "G\\u00e9nero": "latin pop", "Tipo": "track", "Nombre": "Amante bandido", "A\\u00f1o": "2000", "ID": "2lMAx2mhNdHdgw0qDZ2PSB"}, {"Artista": "Ana Torroja", "G\\u00e9nero": "latin pop", "Tipo": "track", "Nombre": "Mujer contra mujer", "A\\u00f1o": "2000", "ID": "68RZ0w4gdgXVWKpooGcYWl"}, {"Artista": "Paulina Rubio", "G\\u00e9nero": "latin pop", "Tipo": "track", "Nombre": "Vive El Verano", "A\\u00f1o": "2000", "ID": "13hnZOARWepu30E9lhn4jO"}, {"Artista": "Rey Ruiz", "G\\u00e9nero": "latin pop", "Tipo": "track", "Nombre": "Muevelo", "A\\u00f1o": "2000", "ID": "2z7qJyoZCeNUyyt7z0Ha1U"}, {"Artista": "Ana Torroja", "G\\u00e9nero": "latin pop", "Tipo": "track", "Nombre": "A contratiempo", "A\\u00f1o": "2000", "ID": "7zDsplBsyc0cyZoR9AJYWt"}, {"Artista": "Thalia", "G\\u00e9nero": "latin pop", "Tipo": "track", "Nombre": "Reencarnacion", "A\\u00f1o": "2000", "ID": "1iT6VaEqoBLCQcAYH75jOC"}, {"Artista": "Walter Olmos", "G\\u00e9nero": "latin pop", "Tipo": "track", "Nombre": "No Me Mientas", "A\\u00f1o": "2000", "ID": "0mYPt9hLmZZvqWAbR9SdNj"}, {"Artista": "Ana Torroja", "G\\u00e9nero": "latin pop", "Tipo": "track", "Nombre": "Si t\\u00fa no vuelves", "A\\u00f1o": "2000", "ID": "07HhvYazaf4LyXNKpmDb5J"}, {"Artista": "Bertin Osborne", "G\\u00e9nero": "latin pop", "Tipo": "track", "Nombre": "Popurr\\u00ed Mexicano", "A\\u00f1o": "2000", "ID": "6vV6BhzqwsuFFRBh1L0mOq"}, {"Artista": "Alejandro Sanz", "G\\u00e9nero": "latin pop", "Tipo": "track", "Nombre": "El alma al aire - Maqueta", "A\\u00f1o": "2000", "ID": "0J1X8DvOXj0GD07UN3kyci"}, {"Artista": "Chayanne", "G\\u00e9nero": "latin pop", "Tipo": "track", "Nombre": "Ay Mama", "A\\u00f1o": "2000", "ID": "3x7w1y7WLU7lpCSh39VSrZ"}, {"Artista": "Alejandro Sanz", "G\\u00e9nero": "latin pop", "Tipo": "track", "Nombre": "Hicimos un trato", "A\\u00f1o": "2000", "ID": "6AF3xHHs3tmL7JN8lkNkgR"}, {"Artista": "La Retrocumbia", "G\\u00e9nero": "latin pop", "Tipo": "track", "Nombre": "Popurri - Cartagenera - El orangutan - No te vayas - La Piragua - Cumbia sobre el mar", "A\\u00f1o": "2000", "ID": "0PDd6bNpNQdJXQhvNWSC3O"}, {"Artista": "La Retrocumbia", "G\\u00e9nero": "latin pop", "Tipo": "track", "Nombre": "Popurri - Alejate de mi - Mentiras, mientras - Muchacha ojos de miel", "A\\u00f1o": "2000", "ID": "3vWUFIYGhO5AH4jvgVouPv"}, {"Artista": "La Gran Banda", "G\\u00e9nero": "latin pop", "Tipo": "track", "Nombre": "Popurri Romantico", "A\\u00f1o": "2000", "ID": "312V3J3wZS2wv53UsD97oy"}, {"Artista": "Luis Alberto Posada", "G\\u00e9nero": "latin pop", "Tipo": "track", "Nombre": "Cruz de Dolor", "A\\u00f1o": "2000", "ID": "5GODB1nafsfms7LyFymC4V"}, {"Artista": "Luis Alberto Posada", "G\\u00e9nero": "latin pop", "Tipo": "track", "Nombre": "No Soy un Juguete", "A\\u00f1o": "2000", "ID": "7JoZyPwW1w1TjoO5yrzks0"}, {"Artista": "La Retrocumbia", "G\\u00e9nero": "latin pop", "Tipo": "track", "Nombre": "Popurri - La Negra Salome - Juana la Cubana", "A\\u00f1o": "2000", "ID": "3MqI7CgT8Y57MbbcvbT5pX"}, {"Artista": "La Retrocumbia", "G\\u00e9nero": "latin pop", "Tipo": "track", "Nombre": "Popurri - Las chiquillas - La Revoltosa - El Parrandero - Pajaro del monte", "A\\u00f1o": "2000", "ID": "5oWiYUPBnKii0nuqfzr30o"}, {"Artista": "La Retrocumbia", "G\\u00e9nero": "latin pop", "Tipo": "track", "Nombre": "Popurri - El pescador - Todos los domingos - Atrevete a mirarme de frente - Santa Martha - Se va el caiman - La Burrita - Quiero un sombrero - Para que", "A\\u00f1o": "2000", "ID": "52b25x2jxiV9Iapiq2ni6s"}, {"Artista": "Los Razos", "G\\u00e9nero": "latin pop", "Tipo": "track", "Nombre": "Chingon De Chingones", "A\\u00f1o": "2000", "ID": "5lduUBDO2K74wlWcReMTJ8"}, {"Artista": "Walter Olmos", "G\\u00e9nero": "latin pop", "Tipo": "track", "Nombre": "Chico De La Calle", "A\\u00f1o": "2000", "ID": "4zmK84b3QtttgoP5mNZpse"}, {"Artista": "Beto Quintanilla", "G\\u00e9nero": "latin pop", "Tipo": "track", "Nombre": "El Plebe y el Cholo", "A\\u00f1o": "2000", "ID": "2jR8SDgmlxxxsiJ2iwd6Ms"}, {"Artista": "Walter Olmos", "G\\u00e9nero": "latin pop", "Tipo": "track", "Nombre": "Extra\\u00f1\\u00e1ndote", "A\\u00f1o": "2000", "ID": "0zXjhiCo3x42xLcxK0GoFf"}, {"Artista": "Walter Olmos", "G\\u00e9nero": "latin pop", "Tipo": "track", "Nombre": "Por Lo Que Yo Te Quiero", "A\\u00f1o": "2000", "ID": "3dKjmF3Yjl79hybcSkE9M5"}, {"Artista": "Beto Quintanilla", "G\\u00e9nero": "latin pop", "Tipo": "track", "Nombre": "Raquenel Villanueva", "A\\u00f1o": "2000", "ID": "71rQncW9uGaAg4QplpEbeL"}, {"Artista": "Alejandro Sanz", "G\\u00e9nero": "latin pop", "Tipo": "track", "Nombre": "El alma al aire", "A\\u00f1o": "2000", "ID": "0JDTLHMnltIIVnXi72RTom"}, {"Artista": "Chayanne", "G\\u00e9nero": "latin pop", "Tipo": "track", "Nombre": "Simplemente", "A\\u00f1o": "2000", "ID": "1bMQ3pR8fxeAAVg4TwXPrM"}, {"Artista": "Alejandro Sanz", "G\\u00e9nero": "latin pop", "Tipo": "track", "Nombre": "Cuando nadie me ve", "A\\u00f1o": "2000", "ID": "0bfPmBR6iN2cyJQJUUQOG0"}, {"Artista": "Donato Y Estefano", "G\\u00e9nero": "latin pop", "Tipo": "track", "Nombre": "Toma Tu Tiempo Y Suena", "A\\u00f1o": "2000", "ID": "3ANzgIoMEW7KobbWrA6crP"}, {"Artista": "El Cuarteto De Nos", "G\\u00e9nero": "latin pop", "Tipo": "track", "Nombre": "Me Amo", "A\\u00f1o": "2000", "ID": "5aRef1fGbwM1t0MqXSrwzV"}, {"Artista": "Ana Torroja", "G\\u00e9nero": "latin pop", "Tipo": "track", "Nombre": "Un a\\u00f1o m\\u00e1s", "A\\u00f1o": "2000", "ID": "58dwFuu8GK2Gnab1ucCSlj"}, {"Artista": "Jean Carlos", "G\\u00e9nero": "latin pop", "Tipo": "track", "Nombre": "A Puro Dolor", "A\\u00f1o": "2000", "ID": "2K5ureC8z6V2dAtj0B8ASW"}, {"Artista": "La Oreja de Van Gogh", "G\\u00e9nero": "latin pop", "Tipo": "track", "Nombre": "Rosas", "A\\u00f1o": "2000", "ID": "0iCTZBrskLb7xIZBuGcNrn"}, {"Artista": "Julio Iglesias", "G\\u00e9nero": "latin pop", "Tipo": "track", "Nombre": "No Es Amor Ni Es Amar (Gone Too Far)", "A\\u00f1o": "2000", "ID": "3yggjuzrpJ9qNnVuz6va83"}, {"Artista": "Chayanne", "G\\u00e9nero": "latin pop", "Tipo": "track", "Nombre": "Hasta Que El Alma Resista", "A\\u00f1o": "2000", "ID": "24roOHa0bnZSohbWE7Ligd"}, {"Artista": "Donato Y Estefano", "G\\u00e9nero": "latin pop", "Tipo": "track", "Nombre": "Naturaleza", "A\\u00f1o": "2000", "ID": "6oGgP96pCoPGVH9WhFZus0"}, {"Artista": "Juanes", "G\\u00e9nero": "latin pop", "Tipo": "track", "Nombre": "Podemos Hacernos Da\\u00f1o", "A\\u00f1o": "2000", "ID": "4dK3GtjIEt42iVHo3qjMss"}, {"Artista": "Ana Torroja", "G\\u00e9nero": "latin pop", "Tipo": "track", "Nombre": "Bamb\\u00fa", "A\\u00f1o": "2000", "ID": "1TuvKksFlFgn6D3VkGUhPs"}, {"Artista": "Jimmy Bosch", "G\\u00e9nero": "latin pop", "Tipo": "track", "Nombre": "Pa\' Mantener Tradici\\u00f3n", "A\\u00f1o": "2000", "ID": "5m9rNQ7CqWffaZGBXTF98n"}, {"Artista": "Ana Torroja", "G\\u00e9nero": "latin pop", "Tipo": "track", "Nombre": "Muro", "A\\u00f1o": "2000", "ID": "4KYnziYaVyyM2KHT2hZfZI"}, {"Artista": "Banda XXI", "G\\u00e9nero": "latin pop", "Tipo": "track", "Nombre": "Y Te Amo Solo", "A\\u00f1o": "2000", "ID": "78Of4ie3Av5b8BKSf8CG6H"}, {"Artista": "Shakira", "G\\u00e9nero": "latin pop", "Tipo": "track", "Nombre": "No Creo - En Vivo", "A\\u00f1o": "2000", "ID": "1GM2ouHHKW3tuCzjSZKIyr"}, {"Artista": "Ricky Martin", "G\\u00e9nero"

In [21]:
with open('lista_latin_pop.json', 'w', encoding="utf-8") as archivo_json: 
    json.dump(lista_latin_pop, archivo_json)

In [ ]:
df_latin_pop.to_csv("df_latin_pop.csv", index=False, encoding="utf-8")
# (encoding="utf-8") garantiza que acentos, eñes y caracteres especiales se guarden correctamente (por ejemplo: “niña”, “España”, etc.).

In [30]:
## convertimos en tupla lista artista para poder iterar por ella y pasarla a lastfm

In [31]:
def convertir_df(ruta):
    df = pd.read_csv(ruta)
    lista_listas = df.values.tolist()

    lista_tuplas = []
    for lista in lista_listas:
        t = tuple(lista)
        lista_tuplas.append(t)

    return lista_tuplas

In [32]:
df_latin_pop_tuplas = convertir_df("df_latin_pop.csv")

In [33]:
df_latin_pop_tuplas

[('La Oreja de Van Gogh',
  'latin pop',
  'track',
  'Pop',
  2000,
  '4FXSEdmbbeGmPIQltH27C8'),
 ('Ricky Martin',
  'latin pop',
  'track',
  'She Bangs - Spanish Version',
  2000,
  '4ti5pZ0zs1PDf1eQswskFB'),
 ('Thalia',
  'latin pop',
  'track',
  'Entre El Mar Y Una Estrella',
  2000,
  '2KNtKG2X0jpOIgVunVbAkQ'),
 ('Rodrigo',
  'latin pop',
  'track',
  'Fuego y Pasion',
  2000,
  '0SBHkYiZh8ih1RHoOcDtHl'),
 ('Rodrigo',
  'latin pop',
  'track',
  'Como Le Digo',
  2000,
  '4nH1lpWkgzQPpTYPPjWKaI'),
 ('Paulina Rubio',
  'latin pop',
  'track',
  'Tal Vez Quizas',
  2000,
  '4Ft4AbNwk1acKagaBOmvHb'),
 ('Los Tucanes De Tijuana',
  'latin pop',
  'track',
  'Mis Tres Viejas',
  2000,
  '1yxJIFPhP2EqnQ6oWJKbmP'),
 ('Rodrigo',
  'latin pop',
  'track',
  'Soy Cordobes',
  2000,
  '5wG4J1UECH0c42YhMhSkcS'),
 ('Rodrigo',
  'latin pop',
  'track',
  'Amor Clasificado',
  2000,
  '5MK642wCaNr9hRDZ3kWyDX'),
 ('Alejandro Sanz',
  'latin pop',
  'track',
  'Cuando nadie me ve - Maqueta',
  2000,
  '7IxcEDXDSefpahEg6zmDs5'),
 ('Thalia',
  'latin pop',
  'track',
  'Regresa A Mi',
  2000,
  '36GbwUTkCSQ18aysIFYEPF'),
 ('Chayanne', 'latin pop', 'track', 'Candela', 2000, '6aZVaIudGaHm88ydUe9k4i'),
 ('Celia Cruz',
  'latin pop',
  'track',
  "Celia's Oye Como Va (Oye Como Va)",
  2000,
  '7fhCXXF7V5jsU06bOgVBqJ'),
 ('Juanes',
  'latin pop',
  'track',
  'Fijate Bien',
  2000,
  '3wE4fvPhhScUAhY37TDc1D'),
 ('Chayanne',
  'latin pop',
  'track',
  'Boom Boom',
  2000,
  '4zkOTmiamebLJ39Sqbp7sb'),
 ('Chayanne', 'latin pop', 'track', 'Salomé', 2000, '4l8i9h5PNoJte95Es3HftJ'),
 ('Rodrigo',
  'latin pop',
  'track',
  'Que Ironia',
  2000,
  '0E9YlthbJZ6WOPKi3LTBJc'),
 ('Ana Torroja',
  'latin pop',
  'track',
  'Duende',
  2000,
  '3WX2KhnJq3QdRTfPgHWgZU'),
 ('Laura Pausini',
  'latin pop',
  'track',
  'Un error de los grandes',
  2000,
  '0cZRvN0JNRbkmhJK90x4cH'),
 ('Alejandro Sanz',
  'latin pop',
  'track',
  'Me iré',
  2000,
  '42t0ZnBaS3dYFcs3xyQF2Y'),
 ('La Oreja de Van Gogh',
  'latin pop',
  'track',
  'Tantas Cosas Que Contar',
  2000,
  '09oZXunRcHWgNc4jYxDeue'),
 ('Chayanne',
  'latin pop',
  'track',
  'Mariana Mambo',
  2000,
  '3ppKW2voPfRuCtdWhF1R9z'),
 ('Armando Manzanero',
  'latin pop',
  'track',
  'Esperaré (feat. Café Quijano)',
  2000,
  '4RclcYWxQMRsdmT25OK9ic'),
 ('Paulina Rubio',
  'latin pop',
  'track',
  'El Ultimo Adios',
  2000,
  '7lnun6viJADQCvZnE0w9q8'),
 ('Donato Y Estefano',
  'latin pop',
  'track',
  'Sin Ti',
  2000,
  '3c9KuwSygZBPj6gbXLxRc7'),
 ('Ana Torroja',
  'latin pop',
  'track',
  'Corazones',
  2000,
  '6cbvo1vIHJZfIXrGxOzza9'),
 ('Alejandro Sanz',
  'latin pop',
  'track',
  'Hay un universo de pequeñas cosas',
  2000,
  '5JA04DokXsoCNcVPI9NRmD'),
 ('Paulina Rubio',
  'latin pop',
  'track',
  'Lo Haré Por Ti',
  2000,
  '2j0vCRV8XySsYHDYasQwbi'),
 ('Alejandro Sanz',
  'latin pop',
  'track',
  'Para que me quieras',
  2000,
  '3QYWYwpcCdf5f5DQW52oaz'),
 ('Christina Aguilera',
  'latin pop',
  'track',
  'Ven Conmigo (Solamente Tú)',
  2000,
  '2PYJnUWEPPP8C6b79UiwIl'),
 ('Gloria Estefan',
  'latin pop',
  'track',
  'Como Me Duele Perderte',
  2000,
  '7deJdnhCWumMOBJtXeIVyN'),
 ('Chayanne',
  'latin pop',
  'track',
  'Yo Te Amo',
  2000,
  '2sKo5u6IppUEudIz265wYa'),
 ('Celia Cruz',
  'latin pop',
  'track',
  'Rie y Llora',
  2000,
  '63knvuoSPpfzIwdDuWRSoV'),
 ('Alejandro Sanz',
  'latin pop',
  'track',
  'El alma al aire',
  2000,
  '0Bs7Y5vCIzuvFTS9SLBPn8'),
 ('La Oreja de Van Gogh',
  'latin pop',
  'track',
  'Tu Pelo',
  2000,
  '36wsPM9GCrgt9pxS95PYr2'),
 ('Christina Aguilera',
  'latin pop',
  'track',
  'Genio Atrapado',
  2000,
  '3ne8ipFCs7RUr2K6QoD6BQ'),
 ('La Oreja de Van Gogh',
  'latin pop',
  'track',
  'Paris',
  2000,
  '5ByvJeBlrYISiwy7AVEAmP'),
 ('Eros Ramazzotti',
  'latin pop',
  'track',
  'Fuego en el Fuego',
  2000,
  '3P8ruszvU7rSrL6rrGbLUQ'),
 ('Paulina Rubio',
  'latin pop',
  'track',
  'Y Yo Sigo Aqui - Spanglish',
  2000,
  '2Ma2f8jV8VKMJoAcnCvZ8h'),
 ('Paulina Rubio',
  'latin pop',
  'track',
  'Yo No Soy Esa Mujer',
  2000,
  '0JAGODD5w6MeYQzA9lV6Zm'),
 ('Thalia', 'latin pop', 'track', 'Arrasando', 2000, '1EhDeCHd34jt7dMDqkGQBC'),
 ('La Oreja de Van Gogh',
  'latin pop',
  'track',
  'Cuídate',
  2000,
  '7gqIqyeCaV2xNtfZWxEphD'),
 ('La Oreja de Van Gogh',
  'latin pop',
  'track',
  'La Chica del Gorro Azul',
  2000,
  '3MtGBLot4sqvpT0cDyWTC8'),
 ('La Oreja de Van Gogh',
  'latin pop',
  'track',
  'La Playa',
  2000,
  '2DNyZP4Py6f4zMASLBnIu6'),
 ('La Oreja de Van Gogh',
  'latin pop',
  'track',
  'Dicen Que Dicen',
  2000,
  '69sZqRBNGrcRHZBFkvlRGW'),
 ('La Oreja de Van Gogh',
  'latin pop',
  'track',
  'Mariposa',
  2000,
  '50CFzmM2N9wxobKcURrZdw'),
 ('Eros Ramazzotti',
  'latin pop',
  'track',
  'Fuego en el Fuego',
  2000,
  '5zGJT3TTShcNHeJeDrjPvs'),
 ('La Oreja de Van Gogh',
  'latin pop',
  'track',
  'Soledad',
  2000,
  '4NLpfB52hwDPLn7bphgjgD'),
 ('Alejandro Sanz',
  'latin pop',
  'track',
  'Cuando nadie me ve',
  2000,
  '7sNpt6AvOvXXZVaqTCFVCu'),
 ('Alejandro Sanz',
  'latin pop',
  'track',
  'Quisiera ser',
  2000,
  '2MnNZIetVS8IVfy9PtpLeb'),
 ('El Cuarteto De Nos',
  'latin pop',
  'track',
  'Cristo Te Odia',
  2000,
  '6nGheW6QepWxeMuwkPLDfS'),
 ('Los Tucanes De Tijuana',
  'latin pop',
  'track',
  'Gripa Colombiana',
  2000,
  '33Kxt0fCaltxIuIOzM7hfs'),
 ('El Cuarteto De Nos',
  'latin pop',
  'track',
  'La Pequeña Leti',
  2000,
  '1NisqP9RbbUN7IR3rw83EE'),
 ('Ricardo Arjona',
  'latin pop',
  'track',
  'Sólo Quería un Café',
  2000,
  '2kWYn9WboACIhmjQWRwMMX'),
 ('Paulina Rubio',
  'latin pop',
  'track',
  'Sexi Dance',
  2000,
  '2HUMe9s1Sn8ZrpsbmDjEAH'),
 ('Celia Cruz',
  'latin pop',
  'track',
  "Celia's Oye Como Va (Oye Como Va)",
  2000,
  '21pnPg1UFfvVpLInYio1sR'),
 ('Jean Carlos',
  'latin pop',
  'track',
  'Tu Vas a Volar',
  2000,
  '5aarNSF6jcTWgC8L25kpYi'),
 ('Banda XXI',
  'latin pop',
  'track',
  'Quiero Saber De Ti',
  2000,
  '68mzTYsp45l51K37Tv3V8r'),
 ('Nek', 'latin pop', 'track', 'La vida es', 2000, '2KV7Z8NrqJTSq206nKiGGf'),
 ('Los Tucanes De Tijuana',
  'latin pop',
  'track',
  'Cien Por Uno',
  2000,
  '64VeKDD6z3P2UnDl8nphc4'),
 ('Walter Olmos',
  'latin pop',
  'track',
  'Amor Fugitivo',
  2000,
  '5inaJ88bGKl7HkA9S7ktmV'),
 ('Walter Olmos',
  'latin pop',
  'track',
  'Adicto A Ti',
  2000,
  '53p8lIxLmoCoBINK0zuQ4G'),
 ('Rodrigo',
  'latin pop',
  'track',
  'Por Lo Que Yo Te Quiero',
  2000,
  '5i9yLs9LPercK6BJgj87gj'),
 ('Beto Quintanilla',
  'latin pop',
  'track',
  'Escolta Suicida',
  2000,
  '4P26HKA1ijPe4o7NQqkHlP'),
 ('Alejandro Sanz',
  'latin pop',
  'track',
  'Una noche (feat. The Corrs)',
  2000,
  '1QHK82whaHGYWfARl21hUs'),
 ('Rodrigo', 'latin pop', 'track', 'El Viaje', 2000, '6yBiLjtUHxkO5OJFuSRIeK'),
 ('Rodrigo',
  'latin pop',
  'track',
  'Yerba Mala',
  2000,
  '6DAZuerCWNL5TtgKo8M2jl'),
 ('Luis Alberto Posada',
  'latin pop',
  'track',
  'Corazón Partido',
  2000,
  '2XjKVBc0FnVE2IQNYusZg5'),
 ('Rodrigo', 'latin pop', 'track', 'Aprendiz', 2000, '3zOKIMB5FOUtlhYB3nqEJY'),
 ('Rodrigo',
  'latin pop',
  'track',
  'La mano de Dios (Homenaje a Diego Maradona)',
  2000,
  '6bQkinbnTaWeLtMObzIxf0'),
 ('El Cuarteto De Nos',
  'latin pop',
  'track',
  'Necesito Una Mujer',
  2000,
  '7d6hieV5hQnqZNYnrYfjob'),
 ('Alejandro Sanz',
  'latin pop',
  'track',
  'Llega, llegó soledad',
  2000,
  '7e7ojN0bPRY4b9y7yuE40Y'),
 ('Thalia', 'latin pop', 'track', 'Rosalinda', 2000, '4KufWaE6epxrctKlrfVsQh'),
 ('Ana Torroja',
  'latin pop',
  'track',
  'Hacer por hacer',
  2000,
  '3bJMFkv8AhKbE9CDJYp5G8'),
 ('Ana Torroja',
  'latin pop',
  'track',
  'Nada particular',
  2000,
  '3EL9ISVp1tp06Euqc8492e'),
 ('El Cuarteto De Nos',
  'latin pop',
  'track',
  'Pegame Y Decime Shirley',
  2000,
  '5OPEU3148saJYZplRlZn8U'),
 ('Ana Torroja',
  'latin pop',
  'track',
  'Siete de septiembre',
  2000,
  '6fzT2ceqglZpffBISnqM7w'),
 ('Fey',
  'latin pop',
  'track',
  'Azúcar Amargo',
  2000,
  '2arXuCWrLfgcELqYogQDbt'),
 ('Celia Cruz',
  'latin pop',
  'track',
  'Por Si Acaso No Regreso',
  2000,
  '1n52ulXSj7E3GOjcpw1EKF'),
 ('Debelah Morgan',
  'latin pop',
  'track',
  'Dance with Me',
  2000,
  '1C2Q3AymKS17bw7T5gfq6p'),
 ('Ana Torroja',
  'latin pop',
  'track',
  'Amante bandido',
  2000,
  '2lMAx2mhNdHdgw0qDZ2PSB'),
 ('Ana Torroja',
  'latin pop',
  'track',
  'Mujer contra mujer',
  2000,
  '68RZ0w4gdgXVWKpooGcYWl'),
 ('Paulina Rubio',
  'latin pop',
  'track',
  'Vive El Verano',
  2000,
  '13hnZOARWepu30E9lhn4jO'),
 ('Rey Ruiz', 'latin pop', 'track', 'Muevelo', 2000, '2z7qJyoZCeNUyyt7z0Ha1U'),
 ('Ana Torroja',
  'latin pop',
  'track',
  'A contratiempo',
  2000,
  '7zDsplBsyc0cyZoR9AJYWt'),
 ('Thalia',
  'latin pop',
  'track',
  'Reencarnacion',
  2000,
  '1iT6VaEqoBLCQcAYH75jOC'),
 ('Walter Olmos',
  'latin pop',
  'track',
  'No Me Mientas',
  2000,
  '0mYPt9hLmZZvqWAbR9SdNj'),
 ('Ana Torroja',
  'latin pop',
  'track',
  'Si tú no vuelves',
  2000,
  '07HhvYazaf4LyXNKpmDb5J'),
 ('Bertin Osborne',
  'latin pop',
  'track',
  'Popurrí Mexicano',
  2000,
  '6vV6BhzqwsuFFRBh1L0mOq'),
 ('Alejandro Sanz',
  'latin pop',
  'track',
  'El alma al aire - Maqueta',
  2000,
  '0J1X8DvOXj0GD07UN3kyci'),
 ('Chayanne', 'latin pop', 'track', 'Ay Mama', 2000, '3x7w1y7WLU7lpCSh39VSrZ'),
 ('Alejandro Sanz',
  'latin pop',
  'track',
  'Hicimos un trato',
  2000,
  '6AF3xHHs3tmL7JN8lkNkgR'),
 ('La Retrocumbia',
  'latin pop',
  'track',
  'Popurri - Cartagenera - El orangutan - No te vayas - La Piragua - Cumbia sobre el mar',
  2000,
  '0PDd6bNpNQdJXQhvNWSC3O'),
 ('La Retrocumbia',
  'latin pop',
  'track',
  'Popurri - Alejate de mi - Mentiras, mientras - Muchacha ojos de miel',
  2000,
  '3vWUFIYGhO5AH4jvgVouPv'),
 ('La Gran Banda',
  'latin pop',
  'track',
  'Popurri Romantico',
  2000,
  '312V3J3wZS2wv53UsD97oy'),
 ('Luis Alberto Posada',
  'latin pop',
  'track',
  'Cruz de Dolor',
  2000,
  '5GODB1nafsfms7LyFymC4V'),
 ('Luis Alberto Posada',
  'latin pop',
  'track',
  'No Soy un Juguete',
  2000,
  '7JoZyPwW1w1TjoO5yrzks0'),
 ('La Retrocumbia',
  'latin pop',
  'track',
  'Popurri - La Negra Salome - Juana la Cubana',
  2000,
  '3MqI7CgT8Y57MbbcvbT5pX'),
 ('La Retrocumbia',
  'latin pop',
  'track',
  'Popurri - Las chiquillas - La Revoltosa - El Parrandero - Pajaro del monte',
  2000,
  '5oWiYUPBnKii0nuqfzr30o'),
 ('La Retrocumbia',
  'latin pop',
  'track',
  'Popurri - El pescador - Todos los domingos - Atrevete a mirarme de frente - Santa Martha - Se va el caiman - La Burrita - Quiero un sombrero - Para que',
  2000,
  '52b25x2jxiV9Iapiq2ni6s'),
 ('Los Razos',
  'latin pop',
  'track',
  'Chingon De Chingones',
  2000,
  '5lduUBDO2K74wlWcReMTJ8'),
 ('Walter Olmos',
  'latin pop',
  'track',
  'Chico De La Calle',
  2000,
  '4zmK84b3QtttgoP5mNZpse'),
 ('Beto Quintanilla',
  'latin pop',
  'track',
  'El Plebe y el Cholo',
  2000,
  '2jR8SDgmlxxxsiJ2iwd6Ms'),
 ('Walter Olmos',
  'latin pop',
  'track',
  'Extrañándote',
  2000,
  '0zXjhiCo3x42xLcxK0GoFf'),
 ('Walter Olmos',
  'latin pop',
  'track',
  'Por Lo Que Yo Te Quiero',
  2000,
  '3dKjmF3Yjl79hybcSkE9M5'),
 ('Beto Quintanilla',
  'latin pop',
  'track',
  'Raquenel Villanueva',
  2000,
  '71rQncW9uGaAg4QplpEbeL'),
 ('Alejandro Sanz',
  'latin pop',
  'track',
  'El alma al aire',
  2000,
  '0JDTLHMnltIIVnXi72RTom'),
 ('Chayanne',
  'latin pop',
  'track',
  'Simplemente',
  2000,
  '1bMQ3pR8fxeAAVg4TwXPrM'),
 ('Alejandro Sanz',
  'latin pop',
  'track',
  'Cuando nadie me ve',
  2000,
  '0bfPmBR6iN2cyJQJUUQOG0'),
 ('Donato Y Estefano',
  'latin pop',
  'track',
  'Toma Tu Tiempo Y Suena',
  2000,
  '3ANzgIoMEW7KobbWrA6crP'),
 ('El Cuarteto De Nos',
  'latin pop',
  'track',
  'Me Amo',
  2000,
  '5aRef1fGbwM1t0MqXSrwzV'),
 ('Ana Torroja',
  'latin pop',
  'track',
  'Un año más',
  2000,
  '58dwFuu8GK2Gnab1ucCSlj'),
 ('Jean Carlos',
  'latin pop',
  'track',
  'A Puro Dolor',
  2000,
  '2K5ureC8z6V2dAtj0B8ASW'),
 ('La Oreja de Van Gogh',
  'latin pop',
  'track',
  'Rosas',
  2000,
  '0iCTZBrskLb7xIZBuGcNrn'),
 ('Julio Iglesias',
  'latin pop',
  'track',
  'No Es Amor Ni Es Amar (Gone Too Far)',
  2000,
  '3yggjuzrpJ9qNnVuz6va83'),
 ('Chayanne',
  'latin pop',
  'track',
  'Hasta Que El Alma Resista',
  2000,
  '24roOHa0bnZSohbWE7Ligd'),
 ('Donato Y Estefano',
  'latin pop',
  'track',
  'Naturaleza',
  2000,
  '6oGgP96pCoPGVH9WhFZus0'),
 ('Juanes',
  'latin pop',
  'track',
  'Podemos Hacernos Daño',
  2000,
  '4dK3GtjIEt42iVHo3qjMss'),
 ('Ana Torroja',
  'latin pop',
  'track',
  'Bambú',
  2000,
  '1TuvKksFlFgn6D3VkGUhPs'),
 ('Jimmy Bosch',
  'latin pop',
  'track',
  "Pa' Mantener Tradición",
  2000,
  '5m9rNQ7CqWffaZGBXTF98n'),
 ('Ana Torroja', 'latin pop', 'track', 'Muro', 2000, '4KYnziYaVyyM2KHT2hZfZI'),
 ('Banda XXI',
  'latin pop',
  'track',
  'Y Te Amo Solo',
  2000,
  '78Of4ie3Av5b8BKSf8CG6H'),
 ('Shakira',
  'latin pop',
  'track',
  'No Creo - En Vivo',
  2000,
  '1GM2ouHHKW3tuCzjSZKIyr'),
 ('Ricky Martin',
  'latin pop',
  'track',
  'Dame Más (Loaded) - Spanish Edit',
  2000,
  '3zBP6rvzlBtcn1gEsgzeBI'),
 ('Ana Torroja',
  'latin pop',
  'track',
  'Salamandra',
  2000,
  '6dLlU2XOMZLWoXrKA9baY8'),
 ('Donato Y Estefano',
  'latin pop',
  'track',
  'Entre La Linea Del Bien Y La Linea Del Mal',
  2000,
  '4iKnaiZ1Rb1emdpboOte67'),
 ('Luis Alberto Posada',
  'latin pop',
  'track',
  'Negros Recuerdos',
  2000,
  '2eaqczOTq5cAAZxIdbkYr9'),
 ('Donato Y Estefano',
  'latin pop',
  'track',
  'Y Bailo',
  2000,
  '4qrhU545tqm3RHvNrql1YA'),
 ('Ana Torroja', 'latin pop', 'track', 'Nena', 2000, '05lfAUHuoiSTGESSyLbiZ4'),
 ('Alejandro Sanz',
  'latin pop',
  'track',
  'Silencio (Ghost Track)',
  2000,
  '41IpfXrlcy5uVYLHSD4hw1'),
 ('Issac Delgado',
  'latin pop',
  'track',
  "Popourri Pa'l Sonero",
  2000,
  '13ViPREtq0llZeSbArTKno'),
 ('Nek', 'latin pop', 'track', 'Llegas tu', 2000, '3YX0QfZP4EhzAc4PmlUlTS'),
 ('Juanes', 'latin pop', 'track', 'Nada', 2000, '0fxLW78I51KMo6SNMm7Fcg'),
 ('La Mosca',
  'latin pop',
  'track',
  'Cha Cha Cha',
  2000,
  '36in1jDriTe1PQhU4iTKkv'),
 ('Ana Torroja',
  'latin pop',
  'track',
  'Como sueñan las sirenas',
  2000,
  '3SYX4F2sGa3k3sTnQD1oC5'),
 ('Polo Montañez',
  'latin pop',
  'track',
  'Un Montón De Estrellas - Montuno pop mix',
  2000,
  '57kkKgQqufYrdRrkXk02nr'),
 ('Walter Olmos',
  'latin pop',
  'track',
  'Ay Corazón',
  2000,
  '2qOIRBrWn2fll2ude8zBo4'),
 ('Tru La La',
  'latin pop',
  'track',
  'Como Tú',
  2000,
  '0HF43dp7GkUmDSTwtFAKE7'),
 ('Rodrigo',
  'latin pop',
  'track',
  'Un Largo Camino al Cielo',
  2000,
  '2PlSYK2fahYQAfOQ5oZkDt'),
 ('Alejandro Sanz',
  'latin pop',
  'track',
  'Tiene que ser pecado',
  2000,
  '3Mu0D93GhMoPKjPx7htLXY'),
 ('Celia Cruz',
  'latin pop',
  'track',
  'Por Si Acaso No Regreso',
  2000,
  '50TcSPtqH5VsexbUlbptVu'),
 ('Donato Y Estefano',
  'latin pop',
  'track',
  'Mar Adentro',
  2000,
  '5zGneVMVXG5uTqNjVUenWH'),
 ('El Cuarteto De Nos',
  'latin pop',
  'track',
  'No Somos Latinos',
  2000,
  '3Hh2NDo6xmxPZEVQ4E7NOT'),
 ('Ana Torroja',
  'latin pop',
  'track',
  'Barco a Venus',
  2000,
  '2CPucIrbVXPHysngMqfmSI'),
 ('Ana Torroja',
  'latin pop',
  'track',
  'Ya no te quiero',
  2000,
  '36q0PyyQa1u39ZUala53gD'),
 ('Ana Torroja',
  'latin pop',
  'track',
  'Hoy no me puedo levantar',
  2000,
  '1R7Xolq9aQh8fTZ4qa9rnb'),
 ('Luisito Muñoz',
  'latin pop',
  'track',
  'Si Supieras',
  2000,
  '5r6tP7am1kGACxGbLhKIUg'),
 ('Walter Olmos',
  'latin pop',
  'track',
  'Amor De Adolescentes',
  2000,
  '2ChbVApTbkUwVmd4xOvLtP'),
 ('Luis Alberto Posada',
  'latin pop',
  'track',
  'Destino Marcado',
  2000,
  '4ioo5mmNAB8XjaCNtsq7ww'),
 ("Los Chaque's",
  'latin pop',
  'track',
  'Popurrí',
  2000,
  '7b3uMBF8ofWeYgMQiPEM2C'),
 ('Sabroso',
  'latin pop',
  'track',
  'Llegó Tu Papi',
  2001,
  '3jdU5hu76KBxor1EBDDSXR'),
 ('Shakira',
  'latin pop',
  'track',
  'Que Me Quedes Tú',
  2001,
  '3pWF6sOdKOtwtIbVaFMN6U'),
 ('José José',
  'latin pop',
  'track',
  'Popurrí: Cómo Hacer para Olvidar / Con Mis Propias Manos (with Juan Gabriel)',
  2001,
  '63IIgFOKUy9bUPsFbFg5Hz'),
 ('Shakira',
  'latin pop',
  'track',
  'Objection (Tango)',
  2001,
  '36YNa8joLwu9yor2TkZbIY'),
 ('Aleks Syntek',
  'latin pop',
  'track',
  'Por Volverte A Ver',
  2001,
  '5mQAisM7QzOcAGwi9uSMIh'),
 ('Shakira',
  'latin pop',
  'track',
  'Te Aviso, Te Anuncio (Tango)',
  2001,
  '1w5nWhUzrQqj0WnDXrgsnC'),
 ('Shakira',
  'latin pop',
  'track',
  'Suerte (Whenever, Wherever)',
  2001,
  '3TY1PFZXmYeiLcXygB74My'),
 ('Jean Carlos',
  'latin pop',
  'track',
  'Quiereme',
  2001,
  '2749jULVf3n93RHzAIpmTi'),
 ('Miguel Bosé',
  'latin pop',
  'track',
  'Mirarte',
  2001,
  '0aRXxDCsqv15KjKeUrTT3Z'),
 ("Mo' Horizons",
  'latin pop',
  'track',
  'Cha Cha Cha',
  2001,
  '3autSJVPpfSpsvSKHm6PF2'),
 ('Shakira',
  'latin pop',
  'track',
  'Te Dejo Madrid',
  2001,
  '3ToWC9JYSmDIa9yJs0k6PO'),
 ('Enrique Iglesias',
  'latin pop',
  'track',
  'Escapar',
  2001,
  '3UTEEPuMNeMjfer5BZg2ne'),
 ('Beny Moré',
  'latin pop',
  'track',
  'Bonito y Sabroso',
  2001,
  '0mxOACRTcfoUtCcsbgSw2R'),
 ('Andrés Cepeda',
  'latin pop',
  'track',
  'El Carpintero del Amor',
  2001,
  '48gkJPgPQRWEQ6KROOXHB4'),
 ('Jennifer Lopez',
  'latin pop',
  'track',
  "Que Ironia (Ain't It Funny)",
  2001,
  '6GraX5ZAA1H3ahBuY9bUsj'),
 ('Laura Pausini',
  'latin pop',
  'track',
  'Se fué - Versión 2001',
  2001,
  '1okB84GHnf4CUGaR41TdkW'),
 ('Carlos Vives',
  'latin pop',
  'track',
  'Dejame Entrar - Vallenato',
  2001,
  '6Hb2ACYykM73uDQ3h2HVZc'),
 ('Marc Anthony',
  'latin pop',
  'track',
  'Tragedia',
  2001,
  '57Jg4oOmi5nDxTfgYupXOF'),
 ('Luis Miguel',
  'latin pop',
  'track',
  'Amor (Amor, amor, amor)',
  2001,
  '1k4GYtmW7edpJ9uhQmzO66'),
 ('Bacilos',
  'latin pop',
  'track',
  'Lo Mismo Que Yo',
  2001,
  '6FIZDGD7A15jGZ5oI3b5sG'),
 ('Bacilos',
  'latin pop',
  'track',
  'Besala Ya',
  2001,
  '50mROPNHQ6xkNnHcXlNhOZ'),
 ('Miguel Bosé',
  'latin pop',
  'track',
  'Puede que',
  2001,
  '6ZioYho38EzmR15NRVKOl9'),
 ('Carlos Vives',
  'latin pop',
  'track',
  'Quiero Verte Sonreir',
  2001,
  '15pVedXa5un2RkNRix3Qet'),
 ('Guaraná',
  'latin pop',
  'track',
  'Echame a Mí la Culpa',
  2001,
  '2vIprOKFrPtsnQtADuVUp8'),
 ('Miguel Bosé',
  'latin pop',
  'track',
  'Te digo amor',
  2001,
  '1ceXRxQfEX0yuN3wZWcG3J'),
 ('Marc Anthony',
  'latin pop',
  'track',
  'Valio la Pena',
  2001,
  '0auNaXOXs33GglZq5W0ixb'),
 ('Carlos Vives',
  'latin pop',
  'track',
  'Luna Nueva',
  2001,
  '1fAzF0YA0bPy65wNS7pu9h'),
 ('Miguel Bosé',
  'latin pop',
  'track',
  'Gulliver',
  2001,
  '0ozPBJGryvMbMCadTU3M9a'),
 ('Miguel Bosé',
  'latin pop',
  'track',
  'Sereno',
  2001,
  '0lb2MUjcw5ijjStEGf5AZE'),
 ('Diego Torres',
  'latin pop',
  'track',
  'Que No Me Pierda',
  2001,
  '1hddbV736FaAFxMho50n75'),
 ('Raulin Rodriguez',
  'latin pop',
  'track',
  'Popurry Porque Tengo Ganas - En Vivo',
  2001,
  '7adMt1YTURYd7AMFOswVgy'),
 ('Alejandro Sanz',
  'latin pop',
  'track',
  'Aprendiz - Unplugged',
  2001,
  '7efXKi4jjGrXMvO6N7U2N4'),
 ('Diego Torres',
  'latin pop',
  'track',
  'Color Esperanza',
  2001,
  '3T07pNAEVr9adeIG9i1ex4'),
 ('Shakira',
  'latin pop',
  'track',
  'Te Dejo Madrid',
  2001,
  '0IESLhxv5iqXvMH5mm3z88'),
 ('Bacilos',
  'latin pop',
  'track',
  'Tabaco y Chanel',
  2001,
  '48svUiwMMYQRPyesVEnof1'),
 ('Alejandro Sanz',
  'latin pop',
  'track',
  'Y sólo se me ocurre amarte',
  2001,
  '05Zcw1sWmSu3wfbaLTeosp'),
 ('Carlos Vives',
  'latin pop',
  'track',
  'Carito',
  2001,
  '5czkBkWogUvTf2jleGyHaQ'),
 ('Carlos Vives',
  'latin pop',
  'track',
  'Dejame Entrar',
  2001,
  '2jNqxXMkVVpEvjvvwvUDDD'),
 ('Miguel Bosé',
  'latin pop',
  'track',
  'Morena mía',
  2001,
  '0HmQkmfYXRPweIg1ycw1R8'),
 ('Enrique Iglesias',
  'latin pop',
  'track',
  'Heroe',
  2001,
  '4AkrkORGjiz7c90mwxAvdW'),
 ('Diego Torres',
  'latin pop',
  'track',
  'Sueños',
  2001,
  '6arKgQHCGt2buopAxKTpQt'),
 ('Shakira',
  'latin pop',
  'track',
  'Que Me Quedes Tú',

In [34]:
## saco de mi lista de tuplas una lista de artistas para traspasarla a lastfm

In [36]:
def artista_tupla(lista_tuplas):
    lista_artista = []
    for dato in lista_tuplas:
        artista = dato[0]
        lista_artista.append(artista)
    print(lista_artista)
    return lista_artista

In [37]:

artista_tupla(df_latin_pop_tuplas)

['La Oreja de Van Gogh', 'Ricky Martin', 'Thalia', 'Rodrigo', 'Rodrigo', 'Paulina Rubio', 'Los Tucanes De Tijuana', 'Rodrigo', 'Rodrigo', 'Alejandro Sanz', 'Thalia', 'Chayanne', 'Celia Cruz', 'Juanes', 'Chayanne', 'Chayanne', 'Rodrigo', 'Ana Torroja', 'Laura Pausini', 'Alejandro Sanz', 'La Oreja de Van Gogh', 'Chayanne', 'Armando Manzanero', 'Paulina Rubio', 'Donato Y Estefano', 'Ana Torroja', 'Alejandro Sanz', 'Paulina Rubio', 'Alejandro Sanz', 'Christina Aguilera', 'Gloria Estefan', 'Chayanne', 'Celia Cruz', 'Alejandro Sanz', 'La Oreja de Van Gogh', 'Christina Aguilera', 'La Oreja de Van Gogh', 'Eros Ramazzotti', 'Paulina Rubio', 'Paulina Rubio', 'Thalia', 'La Oreja de Van Gogh', 'La Oreja de Van Gogh', 'La Oreja de Van Gogh', 'La Oreja de Van Gogh', 'La Oreja de Van Gogh', 'Eros Ramazzotti', 'La Oreja de Van Gogh', 'Alejandro Sanz', 'Alejandro Sanz', 'El Cuarteto De Nos', 'Los Tucanes De Tijuana', 'El Cuarteto De Nos', 'Ricardo Arjona', 'Paulina Rubio', 'Celia Cruz', 'Jean Carlos', 'Banda XXI', 'Nek', 'Los Tucanes De Tijuana', 'Walter Olmos', 'Walter Olmos', 'Rodrigo', 'Beto Quintanilla', 'Alejandro Sanz', 'Rodrigo', 'Rodrigo', 'Luis Alberto Posada', 'Rodrigo', 'Rodrigo', 'El Cuarteto De Nos', 'Alejandro Sanz', 'Thalia', 'Ana Torroja', 'Ana Torroja', 'El Cuarteto De Nos', 'Ana Torroja', 'Fey', 'Celia Cruz', 'Debelah Morgan', 'Ana Torroja', 'Ana Torroja', 'Paulina Rubio', 'Rey Ruiz', 'Ana Torroja', 'Thalia', 'Walter Olmos', 'Ana Torroja', 'Bertin Osborne', 'Alejandro Sanz', 'Chayanne', 'Alejandro Sanz', 'La Retrocumbia', 'La Retrocumbia', 'La Gran Banda', 'Luis Alberto Posada', 'Luis Alberto Posada', 'La Retrocumbia', 'La Retrocumbia', 'La Retrocumbia', 'Los Razos', 'Walter Olmos', 'Beto Quintanilla', 'Walter Olmos', 'Walter Olmos', 'Beto Quintanilla', 'Alejandro Sanz', 'Chayanne', 'Alejandro Sanz', 'Donato Y Estefano', 'El Cuarteto De Nos', 'Ana Torroja', 'Jean Carlos', 'La Oreja de Van Gogh', 'Julio Iglesias', 'Chayanne', 'Donato Y Estefano', 'Juanes', 'Ana Torroja', 'Jimmy Bosch', 'Ana Torroja', 'Banda XXI', 'Shakira', 'Ricky Martin', 'Ana Torroja', 'Donato Y Estefano', 'Luis Alberto Posada', 'Donato Y Estefano', 'Ana Torroja', 'Alejandro Sanz', 'Issac Delgado', 'Nek', 'Juanes', 'La Mosca', 'Ana Torroja', 'Polo Montañez', 'Walter Olmos', 'Tru La La', 'Rodrigo', 'Alejandro Sanz', 'Celia Cruz', 'Donato Y Estefano', 'El Cuarteto De Nos', 'Ana Torroja', 'Ana Torroja', 'Ana Torroja', 'Luisito Muñoz', 'Walter Olmos', 'Luis Alberto Posada', "Los Chaque's", 'Sabroso', 'Shakira', 'José José', 'Shakira', 'Aleks Syntek', 'Shakira', 'Shakira', 'Jean Carlos', 'Miguel Bosé', "Mo' Horizons", 'Shakira', 'Enrique Iglesias', 'Beny Moré', 'Andrés Cepeda', 'Jennifer Lopez', 'Laura Pausini', 'Carlos Vives', 'Marc Anthony', 'Luis Miguel', 'Bacilos', 'Bacilos', 'Miguel Bosé', 'Carlos Vives', 'Guaraná', 'Miguel Bosé', 'Marc Anthony', 'Carlos Vives', 'Miguel Bosé', 'Miguel Bosé', 'Diego Torres', 'Raulin Rodriguez', 'Alejandro Sanz', 'Diego Torres', 'Shakira', 'Bacilos', 'Alejandro Sanz', 'Carlos Vives', 'Carlos Vives', 'Miguel Bosé', 'Enrique Iglesias', 'Diego Torres', 'Shakira', 'Sin Bandera', 'Sin Bandera', 'Sin Bandera', 'Shakira', 'Shakira', 'Cristian Castro', 'Sin Bandera', 'Cristian Castro', 'Cristian Castro', 'Los Tigres Del Norte', 'Aleks Syntek', 'Sabroso', 'Los Razos', 'Cristian Castro', 'Beto Quintanilla', 'Lemon', 'Carlos Vives', 'Bacilos', 'Shakira', 'Laura Pausini', 'Shakira', 'Shakira', 'Jimmy Gutierrez', 'Alejandro Parreño', 'Jennifer Lopez', 'Rodrigo', 'Enrique Iglesias', 'Shakira', 'Jean Carlos', 'Shakira', 'Carlos Vives', 'Diego Torres', 'Diego Torres', 'Shakira', 'Enrique Iglesias', 'Marc Anthony', 'Shakira', 'Rios De Gloria', 'Carlos Vives', 'Shakira', 'Miguel Bosé', 'Shakira', 'Diego Torres', 'Enrique Iglesias', 'Skeewiff', 'Jennifer Lopez', 'Jennifer Lopez', 'Orquesta Tabaco Y Ron', 'Bacilos', 'Malú', 'Joaquín Sabina', 'Marcela Morelo', 'Clave Cubana', 'Miguel Bosé', 'Chayanne', 'Miguel Bosé', 'Tru La La', 'Miguel Bosé', 'Los Originales De San Juan', 'Aleks Syntek', 'Glup!', 'Tru La La', 'Beto Quintanilla', 'Diego Torres', 'Hermanos Rigual', 'Bacilos', 'Los Cachorros de Juan Villarreal', 'Diego Torres', 'Chayanne', 'Walter Olmos', 'Marc Anthony', 'Laura Miller', 'Enrique Iglesias', 'Sin Bandera', 'Walter Olmos', 'Beto Quintanilla', 'Carlos Vives', 'Marc Anthony', 'Malú', 'Walter Olmos', 'Jean Carlos', 'Enrique Iglesias', 'Thalia', 'Rodrigo', 'Sin Bandera', 'Enrique Iglesias', 'Huey Dunbar', 'Carlos Vives', 'Alejandra Guzman', 'Beto Quintanilla', 'Sin Bandera', 'Carlos Vives', 'Ricardo Montaner', 'Clave Cubana', 'La Mona Jimenez', 'La Barra', 'Enrique Iglesias', 'Diego Torres', 'Sabroso', 'Alejandra Guzman', 'Enrique Iglesias', 'Alejandra Guzman', 'Tommy Torres', 'Diego Torres', 'Beto Quintanilla', 'Jon Secada', 'Andrés Cepeda', 'Draco Rosa', 'Ricardo Arjona', 'Chayanne', 'Alejandra Guzman', 'Bacilos', 'Nek', 'Ricardo Arjona', 'La Quinta Estacion', 'Francisco Céspedes', 'Thalia', 'Marc Anthony', 'Enrique Iglesias', 'Cabas', 'Marc Anthony', 'David Bisbal', 'Shakira', 'La Quinta Estacion', 'Chayanne', 'Shakira', 'Natalia Lafourcade', 'Enrique Iglesias', 'Alejandro Fernández', 'Alejandro Fernández', 'David Bisbal', 'Enrique Iglesias', 'La Gran Banda', 'Marc Anthony', 'Thalia', 'Thalia', 'David Bisbal', 'Paulina Rubio', 'Paulina Rubio', 'Paulina Rubio', 'Enrique Iglesias', 'Chayanne', 'Chayanne', 'Ricardo Arjona', 'Cristian Castro', 'Juanes', 'Cristian Castro', 'Ricardo Arjona', 'Shakira', 'David Bisbal', 'Juanes', 'David Bisbal', 'Bacilos', 'Juanes', 'Juanes', 'Bacilos', 'Shakira', 'Chayanne', 'Ricardo Arjona', 'Los Caligaris', 'La Mona Jimenez', 'Thalia', 'Paulina Rubio', 'Juanes', 'Marc Anthony', 'Chayanne', 'Las Ketchup', 'Shakira', 'Paulina Rubio', 'Ricardo Arjona', 'Chayanne', 'Juanes', 'David Bisbal', 'Ricardo Arjona', 'Thalia', 'Thalia', 'Enrique Iglesias', 'Ricardo Arjona', 'Ricardo Arjona', 'Chayanne', 'Chayanne', 'Shakira', 'Chayanne', 'Juanes', 'David Bisbal', 'La Barra', 'Shakira', 'Chayanne', 'Ricardo Montaner', 'Ricardo Arjona', 'Shakira', 'Edwin Bonilla', 'Juanes', 'Ricardo Arjona', 'Shakira', 'Chayanne', 'Cubismo', 'Bacilos', 'David Bisbal', 'Chayanne', 'Shakira', 'Shakira', 'Alejandro Fernández', 'Marc Anthony', 'Alejandro Fernández', 'Los Fachero´s', 'Alejandro Fernández', 'Raulin Rodriguez', 'Los Playeros', 'Los Playeros', 'Los Incomparables De Tijuana', 'Los Playeros', 'Uriel Henao', 'Banda XXI', 'Bacilos', 'Miranda!', 'Marc Anthony', 'Chayanne', 'Enrique Iglesias', 'Juanes', 'Banda XXI', 'Juanes', 'Chayanne', 'Amparanoia', 'Luis Miguel', 'Eydie Gormé', 'Ricardo Arjona', 'David Bisbal', 'Los Playeros', 'Chayanne', 'Enrique Iglesias', 'Ricardo Arjona', 'Chayanne', 'La Quinta Estacion', 'Víctor Manuelle', 'Bacilos', 'Andy Aguilera', 'Aleks Syntek', 'Carlos Ponce', 'Murga Contrafarsa', 'Shakira', 'Shakira', 'Enrique Iglesias', 'La Quinta Estacion', 'Ricardo Montaner', 'Enrique Iglesias', 'Alejandra Guzman', 'Paulina Rubio', 'Chayanne', 'Juanes', 'La Quinta Estacion', 'Chayanne', 'Shakira', 'La Quinta Estacion', 'Ricardo Arjona', 'Banda XXI', 'Juan Formell y Los Van Van', 'Los Fachero´s', 'Ricky Martin', 'Ha*Ash', 'Sebastian', 'Belinda', 'Chayanne', 'Los Tucanes De Tijuana', 'Chayanne', 'Sin Bandera', 'Yahir', 'Ricky Martin', 'Julieta Venegas', 'Luis Miguel', 'Julieta Venegas', 'Ricky Martin', 'Luis Miguel', 'Julieta Venegas', 'Ha*Ash', 'Luis Miguel', 'Sin Bandera', 'Chayanne', 'Chayanne', 'Jimmy Sabater', 'Willie Bobo', 'Jarabe De Palo', 'Belinda', 'Sin Bandera', 'Luis Miguel', 'Mauricio & PalodeAgua', 'La Oreja de Van Gogh', 'La Oreja de Van Gogh', 'La Oreja de Van Gogh', 'La Oreja de Van Gogh', 'Ricky Martin', 'Sin Bandera', 'La Oreja de Van Gogh', 'La Oreja de Van Gogh', 'La Oreja de Van Gogh', 'La Oreja de Van Gogh', 'La Oreja de Van Gogh', 'Luis Miguel', 'La Oreja de Van Gogh', 'La Oreja de Van Gogh', 'Sin Bandera', 'La Oreja de Van Gogh', 'Sin Bandera', 'Michael Bublé', 'Julieta Venegas', 'La Oreja de Van Gogh', 'Julieta Venegas', 'Gloria Estefan', 'Grupo Exterminador', 'Grupo Exterminador', 'La Barra', 'Banda XXI', 'Tranzas', 'Latin Dreams', 'Tru La La', 'Sin Bandera', 'Mauricio & PalodeAgua', 'Belinda', 'Danni Ubeda', 'Luis Fonsi', 'Rey Ruiz', 'Noelia', 'Sin Bandera', 'Ana Torroja', 'Bacanos', 'Alexandre Pires', 'Chayanne', 'OBK', 'Ha*Ash', 'Tiziano Ferro', 'Beto Quintanilla', 'Yámana', 'David Calzado y su Charanga Habanera', 'Tru La La', 'Moises Angulo', 'Patricia Manterola', 'Danni Ubeda', 'Ha*Ash', 'Ana Torroja', 'Belinda', 'Sin Bandera', 'Enrique Iglesias', 'Ha*Ash', 'Danni Ubeda', 'Mauricio & PalodeAgua', 'Sin Bandera', 'Raul Paz', 'Beto Quintanilla', 'Tiziano Ferro', 'Los Tucanes De Tijuana', 'Ricky Martin', 'Beto Quintanilla', 'Julieta Venegas', 'Julieta Venegas', 'Pepe Aguilar', 'Wakal', 'Grupo Aliados', 'Paco Pineda y Su Grupo Tex Mex', 'Beto Quintanilla', 'Los Playeros', 'Papá Levante', 'Yuri Buenaventura', 'Shalim', 'Enrique Iglesias', 'Ana Torroja', 'Bustamante', 'La Mona Jimenez', 'Belinda', 'Geno', 'Chic Savanna', 'Sebastian', 'Obie Bermudez', 'Thalia', 'Ricardo Montaner', 'Jean Carlos', 'Banda XXI', 'Thalia', 'Mauricio & PalodeAgua', 'Chayanne', 'Luis Fonsi', 'Ana Torroja', 'Julieta Venegas', 'Julieta Venegas', 'Tiziano Ferro', 'Grupo Escuela del Amor', 'Beto Quintanilla', 'Los Playeros', 'Paco Pineda y Su Grupo Tex Mex', 'Wakal', 'Andrés Cepeda', 'Julieta Venegas', 'Wakal', 'Grupo Exterminador', 'La Barra', 'Chayanne', 'La Fiesta', 'Sin Bandera', 'Qarto Aparte', 'Christina Aguilera', 'Chayanne', 'Ricky Martin', 'Chayanne', 'Banda XXI', 'Ricky Martin', 'Thalia', 'Papá Levante', 'Tiziano Ferro', 'Wakal', 'LU', 'RBD', 'Diego Torres', 'El Cuarteto De Nos', 'Miguel Bosé', 'Juanes', 'David Bisbal', 'El Cuarteto De Nos', 'La Oreja de Van Gogh', 'Alejandro Sanz', 'Juanes', 'Laura Pausini', 'Bacilos', 'Diego Torres', 'Marc Anthony', 'La Oreja de Van Gogh', 'La Oreja de Van Gogh', 'RBD', 'La Oreja de Van Gogh', 'RBD', 'Alejandro Sanz', 'La Quinta Estacion', 'Alejandro Sanz', 'La Oreja de Van Gogh', 'Alejandro Sanz', 'RBD', 'Ricardo Arjona', 'La Oreja de Van Gogh', 'Juanes', 'Bacilos', 'La Quinta Estacion', 'Alejandro Fernández', 'Franco De Vita', 'Gloria Estefan', 'David Bisbal', 'Juanes', 'Paulina Rubio', 'RBD', 'Alejandro Fernández', 'Aleks Syntek', 'La Oreja de Van Gogh', 'Alejandro Sanz', 'RBD', 'Juanes', 'Franco De Vita', 'La Quinta Estacion', 'Juanes', 'La Oreja de Van Gogh', 'La Oreja de Van Gogh', 'Alejandro Sanz', 'Marc Anthony', 'RBD', 'La Quinta Estacion', 'RBD', 'Benny', 'RBD', 'Ricardo Arjona', 'Aleks Syntek', 'Lucas Arnau', 'Alejandro Sanz', 'RBD', 'Alejandro Sanz', 'La Oreja de Van Gogh', 'David Bisbal', 'La Oreja de Van Gogh', 'David Bisbal', 'La Quinta Estacion', 'Alejandro Sanz', 'Alejandro Sanz', 'Juanes', 'Alejandro Sanz', 'Diego Torres', 'Alejandro Sanz', 'David Bisbal', 'Juanes', 'Alejandro Sanz', 'La-33', 'La Oreja de Van Gogh', 'Alejandro Sanz', 'Alejandro Sanz', 'La Oreja de Van Gogh', 'La Oreja de Van Gogh', 'Marc Anthony', 'Obie Bermudez', 'La Oreja de Van Gogh', 'Carlos Vives', 'Marc Anthony', 'La Oreja de Van Gogh', 'Miguel Bosé', 'El Cuarteto De Nos', 'Alejandro Sanz', 'Thalia', 'Marc Anthony', 'Alejandro Sanz', 'La Oreja de Van Gogh', 'Alejandro Sanz', 'Marc Anthony', 'David Bisbal', 'Alejandro Sanz', 'Alejandro Sanz', 'Yahir', 'Marc Anthony', 'El Cuarteto De Nos', 'Franco De Vita', 'El Cuarteto De Nos', 'El Cuarteto De Nos', 'Alejandro Sanz', 'Thalia', 'El Cuarteto De Nos', 'Gloria Trevi', 'Alejandro Sanz', 'Laura Pausini', 'Nek', 'LU', 'Diego Torres', 'La Oreja de Van Gogh', 'Thalia', 'Ricardo Arjona', 'Juanes', 'Alejandro Sanz', 'Juanes', 'KEMA', 'Los Palmeras', 'Paulina Rubio', 'Alejandro Sanz', 'Miranda!', 'La Oreja de Van Gogh', 'Alejandro Sanz', 'Alejandro Sanz', 'La Quinta Estacion', 'La Oreja de Van Gogh', 'Alejandro Sanz', 'El Cuarteto De Nos', 'Lucas Arnau', 'Miranda!', 'Lucas Arnau', 'Damas Gratis', 'RBD', 'La Oreja de Van Gogh', 'La Oreja de Van Gogh', 'Juanes', 'Diego Torres', 'Ricardo Arjona', 'Alejandro Sanz', 'Paulina Rubio', 'Alejandro Sanz', 'Carlos Vives', 'Franco De Vita', 'Yahir', 'Alejandro Sanz']

['La Oreja de Van Gogh',
 'Ricky Martin',
 'Thalia',
 'Rodrigo',
 'Rodrigo',
 'Paulina Rubio',
 'Los Tucanes De Tijuana',
 'Rodrigo',
 'Rodrigo',
 'Alejandro Sanz',
 'Thalia',
 'Chayanne',
 'Celia Cruz',
 'Juanes',
 'Chayanne',
 'Chayanne',
 'Rodrigo',
 'Ana Torroja',
 'Laura Pausini',
 'Alejandro Sanz',
 'La Oreja de Van Gogh',
 'Chayanne',
 'Armando Manzanero',
 'Paulina Rubio',
 'Donato Y Estefano',
 'Ana Torroja',
 'Alejandro Sanz',
 'Paulina Rubio',
 'Alejandro Sanz',
 'Christina Aguilera',
 'Gloria Estefan',
 'Chayanne',
 'Celia Cruz',
 'Alejandro Sanz',
 'La Oreja de Van Gogh',
 'Christina Aguilera',
 'La Oreja de Van Gogh',
 'Eros Ramazzotti',
 'Paulina Rubio',
 'Paulina Rubio',
 'Thalia',
 'La Oreja de Van Gogh',
 'La Oreja de Van Gogh',
 'La Oreja de Van Gogh',
 'La Oreja de Van Gogh',
 'La Oreja de Van Gogh',
 'Eros Ramazzotti',
 'La Oreja de Van Gogh',
 'Alejandro Sanz',
 'Alejandro Sanz',
 'El Cuarteto De Nos',
 'Los Tucanes De Tijuana',
 'El Cuarteto De Nos',
 'Ricardo Arjona',
 'Paulina Rubio',
 'Celia Cruz',
 'Jean Carlos',
 'Banda XXI',
 'Nek',
 'Los Tucanes De Tijuana',
 'Walter Olmos',
 'Walter Olmos',
 'Rodrigo',
 'Beto Quintanilla',
 'Alejandro Sanz',
 'Rodrigo',
 'Rodrigo',
 'Luis Alberto Posada',
 'Rodrigo',
 'Rodrigo',
 'El Cuarteto De Nos',
 'Alejandro Sanz',
 'Thalia',
 'Ana Torroja',
 'Ana Torroja',
 'El Cuarteto De Nos',
 'Ana Torroja',
 'Fey',
 'Celia Cruz',
 'Debelah Morgan',
 'Ana Torroja',
 'Ana Torroja',
 'Paulina Rubio',
 'Rey Ruiz',
 'Ana Torroja',
 'Thalia',
 'Walter Olmos',
 'Ana Torroja',
 'Bertin Osborne',
 'Alejandro Sanz',
 'Chayanne',
 'Alejandro Sanz',
 'La Retrocumbia',
 'La Retrocumbia',
 'La Gran Banda',
 'Luis Alberto Posada',
 'Luis Alberto Posada',
 'La Retrocumbia',
 'La Retrocumbia',
 'La Retrocumbia',
 'Los Razos',
 'Walter Olmos',
 'Beto Quintanilla',
 'Walter Olmos',
 'Walter Olmos',
 'Beto Quintanilla',
 'Alejandro Sanz',
 'Chayanne',
 'Alejandro Sanz',
 'Donato Y Estefano',
 'El Cuarteto De Nos',
 'Ana Torroja',
 'Jean Carlos',
 'La Oreja de Van Gogh',
 'Julio Iglesias',
 'Chayanne',
 'Donato Y Estefano',
 'Juanes',
 'Ana Torroja',
 'Jimmy Bosch',
 'Ana Torroja',
 'Banda XXI',
 'Shakira',
 'Ricky Martin',
 'Ana Torroja',
 'Donato Y Estefano',
 'Luis Alberto Posada',
 'Donato Y Estefano',
 'Ana Torroja',
 'Alejandro Sanz',
 'Issac Delgado',
 'Nek',
 'Juanes',
 'La Mosca',
 'Ana Torroja',
 'Polo Montañez',
 'Walter Olmos',
 'Tru La La',
 'Rodrigo',
 'Alejandro Sanz',
 'Celia Cruz',
 'Donato Y Estefano',
 'El Cuarteto De Nos',
 'Ana Torroja',
 'Ana Torroja',
 'Ana Torroja',
 'Luisito Muñoz',
 'Walter Olmos',
 'Luis Alberto Posada',
 "Los Chaque's",
 'Sabroso',
 'Shakira',
 'José José',
 'Shakira',
 'Aleks Syntek',
 'Shakira',
 'Shakira',
 'Jean Carlos',
 'Miguel Bosé',
 "Mo' Horizons",
 'Shakira',
 'Enrique Iglesias',
 'Beny Moré',
 'Andrés Cepeda',
 'Jennifer Lopez',
 'Laura Pausini',
 'Carlos Vives',
 'Marc Anthony',
 'Luis Miguel',
 'Bacilos',
 'Bacilos',
 'Miguel Bosé',
 'Carlos Vives',
 'Guaraná',
 'Miguel Bosé',
 'Marc Anthony',
 'Carlos Vives',
 'Miguel Bosé',
 'Miguel Bosé',
 'Diego Torres',
 'Raulin Rodriguez',
 'Alejandro Sanz',
 'Diego Torres',
 'Shakira',
 'Bacilos',
 'Alejandro Sanz',
 'Carlos Vives',
 'Carlos Vives',
 'Miguel Bosé',
 'Enrique Iglesias',
 'Diego Torres',
 'Shakira',
 'Sin Bandera',
 'Sin Bandera',
 'Sin Bandera',
 'Shakira',
 'Shakira',
 'Cristian Castro',
 'Sin Bandera',
 'Cristian Castro',
 'Cristian Castro',
 'Los Tigres Del Norte',
 'Aleks Syntek',
 'Sabroso',
 'Los Razos',
 'Cristian Castro',
 'Beto Quintanilla',
 'Lemon',
 'Carlos Vives',
 'Bacilos',
 'Shakira',
 'Laura Pausini',
 'Shakira',
 'Shakira',
 'Jimmy Gutierrez',
 'Alejandro Parreño',
 'Jennifer Lopez',
 'Rodrigo',
 'Enrique Iglesias',
 'Shakira',
 'Jean Carlos',
 'Shakira',
 'Carlos Vives',
 'Diego Torres',
 'Diego Torres',
 'Shakira',
 'Enrique Iglesias',
 'Marc Anthony',
 'Shakira',
 'Rios De Gloria',
 'Carlos Vives',
 'Shakira',
 'Miguel Bosé',
 'Shakira',
 'Diego Torres',
 'Enrique Iglesias',
 'Skeewiff',
 'Jennifer Lopez',
 'Jennifer Lopez',
 'Orquesta Tabaco Y Ron',
 'Bacilos',
 'Malú',
 'Joaquín Sabina',
 'Marcela Morelo',
 'Clave Cubana',
 'Miguel Bosé',
 'Chayanne',
 'Miguel Bosé',
 'Tru La La',
 'Miguel Bosé',
 'Los Originales De San Juan',
 'Aleks Syntek',
 'Glup!',
 'Tru La La',
 'Beto Quintanilla',
 'Diego Torres',
 'Hermanos Rigual',
 'Bacilos',
 'Los Cachorros de Juan Villarreal',
 'Diego Torres',
 'Chayanne',
 'Walter Olmos',
 'Marc Anthony',
 'Laura Miller',
 'Enrique Iglesias',
 'Sin Bandera',
 'Walter Olmos',
 'Beto Quintanilla',
 'Carlos Vives',
 'Marc Anthony',
 'Malú',
 'Walter Olmos',
 'Jean Carlos',
 'Enrique Iglesias',
 'Thalia',
 'Rodrigo',
 'Sin Bandera',
 'Enrique Iglesias',
 'Huey Dunbar',
 'Carlos Vives',
 'Alejandra Guzman',
 'Beto Quintanilla',
 'Sin Bandera',
 'Carlos Vives',
 'Ricardo Montaner',
 'Clave Cubana',
 'La Mona Jimenez',
 'La Barra',
 'Enrique Iglesias',
 'Diego Torres',
 'Sabroso',
 'Alejandra Guzman',
 'Enrique Iglesias',
 'Alejandra Guzman',
 'Tommy Torres',
 'Diego Torres',
 'Beto Quintanilla',
 'Jon Secada',
 'Andrés Cepeda',
 'Draco Rosa',
 'Ricardo Arjona',
 'Chayanne',
 'Alejandra Guzman',
 'Bacilos',
 'Nek',
 'Ricardo Arjona',
 'La Quinta Estacion',
 'Francisco Céspedes',
 'Thalia',
 'Marc Anthony',
 'Enrique Iglesias',
 'Cabas',
 'Marc Anthony',
 'David Bisbal',
 'Shakira',
 'La Quinta Estacion',
 'Chayanne',
 'Shakira',
 'Natalia Lafourcade',
 'Enrique Iglesias',
 'Alejandro Fernández',
 'Alejandro Fernández',
 'David Bisbal',
 'Enrique Iglesias',
 'La Gran Banda',
 'Marc Anthony',
 'Thalia',
 'Thalia',
 'David Bisbal',
 'Paulina Rubio',
 'Paulina Rubio',
 'Paulina Rubio',
 'Enrique Iglesias',
 'Chayanne',
 'Chayanne',
 'Ricardo Arjona',
 'Cristian Castro',
 'Juanes',
 'Cristian Castro',
 'Ricardo Arjona',
 'Shakira',
 'David Bisbal',
 'Juanes',
 'David Bisbal',
 'Bacilos',
 'Juanes',
 'Juanes',
 'Bacilos',
 'Shakira',
 'Chayanne',
 'Ricardo Arjona',
 'Los Caligaris',
 'La Mona Jimenez',
 'Thalia',
 'Paulina Rubio',
 'Juanes',
 'Marc Anthony',
 'Chayanne',
 'Las Ketchup',
 'Shakira',
 'Paulina Rubio',
 'Ricardo Arjona',
 'Chayanne',
 'Juanes',
 'David Bisbal',
 'Ricardo Arjona',
 'Thalia',
 'Thalia',
 'Enrique Iglesias',
 'Ricardo Arjona',
 'Ricardo Arjona',
 'Chayanne',
 'Chayanne',
 'Shakira',
 'Chayanne',
 'Juanes',
 'David Bisbal',
 'La Barra',
 'Shakira',
 'Chayanne',
 'Ricardo Montaner',
 'Ricardo Arjona',
 'Shakira',
 'Edwin Bonilla',
 'Juanes',
 'Ricardo Arjona',
 'Shakira',
 'Chayanne',
 'Cubismo',
 'Bacilos',
 'David Bisbal',
 'Chayanne',
 'Shakira',
 'Shakira',
 'Alejandro Fernández',
 'Marc Anthony',
 'Alejandro Fernández',
 'Los Fachero´s',
 'Alejandro Fernández',
 'Raulin Rodriguez',
 'Los Playeros',
 'Los Playeros',
 'Los Incomparables De Tijuana',
 'Los Playeros',
 'Uriel Henao',
 'Banda XXI',
 'Bacilos',
 'Miranda!',
 'Marc Anthony',
 'Chayanne',
 'Enrique Iglesias',
 'Juanes',
 'Banda XXI',
 'Juanes',
 'Chayanne',
 'Amparanoia',
 'Luis Miguel',
 'Eydie Gormé',
 'Ricardo Arjona',
 'David Bisbal',
 'Los Playeros',
 'Chayanne',
 'Enrique Iglesias',
 'Ricardo Arjona',
 'Chayanne',
 'La Quinta Estacion',
 'Víctor Manuelle',
 'Bacilos',
 'Andy Aguilera',
 'Aleks Syntek',
 'Carlos Ponce',
 'Murga Contrafarsa',
 'Shakira',
 'Shakira',
 'Enrique Iglesias',
 'La Quinta Estacion',
 'Ricardo Montaner',
 'Enrique Iglesias',
 'Alejandra Guzman',
 'Paulina Rubio',
 'Chayanne',
 'Juanes',
 'La Quinta Estacion',
 'Chayanne',
 'Shakira',
 'La Quinta Estacion',
 'Ricardo Arjona',
 'Banda XXI',
 'Juan Formell y Los Van Van',
 'Los Fachero´s',
 'Ricky Martin',
 'Ha*Ash',
 'Sebastian',
 'Belinda',
 'Chayanne',
 'Los Tucanes De Tijuana',
 'Chayanne',
 'Sin Bandera',
 'Yahir',
 'Ricky Martin',
 'Julieta Venegas',
 'Luis Miguel',
 'Julieta Venegas',
 'Ricky Martin',
 'Luis Miguel',
 'Julieta Venegas',
 'Ha*Ash',
 'Luis Miguel',
 'Sin Bandera',
 'Chayanne',
 'Chayanne',
 'Jimmy Sabater',
 'Willie Bobo',
 'Jarabe De Palo',
 'Belinda',
 'Sin Bandera',
 'Luis Miguel',
 'Mauricio & PalodeAgua',
 'La Oreja de Van Gogh',
 'La Oreja de Van Gogh',
 'La Oreja de Van Gogh',
 'La Oreja de Van Gogh',
 'Ricky Martin',
 'Sin Bandera',
 'La Oreja de Van Gogh',
 'La Oreja de Van Gogh',
 'La Oreja de Van Gogh',
 'La Oreja de Van Gogh',
 'La Oreja de Van Gogh',
 'Luis Miguel',
 'La Oreja de Van Gogh',
 'La Oreja de Van Gogh',
 'Sin Bandera',
 'La Oreja de Van Gogh',
 'Sin Bandera',
 'Michael Bublé',
 'Julieta Venegas',
 'La Oreja de Van Gogh',
 'Julieta Venegas',
 'Gloria Estefan',
 'Grupo Exterminador',
 'Grupo Exterminador',
 'La Barra',
 'Banda XXI',
 'Tranzas',
 'Latin Dreams',
 'Tru La La',
 'Sin Bandera',
 'Mauricio & PalodeAgua',
 'Belinda',
 'Danni Ubeda',
 'Luis Fonsi',
 'Rey Ruiz',
 'Noelia',
 'Sin Bandera',
 'Ana Torroja',
 'Bacanos',
 'Alexandre Pires',
 'Chayanne',
 'OBK',
 'Ha*Ash',
 'Tiziano Ferro',
 'Beto Quintanilla',
 'Yámana',
 'David Calzado y su Charanga Habanera',
 'Tru La La',
 'Moises Angulo',
 'Patricia Manterola',
 'Danni Ubeda',
 'Ha*Ash',
 'Ana Torroja',
 'Belinda',
 'Sin Bandera',
 'Enrique Iglesias',
 'Ha*Ash',
 'Danni Ubeda',
 'Mauricio & PalodeAgua',
 'Sin Bandera',
 'Raul Paz',
 'Beto Quintanilla',
 'Tiziano Ferro',
 'Los Tucanes De Tijuana',
 'Ricky Martin',
 'Beto Quintanilla',
 'Julieta Venegas',
 'Julieta Venegas',
 'Pepe Aguilar',
 'Wakal',
 'Grupo Aliados',
 'Paco Pineda y Su Grupo Tex Mex',
 'Beto Quintanilla',
 'Los Playeros',
 'Papá Levante',
 'Yuri Buenaventura',
 'Shalim',
 'Enrique Iglesias',
 'Ana Torroja',
 'Bustamante',
 'La Mona Jimenez',
 'Belinda',
 'Geno',
 'Chic Savanna',
 'Sebastian',
 'Obie Bermudez',
 'Thalia',
 'Ricardo Montaner',
 'Jean Carlos',
 'Banda XXI',
 'Thalia',
 'Mauricio & PalodeAgua',
 'Chayanne',
 'Luis Fonsi',
 'Ana Torroja',
 'Julieta Venegas',
 'Julieta Venegas',
 'Tiziano Ferro',
 'Grupo Escuela del Amor',
 'Beto Quintanilla',
 'Los Playeros',
 'Paco Pineda y Su Grupo Tex Mex',
 'Wakal',
 'Andrés Cepeda',
 'Julieta Venegas',
 'Wakal',
 'Grupo Exterminador',
 'La Barra',
 'Chayanne',
 'La Fiesta',
 'Sin Bandera',
 'Qarto Aparte',
 'Christina Aguilera',
 'Chayanne',
 'Ricky Martin',
 'Chayanne',
 'Banda XXI',
 'Ricky Martin',
 'Thalia',
 'Papá Levante',
 'Tiziano Ferro',
 'Wakal',
 'LU',
 'RBD',
 'Diego Torres',
 'El Cuarteto De Nos',
 'Miguel Bosé',
 'Juanes',
 'David Bisbal',
 'El Cuarteto De Nos',
 'La Oreja de Van Gogh',
 'Alejandro Sanz',
 'Juanes',
 'Laura Pausini',
 'Bacilos',
 'Diego Torres',
 'Marc Anthony',
 'La Oreja de Van Gogh',
 'La Oreja de Van Gogh',
 'RBD',
 'La Oreja de Van Gogh',
 'RBD',
 'Alejandro Sanz',
 'La Quinta Estacion',
 'Alejandro Sanz',
 'La Oreja de Van Gogh',
 'Alejandro Sanz',
 'RBD',
 'Ricardo Arjona',
 'La Oreja de Van Gogh',
 'Juanes',
 'Bacilos',
 'La Quinta Estacion',
 'Alejandro Fernández',
 'Franco De Vita',
 'Gloria Estefan',
 'David Bisbal',
 'Juanes',
 'Paulina Rubio',
 'RBD',
 'Alejandro Fernández',
 'Aleks Syntek',
 'La Oreja de Van Gogh',
 'Alejandro Sanz',
 'RBD',
 'Juanes',
 'Franco De Vita',
 'La Quinta Estacion',
 'Juanes',
 'La Oreja de Van Gogh',
 'La Oreja de Van Gogh',
 'Alejandro Sanz',
 'Marc Anthony',
 'RBD',
 'La Quinta Estacion',
 'RBD',
 'Benny',
 'RBD',
 'Ricardo Arjona',
 'Aleks Syntek',
 'Lucas Arnau',
 'Alejandro Sanz',
 'RBD',
 'Alejandro Sanz',
 'La Oreja de Van Gogh',
 'David Bisbal',
 'La Oreja de Van Gogh',
 'David Bisbal',
 'La Quinta Estacion',
 'Alejandro Sanz',
 'Alejandro Sanz',
 'Juanes',
 'Alejandro Sanz',
 'Diego Torres',
 'Alejandro Sanz',
 'David Bisbal',
 'Juanes',
 'Alejandro Sanz',
 'La-33',
 'La Oreja de Van Gogh',
 'Alejandro Sanz',
 'Alejandro Sanz',
 'La Oreja de Van Gogh',
 'La Oreja de Van Gogh',
 'Marc Anthony',
 'Obie Bermudez',
 'La Oreja de Van Gogh',
 'Carlos Vives',
 'Marc Anthony',
 'La Oreja de Van Gogh',
 'Miguel Bosé',
 'El Cuarteto De Nos',
 'Alejandro Sanz',
 'Thalia',
 'Marc Anthony',
 'Alejandro Sanz',
 'La Oreja de Van Gogh',
 'Alejandro Sanz',
 'Marc Anthony',
 'David Bisbal',
 'Alejandro Sanz',
 'Alejandro Sanz',
 'Yahir',
 'Marc Anthony',
 'El Cuarteto De Nos',
 'Franco De Vita',
 'El Cuarteto De Nos',
 'El Cuarteto De Nos',
 'Alejandro Sanz',
 'Thalia',
 'El Cuarteto De Nos',
 'Gloria Trevi',
 'Alejandro Sanz',
 'Laura Pausini',
 'Nek',
 'LU',
 'Diego Torres',
 'La Oreja de Van Gogh',
 'Thalia',
 'Ricardo Arjona',
 'Juanes',
 'Alejandro Sanz',
 'Juanes',
 'KEMA',
 'Los Palmeras',
 'Paulina Rubio',
 'Alejandro Sanz',
 'Miranda!',
 'La Oreja de Van Gogh',
 'Alejandro Sanz',
 'Alejandro Sanz',
 'La Quinta Estacion',
 'La Oreja de Van Gogh',
 'Alejandro Sanz',
 'El Cuarteto De Nos',
 'Lucas Arnau',
 'Miranda!',
 'Lucas Arnau',
 'Damas Gratis',
 'RBD',
 'La Oreja de Van Gogh',
 'La Oreja de Van Gogh',
 'Juanes',
 'Diego Torres',
 'Ricardo Arjona',
 'Alejandro Sanz',
 'Paulina Rubio',
 'Alejandro Sanz',
 'Carlos Vives',
 'Franco De Vita',
 'Yahir',
 'Alejandro Sanz']

In [38]:
lista_artista_latin_pop = artista_tupla(df_latin_pop_tuplas)

['La Oreja de Van Gogh', 'Ricky Martin', 'Thalia', 'Rodrigo', 'Rodrigo', 'Paulina Rubio', 'Los Tucanes De Tijuana', 'Rodrigo', 'Rodrigo', 'Alejandro Sanz', 'Thalia', 'Chayanne', 'Celia Cruz', 'Juanes', 'Chayanne', 'Chayanne', 'Rodrigo', 'Ana Torroja', 'Laura Pausini', 'Alejandro Sanz', 'La Oreja de Van Gogh', 'Chayanne', 'Armando Manzanero', 'Paulina Rubio', 'Donato Y Estefano', 'Ana Torroja', 'Alejandro Sanz', 'Paulina Rubio', 'Alejandro Sanz', 'Christina Aguilera', 'Gloria Estefan', 'Chayanne', 'Celia Cruz', 'Alejandro Sanz', 'La Oreja de Van Gogh', 'Christina Aguilera', 'La Oreja de Van Gogh', 'Eros Ramazzotti', 'Paulina Rubio', 'Paulina Rubio', 'Thalia', 'La Oreja de Van Gogh', 'La Oreja de Van Gogh', 'La Oreja de Van Gogh', 'La Oreja de Van Gogh', 'La Oreja de Van Gogh', 'Eros Ramazzotti', 'La Oreja de Van Gogh', 'Alejandro Sanz', 'Alejandro Sanz', 'El Cuarteto De Nos', 'Los Tucanes De Tijuana', 'El Cuarteto De Nos', 'Ricardo Arjona', 'Paulina Rubio', 'Celia Cruz', 'Jean Carlos', 'Banda XXI', 'Nek', 'Los Tucanes De Tijuana', 'Walter Olmos', 'Walter Olmos', 'Rodrigo', 'Beto Quintanilla', 'Alejandro Sanz', 'Rodrigo', 'Rodrigo', 'Luis Alberto Posada', 'Rodrigo', 'Rodrigo', 'El Cuarteto De Nos', 'Alejandro Sanz', 'Thalia', 'Ana Torroja', 'Ana Torroja', 'El Cuarteto De Nos', 'Ana Torroja', 'Fey', 'Celia Cruz', 'Debelah Morgan', 'Ana Torroja', 'Ana Torroja', 'Paulina Rubio', 'Rey Ruiz', 'Ana Torroja', 'Thalia', 'Walter Olmos', 'Ana Torroja', 'Bertin Osborne', 'Alejandro Sanz', 'Chayanne', 'Alejandro Sanz', 'La Retrocumbia', 'La Retrocumbia', 'La Gran Banda', 'Luis Alberto Posada', 'Luis Alberto Posada', 'La Retrocumbia', 'La Retrocumbia', 'La Retrocumbia', 'Los Razos', 'Walter Olmos', 'Beto Quintanilla', 'Walter Olmos', 'Walter Olmos', 'Beto Quintanilla', 'Alejandro Sanz', 'Chayanne', 'Alejandro Sanz', 'Donato Y Estefano', 'El Cuarteto De Nos', 'Ana Torroja', 'Jean Carlos', 'La Oreja de Van Gogh', 'Julio Iglesias', 'Chayanne', 'Donato Y Estefano', 'Juanes', 'Ana Torroja', 'Jimmy Bosch', 'Ana Torroja', 'Banda XXI', 'Shakira', 'Ricky Martin', 'Ana Torroja', 'Donato Y Estefano', 'Luis Alberto Posada', 'Donato Y Estefano', 'Ana Torroja', 'Alejandro Sanz', 'Issac Delgado', 'Nek', 'Juanes', 'La Mosca', 'Ana Torroja', 'Polo Montañez', 'Walter Olmos', 'Tru La La', 'Rodrigo', 'Alejandro Sanz', 'Celia Cruz', 'Donato Y Estefano', 'El Cuarteto De Nos', 'Ana Torroja', 'Ana Torroja', 'Ana Torroja', 'Luisito Muñoz', 'Walter Olmos', 'Luis Alberto Posada', "Los Chaque's", 'Sabroso', 'Shakira', 'José José', 'Shakira', 'Aleks Syntek', 'Shakira', 'Shakira', 'Jean Carlos', 'Miguel Bosé', "Mo' Horizons", 'Shakira', 'Enrique Iglesias', 'Beny Moré', 'Andrés Cepeda', 'Jennifer Lopez', 'Laura Pausini', 'Carlos Vives', 'Marc Anthony', 'Luis Miguel', 'Bacilos', 'Bacilos', 'Miguel Bosé', 'Carlos Vives', 'Guaraná', 'Miguel Bosé', 'Marc Anthony', 'Carlos Vives', 'Miguel Bosé', 'Miguel Bosé', 'Diego Torres', 'Raulin Rodriguez', 'Alejandro Sanz', 'Diego Torres', 'Shakira', 'Bacilos', 'Alejandro Sanz', 'Carlos Vives', 'Carlos Vives', 'Miguel Bosé', 'Enrique Iglesias', 'Diego Torres', 'Shakira', 'Sin Bandera', 'Sin Bandera', 'Sin Bandera', 'Shakira', 'Shakira', 'Cristian Castro', 'Sin Bandera', 'Cristian Castro', 'Cristian Castro', 'Los Tigres Del Norte', 'Aleks Syntek', 'Sabroso', 'Los Razos', 'Cristian Castro', 'Beto Quintanilla', 'Lemon', 'Carlos Vives', 'Bacilos', 'Shakira', 'Laura Pausini', 'Shakira', 'Shakira', 'Jimmy Gutierrez', 'Alejandro Parreño', 'Jennifer Lopez', 'Rodrigo', 'Enrique Iglesias', 'Shakira', 'Jean Carlos', 'Shakira', 'Carlos Vives', 'Diego Torres', 'Diego Torres', 'Shakira', 'Enrique Iglesias', 'Marc Anthony', 'Shakira', 'Rios De Gloria', 'Carlos Vives', 'Shakira', 'Miguel Bosé', 'Shakira', 'Diego Torres', 'Enrique Iglesias', 'Skeewiff', 'Jennifer Lopez', 'Jennifer Lopez', 'Orquesta Tabaco Y Ron', 'Bacilos', 'Malú', 'Joaquín Sabina', 'Marcela Morelo', 'Clave Cubana', 'Miguel Bosé', 'Chayanne', 'Miguel Bosé', 'Tru La La', 'Miguel Bosé', 'Los Originales De San Juan', 'Aleks Syntek', 'Glup!', 'Tru La La', 'Beto Quintanilla', 'Diego Torres', 'Hermanos Rigual', 'Bacilos', 'Los Cachorros de Juan Villarreal', 'Diego Torres', 'Chayanne', 'Walter Olmos', 'Marc Anthony', 'Laura Miller', 'Enrique Iglesias', 'Sin Bandera', 'Walter Olmos', 'Beto Quintanilla', 'Carlos Vives', 'Marc Anthony', 'Malú', 'Walter Olmos', 'Jean Carlos', 'Enrique Iglesias', 'Thalia', 'Rodrigo', 'Sin Bandera', 'Enrique Iglesias', 'Huey Dunbar', 'Carlos Vives', 'Alejandra Guzman', 'Beto Quintanilla', 'Sin Bandera', 'Carlos Vives', 'Ricardo Montaner', 'Clave Cubana', 'La Mona Jimenez', 'La Barra', 'Enrique Iglesias', 'Diego Torres', 'Sabroso', 'Alejandra Guzman', 'Enrique Iglesias', 'Alejandra Guzman', 'Tommy Torres', 'Diego Torres', 'Beto Quintanilla', 'Jon Secada', 'Andrés Cepeda', 'Draco Rosa', 'Ricardo Arjona', 'Chayanne', 'Alejandra Guzman', 'Bacilos', 'Nek', 'Ricardo Arjona', 'La Quinta Estacion', 'Francisco Céspedes', 'Thalia', 'Marc Anthony', 'Enrique Iglesias', 'Cabas', 'Marc Anthony', 'David Bisbal', 'Shakira', 'La Quinta Estacion', 'Chayanne', 'Shakira', 'Natalia Lafourcade', 'Enrique Iglesias', 'Alejandro Fernández', 'Alejandro Fernández', 'David Bisbal', 'Enrique Iglesias', 'La Gran Banda', 'Marc Anthony', 'Thalia', 'Thalia', 'David Bisbal', 'Paulina Rubio', 'Paulina Rubio', 'Paulina Rubio', 'Enrique Iglesias', 'Chayanne', 'Chayanne', 'Ricardo Arjona', 'Cristian Castro', 'Juanes', 'Cristian Castro', 'Ricardo Arjona', 'Shakira', 'David Bisbal', 'Juanes', 'David Bisbal', 'Bacilos', 'Juanes', 'Juanes', 'Bacilos', 'Shakira', 'Chayanne', 'Ricardo Arjona', 'Los Caligaris', 'La Mona Jimenez', 'Thalia', 'Paulina Rubio', 'Juanes', 'Marc Anthony', 'Chayanne', 'Las Ketchup', 'Shakira', 'Paulina Rubio', 'Ricardo Arjona', 'Chayanne', 'Juanes', 'David Bisbal', 'Ricardo Arjona', 'Thalia', 'Thalia', 'Enrique Iglesias', 'Ricardo Arjona', 'Ricardo Arjona', 'Chayanne', 'Chayanne', 'Shakira', 'Chayanne', 'Juanes', 'David Bisbal', 'La Barra', 'Shakira', 'Chayanne', 'Ricardo Montaner', 'Ricardo Arjona', 'Shakira', 'Edwin Bonilla', 'Juanes', 'Ricardo Arjona', 'Shakira', 'Chayanne', 'Cubismo', 'Bacilos', 'David Bisbal', 'Chayanne', 'Shakira', 'Shakira', 'Alejandro Fernández', 'Marc Anthony', 'Alejandro Fernández', 'Los Fachero´s', 'Alejandro Fernández', 'Raulin Rodriguez', 'Los Playeros', 'Los Playeros', 'Los Incomparables De Tijuana', 'Los Playeros', 'Uriel Henao', 'Banda XXI', 'Bacilos', 'Miranda!', 'Marc Anthony', 'Chayanne', 'Enrique Iglesias', 'Juanes', 'Banda XXI', 'Juanes', 'Chayanne', 'Amparanoia', 'Luis Miguel', 'Eydie Gormé', 'Ricardo Arjona', 'David Bisbal', 'Los Playeros', 'Chayanne', 'Enrique Iglesias', 'Ricardo Arjona', 'Chayanne', 'La Quinta Estacion', 'Víctor Manuelle', 'Bacilos', 'Andy Aguilera', 'Aleks Syntek', 'Carlos Ponce', 'Murga Contrafarsa', 'Shakira', 'Shakira', 'Enrique Iglesias', 'La Quinta Estacion', 'Ricardo Montaner', 'Enrique Iglesias', 'Alejandra Guzman', 'Paulina Rubio', 'Chayanne', 'Juanes', 'La Quinta Estacion', 'Chayanne', 'Shakira', 'La Quinta Estacion', 'Ricardo Arjona', 'Banda XXI', 'Juan Formell y Los Van Van', 'Los Fachero´s', 'Ricky Martin', 'Ha*Ash', 'Sebastian', 'Belinda', 'Chayanne', 'Los Tucanes De Tijuana', 'Chayanne', 'Sin Bandera', 'Yahir', 'Ricky Martin', 'Julieta Venegas', 'Luis Miguel', 'Julieta Venegas', 'Ricky Martin', 'Luis Miguel', 'Julieta Venegas', 'Ha*Ash', 'Luis Miguel', 'Sin Bandera', 'Chayanne', 'Chayanne', 'Jimmy Sabater', 'Willie Bobo', 'Jarabe De Palo', 'Belinda', 'Sin Bandera', 'Luis Miguel', 'Mauricio & PalodeAgua', 'La Oreja de Van Gogh', 'La Oreja de Van Gogh', 'La Oreja de Van Gogh', 'La Oreja de Van Gogh', 'Ricky Martin', 'Sin Bandera', 'La Oreja de Van Gogh', 'La Oreja de Van Gogh', 'La Oreja de Van Gogh', 'La Oreja de Van Gogh', 'La Oreja de Van Gogh', 'Luis Miguel', 'La Oreja de Van Gogh', 'La Oreja de Van Gogh', 'Sin Bandera', 'La Oreja de Van Gogh', 'Sin Bandera', 'Michael Bublé', 'Julieta Venegas', 'La Oreja de Van Gogh', 'Julieta Venegas', 'Gloria Estefan', 'Grupo Exterminador', 'Grupo Exterminador', 'La Barra', 'Banda XXI', 'Tranzas', 'Latin Dreams', 'Tru La La', 'Sin Bandera', 'Mauricio & PalodeAgua', 'Belinda', 'Danni Ubeda', 'Luis Fonsi', 'Rey Ruiz', 'Noelia', 'Sin Bandera', 'Ana Torroja', 'Bacanos', 'Alexandre Pires', 'Chayanne', 'OBK', 'Ha*Ash', 'Tiziano Ferro', 'Beto Quintanilla', 'Yámana', 'David Calzado y su Charanga Habanera', 'Tru La La', 'Moises Angulo', 'Patricia Manterola', 'Danni Ubeda', 'Ha*Ash', 'Ana Torroja', 'Belinda', 'Sin Bandera', 'Enrique Iglesias', 'Ha*Ash', 'Danni Ubeda', 'Mauricio & PalodeAgua', 'Sin Bandera', 'Raul Paz', 'Beto Quintanilla', 'Tiziano Ferro', 'Los Tucanes De Tijuana', 'Ricky Martin', 'Beto Quintanilla', 'Julieta Venegas', 'Julieta Venegas', 'Pepe Aguilar', 'Wakal', 'Grupo Aliados', 'Paco Pineda y Su Grupo Tex Mex', 'Beto Quintanilla', 'Los Playeros', 'Papá Levante', 'Yuri Buenaventura', 'Shalim', 'Enrique Iglesias', 'Ana Torroja', 'Bustamante', 'La Mona Jimenez', 'Belinda', 'Geno', 'Chic Savanna', 'Sebastian', 'Obie Bermudez', 'Thalia', 'Ricardo Montaner', 'Jean Carlos', 'Banda XXI', 'Thalia', 'Mauricio & PalodeAgua', 'Chayanne', 'Luis Fonsi', 'Ana Torroja', 'Julieta Venegas', 'Julieta Venegas', 'Tiziano Ferro', 'Grupo Escuela del Amor', 'Beto Quintanilla', 'Los Playeros', 'Paco Pineda y Su Grupo Tex Mex', 'Wakal', 'Andrés Cepeda', 'Julieta Venegas', 'Wakal', 'Grupo Exterminador', 'La Barra', 'Chayanne', 'La Fiesta', 'Sin Bandera', 'Qarto Aparte', 'Christina Aguilera', 'Chayanne', 'Ricky Martin', 'Chayanne', 'Banda XXI', 'Ricky Martin', 'Thalia', 'Papá Levante', 'Tiziano Ferro', 'Wakal', 'LU', 'RBD', 'Diego Torres', 'El Cuarteto De Nos', 'Miguel Bosé', 'Juanes', 'David Bisbal', 'El Cuarteto De Nos', 'La Oreja de Van Gogh', 'Alejandro Sanz', 'Juanes', 'Laura Pausini', 'Bacilos', 'Diego Torres', 'Marc Anthony', 'La Oreja de Van Gogh', 'La Oreja de Van Gogh', 'RBD', 'La Oreja de Van Gogh', 'RBD', 'Alejandro Sanz', 'La Quinta Estacion', 'Alejandro Sanz', 'La Oreja de Van Gogh', 'Alejandro Sanz', 'RBD', 'Ricardo Arjona', 'La Oreja de Van Gogh', 'Juanes', 'Bacilos', 'La Quinta Estacion', 'Alejandro Fernández', 'Franco De Vita', 'Gloria Estefan', 'David Bisbal', 'Juanes', 'Paulina Rubio', 'RBD', 'Alejandro Fernández', 'Aleks Syntek', 'La Oreja de Van Gogh', 'Alejandro Sanz', 'RBD', 'Juanes', 'Franco De Vita', 'La Quinta Estacion', 'Juanes', 'La Oreja de Van Gogh', 'La Oreja de Van Gogh', 'Alejandro Sanz', 'Marc Anthony', 'RBD', 'La Quinta Estacion', 'RBD', 'Benny', 'RBD', 'Ricardo Arjona', 'Aleks Syntek', 'Lucas Arnau', 'Alejandro Sanz', 'RBD', 'Alejandro Sanz', 'La Oreja de Van Gogh', 'David Bisbal', 'La Oreja de Van Gogh', 'David Bisbal', 'La Quinta Estacion', 'Alejandro Sanz', 'Alejandro Sanz', 'Juanes', 'Alejandro Sanz', 'Diego Torres', 'Alejandro Sanz', 'David Bisbal', 'Juanes', 'Alejandro Sanz', 'La-33', 'La Oreja de Van Gogh', 'Alejandro Sanz', 'Alejandro Sanz', 'La Oreja de Van Gogh', 'La Oreja de Van Gogh', 'Marc Anthony', 'Obie Bermudez', 'La Oreja de Van Gogh', 'Carlos Vives', 'Marc Anthony', 'La Oreja de Van Gogh', 'Miguel Bosé', 'El Cuarteto De Nos', 'Alejandro Sanz', 'Thalia', 'Marc Anthony', 'Alejandro Sanz', 'La Oreja de Van Gogh', 'Alejandro Sanz', 'Marc Anthony', 'David Bisbal', 'Alejandro Sanz', 'Alejandro Sanz', 'Yahir', 'Marc Anthony', 'El Cuarteto De Nos', 'Franco De Vita', 'El Cuarteto De Nos', 'El Cuarteto De Nos', 'Alejandro Sanz', 'Thalia', 'El Cuarteto De Nos', 'Gloria Trevi', 'Alejandro Sanz', 'Laura Pausini', 'Nek', 'LU', 'Diego Torres', 'La Oreja de Van Gogh', 'Thalia', 'Ricardo Arjona', 'Juanes', 'Alejandro Sanz', 'Juanes', 'KEMA', 'Los Palmeras', 'Paulina Rubio', 'Alejandro Sanz', 'Miranda!', 'La Oreja de Van Gogh', 'Alejandro Sanz', 'Alejandro Sanz', 'La Quinta Estacion', 'La Oreja de Van Gogh', 'Alejandro Sanz', 'El Cuarteto De Nos', 'Lucas Arnau', 'Miranda!', 'Lucas Arnau', 'Damas Gratis', 'RBD', 'La Oreja de Van Gogh', 'La Oreja de Van Gogh', 'Juanes', 'Diego Torres', 'Ricardo Arjona', 'Alejandro Sanz', 'Paulina Rubio', 'Alejandro Sanz', 'Carlos Vives', 'Franco De Vita', 'Yahir', 'Alejandro Sanz']

In [39]:
type(lista_artista_latin_pop)

list

In [40]:
nombre_archivo = 'artistas_latin_pop.json' # Nombre del archivo donde se guardará

In [41]:
lista_artista_latin_pop

with open(nombre_archivo, 'w', encoding='utf-8') as archivo:
    
    json.dump(lista_artista_latin_pop, archivo, indent=4) # Usamos json.dump para escribir la lista en el archivo, indent=4 es la identacion en un archivo json

print(f"Lista de artistas guardada en {'Artista_latin_pop.json'}")

Lista de artistas guardada en Artista_latin_pop.json

In [ ]:
## NOTA ESTE ULTIMO ARCHIVO CONTIENE ARTISTAS DUPLICADOS LO QUE ES UN ERROR, QUE REVISAREMOS EN LASTFM