In [19]:
# pip install spotipy --upgrade

In [20]:
import spotipy
from spotipy.oauth2 import SpotifyClientCredentials

In [21]:
import pandas as pd
pd.set_option('display.max_columns', None)

In [22]:
import json

In [23]:
cliente = "18d8e23ee0a94acd9499bc06ae295e88"

In [24]:
secreto = "efcbe5326160470a9fee7d1f44edc254"

In [25]:
# Autenticación
auth_manager = SpotifyClientCredentials(cliente, secreto)
sp = spotipy.Spotify(auth_manager=auth_manager)

In [26]:
datos = sp.search(q="genre:reggae, year:2000", type="track", limit=50, offset=0)

In [27]:
datos

{'tracks': {'href': 'https://api.spotify.com/v1/search?offset=0&limit=50&query=genre%3Areggae%2C%20year%3A2000&type=track',
  'limit': 50,
  'next': 'https://api.spotify.com/v1/search?offset=50&limit=50&query=genre%3Areggae%2C%20year%3A2000&type=track',
  'offset': 0,
  'previous': None,
  'total': 100,
  'items': [{'album': {'album_type': 'album',
     'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/3Isy6kedDrgPYoTS1dazA9'},
       'href': 'https://api.spotify.com/v1/artists/3Isy6kedDrgPYoTS1dazA9',
       'id': '3Isy6kedDrgPYoTS1dazA9',
       'name': 'Sean Paul',
       'type': 'artist',
       'uri': 'spotify:artist:3Isy6kedDrgPYoTS1dazA9'}],
     'available_markets': ['AR',
      'AU',
      'AT',
      'BE',
      'BO',
      'BR',
      'BG',
      'CA',
      'CL',
      'CO',
      'CR',
      'CY',
      'CZ',
      'DK',
      'DO',
      'DE',
      'EC',
      'EE',
      'SV',
      'FI',
      'FR',
      'GR',
      'GT',
      'HN',
      'HK',
      'HU',
      'IS',
      'IE',
      'IT',
      'LV',
      'LT',
      'LU',
      'MY',
      'MT',
      'MX',
      'NL',
      'NZ',
      'NI',
      'NO',
      'PA',
      'PY',
      'PE',
      'PH',
      'PL',
      'PT',
      'SG',
      'SK',
      'ES',
      'SE',
      'CH',
      'TW',
      'TR',
      'UY',
      'US',
      'GB',
      'AD',
      'LI',
      'MC',
      'ID',
      'JP',
      'TH',
      'VN',
      'RO',
      'IL',
      'ZA',
      'SA',
      'AE',
      'BH',
      'QA',
      'OM',
      'KW',
      'EG',
      'MA',
      'DZ',
      'TN',
      'LB',
      'JO',
      'PS',
      'IN',
      'KZ',
      'MD',
      'UA',
      'AL',
      'BA',
      'HR',
      'ME',
      'MK',
      'RS',
      'SI',
      'KR',
      'BD',
      'PK',
      'LK',
      'GH',
      'KE',
      'NG',
      'TZ',
      'UG',
      'AG',
      'AM',
      'BS',
      'BB',
      'BZ',
      'BT',
      'BW',
      'BF',
      'CV',
      'CW',
      'DM',
      'FJ',
      'GM',
      'GE',
      'GD',
      'GW',
      'GY',
      'HT',
      'JM',
      'KI',
      'LS',
      'LR',
      'MW',
      'MV',
      'ML',
      'MH',
      'FM',
      'NA',
      'NR',
      'NE',
      'PW',
      'PG',
      'PR',
      'WS',
      'SM',
      'ST',
      'SN',
      'SC',
      'SL',
      'SB',
      'KN',
      'LC',
      'VC',
      'SR',
      'TL',
      'TO',
      'TT',
      'TV',
      'VU',
      'AZ',
      'BN',
      'BI',
      'KH',
      'CM',
      'TD',
      'KM',
      'GQ',
      'SZ',
      'GA',
      'GN',
      'KG',
      'LA',
      'MO',
      'MR',
      'MN',
      'NP',
      'RW',
      'TG',
      'UZ',
      'ZW',
      'BJ',
      'MG',
      'MU',
      'MZ',
      'AO',
      'CI',
      'DJ',
      'ZM',
      'CD',
      'CG',
      'IQ',
      'LY',
      'TJ',
      'VE',
      'ET',
      'XK'],
     'external_urls': {'spotify': 'https://open.spotify.com/album/6Y5344aCqHNxQNAUStzHrd'},
     'href': 'https://api.spotify.com/v1/albums/6Y5344aCqHNxQNAUStzHrd',
     'id': '6Y5344aCqHNxQNAUStzHrd',
     'images': [{'height': 640,
       'width': 640,
       'url': 'https://i.scdn.co/image/ab67616d0000b27314f35992ffc62ef3d70705f8'},
      {'height': 300,
       'width': 300,
       'url': 'https://i.scdn.co/image/ab67616d00001e0214f35992ffc62ef3d70705f8'},
      {'height': 64,
       'width': 64,
       'url': 'https://i.scdn.co/image/ab67616d0000485114f35992ffc62ef3d70705f8'}],
     'is_playable': True,
     'name': 'Stage One',
     'release_date': '2000',
     'release_date_precision': 'year',
     'total_tracks': 25,
     'type': 'album',
     'uri': 'spotify:album:6Y5344aCqHNxQNAUStzHrd'},
    'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/3Isy6kedDrgPYoTS1dazA9'},
      'href': 'https://api.spotify.com/v1/artists/3Isy6kedDrgPYoTS1dazA9',
      'id': '3Isy6kedDrgPYoTS1dazA9',
      'name': 'Sean Paul',
      'type': 'artist',
      'uri': 'spotify:artist:3Isy6kedDrgPYoTS1dazA9'}],
    'available_markets': ['AR',
     'AU',
     'AT',
     'BE',
     'BO',
     'BR',
     'BG',
     'CA',
     'CL',
     'CO',
     'CR',
     'CY',
     'CZ',
     'DK',
     'DO',
     'DE',
     'EC',
     'EE',
     'SV',
     'FI',
     'FR',
     'GR',
     'GT',
     'HN',
     'HK',
     'HU',
     'IS',
     'IE',
     'IT',
     'LV',
     'LT',
     'LU',
     'MY',
     'MT',
     'MX',
     'NL',
     'NZ',
     'NI',
     'NO',
     'PA',
     'PY',
     'PE',
     'PH',
     'PL',
     'PT',
     'SG',
     'SK',
     'ES',
     'SE',
     'CH',
     'TW',
     'TR',
     'UY',
     'US',
     'GB',
     'AD',
     'LI',
     'MC',
     'ID',
     'JP',
     'TH',
     'VN',
     'RO',
     'IL',
     'ZA',
     'SA',
     'AE',
     'BH',
     'QA',
     'OM',
     'KW',
     'EG',
     'MA',
     'DZ',
     'TN',
     'LB',
     'JO',
     'PS',
     'IN',
     'KZ',
     'MD',
     'UA',
     'AL',
     'BA',
     'HR',
     'ME',
     'MK',
     'RS',
     'SI',
     'KR',
     'BD',
     'PK',
     'LK',
     'GH',
     'KE',
     'NG',
     'TZ',
     'UG',
     'AG',
     'AM',
     'BS',
     'BB',
     'BZ',
     'BT',
     'BW',
     'BF',
     'CV',
     'CW',
     'DM',
     'FJ',
     'GM',
     'GE',
     'GD',
     'GW',
     'GY',
     'HT',
     'JM',
     'KI',
     'LS',
     'LR',
     'MW',
     'MV',
     'ML',
     'MH',
     'FM',
     'NA',
     'NR',
     'NE',
     'PW',
     'PG',
     'PR',
     'WS',
     'SM',
     'ST',
     'SN',
     'SC',
     'SL',
     'SB',
     'KN',
     'LC',
     'VC',
     'SR',
     'TL',
     'TO',
     'TT',
     'TV',
     'VU',
     'AZ',
     'BN',
     'BI',
     'KH',
     'CM',
     'TD',
     'KM',
     'GQ',
     'SZ',
     'GA',
     'GN',
     'KG',
     'LA',
     'MO',
     'MR',
     'MN',
     'NP',
     'RW',
     'TG',
     'UZ',
     'ZW',
     'BJ',
     'MG',
     'MU',
     'MZ',
     'AO',
     'CI',
     'DJ',
     'ZM',
     'CD',
     'CG',
     'IQ',
     'LY',
     'TJ',
     'VE',
     'ET',
     'XK'],
    'disc_number': 1,
    'duration_ms': 209466,
    'explicit': False,
    'external_ids': {'isrc': 'USVPR0006995'},
    'external_urls': {'spotify': 'https://open.spotify.com/track/0ru8bc0XnKjUL2O1Fl1k7a'},
    'href': 'https://api.spotify.com/v1/tracks/0ru8bc0XnKjUL2O1Fl1k7a',
    'id': '0ru8bc0XnKjUL2O1Fl1k7a',
    'is_local': False,
    'is_playable': True,
    'name': 'Infiltrate',
    'popularity': 50,
    'preview_url': None,
    'track_number': 3,
    'type': 'track',
    'uri': 'spotify:track:0ru8bc0XnKjUL2O1Fl1k7a'},
   {'album': {'album_type': 'album',
     'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/3Isy6kedDrgPYoTS1dazA9'},
       'href': 'https://api.spotify.com/v1/artists/3Isy6kedDrgPYoTS1dazA9',
       'id': '3Isy6kedDrgPYoTS1dazA9',
       'name': 'Sean Paul',
       'type': 'artist',
       'uri': 'spotify:artist:3Isy6kedDrgPYoTS1dazA9'}],
     'available_markets': ['AR',
      'AU',
      'AT',
      'BE',
      'BO',
      'BR',
      'BG',
      'CA',
      'CL',
      'CO',
      'CR',
      'CY',
      'CZ',
      'DK',
      'DO',
      'DE',
      'EC',
      'EE',
      'SV',
      'FI',
      'FR',
      'GR',
      'GT',
      'HN',
      'HK',
      'HU',
      'IS',
      'IE',
      'IT',
      'LV',
      'LT',
      'LU',
      'MY',
      'MT',
      'MX',
      'NL',
      'NZ',
      'NI',
      'NO',
      'PA',
      'PY',
      'PE',
      'PH',
      'PL',
      'PT',
      'SG',
      'SK',
      'ES',
      'SE',
      'CH',
      'TW',
      'TR',
      'UY',
      'US',
      'GB',
      'AD',
      'LI',
      'MC',
      'ID',
      'JP',
      'TH',
      'VN',
      'RO',
      'IL',
      'ZA',
      'SA',
      'AE',
      'BH',
      'QA',
      'OM',
      'KW',
      'EG',
      'MA',
      'DZ',
      'TN',
      'LB',
      'JO',
      'PS',
      'IN',
      'KZ',
      'MD',
      'UA',
      'AL',
      'BA',
      'HR',
      'ME',
      'MK',
      'RS',
      'SI',
      'KR',
      'BD',
      'PK',
      'LK',
      'GH',
      'KE',
      'NG',
      'TZ',
      'UG',
      'AG',
      'AM',
      'BS',
      'BB',
      'BZ',
      'BT',
      'BW',
      'BF',
      'CV',
      'CW',
      'DM',
      'FJ',
      'GM',
      'GE',
      'GD',
      'GW',
      'GY',
      'HT',
      'JM',
      'KI',
      'LS',
      'LR',
      'MW',
      'MV',
      'ML',
      'MH',
      'FM',
      'NA',
      'NR',
      'NE',
      'PW',
      'PG',
      'PR',
      'WS',
      'SM',
      'ST',
      'SN',
      'SC',
      'SL',
      'SB',
      'KN',
      'LC',
      'VC',
      'SR',
      'TL',
      'TO',
      'TT',
      'TV',
      'VU',
      'AZ',
      'BN',
      'BI',
      'KH',
      'CM',
      'TD',
      'KM',
      'GQ',
      'SZ',
      'GA',
      'GN',
      'KG',
      'LA',
      'MO',
      'MR',
      'MN',
      'NP',
      'RW',
      'TG',
      'UZ',
      'ZW',
      'BJ',
      'MG',
      'MU',
      'MZ',
      'AO',
      'CI',
      'DJ',
      'ZM',
      'CD',
      'CG',
      'IQ',
      'LY',
      'TJ',
      'VE',
      'ET',
      'XK'],
     'external_urls': {'spotify': 'https://open.spotify.com/album/6Y5344aCqHNxQNAUStzHrd'},
     'href': 'https://api.spotify.com/v1/albums/6Y5344aCqHNxQNAUStzHrd',
     'id': '6Y5344aCqHNxQNAUStzHrd',
     'images': [{'height': 640,
       'width': 640,
       'url': 'https://i.scdn.co/image/ab67616d0000b27314f35992ffc62ef3d70705f8'},
      {'height': 300,
       'width': 300,
       'url': 'https://i.scdn.co/image/ab67616d00001e0214f35992ffc62ef3d70705f8'},
      {'height': 64,
       'width': 64,
       'url': 'https://i.scdn.co/image/ab67616d0000485114f35992ffc62ef3d70705f8'}],
     'is_playable': True,
     'name': 'Stage One',
     'release_date': '2000',
     'release_date_precision': 'year',
     'total_tracks': 25,
     'type': 'album',
     'uri': 'spotify:album:6Y5344aCqHNxQNAUStzHrd'},
    'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/3Isy6kedDrgPYoTS1dazA9'},
      'href': 'https://api.spotify.com/v1/artists/3Isy6kedDrgPYoTS1dazA9',
      'id': '3Isy6kedDrgPYoTS1dazA9',
      'name': 'Sean Paul',
      'type': 'artist',
      'uri': 'spotify:artist:3Isy6kedDrgPYoTS1dazA9'}],
    'available_markets': ['AR',
     'AU',
     'AT',
     'BE',
     'BO',
     'BR',
     'BG',
     'CA',
     'CL',
     'CO',
     'CR',
     'CY',
     'CZ',
     'DK',
     'DO',
     'DE',
     'EC',
     'EE',
     'SV',
     'FI',
     'FR',
     'GR',
     'GT',
     'HN',
     'HK',
     'HU',
     'IS',
     'IE',
     'IT',
     'LV',
     'LT',
     'LU',
     'MY',
     'MT',
     'MX',
     'NL',
     'NZ',
     'NI',
     'NO',
     'PA',
     'PY',
     'PE',
     'PH',
     'PL',
     'PT',
     'SG',
     'SK',
     'ES',
     'SE',
     'CH',
     'TW',
     'TR',
     'UY',
     'US',
     'GB',
     'AD',
     'LI',
     'MC',
     'ID',
     'JP',
     'TH',
     'VN',
     'RO',
     'IL',
     'ZA',
     'SA',
     'AE',
     'BH',
     'QA',
     'OM',
     'KW',
     'EG',
     'MA',
     'DZ',
     'TN',
     'LB',
     'JO',
     'PS',
     'IN',
     'KZ',
     'MD',
     'UA',
     'AL',
     'BA',
     'HR',
     'ME',
     'MK',
     'RS',
     'SI',
     'KR',
     'BD',
     'PK',
     'LK',
     'GH',
     'KE',
     'NG',
     'TZ',
     'UG',
     'AG',
     'AM',
     'BS',
     'BB',
     'BZ',
     'BT',
     'BW',
     'BF',
     'CV',
     'CW',
     'DM',
     'FJ',
     'GM',
     'GE',
     'GD',
     'GW',
     'GY',
     'HT',
     'JM',
     'KI',
     'LS',
     'LR',
     'MW',
     'MV',
     'ML',
     'MH',
     'FM',
     'NA',
     'NR',
     'NE',
     'PW',
     'PG',
     'PR',
     'WS',
     'SM',
     'ST',
     'SN',
     'SC',
     'SL',
     'SB',
     'KN',
     'LC',
     'VC',
     'SR',
     'TL',
     'TO',
     'TT',
     'TV',
     'VU',
     'AZ',
     'BN',
     'BI',
     'KH',
     'CM',
     'TD',
     'KM',
     'GQ',
     'SZ',
     'GA',
     'GN',
     'KG',
     'LA',
     'MO',
     'MR',
     'MN',
     'NP',
     'RW',
     'TG',
     'UZ',
     'ZW',
     'BJ',
     'MG',
     'MU',
     'MZ',
     'AO',
     'CI',
     'DJ',
     'ZM',
     'CD',
     'CG',
     'IQ',
     'LY',
     'TJ',
     'VE',
     'ET',
     'XK'],
    'disc_number': 1,
    'duration_ms': 188306,
    'explicit': False,
    'external_ids': {'isrc': 'USVPR0007000'},
    'external_urls': {'spotify': 'https://open.spotify.com/track/5KhypMVGqMI9mgsrrv2lxc'},
    'href': 'https://api.spotify.com/v1/tracks/5KhypMVGqMI9mgsrrv2lxc',
    'id': '5KhypMVGqMI9mgsrrv2lxc',
    'is_local': False,
    'is_playable': True,
    'name': 'Deport Them',
    'popularity': 51,
    'preview_url': None,
    'track_number': 11,
    'type': 'track',
    'uri': 'spotify:track:5KhypMVGqMI9mgsrrv2lxc'},
   {'album': {'album_type': 'album',
     'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/5EvFsr3kj42KNv97ZEnqij'},
       'href': 'https://api.spotify.com/v1/artists/5EvFsr3kj42KNv97ZEnqij',
       'id': '5EvFsr3kj42KNv97ZEnqij',
       'name': 'Shaggy',
       'type': 'artist',
       'uri': 'spotify:artist:5EvFsr3kj42KNv97ZEnqij'}],
     'available_markets': ['AR',
      'AU',
      'AT',
      'BE',
      'BO',
      'BR',
      'BG',
      'CA',
      'CL',
      'CO',
      'CR',
      'CY',
      'CZ',
      'DK',
      'DO',
      'DE',
      'EC',
      'EE',
      'SV',
      'FI',
      'FR',
      'GR',
      'GT',
      'HN',
      'HK',
      'HU',
      'IS',
      'IE',
      'IT',
      'LV',
      'LT',
      'LU',
      'MY',
      'MT',
      'MX',
      'NL',
      'NZ',
      'NI',
      'NO',
      'PA',
      'PY',
      'PE',
      'PH',
      'PL',
      'PT',
      'SG',
      'SK',
      'ES',
      'SE',
      'CH',
      'TW',
      'TR',
      'UY',
      'US',
      'GB',
      'AD',
      'LI',
      'MC',
      'ID',
      'JP',
      'TH',
      'VN',
      'RO',
      'IL',
      'ZA',
      'SA',
      'AE',
      'BH',
      'QA',
      'OM',
      'KW',
      'EG',
      'MA',
      'DZ',
      'TN',
      'LB',
      'JO',
      'PS',
      'IN',
      'BY',
      'KZ',
      'MD',
      'UA',
      'AL',
      'BA',
      'HR',
      'ME',
      'MK',
      'RS',
      'SI',
      'KR',
      'BD',
      'PK',
      'LK',
      'GH',
      'KE',
      'NG',
      'TZ',
      'UG',
      'AG',
      'AM',
      'BS',
      'BB',
      'BZ',
      'BT',
      'BW',
      'BF',
      'CV',
      'CW',
      'DM',
      'FJ',
      'GM',
      'GE',
      'GD',
      'GW',
      'GY',
      'HT',
      'JM',
      'KI',
      'LS',
      'LR',
      'MW',
      'MV',
      'ML',
      'MH',
      'FM',
      'NA',
      'NR',
      'NE',
      'PW',
      'PG',
      'WS',
      'SM',
      'ST',
      'SN',
      'SC',
      'SL',
      'SB',
      'KN',
      'LC',
      'VC',
      'SR',
      'TL',
      'TO',
      'TT',
      'TV',
      'VU',
      'AZ',
      'BN',
      'BI',
      'KH',
      'CM',
      'TD',
      'KM',
      'GQ',
      'SZ',
      'GA',
      'GN',
      'KG',
      'LA',
      'MO',
      'MR',
      'MN',
      'NP',
      'RW',
      'TG',
      'UZ',
      'ZW',
      'BJ',
      'MG',
      'MU',
      'MZ',
      'AO',
      'CI',
      'DJ',
      'ZM',
      'CD',
      'CG',
      'IQ',
      'LY',
      'TJ',
      'VE',
      'ET',
      'XK'],
     'external_urls': {'spotify': 'https://open.spotify.com/album/3MT88SSyxQGbqYXj4LVk3b'},
     'href': 'https://api.spotify.com/v1/albums/3MT88SSyxQGbqYXj4LVk3b',
     'id': '3MT88SSyxQGbqYXj4LVk3b',
     'images': [{'height': 640,
       'width': 640,
       'url': 'https://i.scdn.co/image/ab67616d0000b2739449f9491c364d28a9668e17'},
      {'height': 300,
       'width': 300,
       'url': 'https://i.scdn.co/image/ab67616d00001e029449f9491c364d28a9668e17'},
      {'height': 64,
       'width': 64,
       'url': 'https://i.scdn.co/image/ab67616d000048519449f9491c364d28a9668e17'}],
     'is_playable': True,
     'name': 'Hot Shot',
     'release_date': '2000-08-08',
     'release_date_precision': 'day',
     'total_tracks': 15,
     'type': 'album',
     'uri': 'spotify:album:3MT88SSyxQGbqYXj4LVk3b'},
    'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/5EvFsr3kj42KNv97ZEnqij'},
      'href': 'https://api.spotify.com/v1/artists/5EvFsr3kj42KNv97ZEnqij',
      'id': '5EvFsr3kj42KNv97ZEnqij',
      'name': 'Shaggy',
      'type': 'artist',
      'uri': 'spotify:artist:5EvFsr3kj42KNv97ZEnqij'},
     {'external_urls': {'spotify': 'https://open.spotify.com/artist/4VnMJXQpix0onjop2VNFvX'},
      'href': 'https://api.spotify.com/v1/artists/4VnMJXQpix0onjop2VNFvX',
      'id': '4VnMJXQpix0onjop2VNFvX',
      'name': 'Samantha Cole',
      'type': 'artist',
      'uri': 'spotify:artist:4VnMJXQpix0onjop2VNFvX'}],
    'available_markets': ['AR',
     'AU',
     'AT',
     'BE',
     'BO',
     'BR',
     'BG',
     'CA',
     'CL',
     'CO',
     'CR',
     'CY',
     'CZ',
     'DK',
     'DO',
     'DE',
     'EC',
     'EE',
     'SV',
     'FI',
     'FR',
     'GR',
     'GT',
     'HN',
     'HK',
     'HU',
     'IS',
     'IE',
     'IT',
     'LV',
     'LT',
     'LU',
     'MY',
     'MT',
     'MX',
     'NL',
     'NZ',
     'NI',
     'NO',
     'PA',
     'PY',
     'PE',
     'PH',
     'PL',
     'PT',
     'SG',
     'SK',
     'ES',
     'SE',
     'CH',
     'TW',
     'TR',
     'UY',
     'US',
     'GB',
     'AD',
     'LI',
     'MC',
     'ID',
     'JP',
     'TH',
     'VN',
     'RO',
     'IL',
     'ZA',
     'SA',
     'AE',
     'BH',
     'QA',
     'OM',
     'KW',
     'EG',
     'MA',
     'DZ',
     'TN',
     'LB',
     'JO',
     'PS',
     'IN',
     'BY',
     'KZ',
     'MD',
     'UA',
     'AL',
     'BA',
     'HR',
     'ME',
     'MK',
     'RS',
     'SI',
     'KR',
     'BD',
     'PK',
     'LK',
     'GH',
     'KE',
     'NG',
     'TZ',
     'UG',
     'AG',
     'AM',
     'BS',
     'BB',
     'BZ',
     'BT',
     'BW',
     'BF',
     'CV',
     'CW',
     'DM',
     'FJ',
     'GM',
     'GE',
     'GD',
     'GW',
     'GY',
     'HT',
     'JM',
     'KI',
     'LS',
     'LR',
     'MW',
     'MV',
     'ML',
     'MH',
     'FM',
     'NA',
     'NR',
     'NE',
     'PW',
     'PG',
     'WS',
     'SM',
     'ST',
     'SN',
     'SC',
     'SL',
     'SB',
     'KN',
     'LC',
     'VC',
     'SR',
     'TL',
     'TO',
     'TT',
     'TV',
     'VU',
     'AZ',
     'BN',
     'BI',
     'KH',
     'CM',
     'TD',
     'KM',
     'GQ',
     'SZ',
     'GA',
     'GN',
     'KG',
     'LA',
     'MO',
     'MR',
     'MN',
     'NP',
     'RW',
     'TG',
     'UZ',
     'ZW',
     'BJ',
     'MG',
     'MU',
     'MZ',
     'AO',
     'CI',
     'DJ',
     'ZM',
     'CD',
     'CG',
     'IQ',
     'LY',
     'TJ',
     'VE',
     'ET',
     'XK'],
    'disc_number': 1,
    'duration_ms': 215506,
    'explicit': False,
    'external_ids': {'isrc': 'USMC10000615'},
    'external_urls': {'spotify': 'https://open.spotify.com/track/7hV4x7PMKGC4qD3NWLt2UJ'},
    'href': 'https://api.spotify.com/v1/tracks/7hV4x7PMKGC4qD3NWLt2UJ',
    'id': '7hV4x7PMKGC4qD3NWLt2UJ',
    'is_local': False,
    'is_playable': True,
    'name': 'Luv Me, Luv Me',
    'popularity': 52,
    'preview_url': None,
    'track_number': 9,
    'type': 'track',
    'uri': 'spotify:track:7hV4x7PMKGC4qD3NWLt2UJ'},
   {'album': {'album_type': 'album',
     'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/4wvAGBushcLkCZ1lEZsYMf'},
       'href': 'https://api.spotify.com/v1/artists/4wvAGBushcLkCZ1lEZsYMf',
       'id': '4wvAGBushcLkCZ1lEZsYMf',
       'name': 'Maskavo',
       'type': 'artist',
       'uri': 'spotify:artist:4wvAGBushcLkCZ1lEZsYMf'}],
     'available_markets': ['AR',
      'AU',
      'AT',

In [28]:
datos.keys()

dict_keys(['tracks'])

In [29]:
datos["tracks"]

{'href': 'https://api.spotify.com/v1/search?offset=0&limit=50&query=genre%3Areggae%2C%20year%3A2000&type=track',
 'limit': 50,
 'next': 'https://api.spotify.com/v1/search?offset=50&limit=50&query=genre%3Areggae%2C%20year%3A2000&type=track',
 'offset': 0,
 'previous': None,
 'total': 100,
 'items': [{'album': {'album_type': 'album',
    'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/3Isy6kedDrgPYoTS1dazA9'},
      'href': 'https://api.spotify.com/v1/artists/3Isy6kedDrgPYoTS1dazA9',
      'id': '3Isy6kedDrgPYoTS1dazA9',
      'name': 'Sean Paul',
      'type': 'artist',
      'uri': 'spotify:artist:3Isy6kedDrgPYoTS1dazA9'}],
    'available_markets': ['AR',
     'AU',
     'AT',
     'BE',
     'BO',
     'BR',
     'BG',
     'CA',
     'CL',
     'CO',
     'CR',
     'CY',
     'CZ',
     'DK',
     'DO',
     'DE',
     'EC',
     'EE',
     'SV',
     'FI',
     'FR',
     'GR',
     'GT',
     'HN',
     'HK',
     'HU',
     'IS',
     'IE',
     'IT',
     'LV',
     'LT',
     'LU',
     'MY',
     'MT',
     'MX',
     'NL',
     'NZ',
     'NI',
     'NO',
     'PA',
     'PY',
     'PE',
     'PH',
     'PL',
     'PT',
     'SG',
     'SK',
     'ES',
     'SE',
     'CH',
     'TW',
     'TR',
     'UY',
     'US',
     'GB',
     'AD',
     'LI',
     'MC',
     'ID',
     'JP',
     'TH',
     'VN',
     'RO',
     'IL',
     'ZA',
     'SA',
     'AE',
     'BH',
     'QA',
     'OM',
     'KW',
     'EG',
     'MA',
     'DZ',
     'TN',
     'LB',
     'JO',
     'PS',
     'IN',
     'KZ',
     'MD',
     'UA',
     'AL',
     'BA',
     'HR',
     'ME',
     'MK',
     'RS',
     'SI',
     'KR',
     'BD',
     'PK',
     'LK',
     'GH',
     'KE',
     'NG',
     'TZ',
     'UG',
     'AG',
     'AM',
     'BS',
     'BB',
     'BZ',
     'BT',
     'BW',
     'BF',
     'CV',
     'CW',
     'DM',
     'FJ',
     'GM',
     'GE',
     'GD',
     'GW',
     'GY',
     'HT',
     'JM',
     'KI',
     'LS',
     'LR',
     'MW',
     'MV',
     'ML',
     'MH',
     'FM',
     'NA',
     'NR',
     'NE',
     'PW',
     'PG',
     'PR',
     'WS',
     'SM',
     'ST',
     'SN',
     'SC',
     'SL',
     'SB',
     'KN',
     'LC',
     'VC',
     'SR',
     'TL',
     'TO',
     'TT',
     'TV',
     'VU',
     'AZ',
     'BN',
     'BI',
     'KH',
     'CM',
     'TD',
     'KM',
     'GQ',
     'SZ',
     'GA',
     'GN',
     'KG',
     'LA',
     'MO',
     'MR',
     'MN',
     'NP',
     'RW',
     'TG',
     'UZ',
     'ZW',
     'BJ',
     'MG',
     'MU',
     'MZ',
     'AO',
     'CI',
     'DJ',
     'ZM',
     'CD',
     'CG',
     'IQ',
     'LY',
     'TJ',
     'VE',
     'ET',
     'XK'],
    'external_urls': {'spotify': 'https://open.spotify.com/album/6Y5344aCqHNxQNAUStzHrd'},
    'href': 'https://api.spotify.com/v1/albums/6Y5344aCqHNxQNAUStzHrd',
    'id': '6Y5344aCqHNxQNAUStzHrd',
    'images': [{'height': 640,
      'width': 640,
      'url': 'https://i.scdn.co/image/ab67616d0000b27314f35992ffc62ef3d70705f8'},
     {'height': 300,
      'width': 300,
      'url': 'https://i.scdn.co/image/ab67616d00001e0214f35992ffc62ef3d70705f8'},
     {'height': 64,
      'width': 64,
      'url': 'https://i.scdn.co/image/ab67616d0000485114f35992ffc62ef3d70705f8'}],
    'is_playable': True,
    'name': 'Stage One',
    'release_date': '2000',
    'release_date_precision': 'year',
    'total_tracks': 25,
    'type': 'album',
    'uri': 'spotify:album:6Y5344aCqHNxQNAUStzHrd'},
   'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/3Isy6kedDrgPYoTS1dazA9'},
     'href': 'https://api.spotify.com/v1/artists/3Isy6kedDrgPYoTS1dazA9',
     'id': '3Isy6kedDrgPYoTS1dazA9',
     'name': 'Sean Paul',
     'type': 'artist',
     'uri': 'spotify:artist:3Isy6kedDrgPYoTS1dazA9'}],
   'available_markets': ['AR',
    'AU',
    'AT',
    'BE',
    'BO',
    'BR',
    'BG',
    'CA',
    'CL',
    'CO',
    'CR',
    'CY',
    'CZ',
    'DK',
    'DO',
    'DE',
    'EC',
    'EE',
    'SV',
    'FI',
    'FR',
    'GR',
    'GT',
    'HN',
    'HK',
    'HU',
    'IS',
    'IE',
    'IT',
    'LV',
    'LT',
    'LU',
    'MY',
    'MT',
    'MX',
    'NL',
    'NZ',
    'NI',
    'NO',
    'PA',
    'PY',
    'PE',
    'PH',
    'PL',
    'PT',
    'SG',
    'SK',
    'ES',
    'SE',
    'CH',
    'TW',
    'TR',
    'UY',
    'US',
    'GB',
    'AD',
    'LI',
    'MC',
    'ID',
    'JP',
    'TH',
    'VN',
    'RO',
    'IL',
    'ZA',
    'SA',
    'AE',
    'BH',
    'QA',
    'OM',
    'KW',
    'EG',
    'MA',
    'DZ',
    'TN',
    'LB',
    'JO',
    'PS',
    'IN',
    'KZ',
    'MD',
    'UA',
    'AL',
    'BA',
    'HR',
    'ME',
    'MK',
    'RS',
    'SI',
    'KR',
    'BD',
    'PK',
    'LK',
    'GH',
    'KE',
    'NG',
    'TZ',
    'UG',
    'AG',
    'AM',
    'BS',
    'BB',
    'BZ',
    'BT',
    'BW',
    'BF',
    'CV',
    'CW',
    'DM',
    'FJ',
    'GM',
    'GE',
    'GD',
    'GW',
    'GY',
    'HT',
    'JM',
    'KI',
    'LS',
    'LR',
    'MW',
    'MV',
    'ML',
    'MH',
    'FM',
    'NA',
    'NR',
    'NE',
    'PW',
    'PG',
    'PR',
    'WS',
    'SM',
    'ST',
    'SN',
    'SC',
    'SL',
    'SB',
    'KN',
    'LC',
    'VC',
    'SR',
    'TL',
    'TO',
    'TT',
    'TV',
    'VU',
    'AZ',
    'BN',
    'BI',
    'KH',
    'CM',
    'TD',
    'KM',
    'GQ',
    'SZ',
    'GA',
    'GN',
    'KG',
    'LA',
    'MO',
    'MR',
    'MN',
    'NP',
    'RW',
    'TG',
    'UZ',
    'ZW',
    'BJ',
    'MG',
    'MU',
    'MZ',
    'AO',
    'CI',
    'DJ',
    'ZM',
    'CD',
    'CG',
    'IQ',
    'LY',
    'TJ',
    'VE',
    'ET',
    'XK'],
   'disc_number': 1,
   'duration_ms': 209466,
   'explicit': False,
   'external_ids': {'isrc': 'USVPR0006995'},
   'external_urls': {'spotify': 'https://open.spotify.com/track/0ru8bc0XnKjUL2O1Fl1k7a'},
   'href': 'https://api.spotify.com/v1/tracks/0ru8bc0XnKjUL2O1Fl1k7a',
   'id': '0ru8bc0XnKjUL2O1Fl1k7a',
   'is_local': False,
   'is_playable': True,
   'name': 'Infiltrate',
   'popularity': 50,
   'preview_url': None,
   'track_number': 3,
   'type': 'track',
   'uri': 'spotify:track:0ru8bc0XnKjUL2O1Fl1k7a'},
  {'album': {'album_type': 'album',
    'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/3Isy6kedDrgPYoTS1dazA9'},
      'href': 'https://api.spotify.com/v1/artists/3Isy6kedDrgPYoTS1dazA9',
      'id': '3Isy6kedDrgPYoTS1dazA9',
      'name': 'Sean Paul',
      'type': 'artist',
      'uri': 'spotify:artist:3Isy6kedDrgPYoTS1dazA9'}],
    'available_markets': ['AR',
     'AU',
     'AT',
     'BE',
     'BO',
     'BR',
     'BG',
     'CA',
     'CL',
     'CO',
     'CR',
     'CY',
     'CZ',
     'DK',
     'DO',
     'DE',
     'EC',
     'EE',
     'SV',
     'FI',
     'FR',
     'GR',
     'GT',
     'HN',
     'HK',
     'HU',
     'IS',
     'IE',
     'IT',
     'LV',
     'LT',
     'LU',
     'MY',
     'MT',
     'MX',
     'NL',
     'NZ',
     'NI',
     'NO',
     'PA',
     'PY',
     'PE',
     'PH',
     'PL',
     'PT',
     'SG',
     'SK',
     'ES',
     'SE',
     'CH',
     'TW',
     'TR',
     'UY',
     'US',
     'GB',
     'AD',
     'LI',
     'MC',
     'ID',
     'JP',
     'TH',
     'VN',
     'RO',
     'IL',
     'ZA',
     'SA',
     'AE',
     'BH',
     'QA',
     'OM',
     'KW',
     'EG',
     'MA',
     'DZ',
     'TN',
     'LB',
     'JO',
     'PS',
     'IN',
     'KZ',
     'MD',
     'UA',
     'AL',
     'BA',
     'HR',
     'ME',
     'MK',
     'RS',
     'SI',
     'KR',
     'BD',
     'PK',
     'LK',
     'GH',
     'KE',
     'NG',
     'TZ',
     'UG',
     'AG',
     'AM',
     'BS',
     'BB',
     'BZ',
     'BT',
     'BW',
     'BF',
     'CV',
     'CW',
     'DM',
     'FJ',
     'GM',
     'GE',
     'GD',
     'GW',
     'GY',
     'HT',
     'JM',
     'KI',
     'LS',
     'LR',
     'MW',
     'MV',
     'ML',
     'MH',
     'FM',
     'NA',
     'NR',
     'NE',
     'PW',
     'PG',
     'PR',
     'WS',
     'SM',
     'ST',
     'SN',
     'SC',
     'SL',
     'SB',
     'KN',
     'LC',
     'VC',
     'SR',
     'TL',
     'TO',
     'TT',
     'TV',
     'VU',
     'AZ',
     'BN',
     'BI',
     'KH',
     'CM',
     'TD',
     'KM',
     'GQ',
     'SZ',
     'GA',
     'GN',
     'KG',
     'LA',
     'MO',
     'MR',
     'MN',
     'NP',
     'RW',
     'TG',
     'UZ',
     'ZW',
     'BJ',
     'MG',
     'MU',
     'MZ',
     'AO',
     'CI',
     'DJ',
     'ZM',
     'CD',
     'CG',
     'IQ',
     'LY',
     'TJ',
     'VE',
     'ET',
     'XK'],
    'external_urls': {'spotify': 'https://open.spotify.com/album/6Y5344aCqHNxQNAUStzHrd'},
    'href': 'https://api.spotify.com/v1/albums/6Y5344aCqHNxQNAUStzHrd',
    'id': '6Y5344aCqHNxQNAUStzHrd',
    'images': [{'height': 640,
      'width': 640,
      'url': 'https://i.scdn.co/image/ab67616d0000b27314f35992ffc62ef3d70705f8'},
     {'height': 300,
      'width': 300,
      'url': 'https://i.scdn.co/image/ab67616d00001e0214f35992ffc62ef3d70705f8'},
     {'height': 64,
      'width': 64,
      'url': 'https://i.scdn.co/image/ab67616d0000485114f35992ffc62ef3d70705f8'}],
    'is_playable': True,
    'name': 'Stage One',
    'release_date': '2000',
    'release_date_precision': 'year',
    'total_tracks': 25,
    'type': 'album',
    'uri': 'spotify:album:6Y5344aCqHNxQNAUStzHrd'},
   'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/3Isy6kedDrgPYoTS1dazA9'},
     'href': 'https://api.spotify.com/v1/artists/3Isy6kedDrgPYoTS1dazA9',
     'id': '3Isy6kedDrgPYoTS1dazA9',
     'name': 'Sean Paul',
     'type': 'artist',
     'uri': 'spotify:artist:3Isy6kedDrgPYoTS1dazA9'}],
   'available_markets': ['AR',
    'AU',
    'AT',
    'BE',
    'BO',
    'BR',
    'BG',
    'CA',
    'CL',
    'CO',
    'CR',
    'CY',
    'CZ',
    'DK',
    'DO',
    'DE',
    'EC',
    'EE',
    'SV',
    'FI',
    'FR',
    'GR',
    'GT',
    'HN',
    'HK',
    'HU',
    'IS',
    'IE',
    'IT',
    'LV',
    'LT',
    'LU',
    'MY',
    'MT',
    'MX',
    'NL',
    'NZ',
    'NI',
    'NO',
    'PA',
    'PY',
    'PE',
    'PH',
    'PL',
    'PT',
    'SG',
    'SK',
    'ES',
    'SE',
    'CH',
    'TW',
    'TR',
    'UY',
    'US',
    'GB',
    'AD',
    'LI',
    'MC',
    'ID',
    'JP',
    'TH',
    'VN',
    'RO',
    'IL',
    'ZA',
    'SA',
    'AE',
    'BH',
    'QA',
    'OM',
    'KW',
    'EG',
    'MA',
    'DZ',
    'TN',
    'LB',
    'JO',
    'PS',
    'IN',
    'KZ',
    'MD',
    'UA',
    'AL',
    'BA',
    'HR',
    'ME',
    'MK',
    'RS',
    'SI',
    'KR',
    'BD',
    'PK',
    'LK',
    'GH',
    'KE',
    'NG',
    'TZ',
    'UG',
    'AG',
    'AM',
    'BS',
    'BB',
    'BZ',
    'BT',
    'BW',
    'BF',
    'CV',
    'CW',
    'DM',
    'FJ',
    'GM',
    'GE',
    'GD',
    'GW',
    'GY',
    'HT',
    'JM',
    'KI',
    'LS',
    'LR',
    'MW',
    'MV',
    'ML',
    'MH',
    'FM',
    'NA',
    'NR',
    'NE',
    'PW',
    'PG',
    'PR',
    'WS',
    'SM',
    'ST',
    'SN',
    'SC',
    'SL',
    'SB',
    'KN',
    'LC',
    'VC',
    'SR',
    'TL',
    'TO',
    'TT',
    'TV',
    'VU',
    'AZ',
    'BN',
    'BI',
    'KH',
    'CM',
    'TD',
    'KM',
    'GQ',
    'SZ',
    'GA',
    'GN',
    'KG',
    'LA',
    'MO',
    'MR',
    'MN',
    'NP',
    'RW',
    'TG',
    'UZ',
    'ZW',
    'BJ',
    'MG',
    'MU',
    'MZ',
    'AO',
    'CI',
    'DJ',
    'ZM',
    'CD',
    'CG',
    'IQ',
    'LY',
    'TJ',
    'VE',
    'ET',
    'XK'],
   'disc_number': 1,
   'duration_ms': 188306,
   'explicit': False,
   'external_ids': {'isrc': 'USVPR0007000'},
   'external_urls': {'spotify': 'https://open.spotify.com/track/5KhypMVGqMI9mgsrrv2lxc'},
   'href': 'https://api.spotify.com/v1/tracks/5KhypMVGqMI9mgsrrv2lxc',
   'id': '5KhypMVGqMI9mgsrrv2lxc',
   'is_local': False,
   'is_playable': True,
   'name': 'Deport Them',
   'popularity': 51,
   'preview_url': None,
   'track_number': 11,
   'type': 'track',
   'uri': 'spotify:track:5KhypMVGqMI9mgsrrv2lxc'},
  {'album': {'album_type': 'album',
    'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/5EvFsr3kj42KNv97ZEnqij'},
      'href': 'https://api.spotify.com/v1/artists/5EvFsr3kj42KNv97ZEnqij',
      'id': '5EvFsr3kj42KNv97ZEnqij',
      'name': 'Shaggy',
      'type': 'artist',
      'uri': 'spotify:artist:5EvFsr3kj42KNv97ZEnqij'}],
    'available_markets': ['AR',
     'AU',
     'AT',
     'BE',
     'BO',
     'BR',
     'BG',
     'CA',
     'CL',
     'CO',
     'CR',
     'CY',
     'CZ',
     'DK',
     'DO',
     'DE',
     'EC',
     'EE',
     'SV',
     'FI',
     'FR',
     'GR',
     'GT',
     'HN',
     'HK',
     'HU',
     'IS',
     'IE',
     'IT',
     'LV',
     'LT',
     'LU',
     'MY',
     'MT',
     'MX',
     'NL',
     'NZ',
     'NI',
     'NO',
     'PA',
     'PY',
     'PE',
     'PH',
     'PL',
     'PT',
     'SG',
     'SK',
     'ES',
     'SE',
     'CH',
     'TW',
     'TR',
     'UY',
     'US',
     'GB',
     'AD',
     'LI',
     'MC',
     'ID',
     'JP',
     'TH',
     'VN',
     'RO',
     'IL',
     'ZA',
     'SA',
     'AE',
     'BH',
     'QA',
     'OM',
     'KW',
     'EG',
     'MA',
     'DZ',
     'TN',
     'LB',
     'JO',
     'PS',
     'IN',
     'BY',
     'KZ',
     'MD',
     'UA',
     'AL',
     'BA',
     'HR',
     'ME',
     'MK',
     'RS',
     'SI',
     'KR',
     'BD',
     'PK',
     'LK',
     'GH',
     'KE',
     'NG',
     'TZ',
     'UG',
     'AG',
     'AM',
     'BS',
     'BB',
     'BZ',
     'BT',
     'BW',
     'BF',
     'CV',
     'CW',
     'DM',
     'FJ',
     'GM',
     'GE',
     'GD',
     'GW',
     'GY',
     'HT',
     'JM',
     'KI',
     'LS',
     'LR',
     'MW',
     'MV',
     'ML',
     'MH',
     'FM',
     'NA',
     'NR',
     'NE',
     'PW',
     'PG',
     'WS',
     'SM',
     'ST',
     'SN',
     'SC',
     'SL',
     'SB',
     'KN',
     'LC',
     'VC',
     'SR',
     'TL',
     'TO',
     'TT',
     'TV',
     'VU',
     'AZ',
     'BN',
     'BI',
     'KH',
     'CM',
     'TD',
     'KM',
     'GQ',
     'SZ',
     'GA',
     'GN',
     'KG',
     'LA',
     'MO',
     'MR',
     'MN',
     'NP',
     'RW',
     'TG',
     'UZ',
     'ZW',
     'BJ',
     'MG',
     'MU',
     'MZ',
     'AO',
     'CI',
     'DJ',
     'ZM',
     'CD',
     'CG',
     'IQ',
     'LY',
     'TJ',
     'VE',
     'ET',
     'XK'],
    'external_urls': {'spotify': 'https://open.spotify.com/album/3MT88SSyxQGbqYXj4LVk3b'},
    'href': 'https://api.spotify.com/v1/albums/3MT88SSyxQGbqYXj4LVk3b',
    'id': '3MT88SSyxQGbqYXj4LVk3b',
    'images': [{'height': 640,
      'width': 640,
      'url': 'https://i.scdn.co/image/ab67616d0000b2739449f9491c364d28a9668e17'},
     {'height': 300,
      'width': 300,
      'url': 'https://i.scdn.co/image/ab67616d00001e029449f9491c364d28a9668e17'},
     {'height': 64,
      'width': 64,
      'url': 'https://i.scdn.co/image/ab67616d000048519449f9491c364d28a9668e17'}],
    'is_playable': True,
    'name': 'Hot Shot',
    'release_date': '2000-08-08',
    'release_date_precision': 'day',
    'total_tracks': 15,
    'type': 'album',
    'uri': 'spotify:album:3MT88SSyxQGbqYXj4LVk3b'},
   'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/5EvFsr3kj42KNv97ZEnqij'},
     'href': 'https://api.spotify.com/v1/artists/5EvFsr3kj42KNv97ZEnqij',
     'id': '5EvFsr3kj42KNv97ZEnqij',
     'name': 'Shaggy',
     'type': 'artist',
     'uri': 'spotify:artist:5EvFsr3kj42KNv97ZEnqij'},
    {'external_urls': {'spotify': 'https://open.spotify.com/artist/4VnMJXQpix0onjop2VNFvX'},
     'href': 'https://api.spotify.com/v1/artists/4VnMJXQpix0onjop2VNFvX',
     'id': '4VnMJXQpix0onjop2VNFvX',
     'name': 'Samantha Cole',
     'type': 'artist',
     'uri': 'spotify:artist:4VnMJXQpix0onjop2VNFvX'}],
   'available_markets': ['AR',
    'AU',
    'AT',
    'BE',
    'BO',
    'BR',
    'BG',
    'CA',
    'CL',
    'CO',
    'CR',
    'CY',
    'CZ',
    'DK',
    'DO',
    'DE',
    'EC',
    'EE',
    'SV',
    'FI',
    'FR',
    'GR',
    'GT',
    'HN',
    'HK',
    'HU',
    'IS',
    'IE',
    'IT',
    'LV',
    'LT',
    'LU',
    'MY',
    'MT',
    'MX',
    'NL',
    'NZ',
    'NI',
    'NO',
    'PA',
    'PY',
    'PE',
    'PH',
    'PL',
    'PT',
    'SG',
    'SK',
    'ES',
    'SE',
    'CH',
    'TW',
    'TR',
    'UY',
    'US',
    'GB',
    'AD',
    'LI',
    'MC',
    'ID',
    'JP',
    'TH',
    'VN',
    'RO',
    'IL',
    'ZA',
    'SA',
    'AE',
    'BH',
    'QA',
    'OM',
    'KW',
    'EG',
    'MA',
    'DZ',
    'TN',
    'LB',
    'JO',
    'PS',
    'IN',
    'BY',
    'KZ',
    'MD',
    'UA',
    'AL',
    'BA',
    'HR',
    'ME',
    'MK',
    'RS',
    'SI',
    'KR',
    'BD',
    'PK',
    'LK',
    'GH',
    'KE',
    'NG',
    'TZ',
    'UG',
    'AG',
    'AM',
    'BS',
    'BB',
    'BZ',
    'BT',
    'BW',
    'BF',
    'CV',
    'CW',
    'DM',
    'FJ',
    'GM',
    'GE',
    'GD',
    'GW',
    'GY',
    'HT',
    'JM',
    'KI',
    'LS',
    'LR',
    'MW',
    'MV',
    'ML',
    'MH',
    'FM',
    'NA',
    'NR',
    'NE',
    'PW',
    'PG',
    'WS',
    'SM',
    'ST',
    'SN',
    'SC',
    'SL',
    'SB',
    'KN',
    'LC',
    'VC',
    'SR',
    'TL',
    'TO',
    'TT',
    'TV',
    'VU',
    'AZ',
    'BN',
    'BI',
    'KH',
    'CM',
    'TD',
    'KM',
    'GQ',
    'SZ',
    'GA',
    'GN',
    'KG',
    'LA',
    'MO',
    'MR',
    'MN',
    'NP',
    'RW',
    'TG',
    'UZ',
    'ZW',
    'BJ',
    'MG',
    'MU',
    'MZ',
    'AO',
    'CI',
    'DJ',
    'ZM',
    'CD',
    'CG',
    'IQ',
    'LY',
    'TJ',
    'VE',
    'ET',
    'XK'],
   'disc_number': 1,
   'duration_ms': 215506,
   'explicit': False,
   'external_ids': {'isrc': 'USMC10000615'},
   'external_urls': {'spotify': 'https://open.spotify.com/track/7hV4x7PMKGC4qD3NWLt2UJ'},
   'href': 'https://api.spotify.com/v1/tracks/7hV4x7PMKGC4qD3NWLt2UJ',
   'id': '7hV4x7PMKGC4qD3NWLt2UJ',
   'is_local': False,
   'is_playable': True,
   'name': 'Luv Me, Luv Me',
   'popularity': 52,
   'preview_url': None,
   'track_number': 9,
   'type': 'track',
   'uri': 'spotify:track:7hV4x7PMKGC4qD3NWLt2UJ'},
  {'album': {'album_type': 'album',
    'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/4wvAGBushcLkCZ1lEZsYMf'},
      'href': 'https://api.spotify.com/v1/artists/4wvAGBushcLkCZ1lEZsYMf',
      'id': '4wvAGBushcLkCZ1lEZsYMf',
      'name': 'Maskavo',
      'type': 'artist',
      'uri': 'spotify:artist:4wvAGBushcLkCZ1lEZsYMf'}],
    'available_markets': ['AR',
     'AU',
     'AT',
     'BE',
     'BO',
     'BR',
     'BG',
     'CA',
     'CL',
     'CO',
     'CR',
     'CY',
     'CZ',
     'DK',
     'DO',
     'DE',
     'EC',
     'EE',
     'SV',
     'FI',
     'FR',
     'GR',
     'GT',
     'HN',
     'HK',
     'HU',
     'IS',
     'IE',
     'IT',
     'LV',
     'LT',
     'LU',
     'MY',
     'MT',
     'MX',
     'NL',
     'NZ',
     'NI',
     'NO',
     'PA',
     'PY',
     'PE',
     'PH',
     'PL',
     'PT',
     'SG',
     'SK',
     'ES',
     'SE',
     'CH',
     'TW',
     'TR',
     'UY',
     'US',
     'GB',
     'AD',
     'LI',
     'MC',
     'ID',
     'JP',
     'TH',
     'VN',
     'RO',
     'IL',
     'ZA',
     'SA',
     'AE',
     'BH',
     'QA',
     'OM',
     'KW',
     'EG',
     'MA',
     'DZ',
     'TN',
     'LB',
     'JO',
     'PS',
     'IN',
     'BY',
     'KZ',
     'MD',
     'UA',
     'AL',
     'BA',
     'HR',
     'ME',
     'MK',
     'RS',
     'SI',
     'KR',
     'BD',
     'PK',
     'LK',
     'GH',
     'KE',
     'NG',
     'TZ',
     'UG',
     'AG',
     'AM',
     'BS',
     'BB',
     'BZ',
     'BT',
     'BW',
     'BF',
     'CV',
     'CW',
     'DM',
     'FJ',
     'GM',
     'GE',
     'GD',
     'GW',
     'GY',
     'HT',
     'JM',
     'KI',

In [30]:
datos["tracks"]["items"]

[{'album': {'album_type': 'album',
   'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/3Isy6kedDrgPYoTS1dazA9'},
     'href': 'https://api.spotify.com/v1/artists/3Isy6kedDrgPYoTS1dazA9',
     'id': '3Isy6kedDrgPYoTS1dazA9',
     'name': 'Sean Paul',
     'type': 'artist',
     'uri': 'spotify:artist:3Isy6kedDrgPYoTS1dazA9'}],
   'available_markets': ['AR',
    'AU',
    'AT',
    'BE',
    'BO',
    'BR',
    'BG',
    'CA',
    'CL',
    'CO',
    'CR',
    'CY',
    'CZ',
    'DK',
    'DO',
    'DE',
    'EC',
    'EE',
    'SV',
    'FI',
    'FR',
    'GR',
    'GT',
    'HN',
    'HK',
    'HU',
    'IS',
    'IE',
    'IT',
    'LV',
    'LT',
    'LU',
    'MY',
    'MT',
    'MX',
    'NL',
    'NZ',
    'NI',
    'NO',
    'PA',
    'PY',
    'PE',
    'PH',
    'PL',
    'PT',
    'SG',
    'SK',
    'ES',
    'SE',
    'CH',
    'TW',
    'TR',
    'UY',
    'US',
    'GB',
    'AD',
    'LI',
    'MC',
    'ID',
    'JP',
    'TH',
    'VN',
    'RO',
    'IL',
    'ZA',
    'SA',
    'AE',
    'BH',
    'QA',
    'OM',
    'KW',
    'EG',
    'MA',
    'DZ',
    'TN',
    'LB',
    'JO',
    'PS',
    'IN',
    'KZ',
    'MD',
    'UA',
    'AL',
    'BA',
    'HR',
    'ME',
    'MK',
    'RS',
    'SI',
    'KR',
    'BD',
    'PK',
    'LK',
    'GH',
    'KE',
    'NG',
    'TZ',
    'UG',
    'AG',
    'AM',
    'BS',
    'BB',
    'BZ',
    'BT',
    'BW',
    'BF',
    'CV',
    'CW',
    'DM',
    'FJ',
    'GM',
    'GE',
    'GD',
    'GW',
    'GY',
    'HT',
    'JM',
    'KI',
    'LS',
    'LR',
    'MW',
    'MV',
    'ML',
    'MH',
    'FM',
    'NA',
    'NR',
    'NE',
    'PW',
    'PG',
    'PR',
    'WS',
    'SM',
    'ST',
    'SN',
    'SC',
    'SL',
    'SB',
    'KN',
    'LC',
    'VC',
    'SR',
    'TL',
    'TO',
    'TT',
    'TV',
    'VU',
    'AZ',
    'BN',
    'BI',
    'KH',
    'CM',
    'TD',
    'KM',
    'GQ',
    'SZ',
    'GA',
    'GN',
    'KG',
    'LA',
    'MO',
    'MR',
    'MN',
    'NP',
    'RW',
    'TG',
    'UZ',
    'ZW',
    'BJ',
    'MG',
    'MU',
    'MZ',
    'AO',
    'CI',
    'DJ',
    'ZM',
    'CD',
    'CG',
    'IQ',
    'LY',
    'TJ',
    'VE',
    'ET',
    'XK'],
   'external_urls': {'spotify': 'https://open.spotify.com/album/6Y5344aCqHNxQNAUStzHrd'},
   'href': 'https://api.spotify.com/v1/albums/6Y5344aCqHNxQNAUStzHrd',
   'id': '6Y5344aCqHNxQNAUStzHrd',
   'images': [{'height': 640,
     'width': 640,
     'url': 'https://i.scdn.co/image/ab67616d0000b27314f35992ffc62ef3d70705f8'},
    {'height': 300,
     'width': 300,
     'url': 'https://i.scdn.co/image/ab67616d00001e0214f35992ffc62ef3d70705f8'},
    {'height': 64,
     'width': 64,
     'url': 'https://i.scdn.co/image/ab67616d0000485114f35992ffc62ef3d70705f8'}],
   'is_playable': True,
   'name': 'Stage One',
   'release_date': '2000',
   'release_date_precision': 'year',
   'total_tracks': 25,
   'type': 'album',
   'uri': 'spotify:album:6Y5344aCqHNxQNAUStzHrd'},
  'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/3Isy6kedDrgPYoTS1dazA9'},
    'href': 'https://api.spotify.com/v1/artists/3Isy6kedDrgPYoTS1dazA9',
    'id': '3Isy6kedDrgPYoTS1dazA9',
    'name': 'Sean Paul',
    'type': 'artist',
    'uri': 'spotify:artist:3Isy6kedDrgPYoTS1dazA9'}],
  'available_markets': ['AR',
   'AU',
   'AT',
   'BE',
   'BO',
   'BR',
   'BG',
   'CA',
   'CL',
   'CO',
   'CR',
   'CY',
   'CZ',
   'DK',
   'DO',
   'DE',
   'EC',
   'EE',
   'SV',
   'FI',
   'FR',
   'GR',
   'GT',
   'HN',
   'HK',
   'HU',
   'IS',
   'IE',
   'IT',
   'LV',
   'LT',
   'LU',
   'MY',
   'MT',
   'MX',
   'NL',
   'NZ',
   'NI',
   'NO',
   'PA',
   'PY',
   'PE',
   'PH',
   'PL',
   'PT',
   'SG',
   'SK',
   'ES',
   'SE',
   'CH',
   'TW',
   'TR',
   'UY',
   'US',
   'GB',
   'AD',
   'LI',
   'MC',
   'ID',
   'JP',
   'TH',
   'VN',
   'RO',
   'IL',
   'ZA',
   'SA',
   'AE',
   'BH',
   'QA',
   'OM',
   'KW',
   'EG',
   'MA',
   'DZ',
   'TN',
   'LB',
   'JO',
   'PS',
   'IN',
   'KZ',
   'MD',
   'UA',
   'AL',
   'BA',
   'HR',
   'ME',
   'MK',
   'RS',
   'SI',
   'KR',
   'BD',
   'PK',
   'LK',
   'GH',
   'KE',
   'NG',
   'TZ',
   'UG',
   'AG',
   'AM',
   'BS',
   'BB',
   'BZ',
   'BT',
   'BW',
   'BF',
   'CV',
   'CW',
   'DM',
   'FJ',
   'GM',
   'GE',
   'GD',
   'GW',
   'GY',
   'HT',
   'JM',
   'KI',
   'LS',
   'LR',
   'MW',
   'MV',
   'ML',
   'MH',
   'FM',
   'NA',
   'NR',
   'NE',
   'PW',
   'PG',
   'PR',
   'WS',
   'SM',
   'ST',
   'SN',
   'SC',
   'SL',
   'SB',
   'KN',
   'LC',
   'VC',
   'SR',
   'TL',
   'TO',
   'TT',
   'TV',
   'VU',
   'AZ',
   'BN',
   'BI',
   'KH',
   'CM',
   'TD',
   'KM',
   'GQ',
   'SZ',
   'GA',
   'GN',
   'KG',
   'LA',
   'MO',
   'MR',
   'MN',
   'NP',
   'RW',
   'TG',
   'UZ',
   'ZW',
   'BJ',
   'MG',
   'MU',
   'MZ',
   'AO',
   'CI',
   'DJ',
   'ZM',
   'CD',
   'CG',
   'IQ',
   'LY',
   'TJ',
   'VE',
   'ET',
   'XK'],
  'disc_number': 1,
  'duration_ms': 209466,
  'explicit': False,
  'external_ids': {'isrc': 'USVPR0006995'},
  'external_urls': {'spotify': 'https://open.spotify.com/track/0ru8bc0XnKjUL2O1Fl1k7a'},
  'href': 'https://api.spotify.com/v1/tracks/0ru8bc0XnKjUL2O1Fl1k7a',
  'id': '0ru8bc0XnKjUL2O1Fl1k7a',
  'is_local': False,
  'is_playable': True,
  'name': 'Infiltrate',
  'popularity': 50,
  'preview_url': None,
  'track_number': 3,
  'type': 'track',
  'uri': 'spotify:track:0ru8bc0XnKjUL2O1Fl1k7a'},
 {'album': {'album_type': 'album',
   'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/3Isy6kedDrgPYoTS1dazA9'},
     'href': 'https://api.spotify.com/v1/artists/3Isy6kedDrgPYoTS1dazA9',
     'id': '3Isy6kedDrgPYoTS1dazA9',
     'name': 'Sean Paul',
     'type': 'artist',
     'uri': 'spotify:artist:3Isy6kedDrgPYoTS1dazA9'}],
   'available_markets': ['AR',
    'AU',
    'AT',
    'BE',
    'BO',
    'BR',
    'BG',
    'CA',
    'CL',
    'CO',
    'CR',
    'CY',
    'CZ',
    'DK',
    'DO',
    'DE',
    'EC',
    'EE',
    'SV',
    'FI',
    'FR',
    'GR',
    'GT',
    'HN',
    'HK',
    'HU',
    'IS',
    'IE',
    'IT',
    'LV',
    'LT',
    'LU',
    'MY',
    'MT',
    'MX',
    'NL',
    'NZ',
    'NI',
    'NO',
    'PA',
    'PY',
    'PE',
    'PH',
    'PL',
    'PT',
    'SG',
    'SK',
    'ES',
    'SE',
    'CH',
    'TW',
    'TR',
    'UY',
    'US',
    'GB',
    'AD',
    'LI',
    'MC',
    'ID',
    'JP',
    'TH',
    'VN',
    'RO',
    'IL',
    'ZA',
    'SA',
    'AE',
    'BH',
    'QA',
    'OM',
    'KW',
    'EG',
    'MA',
    'DZ',
    'TN',
    'LB',
    'JO',
    'PS',
    'IN',
    'KZ',
    'MD',
    'UA',
    'AL',
    'BA',
    'HR',
    'ME',
    'MK',
    'RS',
    'SI',
    'KR',
    'BD',
    'PK',
    'LK',
    'GH',
    'KE',
    'NG',
    'TZ',
    'UG',
    'AG',
    'AM',
    'BS',
    'BB',
    'BZ',
    'BT',
    'BW',
    'BF',
    'CV',
    'CW',
    'DM',
    'FJ',
    'GM',
    'GE',
    'GD',
    'GW',
    'GY',
    'HT',
    'JM',
    'KI',
    'LS',
    'LR',
    'MW',
    'MV',
    'ML',
    'MH',
    'FM',
    'NA',
    'NR',
    'NE',
    'PW',
    'PG',
    'PR',
    'WS',
    'SM',
    'ST',
    'SN',
    'SC',
    'SL',
    'SB',
    'KN',
    'LC',
    'VC',
    'SR',
    'TL',
    'TO',
    'TT',
    'TV',
    'VU',
    'AZ',
    'BN',
    'BI',
    'KH',
    'CM',
    'TD',
    'KM',
    'GQ',
    'SZ',
    'GA',
    'GN',
    'KG',
    'LA',
    'MO',
    'MR',
    'MN',
    'NP',
    'RW',
    'TG',
    'UZ',
    'ZW',
    'BJ',
    'MG',
    'MU',
    'MZ',
    'AO',
    'CI',
    'DJ',
    'ZM',
    'CD',
    'CG',
    'IQ',
    'LY',
    'TJ',
    'VE',
    'ET',
    'XK'],
   'external_urls': {'spotify': 'https://open.spotify.com/album/6Y5344aCqHNxQNAUStzHrd'},
   'href': 'https://api.spotify.com/v1/albums/6Y5344aCqHNxQNAUStzHrd',
   'id': '6Y5344aCqHNxQNAUStzHrd',
   'images': [{'height': 640,
     'width': 640,
     'url': 'https://i.scdn.co/image/ab67616d0000b27314f35992ffc62ef3d70705f8'},
    {'height': 300,
     'width': 300,
     'url': 'https://i.scdn.co/image/ab67616d00001e0214f35992ffc62ef3d70705f8'},
    {'height': 64,
     'width': 64,
     'url': 'https://i.scdn.co/image/ab67616d0000485114f35992ffc62ef3d70705f8'}],
   'is_playable': True,
   'name': 'Stage One',
   'release_date': '2000',
   'release_date_precision': 'year',
   'total_tracks': 25,
   'type': 'album',
   'uri': 'spotify:album:6Y5344aCqHNxQNAUStzHrd'},
  'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/3Isy6kedDrgPYoTS1dazA9'},
    'href': 'https://api.spotify.com/v1/artists/3Isy6kedDrgPYoTS1dazA9',
    'id': '3Isy6kedDrgPYoTS1dazA9',
    'name': 'Sean Paul',
    'type': 'artist',
    'uri': 'spotify:artist:3Isy6kedDrgPYoTS1dazA9'}],
  'available_markets': ['AR',
   'AU',
   'AT',
   'BE',
   'BO',
   'BR',
   'BG',
   'CA',
   'CL',
   'CO',
   'CR',
   'CY',
   'CZ',
   'DK',
   'DO',
   'DE',
   'EC',
   'EE',
   'SV',
   'FI',
   'FR',
   'GR',
   'GT',
   'HN',
   'HK',
   'HU',
   'IS',
   'IE',
   'IT',
   'LV',
   'LT',
   'LU',
   'MY',
   'MT',
   'MX',
   'NL',
   'NZ',
   'NI',
   'NO',
   'PA',
   'PY',
   'PE',
   'PH',
   'PL',
   'PT',
   'SG',
   'SK',
   'ES',
   'SE',
   'CH',
   'TW',
   'TR',
   'UY',
   'US',
   'GB',
   'AD',
   'LI',
   'MC',
   'ID',
   'JP',
   'TH',
   'VN',
   'RO',
   'IL',
   'ZA',
   'SA',
   'AE',
   'BH',
   'QA',
   'OM',
   'KW',
   'EG',
   'MA',
   'DZ',
   'TN',
   'LB',
   'JO',
   'PS',
   'IN',
   'KZ',
   'MD',
   'UA',
   'AL',
   'BA',
   'HR',
   'ME',
   'MK',
   'RS',
   'SI',
   'KR',
   'BD',
   'PK',
   'LK',
   'GH',
   'KE',
   'NG',
   'TZ',
   'UG',
   'AG',
   'AM',
   'BS',
   'BB',
   'BZ',
   'BT',
   'BW',
   'BF',
   'CV',
   'CW',
   'DM',
   'FJ',
   'GM',
   'GE',
   'GD',
   'GW',
   'GY',
   'HT',
   'JM',
   'KI',
   'LS',
   'LR',
   'MW',
   'MV',
   'ML',
   'MH',
   'FM',
   'NA',
   'NR',
   'NE',
   'PW',
   'PG',
   'PR',
   'WS',
   'SM',
   'ST',
   'SN',
   'SC',
   'SL',
   'SB',
   'KN',
   'LC',
   'VC',
   'SR',
   'TL',
   'TO',
   'TT',
   'TV',
   'VU',
   'AZ',
   'BN',
   'BI',
   'KH',
   'CM',
   'TD',
   'KM',
   'GQ',
   'SZ',
   'GA',
   'GN',
   'KG',
   'LA',
   'MO',
   'MR',
   'MN',
   'NP',
   'RW',
   'TG',
   'UZ',
   'ZW',
   'BJ',
   'MG',
   'MU',
   'MZ',
   'AO',
   'CI',
   'DJ',
   'ZM',
   'CD',
   'CG',
   'IQ',
   'LY',
   'TJ',
   'VE',
   'ET',
   'XK'],
  'disc_number': 1,
  'duration_ms': 188306,
  'explicit': False,
  'external_ids': {'isrc': 'USVPR0007000'},
  'external_urls': {'spotify': 'https://open.spotify.com/track/5KhypMVGqMI9mgsrrv2lxc'},
  'href': 'https://api.spotify.com/v1/tracks/5KhypMVGqMI9mgsrrv2lxc',
  'id': '5KhypMVGqMI9mgsrrv2lxc',
  'is_local': False,
  'is_playable': True,
  'name': 'Deport Them',
  'popularity': 51,
  'preview_url': None,
  'track_number': 11,
  'type': 'track',
  'uri': 'spotify:track:5KhypMVGqMI9mgsrrv2lxc'},
 {'album': {'album_type': 'album',
   'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/5EvFsr3kj42KNv97ZEnqij'},
     'href': 'https://api.spotify.com/v1/artists/5EvFsr3kj42KNv97ZEnqij',
     'id': '5EvFsr3kj42KNv97ZEnqij',
     'name': 'Shaggy',
     'type': 'artist',
     'uri': 'spotify:artist:5EvFsr3kj42KNv97ZEnqij'}],
   'available_markets': ['AR',
    'AU',
    'AT',
    'BE',
    'BO',
    'BR',
    'BG',
    'CA',
    'CL',
    'CO',
    'CR',
    'CY',
    'CZ',
    'DK',
    'DO',
    'DE',
    'EC',
    'EE',
    'SV',
    'FI',
    'FR',
    'GR',
    'GT',
    'HN',
    'HK',
    'HU',
    'IS',
    'IE',
    'IT',
    'LV',
    'LT',
    'LU',
    'MY',
    'MT',
    'MX',
    'NL',
    'NZ',
    'NI',
    'NO',
    'PA',
    'PY',
    'PE',
    'PH',
    'PL',
    'PT',
    'SG',
    'SK',
    'ES',
    'SE',
    'CH',
    'TW',
    'TR',
    'UY',
    'US',
    'GB',
    'AD',
    'LI',
    'MC',
    'ID',
    'JP',
    'TH',
    'VN',
    'RO',
    'IL',
    'ZA',
    'SA',
    'AE',
    'BH',
    'QA',
    'OM',
    'KW',
    'EG',
    'MA',
    'DZ',
    'TN',
    'LB',
    'JO',
    'PS',
    'IN',
    'BY',
    'KZ',
    'MD',
    'UA',
    'AL',
    'BA',
    'HR',
    'ME',
    'MK',
    'RS',
    'SI',
    'KR',
    'BD',
    'PK',
    'LK',
    'GH',
    'KE',
    'NG',
    'TZ',
    'UG',
    'AG',
    'AM',
    'BS',
    'BB',
    'BZ',
    'BT',
    'BW',
    'BF',
    'CV',
    'CW',
    'DM',
    'FJ',
    'GM',
    'GE',
    'GD',
    'GW',
    'GY',
    'HT',
    'JM',
    'KI',
    'LS',
    'LR',
    'MW',
    'MV',
    'ML',
    'MH',
    'FM',
    'NA',
    'NR',
    'NE',
    'PW',
    'PG',
    'WS',
    'SM',
    'ST',
    'SN',
    'SC',
    'SL',
    'SB',
    'KN',
    'LC',
    'VC',
    'SR',
    'TL',
    'TO',
    'TT',
    'TV',
    'VU',
    'AZ',
    'BN',
    'BI',
    'KH',
    'CM',
    'TD',
    'KM',
    'GQ',
    'SZ',
    'GA',
    'GN',
    'KG',
    'LA',
    'MO',
    'MR',
    'MN',
    'NP',
    'RW',
    'TG',
    'UZ',
    'ZW',
    'BJ',
    'MG',
    'MU',
    'MZ',
    'AO',
    'CI',
    'DJ',
    'ZM',
    'CD',
    'CG',
    'IQ',
    'LY',
    'TJ',
    'VE',
    'ET',
    'XK'],
   'external_urls': {'spotify': 'https://open.spotify.com/album/3MT88SSyxQGbqYXj4LVk3b'},
   'href': 'https://api.spotify.com/v1/albums/3MT88SSyxQGbqYXj4LVk3b',
   'id': '3MT88SSyxQGbqYXj4LVk3b',
   'images': [{'height': 640,
     'width': 640,
     'url': 'https://i.scdn.co/image/ab67616d0000b2739449f9491c364d28a9668e17'},
    {'height': 300,
     'width': 300,
     'url': 'https://i.scdn.co/image/ab67616d00001e029449f9491c364d28a9668e17'},
    {'height': 64,
     'width': 64,
     'url': 'https://i.scdn.co/image/ab67616d000048519449f9491c364d28a9668e17'}],
   'is_playable': True,
   'name': 'Hot Shot',
   'release_date': '2000-08-08',
   'release_date_precision': 'day',
   'total_tracks': 15,
   'type': 'album',
   'uri': 'spotify:album:3MT88SSyxQGbqYXj4LVk3b'},
  'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/5EvFsr3kj42KNv97ZEnqij'},
    'href': 'https://api.spotify.com/v1/artists/5EvFsr3kj42KNv97ZEnqij',
    'id': '5EvFsr3kj42KNv97ZEnqij',
    'name': 'Shaggy',
    'type': 'artist',
    'uri': 'spotify:artist:5EvFsr3kj42KNv97ZEnqij'},
   {'external_urls': {'spotify': 'https://open.spotify.com/artist/4VnMJXQpix0onjop2VNFvX'},
    'href': 'https://api.spotify.com/v1/artists/4VnMJXQpix0onjop2VNFvX',
    'id': '4VnMJXQpix0onjop2VNFvX',
    'name': 'Samantha Cole',
    'type': 'artist',
    'uri': 'spotify:artist:4VnMJXQpix0onjop2VNFvX'}],
  'available_markets': ['AR',
   'AU',
   'AT',
   'BE',
   'BO',
   'BR',
   'BG',
   'CA',
   'CL',
   'CO',
   'CR',
   'CY',
   'CZ',
   'DK',
   'DO',
   'DE',
   'EC',
   'EE',
   'SV',
   'FI',
   'FR',
   'GR',
   'GT',
   'HN',
   'HK',
   'HU',
   'IS',
   'IE',
   'IT',
   'LV',
   'LT',
   'LU',
   'MY',
   'MT',
   'MX',
   'NL',
   'NZ',
   'NI',
   'NO',
   'PA',
   'PY',
   'PE',
   'PH',
   'PL',
   'PT',
   'SG',
   'SK',
   'ES',
   'SE',
   'CH',
   'TW',
   'TR',
   'UY',
   'US',
   'GB',
   'AD',
   'LI',
   'MC',
   'ID',
   'JP',
   'TH',
   'VN',
   'RO',
   'IL',
   'ZA',
   'SA',
   'AE',
   'BH',
   'QA',
   'OM',
   'KW',
   'EG',
   'MA',
   'DZ',
   'TN',
   'LB',
   'JO',
   'PS',
   'IN',
   'BY',
   'KZ',
   'MD',
   'UA',
   'AL',
   'BA',
   'HR',
   'ME',
   'MK',
   'RS',
   'SI',
   'KR',
   'BD',
   'PK',
   'LK',
   'GH',
   'KE',
   'NG',
   'TZ',
   'UG',
   'AG',
   'AM',
   'BS',
   'BB',
   'BZ',
   'BT',
   'BW',
   'BF',
   'CV',
   'CW',
   'DM',
   'FJ',
   'GM',
   'GE',
   'GD',
   'GW',
   'GY',
   'HT',
   'JM',
   'KI',
   'LS',
   'LR',
   'MW',
   'MV',
   'ML',
   'MH',
   'FM',
   'NA',
   'NR',
   'NE',
   'PW',
   'PG',
   'WS',
   'SM',
   'ST',
   'SN',
   'SC',
   'SL',
   'SB',
   'KN',
   'LC',
   'VC',
   'SR',
   'TL',
   'TO',
   'TT',
   'TV',
   'VU',
   'AZ',
   'BN',
   'BI',
   'KH',
   'CM',
   'TD',
   'KM',
   'GQ',
   'SZ',
   'GA',
   'GN',
   'KG',
   'LA',
   'MO',
   'MR',
   'MN',
   'NP',
   'RW',
   'TG',
   'UZ',
   'ZW',
   'BJ',
   'MG',
   'MU',
   'MZ',
   'AO',
   'CI',
   'DJ',
   'ZM',
   'CD',
   'CG',
   'IQ',
   'LY',
   'TJ',
   'VE',
   'ET',
   'XK'],
  'disc_number': 1,
  'duration_ms': 215506,
  'explicit': False,
  'external_ids': {'isrc': 'USMC10000615'},
  'external_urls': {'spotify': 'https://open.spotify.com/track/7hV4x7PMKGC4qD3NWLt2UJ'},
  'href': 'https://api.spotify.com/v1/tracks/7hV4x7PMKGC4qD3NWLt2UJ',
  'id': '7hV4x7PMKGC4qD3NWLt2UJ',
  'is_local': False,
  'is_playable': True,
  'name': 'Luv Me, Luv Me',
  'popularity': 52,
  'preview_url': None,
  'track_number': 9,
  'type': 'track',
  'uri': 'spotify:track:7hV4x7PMKGC4qD3NWLt2UJ'},
 {'album': {'album_type': 'album',
   'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/4wvAGBushcLkCZ1lEZsYMf'},
     'href': 'https://api.spotify.com/v1/artists/4wvAGBushcLkCZ1lEZsYMf',
     'id': '4wvAGBushcLkCZ1lEZsYMf',
     'name': 'Maskavo',
     'type': 'artist',
     'uri': 'spotify:artist:4wvAGBushcLkCZ1lEZsYMf'}],
   'available_markets': ['AR',
    'AU',
    'AT',
    'BE',
    'BO',
    'BR',
    'BG',
    'CA',
    'CL',
    'CO',
    'CR',
    'CY',
    'CZ',
    'DK',
    'DO',
    'DE',
    'EC',
    'EE',
    'SV',
    'FI',
    'FR',
    'GR',
    'GT',
    'HN',
    'HK',
    'HU',
    'IS',
    'IE',
    'IT',
    'LV',
    'LT',
    'LU',
    'MY',
    'MT',
    'MX',
    'NL',
    'NZ',
    'NI',
    'NO',
    'PA',
    'PY',
    'PE',
    'PH',
    'PL',
    'PT',
    'SG',
    'SK',
    'ES',
    'SE',
    'CH',
    'TW',
    'TR',
    'UY',
    'US',
    'GB',
    'AD',
    'LI',
    'MC',
    'ID',
    'JP',
    'TH',
    'VN',
    'RO',
    'IL',
    'ZA',
    'SA',
    'AE',
    'BH',
    'QA',
    'OM',
    'KW',
    'EG',
    'MA',
    'DZ',
    'TN',
    'LB',
    'JO',
    'PS',
    'IN',
    'BY',
    'KZ',
    'MD',
    'UA',
    'AL',
    'BA',
    'HR',
    'ME',
    'MK',
    'RS',
    'SI',
    'KR',
    'BD',
    'PK',
    'LK',
    'GH',
    'KE',
    'NG',
    'TZ',
    'UG',
    'AG',
    'AM',
    'BS',
    'BB',
    'BZ',
    'BT',
    'BW',
    'BF',
    'CV',
    'CW',
    'DM',
    'FJ',
    'GM',
    'GE',
    'GD',
    'GW',
    'GY',
    'HT',
    'JM',
    'KI',
    'LS',
    'LR',
    'MW',
    'MV',
    'ML',
    'MH',
    'FM',
    'NA',
    'NR',
    'NE',
    'PW',
    'PG',
    'PR',
    'WS',
    'SM',
    'ST',
    'SN',
    'SC',
    'SL',
    'SB',
    'KN',
    'LC',
    'VC',
    'SR',
    'TL',
    'TO',
    'TT',
    'TV',
    'VU',
    'AZ',
    'BN',
    'BI',
    'KH',
    'CM',
    'TD',
    'KM',
    'GQ',
    'SZ',
    'GA',
    'GN',
    'KG',
    'LA',
    'MO',
    'MR',
    'MN',
    'NP',
    'RW',
    'TG',
    'UZ',
    'ZW',
    'BJ',
    'MG',
    'MU',
    'MZ',
    'AO',
    'CI',
    'DJ',
    'ZM',
    'CD',
    'CG',
    'IQ',
    'LY',
    'TJ',
    'VE',
    'ET',
    'XK'],
   'external_urls': {'spotify': 'https://open.spotify.com/album/6TVsnE10smdfVGIEG5BFbM'},
   'href': 'https://api.spotify.com/v1/albums/6TVsnE10smdfVGIEG5BFbM',
   'id': '6TVsnE10smdfVGIEG5BFbM',
   'images': [{'height': 640,
     'width': 640,
     'url': 'https://i.scdn.co/image/ab67616d0000b2733e9917ee3490cd296517e604'},
    {'height': 300,
     'width': 300,
     'url': 'https://i.scdn.co/image/ab67616d00001e023e9917ee3490cd296517e604'},
    {'height': 64,
     'width': 64,
     'url': 'https://i.scdn.co/image/ab67616d000048513e9917ee3490cd296517e604'}],
   'is_playable': True,
   'name': 'Já',
   'release_date': '2000',
   'release_date_precision': 'year',
   'total_tracks': 14,
   'type': 'album',
   'uri': 'spotify:album:6TVsnE10smdfVGIEG5BFbM'},
  'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/4wvAGBushcLkCZ1lEZsYMf'},
    'href': 'https://api.spotify.com/v1/artists/4wvAGBushcLkCZ1lEZsYMf',
    'id': '4wvAGBushcLkCZ1lEZsYMf',
    'name': 'Maskavo',
    'type': 'artist',

In [31]:
datos["tracks"]["items"][0]

{'album': {'album_type': 'album',
  'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/3Isy6kedDrgPYoTS1dazA9'},
    'href': 'https://api.spotify.com/v1/artists/3Isy6kedDrgPYoTS1dazA9',
    'id': '3Isy6kedDrgPYoTS1dazA9',
    'name': 'Sean Paul',
    'type': 'artist',
    'uri': 'spotify:artist:3Isy6kedDrgPYoTS1dazA9'}],
  'available_markets': ['AR',
   'AU',
   'AT',
   'BE',
   'BO',
   'BR',
   'BG',
   'CA',
   'CL',
   'CO',
   'CR',
   'CY',
   'CZ',
   'DK',
   'DO',
   'DE',
   'EC',
   'EE',
   'SV',
   'FI',
   'FR',
   'GR',
   'GT',
   'HN',
   'HK',
   'HU',
   'IS',
   'IE',
   'IT',
   'LV',
   'LT',
   'LU',
   'MY',
   'MT',
   'MX',
   'NL',
   'NZ',
   'NI',
   'NO',
   'PA',
   'PY',
   'PE',
   'PH',
   'PL',
   'PT',
   'SG',
   'SK',
   'ES',
   'SE',
   'CH',
   'TW',
   'TR',
   'UY',
   'US',
   'GB',
   'AD',
   'LI',
   'MC',
   'ID',
   'JP',
   'TH',
   'VN',
   'RO',
   'IL',
   'ZA',
   'SA',
   'AE',
   'BH',
   'QA',
   'OM',
   'KW',
   'EG',
   'MA',
   'DZ',
   'TN',
   'LB',
   'JO',
   'PS',
   'IN',
   'KZ',
   'MD',
   'UA',
   'AL',
   'BA',
   'HR',
   'ME',
   'MK',
   'RS',
   'SI',
   'KR',
   'BD',
   'PK',
   'LK',
   'GH',
   'KE',
   'NG',
   'TZ',
   'UG',
   'AG',
   'AM',
   'BS',
   'BB',
   'BZ',
   'BT',
   'BW',
   'BF',
   'CV',
   'CW',
   'DM',
   'FJ',
   'GM',
   'GE',
   'GD',
   'GW',
   'GY',
   'HT',
   'JM',
   'KI',
   'LS',
   'LR',
   'MW',
   'MV',
   'ML',
   'MH',
   'FM',
   'NA',
   'NR',
   'NE',
   'PW',
   'PG',
   'PR',
   'WS',
   'SM',
   'ST',
   'SN',
   'SC',
   'SL',
   'SB',
   'KN',
   'LC',
   'VC',
   'SR',
   'TL',
   'TO',
   'TT',
   'TV',
   'VU',
   'AZ',
   'BN',
   'BI',
   'KH',
   'CM',
   'TD',
   'KM',
   'GQ',
   'SZ',
   'GA',
   'GN',
   'KG',
   'LA',
   'MO',
   'MR',
   'MN',
   'NP',
   'RW',
   'TG',
   'UZ',
   'ZW',
   'BJ',
   'MG',
   'MU',
   'MZ',
   'AO',
   'CI',
   'DJ',
   'ZM',
   'CD',
   'CG',
   'IQ',
   'LY',
   'TJ',
   'VE',
   'ET',
   'XK'],
  'external_urls': {'spotify': 'https://open.spotify.com/album/6Y5344aCqHNxQNAUStzHrd'},
  'href': 'https://api.spotify.com/v1/albums/6Y5344aCqHNxQNAUStzHrd',
  'id': '6Y5344aCqHNxQNAUStzHrd',
  'images': [{'height': 640,
    'width': 640,
    'url': 'https://i.scdn.co/image/ab67616d0000b27314f35992ffc62ef3d70705f8'},
   {'height': 300,
    'width': 300,
    'url': 'https://i.scdn.co/image/ab67616d00001e0214f35992ffc62ef3d70705f8'},
   {'height': 64,
    'width': 64,
    'url': 'https://i.scdn.co/image/ab67616d0000485114f35992ffc62ef3d70705f8'}],
  'is_playable': True,
  'name': 'Stage One',
  'release_date': '2000',
  'release_date_precision': 'year',
  'total_tracks': 25,
  'type': 'album',
  'uri': 'spotify:album:6Y5344aCqHNxQNAUStzHrd'},
 'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/3Isy6kedDrgPYoTS1dazA9'},
   'href': 'https://api.spotify.com/v1/artists/3Isy6kedDrgPYoTS1dazA9',
   'id': '3Isy6kedDrgPYoTS1dazA9',
   'name': 'Sean Paul',
   'type': 'artist',
   'uri': 'spotify:artist:3Isy6kedDrgPYoTS1dazA9'}],
 'available_markets': ['AR',
  'AU',
  'AT',
  'BE',
  'BO',
  'BR',
  'BG',
  'CA',
  'CL',
  'CO',
  'CR',
  'CY',
  'CZ',
  'DK',
  'DO',
  'DE',
  'EC',
  'EE',
  'SV',
  'FI',
  'FR',
  'GR',
  'GT',
  'HN',
  'HK',
  'HU',
  'IS',
  'IE',
  'IT',
  'LV',
  'LT',
  'LU',
  'MY',
  'MT',
  'MX',
  'NL',
  'NZ',
  'NI',
  'NO',
  'PA',
  'PY',
  'PE',
  'PH',
  'PL',
  'PT',
  'SG',
  'SK',
  'ES',
  'SE',
  'CH',
  'TW',
  'TR',
  'UY',
  'US',
  'GB',
  'AD',
  'LI',
  'MC',
  'ID',
  'JP',
  'TH',
  'VN',
  'RO',
  'IL',
  'ZA',
  'SA',
  'AE',
  'BH',
  'QA',
  'OM',
  'KW',
  'EG',
  'MA',
  'DZ',
  'TN',
  'LB',
  'JO',
  'PS',
  'IN',
  'KZ',
  'MD',
  'UA',
  'AL',
  'BA',
  'HR',
  'ME',
  'MK',
  'RS',
  'SI',
  'KR',
  'BD',
  'PK',
  'LK',
  'GH',
  'KE',
  'NG',
  'TZ',
  'UG',
  'AG',
  'AM',
  'BS',
  'BB',
  'BZ',
  'BT',
  'BW',
  'BF',
  'CV',
  'CW',
  'DM',
  'FJ',
  'GM',
  'GE',
  'GD',
  'GW',
  'GY',
  'HT',
  'JM',
  'KI',
  'LS',
  'LR',
  'MW',
  'MV',
  'ML',
  'MH',
  'FM',
  'NA',
  'NR',
  'NE',
  'PW',
  'PG',
  'PR',
  'WS',
  'SM',
  'ST',
  'SN',
  'SC',
  'SL',
  'SB',
  'KN',
  'LC',
  'VC',
  'SR',
  'TL',
  'TO',
  'TT',
  'TV',
  'VU',
  'AZ',
  'BN',
  'BI',
  'KH',
  'CM',
  'TD',
  'KM',
  'GQ',
  'SZ',
  'GA',
  'GN',
  'KG',
  'LA',
  'MO',
  'MR',
  'MN',
  'NP',
  'RW',
  'TG',
  'UZ',
  'ZW',
  'BJ',
  'MG',
  'MU',
  'MZ',
  'AO',
  'CI',
  'DJ',
  'ZM',
  'CD',
  'CG',
  'IQ',
  'LY',
  'TJ',
  'VE',
  'ET',
  'XK'],
 'disc_number': 1,
 'duration_ms': 209466,
 'explicit': False,
 'external_ids': {'isrc': 'USVPR0006995'},
 'external_urls': {'spotify': 'https://open.spotify.com/track/0ru8bc0XnKjUL2O1Fl1k7a'},
 'href': 'https://api.spotify.com/v1/tracks/0ru8bc0XnKjUL2O1Fl1k7a',
 'id': '0ru8bc0XnKjUL2O1Fl1k7a',
 'is_local': False,
 'is_playable': True,
 'name': 'Infiltrate',
 'popularity': 50,
 'preview_url': None,
 'track_number': 3,
 'type': 'track',
 'uri': 'spotify:track:0ru8bc0XnKjUL2O1Fl1k7a'}

In [32]:
for i in datos["tracks"]["items"][0]["album"]:
 print(i)

album_type
artists
available_markets
external_urls
href
id
images
is_playable
name
release_date
release_date_precision
total_tracks
type
uri

In [33]:
datos["tracks"]["items"][0]["album"]

{'album_type': 'album',
 'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/3Isy6kedDrgPYoTS1dazA9'},
   'href': 'https://api.spotify.com/v1/artists/3Isy6kedDrgPYoTS1dazA9',
   'id': '3Isy6kedDrgPYoTS1dazA9',
   'name': 'Sean Paul',
   'type': 'artist',
   'uri': 'spotify:artist:3Isy6kedDrgPYoTS1dazA9'}],
 'available_markets': ['AR',
  'AU',
  'AT',
  'BE',
  'BO',
  'BR',
  'BG',
  'CA',
  'CL',
  'CO',
  'CR',
  'CY',
  'CZ',
  'DK',
  'DO',
  'DE',
  'EC',
  'EE',
  'SV',
  'FI',
  'FR',
  'GR',
  'GT',
  'HN',
  'HK',
  'HU',
  'IS',
  'IE',
  'IT',
  'LV',
  'LT',
  'LU',
  'MY',
  'MT',
  'MX',
  'NL',
  'NZ',
  'NI',
  'NO',
  'PA',
  'PY',
  'PE',
  'PH',
  'PL',
  'PT',
  'SG',
  'SK',
  'ES',
  'SE',
  'CH',
  'TW',
  'TR',
  'UY',
  'US',
  'GB',
  'AD',
  'LI',
  'MC',
  'ID',
  'JP',
  'TH',
  'VN',
  'RO',
  'IL',
  'ZA',
  'SA',
  'AE',
  'BH',
  'QA',
  'OM',
  'KW',
  'EG',
  'MA',
  'DZ',
  'TN',
  'LB',
  'JO',
  'PS',
  'IN',
  'KZ',
  'MD',
  'UA',
  'AL',
  'BA',
  'HR',
  'ME',
  'MK',
  'RS',
  'SI',
  'KR',
  'BD',
  'PK',
  'LK',
  'GH',
  'KE',
  'NG',
  'TZ',
  'UG',
  'AG',
  'AM',
  'BS',
  'BB',
  'BZ',
  'BT',
  'BW',
  'BF',
  'CV',
  'CW',
  'DM',
  'FJ',
  'GM',
  'GE',
  'GD',
  'GW',
  'GY',
  'HT',
  'JM',
  'KI',
  'LS',
  'LR',
  'MW',
  'MV',
  'ML',
  'MH',
  'FM',
  'NA',
  'NR',
  'NE',
  'PW',
  'PG',
  'PR',
  'WS',
  'SM',
  'ST',
  'SN',
  'SC',
  'SL',
  'SB',
  'KN',
  'LC',
  'VC',
  'SR',
  'TL',
  'TO',
  'TT',
  'TV',
  'VU',
  'AZ',
  'BN',
  'BI',
  'KH',
  'CM',
  'TD',
  'KM',
  'GQ',
  'SZ',
  'GA',
  'GN',
  'KG',
  'LA',
  'MO',
  'MR',
  'MN',
  'NP',
  'RW',
  'TG',
  'UZ',
  'ZW',
  'BJ',
  'MG',
  'MU',
  'MZ',
  'AO',
  'CI',
  'DJ',
  'ZM',
  'CD',
  'CG',
  'IQ',
  'LY',
  'TJ',
  'VE',
  'ET',
  'XK'],
 'external_urls': {'spotify': 'https://open.spotify.com/album/6Y5344aCqHNxQNAUStzHrd'},
 'href': 'https://api.spotify.com/v1/albums/6Y5344aCqHNxQNAUStzHrd',
 'id': '6Y5344aCqHNxQNAUStzHrd',
 'images': [{'height': 640,
   'width': 640,
   'url': 'https://i.scdn.co/image/ab67616d0000b27314f35992ffc62ef3d70705f8'},
  {'height': 300,
   'width': 300,
   'url': 'https://i.scdn.co/image/ab67616d00001e0214f35992ffc62ef3d70705f8'},
  {'height': 64,
   'width': 64,
   'url': 'https://i.scdn.co/image/ab67616d0000485114f35992ffc62ef3d70705f8'}],
 'is_playable': True,
 'name': 'Stage One',
 'release_date': '2000',
 'release_date_precision': 'year',
 'total_tracks': 25,
 'type': 'album',
 'uri': 'spotify:album:6Y5344aCqHNxQNAUStzHrd'}

In [34]:
datos["tracks"]["items"][0]["album"]["artists"]

[{'external_urls': {'spotify': 'https://open.spotify.com/artist/3Isy6kedDrgPYoTS1dazA9'},
  'href': 'https://api.spotify.com/v1/artists/3Isy6kedDrgPYoTS1dazA9',
  'id': '3Isy6kedDrgPYoTS1dazA9',
  'name': 'Sean Paul',
  'type': 'artist',
  'uri': 'spotify:artist:3Isy6kedDrgPYoTS1dazA9'}]

In [35]:
datos["tracks"]["items"][0]["album"]["artists"][0]

{'external_urls': {'spotify': 'https://open.spotify.com/artist/3Isy6kedDrgPYoTS1dazA9'},
 'href': 'https://api.spotify.com/v1/artists/3Isy6kedDrgPYoTS1dazA9',
 'id': '3Isy6kedDrgPYoTS1dazA9',
 'name': 'Sean Paul',
 'type': 'artist',
 'uri': 'spotify:artist:3Isy6kedDrgPYoTS1dazA9'}

In [36]:
datos["tracks"]["items"][0]["album"]["artists"][0]['external_urls']

{'spotify': 'https://open.spotify.com/artist/3Isy6kedDrgPYoTS1dazA9'}

In [37]:
datos["tracks"]["items"][0]["album"]["artists"][0]['external_urls']['spotify']

'https://open.spotify.com/artist/3Isy6kedDrgPYoTS1dazA9'

In [38]:
for track in datos['tracks']['items']:
    print(track['name'], track['popularity'])
tracks = datos['tracks']['items']
tracks_sorted = sorted(tracks, key=lambda t: t['popularity'], reverse=True)

for t in tracks_sorted:
    print(f"{t['name']} - Popularidad: {t['popularity']}")

    # Extraer indice de popularidad

Infiltrate 50
Deport Them 51
Luv Me, Luv Me 52
Um Anjo do Céu 61
Verde, Amarillo Y Rojo 54
Caminando 51
Here I Am (Come And Take Me) 55
Señorita a Mi Me Gusta Su Style 53
Jah Jah City 47
Humble African 47
Violencia Machista 33
De Mi Mente 54
ETTs 31
If It Happens Again 48
Kingston Town 50
Mestizaje 48
Ghost Town 67
(I Can't Help) Falling In Love With You 50
Tell Me Is It True 46
The Way You Do The Things You Do 49
Light My Fire 45
Lucrecia 34
Dulce Amor (Sólo Un Latido) 52
La Mosca Cojonera 35
Aire 57
99 Red Balloons 61
I Got You Babe 51
Lovers Rock 68
Antonia 60
Naval Xixon 37
Why Am I A Rastaman? 49
Rat In Mi Kitchen 40
A la Mierda 51
King 41
Bring Me Your Cup - Edit 41
Watchdogs 43
Derecho De Admision 39
I Got You Babe 43
Higher Ground 44
Red Red Wine 47
Eres Un@ Mas 43
Planeta Eskoria 45
Kingston Town 47
Tio Sam 43
Bring Me Your Cup - Edit 57
Sin Ti 35
Vergüenza 46
(I Can't Help) Falling In Love With You 44
Red Red Wine 73
Angel 78
Angel - Popularidad: 78
Red Red Wine - Popularidad: 73
Lovers Rock - Popularidad: 68
Ghost Town - Popularidad: 67
Um Anjo do Céu - Popularidad: 61
99 Red Balloons - Popularidad: 61
Antonia - Popularidad: 60
Aire - Popularidad: 57
Bring Me Your Cup - Edit - Popularidad: 57
Here I Am (Come And Take Me) - Popularidad: 55
Verde, Amarillo Y Rojo - Popularidad: 54
De Mi Mente - Popularidad: 54
Señorita a Mi Me Gusta Su Style - Popularidad: 53
Luv Me, Luv Me - Popularidad: 52
Dulce Amor (Sólo Un Latido) - Popularidad: 52
Deport Them - Popularidad: 51
Caminando - Popularidad: 51
I Got You Babe - Popularidad: 51
A la Mierda - Popularidad: 51
Infiltrate - Popularidad: 50
Kingston Town - Popularidad: 50
(I Can't Help) Falling In Love With You - Popularidad: 50
The Way You Do The Things You Do - Popularidad: 49
Why Am I A Rastaman? - Popularidad: 49
If It Happens Again - Popularidad: 48
Mestizaje - Popularidad: 48
Jah Jah City - Popularidad: 47
Humble African - Popularidad: 47
Red Red Wine - Popularidad: 47
Kingston Town - Popularidad: 47
Tell Me Is It True - Popularidad: 46
Vergüenza - Popularidad: 46
Light My Fire - Popularidad: 45
Planeta Eskoria - Popularidad: 45
Higher Ground - Popularidad: 44
(I Can't Help) Falling In Love With You - Popularidad: 44
Watchdogs - Popularidad: 43
I Got You Babe - Popularidad: 43
Eres Un@ Mas - Popularidad: 43
Tio Sam - Popularidad: 43
King - Popularidad: 41
Bring Me Your Cup - Edit - Popularidad: 41
Rat In Mi Kitchen - Popularidad: 40
Derecho De Admision - Popularidad: 39
Naval Xixon - Popularidad: 37
La Mosca Cojonera - Popularidad: 35
Sin Ti - Popularidad: 35
Lucrecia - Popularidad: 34
Violencia Machista - Popularidad: 33
ETTs - Popularidad: 31

In [39]:
for dato in datos['tracks']['items']:
    artista = dato['artists'][0]['name']
    nombre = dato['name']
    tipo = dato['type']
    ano = dato['album']['release_date']
    spotify_id = dato['id']
    print({'Artista': artista,'Género': 'rock','Tipo': tipo,'Nombre': nombre,'Año': ano,'ID': spotify_id})
    break

{'Artista': 'Sean Paul', 'Género': 'rock', 'Tipo': 'track', 'Nombre': 'Infiltrate', 'Año': '2000', 'ID': '0ru8bc0XnKjUL2O1Fl1k7a'}

In [40]:
for dato in datos['tracks']['items']:
    artista = dato['artists'][0]['name']
    nombre = dato['name']
    tipo = dato['type']
    ano = dato['album']['release_date']
    spotify_id = dato['id']
    print({'Artista': artista,'Género': 'rock','Tipo': tipo,'Nombre': nombre,'Año': ano,'ID': spotify_id})

{'Artista': 'Sean Paul', 'Género': 'rock', 'Tipo': 'track', 'Nombre': 'Infiltrate', 'Año': '2000', 'ID': '0ru8bc0XnKjUL2O1Fl1k7a'}
{'Artista': 'Sean Paul', 'Género': 'rock', 'Tipo': 'track', 'Nombre': 'Deport Them', 'Año': '2000', 'ID': '5KhypMVGqMI9mgsrrv2lxc'}
{'Artista': 'Shaggy', 'Género': 'rock', 'Tipo': 'track', 'Nombre': 'Luv Me, Luv Me', 'Año': '2000-08-08', 'ID': '7hV4x7PMKGC4qD3NWLt2UJ'}
{'Artista': 'Maskavo', 'Género': 'rock', 'Tipo': 'track', 'Nombre': 'Um Anjo do Céu', 'Año': '2000', 'ID': '2YgAAAq8h7nPIMVLVVSHtK'}
{'Artista': 'Gondwana', 'Género': 'rock', 'Tipo': 'track', 'Nombre': 'Verde, Amarillo Y Rojo', 'Año': '2000', 'ID': '4Q0y0SOAJ84PvR2Uu6tGXv'}
{'Artista': 'Ganja', 'Género': 'rock', 'Tipo': 'track', 'Nombre': 'Caminando', 'Año': '2000-10-27', 'ID': '5hirK8wva1Nh38fVwWdLlc'}
{'Artista': 'UB40', 'Género': 'rock', 'Tipo': 'track', 'Nombre': 'Here I Am (Come And Take Me)', 'Año': '2000', 'ID': '6YR2MkzMhojHBmW1TbXtZO'}
{'Artista': 'Los Rabanes', 'Género': 'rock', 'Tipo': 'track', 'Nombre': 'Señorita a Mi Me Gusta Su Style', 'Año': '2000-04-06', 'ID': '2jvsbpAxcBkFp6VScarkzT'}
{'Artista': 'Capleton', 'Género': 'rock', 'Tipo': 'track', 'Nombre': 'Jah Jah City', 'Año': '2000-05-16', 'ID': '1QwrhGl2I3D0aNdRQ5YFtm'}
{'Artista': 'Culture', 'Género': 'rock', 'Tipo': 'track', 'Nombre': 'Humble African', 'Año': '2000', 'ID': '0Vzgfs70Aavn0nKDMmJCG8'}
{'Artista': 'Ska-P', 'Género': 'rock', 'Tipo': 'track', 'Nombre': 'Violencia Machista', 'Año': '2000-10-09', 'ID': '2ajDO2C9UGwKJrU2uIWoLE'}
{'Artista': 'Los Cafres', 'Género': 'rock', 'Tipo': 'track', 'Nombre': 'De Mi Mente', 'Año': '2000-09-02', 'ID': '1b8V0hvwAP8dO4xxrvvoXK'}
{'Artista': 'Ska-P', 'Género': 'rock', 'Tipo': 'track', 'Nombre': 'ETTs', 'Año': '2000-10-09', 'ID': '5fSS4Ohnt5GHIVY6Ypi3rH'}
{'Artista': 'UB40', 'Género': 'rock', 'Tipo': 'track', 'Nombre': 'If It Happens Again', 'Año': '2000', 'ID': '4snAWp4mA5DFa2plpH6ch7'}
{'Artista': 'UB40', 'Género': 'rock', 'Tipo': 'track', 'Nombre': 'Kingston Town', 'Año': '2000', 'ID': '1YGh2uqJYfSpFQ3DDnMJV5'}
{'Artista': 'Ska-P', 'Género': 'rock', 'Tipo': 'track', 'Nombre': 'Mestizaje', 'Año': '2000-10-09', 'ID': '2FtUCcJTBE2bb0mdZtzlFI'}
{'Artista': 'The Specials', 'Género': 'rock', 'Tipo': 'track', 'Nombre': 'Ghost Town', 'Año': '2000-08-21', 'ID': '6ewN9MaFbi78oDLT9wYDgn'}
{'Artista': 'UB40', 'Género': 'rock', 'Tipo': 'track', 'Nombre': "(I Can't Help) Falling In Love With You", 'Año': '2000', 'ID': '7aR1QwbQa26sjDXiVMLik4'}
{'Artista': 'UB40', 'Género': 'rock', 'Tipo': 'track', 'Nombre': 'Tell Me Is It True', 'Año': '2000', 'ID': '2VAIOwbPEFlIA0DpFo4RwA'}
{'Artista': 'UB40', 'Género': 'rock', 'Tipo': 'track', 'Nombre': 'The Way You Do The Things You Do', 'Año': '2000', 'ID': '42HaJ7QlInzQ5vHKWb5Ixa'}
{'Artista': 'UB40', 'Género': 'rock', 'Tipo': 'track', 'Nombre': 'Light My Fire', 'Año': '2000', 'ID': '2pcEb3qZ85Zdegn1cowQNu'}
{'Artista': 'Ska-P', 'Género': 'rock', 'Tipo': 'track', 'Nombre': 'Lucrecia', 'Año': '2000-10-09', 'ID': '1MKZIXBpF3K4FzXthCuzyQ'}
{'Artista': 'Gondwana', 'Género': 'rock', 'Tipo': 'track', 'Nombre': 'Dulce Amor (Sólo Un Latido)', 'Año': '2000', 'ID': '23d6sogOKvZOx7XtSEeNVs'}
{'Artista': 'Ska-P', 'Género': 'rock', 'Tipo': 'track', 'Nombre': 'La Mosca Cojonera', 'Año': '2000-10-09', 'ID': '3wms72Uwbi40KXE3moX3cf'}
{'Artista': 'Los Cafres', 'Género': 'rock', 'Tipo': 'track', 'Nombre': 'Aire', 'Año': '2000-09-02', 'ID': '2hkJ7fYPM5V27pjxiPG2gg'}
{'Artista': 'Goldfinger', 'Género': 'rock', 'Tipo': 'track', 'Nombre': '99 Red Balloons', 'Año': '2000-03-28', 'ID': '0rOTMSSa6yscfOrGnzfheM'}
{'Artista': 'UB40', 'Género': 'rock', 'Tipo': 'track', 'Nombre': 'I Got You Babe', 'Año': '2000', 'ID': '3UNa2iZNHZ8cDvzXSNVrUZ'}
{'Artista': 'Sade', 'Género': 'rock', 'Tipo': 'track', 'Nombre': 'Lovers Rock', 'Año': '2000-11-13', 'ID': '77lKjGkhvWuimTzQxA4STK'}
{'Artista': 'Gondwana', 'Género': 'rock', 'Tipo': 'track', 'Nombre': 'Antonia', 'Año': '2000', 'ID': '51LZ2XHdETvNLQ6SKqTjWF'}
{'Artista': 'Ska-P', 'Género': 'rock', 'Tipo': 'track', 'Nombre': 'Naval Xixon', 'Año': '2000-10-09', 'ID': '13ZYIzN5q2xJ04VCWcN6zg'}
{'Artista': 'Culture', 'Género': 'rock', 'Tipo': 'track', 'Nombre': 'Why Am I A Rastaman?', 'Año': '2000', 'ID': '41r3Hd6pRHg4YKA6cACcDQ'}
{'Artista': 'UB40', 'Género': 'rock', 'Tipo': 'track', 'Nombre': 'Rat In Mi Kitchen', 'Año': '2000', 'ID': '2ojhyfZMmaXQFqA1YLofwo'}
{'Artista': 'Ska-P', 'Género': 'rock', 'Tipo': 'track', 'Nombre': 'A la Mierda', 'Año': '2000-10-09', 'ID': '4GERduHBPVmh9ECjBtEPA4'}
{'Artista': 'UB40', 'Género': 'rock', 'Tipo': 'track', 'Nombre': 'King', 'Año': '2000', 'ID': '2f4J3ZsIqKHDzTVWKaagte'}
{'Artista': 'UB40', 'Género': 'rock', 'Tipo': 'track', 'Nombre': 'Bring Me Your Cup - Edit', 'Año': '2000', 'ID': '2xzpFiJhL9E8fRwdI7PPHI'}
{'Artista': 'UB40', 'Género': 'rock', 'Tipo': 'track', 'Nombre': 'Watchdogs', 'Año': '2000', 'ID': '3n83MHEFQnZa5VNJzxIrzk'}
{'Artista': 'Ska-P', 'Género': 'rock', 'Tipo': 'track', 'Nombre': 'Derecho De Admision', 'Año': '2000-10-09', 'ID': '5fXxNenB01Y2BjqRlwJSnO'}
{'Artista': 'UB40', 'Género': 'rock', 'Tipo': 'track', 'Nombre': 'I Got You Babe', 'Año': '2000', 'ID': '1dm4aH91JXQpQ0aYWp7xoQ'}
{'Artista': 'UB40', 'Género': 'rock', 'Tipo': 'track', 'Nombre': 'Higher Ground', 'Año': '2000', 'ID': '62GbYylTNfRNZnA4HbGaNP'}
{'Artista': 'UB40', 'Género': 'rock', 'Tipo': 'track', 'Nombre': 'Red Red Wine', 'Año': '2000', 'ID': '3dRmLxr7tXNsHWYJubwF6G'}
{'Artista': 'Ska-P', 'Género': 'rock', 'Tipo': 'track', 'Nombre': 'Eres Un@ Mas', 'Año': '2000-10-09', 'ID': '0awiprd9BQ4vXukC5aD6Nw'}
{'Artista': 'Ska-P', 'Género': 'rock', 'Tipo': 'track', 'Nombre': 'Planeta Eskoria', 'Año': '2000-10-09', 'ID': '1gU2mB0VSVvEe97g50QpYo'}
{'Artista': 'UB40', 'Género': 'rock', 'Tipo': 'track', 'Nombre': 'Kingston Town', 'Año': '2000', 'ID': '6MTLpOuPg9qfbiJpUXB5qh'}
{'Artista': 'Ska-P', 'Género': 'rock', 'Tipo': 'track', 'Nombre': 'Tio Sam', 'Año': '2000-10-09', 'ID': '3Re4NbN9tBTh7lwVDgcZ5V'}
{'Artista': 'UB40', 'Género': 'rock', 'Tipo': 'track', 'Nombre': 'Bring Me Your Cup - Edit', 'Año': '2000', 'ID': '0ffQpiShZZKtDN06L84FCJ'}
{'Artista': 'King Chango', 'Género': 'rock', 'Tipo': 'track', 'Nombre': 'Sin Ti', 'Año': '2000-01-01', 'ID': '3SPoI7e9GoO1gSOYXi0Fxo'}
{'Artista': 'Ska-P', 'Género': 'rock', 'Tipo': 'track', 'Nombre': 'Vergüenza', 'Año': '2000-10-09', 'ID': '2wOfJd9azprQrbE6uTJD6u'}
{'Artista': 'UB40', 'Género': 'rock', 'Tipo': 'track', 'Nombre': "(I Can't Help) Falling In Love With You", 'Año': '2000', 'ID': '18YJrsXwyJL7dqCtikZ3PU'}
{'Artista': 'UB40', 'Género': 'rock', 'Tipo': 'track', 'Nombre': 'Red Red Wine', 'Año': '2000', 'ID': '4uOKFydzAejjSFqYbv1XPt'}
{'Artista': 'Shaggy', 'Género': 'rock', 'Tipo': 'track', 'Nombre': 'Angel', 'Año': '2000-08-08', 'ID': '7FDV5ELOJHCGLe52AnttEd'}

In [41]:
listacanciones_reggae = []
for dato in datos['tracks']['items']:
    artista = dato['artists'][0]['name']
    nombre = dato['name']
    tipo = dato['type']
    ano = dato['album']['release_date']
    spotify_id = dato['id']
    datos_totales = (artista, nombre, tipo, ano, spotify_id)

    listacanciones_reggae.append({'Artista': artista,'Género': 'reggae','Tipo': tipo,'Nombre': nombre,'Año': ano,'ID': spotify_id}) #AÑADIR EL APPEND CON LA LISTA. HACER LA VARIABLE CON LA LISTA DE CANCIONES
print(listacanciones_reggae)
    #print({'Artista': artista,'Género': 'rock','Tipo': tipo,'Nombre': nombre,'Año': ano,'ID': spotify_id})

[{'Artista': 'Sean Paul', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Infiltrate', 'Año': '2000', 'ID': '0ru8bc0XnKjUL2O1Fl1k7a'}, {'Artista': 'Sean Paul', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Deport Them', 'Año': '2000', 'ID': '5KhypMVGqMI9mgsrrv2lxc'}, {'Artista': 'Shaggy', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Luv Me, Luv Me', 'Año': '2000-08-08', 'ID': '7hV4x7PMKGC4qD3NWLt2UJ'}, {'Artista': 'Maskavo', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Um Anjo do Céu', 'Año': '2000', 'ID': '2YgAAAq8h7nPIMVLVVSHtK'}, {'Artista': 'Gondwana', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Verde, Amarillo Y Rojo', 'Año': '2000', 'ID': '4Q0y0SOAJ84PvR2Uu6tGXv'}, {'Artista': 'Ganja', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Caminando', 'Año': '2000-10-27', 'ID': '5hirK8wva1Nh38fVwWdLlc'}, {'Artista': 'UB40', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Here I Am (Come And Take Me)', 'Año': '2000', 'ID': '6YR2MkzMhojHBmW1TbXtZO'}, {'Artista': 'Los Rabanes', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Señorita a Mi Me Gusta Su Style', 'Año': '2000-04-06', 'ID': '2jvsbpAxcBkFp6VScarkzT'}, {'Artista': 'Capleton', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Jah Jah City', 'Año': '2000-05-16', 'ID': '1QwrhGl2I3D0aNdRQ5YFtm'}, {'Artista': 'Culture', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Humble African', 'Año': '2000', 'ID': '0Vzgfs70Aavn0nKDMmJCG8'}, {'Artista': 'Ska-P', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Violencia Machista', 'Año': '2000-10-09', 'ID': '2ajDO2C9UGwKJrU2uIWoLE'}, {'Artista': 'Los Cafres', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'De Mi Mente', 'Año': '2000-09-02', 'ID': '1b8V0hvwAP8dO4xxrvvoXK'}, {'Artista': 'Ska-P', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'ETTs', 'Año': '2000-10-09', 'ID': '5fSS4Ohnt5GHIVY6Ypi3rH'}, {'Artista': 'UB40', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'If It Happens Again', 'Año': '2000', 'ID': '4snAWp4mA5DFa2plpH6ch7'}, {'Artista': 'UB40', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Kingston Town', 'Año': '2000', 'ID': '1YGh2uqJYfSpFQ3DDnMJV5'}, {'Artista': 'Ska-P', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Mestizaje', 'Año': '2000-10-09', 'ID': '2FtUCcJTBE2bb0mdZtzlFI'}, {'Artista': 'The Specials', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Ghost Town', 'Año': '2000-08-21', 'ID': '6ewN9MaFbi78oDLT9wYDgn'}, {'Artista': 'UB40', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': "(I Can't Help) Falling In Love With You", 'Año': '2000', 'ID': '7aR1QwbQa26sjDXiVMLik4'}, {'Artista': 'UB40', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Tell Me Is It True', 'Año': '2000', 'ID': '2VAIOwbPEFlIA0DpFo4RwA'}, {'Artista': 'UB40', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'The Way You Do The Things You Do', 'Año': '2000', 'ID': '42HaJ7QlInzQ5vHKWb5Ixa'}, {'Artista': 'UB40', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Light My Fire', 'Año': '2000', 'ID': '2pcEb3qZ85Zdegn1cowQNu'}, {'Artista': 'Ska-P', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Lucrecia', 'Año': '2000-10-09', 'ID': '1MKZIXBpF3K4FzXthCuzyQ'}, {'Artista': 'Gondwana', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Dulce Amor (Sólo Un Latido)', 'Año': '2000', 'ID': '23d6sogOKvZOx7XtSEeNVs'}, {'Artista': 'Ska-P', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'La Mosca Cojonera', 'Año': '2000-10-09', 'ID': '3wms72Uwbi40KXE3moX3cf'}, {'Artista': 'Los Cafres', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Aire', 'Año': '2000-09-02', 'ID': '2hkJ7fYPM5V27pjxiPG2gg'}, {'Artista': 'Goldfinger', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': '99 Red Balloons', 'Año': '2000-03-28', 'ID': '0rOTMSSa6yscfOrGnzfheM'}, {'Artista': 'UB40', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'I Got You Babe', 'Año': '2000', 'ID': '3UNa2iZNHZ8cDvzXSNVrUZ'}, {'Artista': 'Sade', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Lovers Rock', 'Año': '2000-11-13', 'ID': '77lKjGkhvWuimTzQxA4STK'}, {'Artista': 'Gondwana', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Antonia', 'Año': '2000', 'ID': '51LZ2XHdETvNLQ6SKqTjWF'}, {'Artista': 'Ska-P', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Naval Xixon', 'Año': '2000-10-09', 'ID': '13ZYIzN5q2xJ04VCWcN6zg'}, {'Artista': 'Culture', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Why Am I A Rastaman?', 'Año': '2000', 'ID': '41r3Hd6pRHg4YKA6cACcDQ'}, {'Artista': 'UB40', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Rat In Mi Kitchen', 'Año': '2000', 'ID': '2ojhyfZMmaXQFqA1YLofwo'}, {'Artista': 'Ska-P', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'A la Mierda', 'Año': '2000-10-09', 'ID': '4GERduHBPVmh9ECjBtEPA4'}, {'Artista': 'UB40', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'King', 'Año': '2000', 'ID': '2f4J3ZsIqKHDzTVWKaagte'}, {'Artista': 'UB40', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Bring Me Your Cup - Edit', 'Año': '2000', 'ID': '2xzpFiJhL9E8fRwdI7PPHI'}, {'Artista': 'UB40', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Watchdogs', 'Año': '2000', 'ID': '3n83MHEFQnZa5VNJzxIrzk'}, {'Artista': 'Ska-P', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Derecho De Admision', 'Año': '2000-10-09', 'ID': '5fXxNenB01Y2BjqRlwJSnO'}, {'Artista': 'UB40', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'I Got You Babe', 'Año': '2000', 'ID': '1dm4aH91JXQpQ0aYWp7xoQ'}, {'Artista': 'UB40', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Higher Ground', 'Año': '2000', 'ID': '62GbYylTNfRNZnA4HbGaNP'}, {'Artista': 'UB40', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Red Red Wine', 'Año': '2000', 'ID': '3dRmLxr7tXNsHWYJubwF6G'}, {'Artista': 'Ska-P', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Eres Un@ Mas', 'Año': '2000-10-09', 'ID': '0awiprd9BQ4vXukC5aD6Nw'}, {'Artista': 'Ska-P', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Planeta Eskoria', 'Año': '2000-10-09', 'ID': '1gU2mB0VSVvEe97g50QpYo'}, {'Artista': 'UB40', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Kingston Town', 'Año': '2000', 'ID': '6MTLpOuPg9qfbiJpUXB5qh'}, {'Artista': 'Ska-P', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Tio Sam', 'Año': '2000-10-09', 'ID': '3Re4NbN9tBTh7lwVDgcZ5V'}, {'Artista': 'UB40', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Bring Me Your Cup - Edit', 'Año': '2000', 'ID': '0ffQpiShZZKtDN06L84FCJ'}, {'Artista': 'King Chango', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Sin Ti', 'Año': '2000-01-01', 'ID': '3SPoI7e9GoO1gSOYXi0Fxo'}, {'Artista': 'Ska-P', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Vergüenza', 'Año': '2000-10-09', 'ID': '2wOfJd9azprQrbE6uTJD6u'}, {'Artista': 'UB40', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': "(I Can't Help) Falling In Love With You", 'Año': '2000', 'ID': '18YJrsXwyJL7dqCtikZ3PU'}, {'Artista': 'UB40', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Red Red Wine', 'Año': '2000', 'ID': '4uOKFydzAejjSFqYbv1XPt'}, {'Artista': 'Shaggy', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Angel', 'Año': '2000-08-08', 'ID': '7FDV5ELOJHCGLe52AnttEd'}]

In [42]:
for diccionario in listacanciones_reggae:
    print (diccionario)

{'Artista': 'Sean Paul', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Infiltrate', 'Año': '2000', 'ID': '0ru8bc0XnKjUL2O1Fl1k7a'}
{'Artista': 'Sean Paul', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Deport Them', 'Año': '2000', 'ID': '5KhypMVGqMI9mgsrrv2lxc'}
{'Artista': 'Shaggy', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Luv Me, Luv Me', 'Año': '2000-08-08', 'ID': '7hV4x7PMKGC4qD3NWLt2UJ'}
{'Artista': 'Maskavo', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Um Anjo do Céu', 'Año': '2000', 'ID': '2YgAAAq8h7nPIMVLVVSHtK'}
{'Artista': 'Gondwana', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Verde, Amarillo Y Rojo', 'Año': '2000', 'ID': '4Q0y0SOAJ84PvR2Uu6tGXv'}
{'Artista': 'Ganja', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Caminando', 'Año': '2000-10-27', 'ID': '5hirK8wva1Nh38fVwWdLlc'}
{'Artista': 'UB40', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Here I Am (Come And Take Me)', 'Año': '2000', 'ID': '6YR2MkzMhojHBmW1TbXtZO'}
{'Artista': 'Los Rabanes', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Señorita a Mi Me Gusta Su Style', 'Año': '2000-04-06', 'ID': '2jvsbpAxcBkFp6VScarkzT'}
{'Artista': 'Capleton', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Jah Jah City', 'Año': '2000-05-16', 'ID': '1QwrhGl2I3D0aNdRQ5YFtm'}
{'Artista': 'Culture', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Humble African', 'Año': '2000', 'ID': '0Vzgfs70Aavn0nKDMmJCG8'}
{'Artista': 'Ska-P', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Violencia Machista', 'Año': '2000-10-09', 'ID': '2ajDO2C9UGwKJrU2uIWoLE'}
{'Artista': 'Los Cafres', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'De Mi Mente', 'Año': '2000-09-02', 'ID': '1b8V0hvwAP8dO4xxrvvoXK'}
{'Artista': 'Ska-P', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'ETTs', 'Año': '2000-10-09', 'ID': '5fSS4Ohnt5GHIVY6Ypi3rH'}
{'Artista': 'UB40', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'If It Happens Again', 'Año': '2000', 'ID': '4snAWp4mA5DFa2plpH6ch7'}
{'Artista': 'UB40', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Kingston Town', 'Año': '2000', 'ID': '1YGh2uqJYfSpFQ3DDnMJV5'}
{'Artista': 'Ska-P', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Mestizaje', 'Año': '2000-10-09', 'ID': '2FtUCcJTBE2bb0mdZtzlFI'}
{'Artista': 'The Specials', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Ghost Town', 'Año': '2000-08-21', 'ID': '6ewN9MaFbi78oDLT9wYDgn'}
{'Artista': 'UB40', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': "(I Can't Help) Falling In Love With You", 'Año': '2000', 'ID': '7aR1QwbQa26sjDXiVMLik4'}
{'Artista': 'UB40', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Tell Me Is It True', 'Año': '2000', 'ID': '2VAIOwbPEFlIA0DpFo4RwA'}
{'Artista': 'UB40', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'The Way You Do The Things You Do', 'Año': '2000', 'ID': '42HaJ7QlInzQ5vHKWb5Ixa'}
{'Artista': 'UB40', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Light My Fire', 'Año': '2000', 'ID': '2pcEb3qZ85Zdegn1cowQNu'}
{'Artista': 'Ska-P', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Lucrecia', 'Año': '2000-10-09', 'ID': '1MKZIXBpF3K4FzXthCuzyQ'}
{'Artista': 'Gondwana', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Dulce Amor (Sólo Un Latido)', 'Año': '2000', 'ID': '23d6sogOKvZOx7XtSEeNVs'}
{'Artista': 'Ska-P', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'La Mosca Cojonera', 'Año': '2000-10-09', 'ID': '3wms72Uwbi40KXE3moX3cf'}
{'Artista': 'Los Cafres', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Aire', 'Año': '2000-09-02', 'ID': '2hkJ7fYPM5V27pjxiPG2gg'}
{'Artista': 'Goldfinger', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': '99 Red Balloons', 'Año': '2000-03-28', 'ID': '0rOTMSSa6yscfOrGnzfheM'}
{'Artista': 'UB40', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'I Got You Babe', 'Año': '2000', 'ID': '3UNa2iZNHZ8cDvzXSNVrUZ'}
{'Artista': 'Sade', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Lovers Rock', 'Año': '2000-11-13', 'ID': '77lKjGkhvWuimTzQxA4STK'}
{'Artista': 'Gondwana', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Antonia', 'Año': '2000', 'ID': '51LZ2XHdETvNLQ6SKqTjWF'}
{'Artista': 'Ska-P', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Naval Xixon', 'Año': '2000-10-09', 'ID': '13ZYIzN5q2xJ04VCWcN6zg'}
{'Artista': 'Culture', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Why Am I A Rastaman?', 'Año': '2000', 'ID': '41r3Hd6pRHg4YKA6cACcDQ'}
{'Artista': 'UB40', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Rat In Mi Kitchen', 'Año': '2000', 'ID': '2ojhyfZMmaXQFqA1YLofwo'}
{'Artista': 'Ska-P', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'A la Mierda', 'Año': '2000-10-09', 'ID': '4GERduHBPVmh9ECjBtEPA4'}
{'Artista': 'UB40', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'King', 'Año': '2000', 'ID': '2f4J3ZsIqKHDzTVWKaagte'}
{'Artista': 'UB40', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Bring Me Your Cup - Edit', 'Año': '2000', 'ID': '2xzpFiJhL9E8fRwdI7PPHI'}
{'Artista': 'UB40', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Watchdogs', 'Año': '2000', 'ID': '3n83MHEFQnZa5VNJzxIrzk'}
{'Artista': 'Ska-P', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Derecho De Admision', 'Año': '2000-10-09', 'ID': '5fXxNenB01Y2BjqRlwJSnO'}
{'Artista': 'UB40', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'I Got You Babe', 'Año': '2000', 'ID': '1dm4aH91JXQpQ0aYWp7xoQ'}
{'Artista': 'UB40', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Higher Ground', 'Año': '2000', 'ID': '62GbYylTNfRNZnA4HbGaNP'}
{'Artista': 'UB40', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Red Red Wine', 'Año': '2000', 'ID': '3dRmLxr7tXNsHWYJubwF6G'}
{'Artista': 'Ska-P', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Eres Un@ Mas', 'Año': '2000-10-09', 'ID': '0awiprd9BQ4vXukC5aD6Nw'}
{'Artista': 'Ska-P', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Planeta Eskoria', 'Año': '2000-10-09', 'ID': '1gU2mB0VSVvEe97g50QpYo'}
{'Artista': 'UB40', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Kingston Town', 'Año': '2000', 'ID': '6MTLpOuPg9qfbiJpUXB5qh'}
{'Artista': 'Ska-P', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Tio Sam', 'Año': '2000-10-09', 'ID': '3Re4NbN9tBTh7lwVDgcZ5V'}
{'Artista': 'UB40', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Bring Me Your Cup - Edit', 'Año': '2000', 'ID': '0ffQpiShZZKtDN06L84FCJ'}
{'Artista': 'King Chango', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Sin Ti', 'Año': '2000-01-01', 'ID': '3SPoI7e9GoO1gSOYXi0Fxo'}
{'Artista': 'Ska-P', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Vergüenza', 'Año': '2000-10-09', 'ID': '2wOfJd9azprQrbE6uTJD6u'}
{'Artista': 'UB40', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': "(I Can't Help) Falling In Love With You", 'Año': '2000', 'ID': '18YJrsXwyJL7dqCtikZ3PU'}
{'Artista': 'UB40', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Red Red Wine', 'Año': '2000', 'ID': '4uOKFydzAejjSFqYbv1XPt'}
{'Artista': 'Shaggy', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Angel', 'Año': '2000-08-08', 'ID': '7FDV5ELOJHCGLe52AnttEd'}

In [43]:
#CREACIÓN DEL DATAFRAME
df_reggae = pd.DataFrame(listacanciones_reggae)

df_reggae

,Artista,Género,Tipo,Nombre,Año,ID
0,Sean Paul,reggae,track,Infiltrate,2000,0ru8bc0XnKjUL2O1Fl1k7a
1,Sean Paul,reggae,track,Deport Them,2000,5KhypMVGqMI9mgsrrv2lxc
2,Shaggy,reggae,track,"Luv Me, Luv Me",2000-08-08,7hV4x7PMKGC4qD3NWLt2UJ
3,Maskavo,reggae,track,Um Anjo do Céu,2000,2YgAAAq8h7nPIMVLVVSHtK
4,Gondwana,reggae,track,"Verde, Amarillo Y Rojo",2000,4Q0y0SOAJ84PvR2Uu6tGXv
5,Ganja,reggae,track,Caminando,2000-10-27,5hirK8wva1Nh38fVwWdLlc
6,UB40,reggae,track,Here I Am (Come And Take Me),2000,6YR2MkzMhojHBmW1TbXtZO
7,Los Rabanes,reggae,track,Señorita a Mi Me Gusta Su Style,2000-04-06,2jvsbpAxcBkFp6VScarkzT
8,Capleton,reggae,track,Jah Jah City,2000-05-16,1QwrhGl2I3D0aNdRQ5YFtm
9,Culture,reggae,track,Humble African,2000,0Vzgfs70Aavn0nKDMmJCG8
10,Ska-P,reggae,track,Violencia Machista,2000-10-09,2ajDO2C9UGwKJrU2uIWoLE
11,Los Cafres,reggae,track,De Mi Mente,2000-09-02,1b8V0hvwAP8dO4xxrvvoXK
12,Ska-P,reggae,track,ETTs,2000-10-09,5fSS4Ohnt5GHIVY6Ypi3rH
13,UB40,reggae,track,If It Happens Again,2000,4snAWp4mA5DFa2plpH6ch7
14,UB40,reggae,track,Kingston Town,2000,1YGh2uqJYfSpFQ3DDnMJV5
15,Ska-P,reggae,track,Mestizaje,2000-10-09,2FtUCcJTBE2bb0mdZtzlFI
16,The Specials,reggae,track,Ghost Town,2000-08-21,6ewN9MaFbi78oDLT9wYDgn
17,UB40,reggae,track,(I Can't Help) Falling In Love With You,2000,7aR1QwbQa26sjDXiVMLik4
18,UB40,reggae,track,Tell Me Is It True,2000,2VAIOwbPEFlIA0DpFo4RwA
19,UB40,reggae,track,The Way You Do The Things You Do,2000,42HaJ7QlInzQ5vHKWb5Ixa
20,UB40,reggae,track,Light My Fire,2000,2pcEb3qZ85Zdegn1cowQNu
21,Ska-P,reggae,track,Lucrecia,2000-10-09,1MKZIXBpF3K4FzXthCuzyQ
22,Gondwana,reggae,track,Dulce Amor (Sólo Un Latido),2000,23d6sogOKvZOx7XtSEeNVs
23,Ska-P,reggae,track,La Mosca Cojonera,2000-10-09,3wms72Uwbi40KXE3moX3cf
24,Los Cafres,reggae,track,Aire,2000-09-02,2hkJ7fYPM5V27pjxiPG2gg
25,Goldfinger,reggae,track,99 Red Balloons,2000-03-28,0rOTMSSa6yscfOrGnzfheM
26,UB40,reggae,track,I Got You Babe,2000,3UNa2iZNHZ8cDvzXSNVrUZ
27,Sade,reggae,track,Lovers Rock,2000-11-13,77lKjGkhvWuimTzQxA4STK
28,Gondwana,reggae,track,Antonia,2000,51LZ2XHdETvNLQ6SKqTjWF
29,Ska-P,reggae,track,Naval Xixon,2000-10-09,13ZYIzN5q2xJ04VCWcN6zg
30,Culture,reggae,track,Why Am I A Rastaman?,2000,41r3Hd6pRHg4YKA6cACcDQ
31,UB40,reggae,track,Rat In Mi Kitchen,2000,2ojhyfZMmaXQFqA1YLofwo
32,Ska-P,reggae,track,A la Mierda,2000-10-09,4GERduHBPVmh9ECjBtEPA4
33,UB40,reggae,track,King,2000,2f4J3ZsIqKHDzTVWKaagte
34,UB40,reggae,track,Bring Me Your Cup - Edit,2000,2xzpFiJhL9E8fRwdI7PPHI
35,UB40,reggae,track,Watchdogs,2000,3n83MHEFQnZa5VNJzxIrzk
36,Ska-P,reggae,track,Derecho De Admision,2000-10-09,5fXxNenB01Y2BjqRlwJSnO
37,UB40,reggae,track,I Got You Babe,2000,1dm4aH91JXQpQ0aYWp7xoQ
38,UB40,reggae,track,Higher Ground,2000,62GbYylTNfRNZnA4HbGaNP
39,UB40,reggae,track,Red Red Wine,2000,3dRmLxr7tXNsHWYJubwF6G
40,Ska-P,reggae,track,Eres Un@ Mas,2000-10-09,0awiprd9BQ4vXukC5aD6Nw
41,Ska-P,reggae,track,Planeta Eskoria,2000-10-09,1gU2mB0VSVvEe97g50QpYo
42,UB40,reggae,track,Kingston Town,2000,6MTLpOuPg9qfbiJpUXB5qh
43,Ska-P,reggae,track,Tio Sam,2000-10-09,3Re4NbN9tBTh7lwVDgcZ5V
44,UB40,reggae,track,Bring Me Your Cup - Edit,2000,0ffQpiShZZKtDN06L84FCJ
45,King Chango,reggae,track,Sin Ti,2000-01-01,3SPoI7e9GoO1gSOYXi0Fxo
46,Ska-P,reggae,track,Vergüenza,2000-10-09,2wOfJd9azprQrbE6uTJD6u
47,UB40,reggae,track,(I Can't Help) Falling In Love With You,2000,18YJrsXwyJL7dqCtikZ3PU
48,UB40,reggae,track,Red Red Wine,2000,4uOKFydzAejjSFqYbv1XPt
49,Shaggy,reggae,track,Angel,2000-08-08,7FDV5ELOJHCGLe52AnttEd

In [44]:
for año in range(2000, 2005):
    for cancion in range (0,150,50):
        q=f"genre:raggae, year:{año}"
    print(q)

genre:raggae, year:2000
genre:raggae, year:2001
genre:raggae, year:2002
genre:raggae, year:2003
genre:raggae, year:2004

In [45]:
listacanciones_reggae = []
for anio in range (2000, 2005):
    for offset in range (0,150,50):
     datos = sp.search(q=f"genre:reggae, year:{anio}", type="track", limit=50, offset=offset)

     for dato in datos['tracks']['items']:
         artista = dato['artists'][0]['name']
         genero = 'latin pop'
         nombre = dato['name']
         tipo = dato['type']
         anio = dato['album']['release_date'][:4]
         spotify_id = dato['id']
       
         informacion_artista = {'Artista': artista, 'Género': 'reggae', 'Tipo': tipo, 'Nombre': nombre, 'Año': ano,'ID': spotify_id} 

         listacanciones_reggae.append(informacion_artista)

print(listacanciones_reggae)

[{'Artista': 'Sean Paul', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Infiltrate', 'Año': '2000-08-08', 'ID': '0ru8bc0XnKjUL2O1Fl1k7a'}, {'Artista': 'Sean Paul', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Deport Them', 'Año': '2000-08-08', 'ID': '5KhypMVGqMI9mgsrrv2lxc'}, {'Artista': 'Shaggy', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Luv Me, Luv Me', 'Año': '2000-08-08', 'ID': '7hV4x7PMKGC4qD3NWLt2UJ'}, {'Artista': 'Maskavo', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Um Anjo do Céu', 'Año': '2000-08-08', 'ID': '2YgAAAq8h7nPIMVLVVSHtK'}, {'Artista': 'Gondwana', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Verde, Amarillo Y Rojo', 'Año': '2000-08-08', 'ID': '4Q0y0SOAJ84PvR2Uu6tGXv'}, {'Artista': 'Ganja', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Caminando', 'Año': '2000-08-08', 'ID': '5hirK8wva1Nh38fVwWdLlc'}, {'Artista': 'UB40', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Here I Am (Come And Take Me)', 'Año': '2000-08-08', 'ID': '6YR2MkzMhojHBmW1TbXtZO'}, {'Artista': 'Los Rabanes', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Señorita a Mi Me Gusta Su Style', 'Año': '2000-08-08', 'ID': '2jvsbpAxcBkFp6VScarkzT'}, {'Artista': 'Capleton', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Jah Jah City', 'Año': '2000-08-08', 'ID': '1QwrhGl2I3D0aNdRQ5YFtm'}, {'Artista': 'Culture', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Humble African', 'Año': '2000-08-08', 'ID': '0Vzgfs70Aavn0nKDMmJCG8'}, {'Artista': 'Ska-P', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Violencia Machista', 'Año': '2000-08-08', 'ID': '2ajDO2C9UGwKJrU2uIWoLE'}, {'Artista': 'Los Cafres', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'De Mi Mente', 'Año': '2000-08-08', 'ID': '1b8V0hvwAP8dO4xxrvvoXK'}, {'Artista': 'Ska-P', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'ETTs', 'Año': '2000-08-08', 'ID': '5fSS4Ohnt5GHIVY6Ypi3rH'}, {'Artista': 'UB40', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'If It Happens Again', 'Año': '2000-08-08', 'ID': '4snAWp4mA5DFa2plpH6ch7'}, {'Artista': 'UB40', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Kingston Town', 'Año': '2000-08-08', 'ID': '1YGh2uqJYfSpFQ3DDnMJV5'}, {'Artista': 'Ska-P', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Mestizaje', 'Año': '2000-08-08', 'ID': '2FtUCcJTBE2bb0mdZtzlFI'}, {'Artista': 'The Specials', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Ghost Town', 'Año': '2000-08-08', 'ID': '6ewN9MaFbi78oDLT9wYDgn'}, {'Artista': 'UB40', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': "(I Can't Help) Falling In Love With You", 'Año': '2000-08-08', 'ID': '7aR1QwbQa26sjDXiVMLik4'}, {'Artista': 'UB40', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Tell Me Is It True', 'Año': '2000-08-08', 'ID': '2VAIOwbPEFlIA0DpFo4RwA'}, {'Artista': 'UB40', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'The Way You Do The Things You Do', 'Año': '2000-08-08', 'ID': '42HaJ7QlInzQ5vHKWb5Ixa'}, {'Artista': 'UB40', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Light My Fire', 'Año': '2000-08-08', 'ID': '2pcEb3qZ85Zdegn1cowQNu'}, {'Artista': 'Ska-P', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Lucrecia', 'Año': '2000-08-08', 'ID': '1MKZIXBpF3K4FzXthCuzyQ'}, {'Artista': 'Gondwana', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Dulce Amor (Sólo Un Latido)', 'Año': '2000-08-08', 'ID': '23d6sogOKvZOx7XtSEeNVs'}, {'Artista': 'Ska-P', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'La Mosca Cojonera', 'Año': '2000-08-08', 'ID': '3wms72Uwbi40KXE3moX3cf'}, {'Artista': 'Los Cafres', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Aire', 'Año': '2000-08-08', 'ID': '2hkJ7fYPM5V27pjxiPG2gg'}, {'Artista': 'Goldfinger', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': '99 Red Balloons', 'Año': '2000-08-08', 'ID': '0rOTMSSa6yscfOrGnzfheM'}, {'Artista': 'UB40', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'I Got You Babe', 'Año': '2000-08-08', 'ID': '3UNa2iZNHZ8cDvzXSNVrUZ'}, {'Artista': 'Sade', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Lovers Rock', 'Año': '2000-08-08', 'ID': '77lKjGkhvWuimTzQxA4STK'}, {'Artista': 'Gondwana', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Antonia', 'Año': '2000-08-08', 'ID': '51LZ2XHdETvNLQ6SKqTjWF'}, {'Artista': 'Ska-P', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Naval Xixon', 'Año': '2000-08-08', 'ID': '13ZYIzN5q2xJ04VCWcN6zg'}, {'Artista': 'Culture', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Why Am I A Rastaman?', 'Año': '2000-08-08', 'ID': '41r3Hd6pRHg4YKA6cACcDQ'}, {'Artista': 'UB40', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Rat In Mi Kitchen', 'Año': '2000-08-08', 'ID': '2ojhyfZMmaXQFqA1YLofwo'}, {'Artista': 'Ska-P', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'A la Mierda', 'Año': '2000-08-08', 'ID': '4GERduHBPVmh9ECjBtEPA4'}, {'Artista': 'UB40', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'King', 'Año': '2000-08-08', 'ID': '2f4J3ZsIqKHDzTVWKaagte'}, {'Artista': 'UB40', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Bring Me Your Cup - Edit', 'Año': '2000-08-08', 'ID': '2xzpFiJhL9E8fRwdI7PPHI'}, {'Artista': 'UB40', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Watchdogs', 'Año': '2000-08-08', 'ID': '3n83MHEFQnZa5VNJzxIrzk'}, {'Artista': 'Ska-P', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Derecho De Admision', 'Año': '2000-08-08', 'ID': '5fXxNenB01Y2BjqRlwJSnO'}, {'Artista': 'UB40', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'I Got You Babe', 'Año': '2000-08-08', 'ID': '1dm4aH91JXQpQ0aYWp7xoQ'}, {'Artista': 'UB40', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Higher Ground', 'Año': '2000-08-08', 'ID': '62GbYylTNfRNZnA4HbGaNP'}, {'Artista': 'UB40', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Red Red Wine', 'Año': '2000-08-08', 'ID': '3dRmLxr7tXNsHWYJubwF6G'}, {'Artista': 'Ska-P', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Eres Un@ Mas', 'Año': '2000-08-08', 'ID': '0awiprd9BQ4vXukC5aD6Nw'}, {'Artista': 'Ska-P', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Planeta Eskoria', 'Año': '2000-08-08', 'ID': '1gU2mB0VSVvEe97g50QpYo'}, {'Artista': 'UB40', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Kingston Town', 'Año': '2000-08-08', 'ID': '6MTLpOuPg9qfbiJpUXB5qh'}, {'Artista': 'Ska-P', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Tio Sam', 'Año': '2000-08-08', 'ID': '3Re4NbN9tBTh7lwVDgcZ5V'}, {'Artista': 'UB40', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Bring Me Your Cup - Edit', 'Año': '2000-08-08', 'ID': '0ffQpiShZZKtDN06L84FCJ'}, {'Artista': 'King Chango', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Sin Ti', 'Año': '2000-08-08', 'ID': '3SPoI7e9GoO1gSOYXi0Fxo'}, {'Artista': 'Ska-P', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Vergüenza', 'Año': '2000-08-08', 'ID': '2wOfJd9azprQrbE6uTJD6u'}, {'Artista': 'UB40', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': "(I Can't Help) Falling In Love With You", 'Año': '2000-08-08', 'ID': '18YJrsXwyJL7dqCtikZ3PU'}, {'Artista': 'UB40', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Red Red Wine', 'Año': '2000-08-08', 'ID': '4uOKFydzAejjSFqYbv1XPt'}, {'Artista': 'Shaggy', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Angel', 'Año': '2000-08-08', 'ID': '7FDV5ELOJHCGLe52AnttEd'}, {'Artista': 'Shaggy', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Hope', 'Año': '2000-08-08', 'ID': '5whIG7u2VjyILwGqm9dkDD'}, {'Artista': 'Capleton', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Who Dem', 'Año': '2000-08-08', 'ID': '1dDHDZWp1j4fkCdGRnopKq'}, {'Artista': 'Shaggy', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': "Keep'n It Real", 'Año': '2000-08-08', 'ID': '7cvop8FcQdqP6qfVmQLkdD'}, {'Artista': 'Shaggy', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Why Me Lord', 'Año': '2000-08-08', 'ID': '7JWIfIICkit2pXeLbdxiZF'}, {'Artista': 'Beenie Man', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Girls Dem Sugar', 'Año': '2000-08-08', 'ID': '3j8EEMm9kbPLqByuaHmUmQ'}, {'Artista': 'Banda Beijo', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Bate Lata', 'Año': '2000-08-08', 'ID': '2ATL6pmlSKBxn9M2U9Qp4t'}, {'Artista': 'Ara Ketu', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Amantes', 'Año': '2000-08-08', 'ID': '6EbbpFc64M1VBp7E29qnQv'}, {'Artista': 'Beenie Man', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Dancehall Queen (feat. Chevelle Franklyn)', 'Año': '2000-08-08', 'ID': '6LGTXFy9KNQeBjUHT9fPFh'}, {'Artista': 'UB40', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': "Don't Break My Heart", 'Año': '2000-08-08', 'ID': '0YUwrzyUcS5wIYUWkXCAbl'}, {'Artista': 'Los Cafres', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Sin Gamulán', 'Año': '2000-08-08', 'ID': '1ccEBfPmipV4R41R6Y3ouy'}, {'Artista': 'UB40', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Cherry Oh Baby', 'Año': '2000-08-08', 'ID': '7zbuCaBemBX0dMnqSTztl1'}, {'Artista': 'UB40', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'One In Ten', 'Año': '2000-08-08', 'ID': '1dKfteL9OIYuFOCwBzV0SB'}, {'Artista': 'Barry Biggs', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Love Come Down', 'Año': '2000-08-08', 'ID': '4VHtdJ0ekkxK9OG5SEwHZ9'}, {'Artista': 'Bob Marley & The Wailers', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Mr. Brown', 'Año': '2000-08-08', 'ID': '0zGXPikeXaT7NHTIBhQM7T'}, {'Artista': 'The Specials', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Do Nothing', 'Año': '2000-08-08', 'ID': '10mO8USTvhC0rMMvRPPZWg'}, {'Artista': 'Los Pericos', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Runaway - Live', 'Año': '2000-08-08', 'ID': '5blxpfx1eNYeA9y7jDUTT6'}, {'Artista': 'UB40', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Rat In Mi Kitchen', 'Año': '2000-08-08', 'ID': '0o7tBKZHvWPJB17wQx1Q8w'}, {'Artista': 'Cutty Ranks', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Limb By Limb', 'Año': '2000-08-08', 'ID': '6lZpBmEGZDVTpxjJZ5slAN'}, {'Artista': 'Bob Marley & The Wailers', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Small Axe', 'Año': '2000-08-08', 'ID': '2GtNJwcRdlBH7ulwl4yFyx'}, {'Artista': 'UB40', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Until My Dying Day', 'Año': '2000-08-08', 'ID': '2y9WjMBxurTYQPxCPGXLgl'}, {'Artista': 'UB40', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'The Earth Dies Screaming - Edit', 'Año': '2000-08-08', 'ID': '5hHBRGPaCPL3GnLWRStRoh'}, {'Artista': 'UB40', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Food For Thought', 'Año': '2000-08-08', 'ID': '7xLFoBLKymnhIaaSBS9vpv'}, {'Artista': '10 Ft. Ganja Plant', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Walkey Walk Tall', 'Año': '2000-08-08', 'ID': '49X280IOWye1tFuIvsD5sS'}, {'Artista': 'Los Pericos', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Eso Es Real - Live', 'Año': '2000-08-08', 'ID': '44wRvFEiNuKlWp4DmBJSyZ'}, {'Artista': 'Jackie Mittoo', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Totally Together', 'Año': '2000-08-08', 'ID': '26g0RB8H1F8GVCyC27zG6I'}, {'Artista': 'Harry Belafonte', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Jump in the Line', 'Año': '2000-08-08', 'ID': '6KkAC41nNRiWA6w3ZD9cJ8'}, {'Artista': 'Seeed', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Papa Noah', 'Año': '2000-08-08', 'ID': '2cxfEfp2dU4QtypUYcZl2j'}, {'Artista': 'Seeed', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Riddim No 1', 'Año': '2000-08-08', 'ID': '1ooatRQWNtl4jB7hQoanFz'}, {'Artista': 'UB40', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Higher Ground', 'Año': '2000-08-08', 'ID': '3aggzBl59puBLxg6ktaqie'}, {'Artista': 'Los Pericos', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Nada Que Perder - Live', 'Año': '2000-08-08', 'ID': '1XkBIrIQN5NoREiSyaTAmI'}, {'Artista': 'Prince Buster', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': "Don't Throw Stones", 'Año': '2000-08-08', 'ID': '6dzAIxWJ7MhwH4iGmjGxgn'}, {'Artista': 'Terra Samba', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Latinha De Cerveja', 'Año': '2000-08-08', 'ID': '18x3R1DdtcFPJ0mckjildc'}, {'Artista': 'Los Pericos', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Ocho Ríos - Live', 'Año': '2000-08-08', 'ID': '4ZaDJD9pWqgxW4kxzQrIjY'}, {'Artista': 'Jackie Mittoo', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Summer Breeze', 'Año': '2000-08-08', 'ID': '5Yu5gDFUjPqxUT5PHEJdIR'}, {'Artista': 'Los Rabanes', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Perfidia', 'Año': '2000-08-08', 'ID': '6P187fxZ0btnCRTy5Xql2Y'}, {'Artista': 'UB40', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Sing Our Own Song', 'Año': '2000-08-08', 'ID': '71P1uKwq0a4J4KUhwhy9qw'}, {'Artista': 'Dirtsman', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Hot This Year', 'Año': '2000-08-08', 'ID': '0Pp9uh741YQbUAcAJlb2RJ'}, {'Artista': 'Los Pericos', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Boulevard - Live', 'Año': '2000-08-08', 'ID': '0a7DgM90xUXYZCgArsEIuA'}, {'Artista': 'Jennifer Lara', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': "I'm In Love", 'Año': '2000-08-08', 'ID': '7LCD89We5JZALirKxgsGXM'}, {'Artista': 'Gondwana', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Alabanza', 'Año': '2000-08-08', 'ID': '1z7SPFBf9NlA4F2c6AvVQ7'}, {'Artista': 'Los Pericos', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Sin Cadenas - Live', 'Año': '2000-08-08', 'ID': '10VPz4veMzaJx2avRqQyxW'}, {'Artista': 'Giuliano Palma & The BlueBeaters', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Wonderful Life - Remastered 2023', 'Año': '2000-08-08', 'ID': '3PSAE8fUwoRNPrUAnnluxt'}, {'Artista': 'The Specials', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Stereotype', 'Año': '2000-08-08', 'ID': '22Vftb3jOTa8IPZwQI1L61'}, {'Artista': '10 Ft. Ganja Plant', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Chalwa', 'Año': '2000-08-08', 'ID': '7BLo3vat0B8BCQD50WOjum'}, {'Artista': 'Chaka Demus & Pliers', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Bam Bam', 'Año': '2000-08-08', 'ID': '07IMOzCQZJPrwSSDmlo2vv'}, {'Artista': 'Los Cafres', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Waitin en Vano', 'Año': '2000-08-08', 'ID': '03eLaRGb1oZgmtGSrMuoty'}, {'Artista': 'Culture', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Revolution', 'Año': '2000-08-08', 'ID': '7vbTbQhjxoiqiV4qxL1DaN'}, {'Artista': 'Ska-P', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'El Autentico', 'Año': '2000-08-08', 'ID': '15pI474vmLftBU7FV8LZF7'}, {'Artista': 'Los Pericos', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Voy Caminando Lento - Live', 'Año': '2000-08-08', 'ID': '7yEbY15xQmLCEstpmx6W5z'}, {'Artista': 'Ska-P', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Como Me Pongo', 'Año': '2000-08-08', 'ID': '6SJ6OfGVsFaO2R1eUdZFeB'}, {'Artista': 'The Specials', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Racist Friend - Edit', 'Año': '2000-08-08', 'ID': '1XGurZjVkgciMcr0phDFVw'}, {'Artista': 'Ara Ketu', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Face Oculta', 'Año': '2000-08-08', 'ID': '5LTwjTZjxnpAe0o0h5RgY0'}, {'Artista': 'Jackie Mittoo', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Get Up and Get It', 'Año': '2000-08-08', 'ID': '5AVhTKB8qBi7PUNFoXYnQ9'}, {'Artista': 'Jah Spirit', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'My Girl - Reggae Style', 'Año': '2000-08-08', 'ID': '69SJz5zBMWngc17HfmupHd'}, {'Artista': 'UB40', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'If It Happens Again', 'Año': '2000-08-08', 'ID': '1KhSlLDEGsVyz8MlJsO3ma'}, {'Artista': 'Goldfinger', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Counting The Days', 'Año': '2000-08-08', 'ID': '3M9ybg6UIG0Ude7uDihJRm'}, {'Artista': 'Resistencia Suburbana', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Cuidado', 'Año': '2000-08-08', 'ID': '4G1ojYqVwpYYoFN52SoSyM'}, {'Artista': 'Wayne Wonder', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Watching You', 'Año': '2000-08-08', 'ID': '0YfTOk4thT06YgPwLpCWHP'}, {'Artista': 'Shaggy', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Leave It To Me', 'Año': '2000-08-08', 'ID': '5L8MxayXG6D3FWUDDmBmzL'}, {'Artista': 'Jackie Mittoo', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Oboe', 'Año': '2000-08-08', 'ID': '3R0EhRQKxplZ32K37xwqDU'}, {'Artista': 'Glen Washington', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Strangers In The Night', 'Año': '2000-08-08', 'ID': '74NtKdZvxIPgZCWMSWPQjd'}, {'Artista': 'Gondwana', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Keep The Faith', 'Año': '2000-08-08', 'ID': '2Qq4l3G6w6WdfM1rKrEqBe'}, {'Artista': 'Los Pericos', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': "Waitin' - Live", 'Año': '2000-08-08', 'ID': '0q7LR23IYycIYTUJuTrQiF'}, {'Artista': 'Culture', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Poverty', 'Año': '2000-08-08', 'ID': '0n0x4ZTL0Q8ywLyo8ayoHk'}, {'Artista': 'UB40', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Light My Fire', 'Año': '2000-08-08', 'ID': '0Nqcp3idH9rXOLDg4zlXbd'}, {'Artista': 'Dr. Calypso', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Cineccita', 'Año': '2000-08-08', 'ID': '4nN1j6X5Umi7O3Evesw2j6'}, {'Artista': 'Swayzak', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Illegal (with Benjamin Zephaniah)', 'Año': '2000-08-08', 'ID': '1HYwdy16VbWnZNG45r19DM'}, {'Artista': 'Rastrillos', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'La Musica', 'Año': '2000-08-08', 'ID': '1UWRoVKwatWvKCMFfn6Z6P'}, {'Artista': 'UB40', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Food For Thought', 'Año': '2000-08-08', 'ID': '0GVAZ5OvagIPfAsuiIWCE8'}, {'Artista': 'La Mosca', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'No Te Despiertes Mi Amor', 'Año': '2000-08-08', 'ID': '6xAVuRNW0h3eR5oUbtSHNq'}, {'Artista': 'Shaggy', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Hey Love', 'Año': '2000-08-08', 'ID': '1tBB4wuK0gw2liPTms0bnX'}, {'Artista': 'Freddie McGregor', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'I See It In You', 'Año': '2000-08-08', 'ID': '6u9q7kZAtPyTu2tO3mHXci'}, {'Artista': 'Justin Hinds', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Rub Up Push Up', 'Año': '2000-08-08', 'ID': '3Pw5U5rugikTmuKvVNJOly'}, {'Artista': 'Lord Kossity', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Morenas', 'Año': '2000-08-08', 'ID': '2oZ1ay8QsrKQxxH1kGjorL'}, {'Artista': 'The Mighty Mighty Bosstones', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'So Sad To Say', 'Año': '2000-08-08', 'ID': '6aSvrNcJuoKOA9uwMXZI1D'}, {'Artista': 'UB40', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Sing Our Own Song', 'Año': '2000-08-08', 'ID': '266LLalLevmzLid2Vt8wxR'}, {'Artista': 'Elephant Man', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Punanny Medley', 'Año': '2000-08-08', 'ID': '5GEid99RgStd0cQIhAlGHQ'}, {'Artista': 'UB40', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Tell Me Is It True', 'Año': '2000-08-08', 'ID': '4Bw8iyN9swGbZ1sHW9F2nR'}, {'Artista': 'Los Pericos', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'La Hiena - Live', 'Año': '2000-08-08', 'ID': '53KpwSYYESclfokgvcbiPH'}, {'Artista': 'UB40', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Come Back Darling', 'Año': '2000-08-08', 'ID': '2Iy1tle7f4OHFB9u7thUNW'}, {'Artista': 'Brother Culture', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Foundation Rockers Dub (Disciples Dub Mix)', 'Año': '2000-08-08', 'ID': '1hjlTHxIn3cmFAlX17Yi5y'}, {'Artista': 'Capleton', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Stand Tall', 'Año': '2000-08-08', 'ID': '6EpY2zBpain6kUYZqhfgRN'}, {'Artista': 'UB40', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Cherry Oh Baby', 'Año': '2000-08-08', 'ID': '39a8Yl8PWJeJUCKWnhtQC9'}, {'Artista': 'UB40', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'One In Ten', 'Año': '2000-08-08', 'ID': '1Emtpza9uUO1UY7gXC4Z16'}, {'Artista': 'King Chango', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': "I Don't Care", 'Año': '2000-08-08', 'ID': '6HdD9uyf8yWCr88NuRmkRg'}, {'Artista': 'Junior Kelly', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Love So Nice', 'Año': '2000-08-08', 'ID': '0ks5sXa1iEMvtVbYOsfiNq'}, {'Artista': 'UB40', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': "Don't Break My Heart", 'Año': '2000-08-08', 'ID': '5M58wbtfIbRGBISCsenRnV'}, {'Artista': 'Jackie Mittoo', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Wall Street', 'Año': '2000-08-08', 'ID': '1AqdE3WGQHiHpAnsXQogWK'}, {'Artista': 'Dennis Brown', 'Género': 'reggae', 'Tipo': 'track', 'Nombre': 'Money

In [46]:
df_reggae = pd.DataFrame(listacanciones_reggae)

df_reggae

,Artista,Género,Tipo,Nombre,Año,ID
0,Sean Paul,reggae,track,Infiltrate,2000-08-08,0ru8bc0XnKjUL2O1Fl1k7a
1,Sean Paul,reggae,track,Deport Them,2000-08-08,5KhypMVGqMI9mgsrrv2lxc
2,Shaggy,reggae,track,"Luv Me, Luv Me",2000-08-08,7hV4x7PMKGC4qD3NWLt2UJ
3,Maskavo,reggae,track,Um Anjo do Céu,2000-08-08,2YgAAAq8h7nPIMVLVVSHtK
4,Gondwana,reggae,track,"Verde, Amarillo Y Rojo",2000-08-08,4Q0y0SOAJ84PvR2Uu6tGXv
...,...,...,...,...,...,...
745,Thievery Corporation,reggae,track,The Outernationalist - Rewound By Thievery Cor...,2000-08-08,3gSi1BsWjWBY0uD79KzxD1
746,Groundation,reggae,track,Smile,2000-08-08,27NdXbVaUTQPgixKn7sD0j
747,Dancing Mood,reggae,track,A Groovy Kind Of Love,2000-08-08,6OoCBB0erdARBcGh7LnlwG
748,Joe Dukie,reggae,track,Midnight Marauders - Dub Version,2000-08-08,6xcpj29ELRteqmCSzMyAfj
749,Holy Piby,reggae,track,My Time,2000-08-08,0A5hoqmtzca09KBqOgz3JX

In [49]:
df_reggae.to_csv("df_reggae.csv")