# API Last fm

In [1]:
import requests
import json
import pandas as pd

In [ ]:
cliente = "mis claves"
secreto = "mis claves"

In [3]:
url_api = "http://ws.audioscrobbler.com/2.0/"

### ------------------------------- Hacemos una función para llamar a la api -------------------------------

In [4]:
def llamar_lastfm_api(method, artist_name, cliente):

        params = {'method': method,'artist': artist_name,'api_key': cliente,'format': 'json'}

        response = requests.get(url_api, params=params)


        if response.status_code == 200:
            return response.json()
        else:
            print(f"Error {response.status_code}: No se pudo obtener la información para el método {method}")
            return

### ------------------------------- Hacemos un bucle for para iterar por cada artista -- en esta prueba lo hacemos con prints de control porque son solo cuatro artistas -------------------------------

In [5]:
artistas_a_consultar_prueba = ["Radiohead", "Pink Floyd", "Led Zeppelin", "Queen",  "The Beatles"]
lista_artistas_prueba = []


for nombre_artista in artistas_a_consultar_prueba:
    print(f"--- Consultando: {nombre_artista} ---")
    
    datos_artista = llamar_lastfm_api('artist.getinfo', nombre_artista, cliente)  
    
    
    if datos_artista and 'artist' in datos_artista:
        
        artista_data = datos_artista['artist']
        
        
        oyentes = artista_data.get('stats', {}).get('listeners', 'arista no encontrado') 
        reproducciones = artista_data.get('stats', {}).get('playcount', 'N/D')
        
        bio_content = artista_data.get('bio', {}).get('content', '')
        
        if not bio_content or bio_content.strip() == "":
            bio_resumen = 'biografia no encontrada'
        else:
            bio_resumen = artista_data.get('bio', {}).get('summary')
        
        lista_artistas_dict = {'artista': artista_data.get('name', nombre_artista),'oyentes': oyentes, 'reproducciones': reproducciones, 'bio_resumen': bio_resumen}
        lista_artistas_prueba.append(lista_artistas_dict)
        
        print(f"Datos de {nombre_artista} procesados y guardados.")
           
    else:
        print(f"No se pudo obtener información de {nombre_artista}")

--- Consultando: Radiohead ---
Datos de Radiohead procesados y guardados.
--- Consultando: Pink Floyd ---
Datos de Pink Floyd procesados y guardados.
--- Consultando: Led Zeppelin ---
Datos de Led Zeppelin procesados y guardados.
--- Consultando: Queen ---
Datos de Queen procesados y guardados.
--- Consultando: The Beatles ---
Datos de The Beatles procesados y guardados.

In [6]:
lista_artistas_prueba

[{'artista': 'Radiohead',
  'oyentes': '7927652',
  'reproducciones': '1273007059',
  'bio_resumen': 'Radiohead is an English rock band formed in Abingdon, Oxfordshire, in 1985. The band consists of Thom Yorke (vocals, guitar, piano, keyboards); brothers Jonny Greenwood (guitar, keyboards, other instruments) and Colin Greenwood (bass); Ed O\'Brien (guitar, backing vocals); and Philip Selway (drums, percussion). Since 1994, they have frequently collaborated with producer Nigel Godrich and cover artist Stanley Donwood. Radiohead are noted for their experimental approach, which has influenced the development of alternative rock. <a href="https://www.last.fm/music/Radiohead">Read more on Last.fm</a>'},
 {'artista': 'Pink Floyd',
  'oyentes': '5344169',
  'reproducciones': '583362534',
  'bio_resumen': 'Pink Floyd was an English rock band formed in London in 1965. Gaining an early following as one of the first British psychedelic groups, they were distinguished by their extended compositions, sonic experimentation, philosophical lyrics and elaborate live shows. They became a leading band of the progressive rock genre, cited by some as the greatest progressive rock band of all time.\n\nPink Floyd were founded in 1965 by Syd Barrett (guitar, lead vocals) <a href="https://www.last.fm/music/Pink+Floyd">Read more on Last.fm</a>'},
 {'artista': 'Led Zeppelin',
  'oyentes': '4796530',
  'reproducciones': '330472785',
  'bio_resumen': 'Led Zeppelin was a hard rock band formed in London in 1968. The group comprised vocalist Robert Plant, guitarist Jimmy Page, bassist and keyboardist John Paul Jones, and drummer John Bonham. With a heavy, guitar-driven sound, they are cited as one of the progenitors of hard rock and heavy metal, although their style drew from a variety of influences, including blues and folk music. Led Zeppelin have been credited as significantly impacting the nature of the music industry <a href="https://www.last.fm/music/Led+Zeppelin">Read more on Last.fm</a>'},
 {'artista': 'Queen',
  'oyentes': '6984252',
  'reproducciones': '406384268',
  'bio_resumen': 'Queen is a British rock band formed in London in 1970 by Freddie Mercury (lead vocals, piano), Brian May (guitar, vocals), and Roger Taylor (drums, vocals), later joined by John Deacon (bass). Their earliest works were influenced by progressive rock, hard rock, and heavy metal, but the band gradually ventured into more conventional and radio-friendly styles by incorporating elements of arena rock and pop rock.\n\nBefore forming Queen, May and Taylor had played together in the band Smile. <a href="https://www.last.fm/music/Queen">Read more on Last.fm</a>'},
 {'artista': 'The Beatles',
  'oyentes': '6293427',
  'reproducciones': '1046098607',
  'bio_resumen': 'The Beatles was an English rock band formed in Liverpool, Lancashire in 1960. With the line-up comprising John Lennon, Paul McCartney,  George Harrison, and Ringo Starr, they are regarded as the most popular and influential band of all time. The group were integral to the development of 1960s counterculture and popular music\'s recognition as an art form. Rooted in skiffle, beat and 1950s rock and roll, their sound incorporated elements of classical <a href="https://www.last.fm/music/The+Beatles">Read more on Last.fm</a>'}]

In [7]:

""" datos_artista = llamar_lastfm_api('artist.getinfo', nombre_artista, cliente)  
    
if datos_artista and 'artist' in datos_artista:
        
    artista = datos_artista['artist']
    oyentes = artista.get('stats', {}).get('listeners')
    reproducciones = artista.get('stats', {}).get('playcount')
        
    print(f"--- Detalles de {nombre_artista} ---")
    print(f"Oyentes (Last.fm): {oyentes}")
    print(f"Reproducciones (Last.fm): {reproducciones}")

    if datos_artista['artist']['bio']['content'] == "":
        print('biografia no encontrada')
    
    else:
        bio_resumen = artista.get('bio', {}).get('summary')
        print(f"Resumen de Biografía:\n{bio_resumen}...")

    # lista_artistas_dict = {'artista': artista, 'oyentes': oyentes, 'reproducciones': reproducciones, 'bio_resumen': bio_resumen}
    # lista_artistas.append(lista_artistas_dict)
           
else:
    print("No se pudo obtener información del artista.")"""

' datos_artista = llamar_lastfm_api(\'artist.getinfo\', nombre_artista, cliente)  \n    \nif datos_artista and \'artist\' in datos_artista:\n        \n    artista = datos_artista[\'artist\']\n    oyentes = artista.get(\'stats\', {}).get(\'listeners\')\n    reproducciones = artista.get(\'stats\', {}).get(\'playcount\')\n        \n    print(f"--- Detalles de {nombre_artista} ---")\n    print(f"Oyentes (Last.fm): {oyentes}")\n    print(f"Reproducciones (Last.fm): {reproducciones}")\n\n    if datos_artista[\'artist\'][\'bio\'][\'content\'] == "":\n        print(\'biografia no encontrada\')\n    \n    else:\n        bio_resumen = artista.get(\'bio\', {}).get(\'summary\')\n        print(f"Resumen de Biografía:\n{bio_resumen}...")\n\n    # lista_artistas_dict = {\'artista\': artista, \'oyentes\': oyentes, \'reproducciones\': reproducciones, \'bio_resumen\': bio_resumen}\n    # lista_artistas.append(lista_artistas_dict)\n           \nelse:\n    print("No se pudo obtener información del artista.")'

In [8]:
datos_artista.keys()

dict_keys(['artist'])

In [9]:
datos_artista['artist'].keys()

dict_keys(['name', 'mbid', 'url', 'image', 'streamable', 'ontour', 'stats', 'similar', 'tags', 'bio'])

In [10]:
datos_artista['artist']['bio']

{'links': {'link': {'#text': '',
   'rel': 'original',
   'href': 'https://last.fm/music/The+Beatles/+wiki'}},
 'published': '03 Feb 2006, 06:05',
 'summary': 'The Beatles was an English rock band formed in Liverpool, Lancashire in 1960. With the line-up comprising John Lennon, Paul McCartney,  George Harrison, and Ringo Starr, they are regarded as the most popular and influential band of all time. The group were integral to the development of 1960s counterculture and popular music\'s recognition as an art form. Rooted in skiffle, beat and 1950s rock and roll, their sound incorporated elements of classical <a href="https://www.last.fm/music/The+Beatles">Read more on Last.fm</a>',
 'content': 'The Beatles was an English rock band formed in Liverpool, Lancashire in 1960. With the line-up comprising John Lennon, Paul McCartney,  George Harrison, and Ringo Starr, they are regarded as the most popular and influential band of all time. The group were integral to the development of 1960s counterculture and popular music\'s recognition as an art form. Rooted in skiffle, beat and 1950s rock and roll, their sound incorporated elements of classical music and traditional pop in innovative ways; the band later explored music styles ranging from ballads and Indian music to psychedelia and hard rock. As pioneers in recording, songwriting and artistic presentation, the group revolutionized many aspects of the music industry and were often publicized as leaders of the era\'s youth and socio-cultural movements. \n\nLed by primary songwriters Lennon and McCartney, the Beatles built their reputation playing clubs in Liverpool and Hamburg over three years from 1960, initially with Stuart Sutcliffe playing bass. The core trio of Lennon, McCartney and Harrison, together since 1958, went through a succession of drummers, eventually settling with Pete Best in 1960, who played with them for two years before being replaced with then Rory Storm & The Hurricanes drummer Ringo Starr in 1962. Manager Brian Epstein molded them into a professional act and producer George Martin guided and developed their recordings, greatly expanding their domestic success after their first hit, "Love Me Do", in late 1962. As their popularity grew into the intense fan frenzy dubbed "Beatlemania", the band acquired the nickname "the Fab Four", with Epstein, Martin and other members of the band\'s entourage sometimes given the informal title of "fifth Beatle".\n\nBy early 1964, the Beatles were international stars, leading the "British Invasion" of the United States pop market and breaking numerous sales records. They soon made their film debut with A Hard Day\'s Night (1964). From 1965 onwards, they produced increasingly innovative recordings, including the albums Rubber Soul (1965), Revolver (1966) and Sgt. Pepper\'s Lonely Hearts Club Band (1967), and enjoyed further commercial success with The Beatles (also known as "the White Album", 1968) and Abbey Road (1969). In 1968, they founded Apple Corps, a multi-armed multimedia corporation that continues to oversee projects related to the band\'s legacy. After the group\'s break-up in 1970, all four members enjoyed success as solo artists. Lennon was shot and killed in December 1980, and Harrison died of lung cancer in November 2001. McCartney and Starr remain musically active.\n\nThe Beatles are the best-selling music act of all time, with estimated sales of 600 million units worldwide. They hold the record for most number-one albums on the UK Albums Chart, most number-one hits on the Billboard Hot 100 chart, and most singles sold in the UK. The group were inducted into the Rock and Roll Hall of Fame in 1988, and all four main members were inducted individually between 1994 and 2015. In 2008, the group topped Billboard\'s list of the all-time most successful artists on the Billboard Hot 100. The band received seven Grammy Awards, four Brit Awards, an Academy Award (for Best Original Song Score for the 1970 film Let It Be) and fifteen Ivor Novello Awards. Time magazine named them among the 20th century\'s 100 most important people.\n\nFormer Rolling Stone associate editor Robert Greenfield compared the Beatles to Picasso, as "artists who broke through the constraints of their time period to come up with something that was unique and original "... In the form of popular music, no one will ever be more revolutionary, more creative and more distinctive ..." The British poet Philip Larkin described their work as "an enchanting and intoxicating hybrid of African-American rock-and-roll with their own adolescent romanticism", and "the first advance in popular music since the War".\n\nThey not only sparked the British Invasion of the US, they became a globally influential phenomenon as well. From the 1920s, the US had dominated popular entertainment culture throughout much of the world, via Hollywood films, jazz, the music of Broadway and Tin Pan Alley and, later, the rock and roll that first emerged in Memphis, Tennessee. The Beatles are regarded as British cultural icons, with young adults from abroad naming the band among a group of people that they most associated with UK culture.\n\nTheir musical innovations and commercial success inspired musicians worldwide. Many artists have acknowledged the Beatles\' influence and enjoyed chart success with covers of their songs. On radio, their arrival marked the beginning of a new era; in 1968 the programme director of New York\'s WABC radio station forbade his DJs from playing any "pre-Beatles" music, marking the defining line of what would be considered oldies on American radio. They helped to redefine the album as something more than just a few hits padded out with "filler", and they were primary innovators of the modern music video. The Shea Stadium show with which they opened their 1965 North American tour attracted an estimated 55,600 people, then the largest audience in concert history; Spitz describes the event as a "major breakthrough ... a giant step toward reshaping the concert business". Emulation of their clothing and especially their hairstyles, which became a mark of rebellion, had a global impact on fashion.\n\nAccording to Gould, the Beatles changed the way people listened to popular music and experienced its role in their lives. From what began as the Beatlemania fad, the group\'s popularity grew into what was seen as an embodiment of socio-cultural movements of the decade. As icons of the 1960s counterculture, Gould continues, they became a catalyst for bohemianism and activism in various social and political arenas, fuelling movements such as women\'s liberation, gay liberation and environmentalism. According to Peter Lavezzoli, after the "more popular than Jesus" controversy in 1966, the Beatles felt considerable pressure to say the right things and "began a concerted effort to spread a message of wisdom and higher consciousness".\n\n\nOther commentators such as Mikal Gilmore and Todd Leopold have traced the inception of their socio-cultural impact earlier, interpreting even the Beatlemania period, particularly on their first visit to the US, as a key moment in the development of generational awareness. Referring to their appearance on the Ed Sullivan Show Leopold states: "In many ways, the Sullivan appearance marked the beginning of a cultural revolution ... The Beatles were like aliens dropped into the United States of 1964."\n\nIn 1965, Queen Elizabeth II appointed Lennon, McCartney, Harrison and Starr Members of the Order of the British Empire (MBE). The Beatles won the 1971 Academy Award for Best Original Song Score for the film Let It Be (1970). The recipients of seven Grammy Awards and fifteen Ivor Novello Awards, the Beatles have six Diamond albums, as well as 20 Multi-Platinum albums, 16 Platinum albums and six Gold albums in the US. In the UK, the Beatles have four Multi-Platinum albums, four Platinum albums, eight Gold albums and one Silver album. They were inducted into the Rock and Roll Hall of Fame in 1988.\n\nThe best-selling band in history, the Beatles have sold more than 800 million physical and digital albums as of 2013. They have had more number-one albums on the UK charts, fifteen, and sold more singles in the UK, 21.9 million, than any other act. In 2004, Rolling Stone ranked the Beatles as the most significant and influential rock music artists of the last 50 years. They ranked number one on Billboard magazine\'s list of the all-time most successful Hot 100 artists, released in 2008 to celebrate the US singles chart\'s 50th anniversary. As of 2017, they hold the record for most number-one hits on the Billboard Hot 100, with twenty. The Recording Industry Association of America certifies that the Beatles have sold 178 million units in the US, more than any other artist. They were collectively included in Time magazine\'s compilation of the 20th century\'s 100 most influential people. In 2014, they received the Grammy Lifetime Achievement Award.\n\nThere are two holidays celebrated for the Beatles: Global Beatles Day on 25 June each year. On that date in 1967, the band performed "All You Need Is Love" on television. In 2001, UNESCO created World Beatles Day on 16 January each year. This date has direct relation to the opening of The Cavern Club in 1957.\n\nFive asteroids, 4147 Lennon, 4148 McCartney, 4149 Harrison, 4150 Starr and 8749 Beatles are named after the Beatles. <a href="https://www.last.fm/music/The+Beatles">Read more on Last.fm</a>. User-contributed text is available under the Creative Commons By-SA License; additional terms may apply.'}

In [11]:
datos_artista['artist']['bio']['content']

'The Beatles was an English rock band formed in Liverpool, Lancashire in 1960. With the line-up comprising John Lennon, Paul McCartney,  George Harrison, and Ringo Starr, they are regarded as the most popular and influential band of all time. The group were integral to the development of 1960s counterculture and popular music\'s recognition as an art form. Rooted in skiffle, beat and 1950s rock and roll, their sound incorporated elements of classical music and traditional pop in innovative ways; the band later explored music styles ranging from ballads and Indian music to psychedelia and hard rock. As pioneers in recording, songwriting and artistic presentation, the group revolutionized many aspects of the music industry and were often publicized as leaders of the era\'s youth and socio-cultural movements. \n\nLed by primary songwriters Lennon and McCartney, the Beatles built their reputation playing clubs in Liverpool and Hamburg over three years from 1960, initially with Stuart Sutcliffe playing bass. The core trio of Lennon, McCartney and Harrison, together since 1958, went through a succession of drummers, eventually settling with Pete Best in 1960, who played with them for two years before being replaced with then Rory Storm & The Hurricanes drummer Ringo Starr in 1962. Manager Brian Epstein molded them into a professional act and producer George Martin guided and developed their recordings, greatly expanding their domestic success after their first hit, "Love Me Do", in late 1962. As their popularity grew into the intense fan frenzy dubbed "Beatlemania", the band acquired the nickname "the Fab Four", with Epstein, Martin and other members of the band\'s entourage sometimes given the informal title of "fifth Beatle".\n\nBy early 1964, the Beatles were international stars, leading the "British Invasion" of the United States pop market and breaking numerous sales records. They soon made their film debut with A Hard Day\'s Night (1964). From 1965 onwards, they produced increasingly innovative recordings, including the albums Rubber Soul (1965), Revolver (1966) and Sgt. Pepper\'s Lonely Hearts Club Band (1967), and enjoyed further commercial success with The Beatles (also known as "the White Album", 1968) and Abbey Road (1969). In 1968, they founded Apple Corps, a multi-armed multimedia corporation that continues to oversee projects related to the band\'s legacy. After the group\'s break-up in 1970, all four members enjoyed success as solo artists. Lennon was shot and killed in December 1980, and Harrison died of lung cancer in November 2001. McCartney and Starr remain musically active.\n\nThe Beatles are the best-selling music act of all time, with estimated sales of 600 million units worldwide. They hold the record for most number-one albums on the UK Albums Chart, most number-one hits on the Billboard Hot 100 chart, and most singles sold in the UK. The group were inducted into the Rock and Roll Hall of Fame in 1988, and all four main members were inducted individually between 1994 and 2015. In 2008, the group topped Billboard\'s list of the all-time most successful artists on the Billboard Hot 100. The band received seven Grammy Awards, four Brit Awards, an Academy Award (for Best Original Song Score for the 1970 film Let It Be) and fifteen Ivor Novello Awards. Time magazine named them among the 20th century\'s 100 most important people.\n\nFormer Rolling Stone associate editor Robert Greenfield compared the Beatles to Picasso, as "artists who broke through the constraints of their time period to come up with something that was unique and original "... In the form of popular music, no one will ever be more revolutionary, more creative and more distinctive ..." The British poet Philip Larkin described their work as "an enchanting and intoxicating hybrid of African-American rock-and-roll with their own adolescent romanticism", and "the first advance in popular music since the War".\n\nThey not only sparked the British Invasion of the US, they became a globally influential phenomenon as well. From the 1920s, the US had dominated popular entertainment culture throughout much of the world, via Hollywood films, jazz, the music of Broadway and Tin Pan Alley and, later, the rock and roll that first emerged in Memphis, Tennessee. The Beatles are regarded as British cultural icons, with young adults from abroad naming the band among a group of people that they most associated with UK culture.\n\nTheir musical innovations and commercial success inspired musicians worldwide. Many artists have acknowledged the Beatles\' influence and enjoyed chart success with covers of their songs. On radio, their arrival marked the beginning of a new era; in 1968 the programme director of New York\'s WABC radio station forbade his DJs from playing any "pre-Beatles" music, marking the defining line of what would be considered oldies on American radio. They helped to redefine the album as something more than just a few hits padded out with "filler", and they were primary innovators of the modern music video. The Shea Stadium show with which they opened their 1965 North American tour attracted an estimated 55,600 people, then the largest audience in concert history; Spitz describes the event as a "major breakthrough ... a giant step toward reshaping the concert business". Emulation of their clothing and especially their hairstyles, which became a mark of rebellion, had a global impact on fashion.\n\nAccording to Gould, the Beatles changed the way people listened to popular music and experienced its role in their lives. From what began as the Beatlemania fad, the group\'s popularity grew into what was seen as an embodiment of socio-cultural movements of the decade. As icons of the 1960s counterculture, Gould continues, they became a catalyst for bohemianism and activism in various social and political arenas, fuelling movements such as women\'s liberation, gay liberation and environmentalism. According to Peter Lavezzoli, after the "more popular than Jesus" controversy in 1966, the Beatles felt considerable pressure to say the right things and "began a concerted effort to spread a message of wisdom and higher consciousness".\n\n\nOther commentators such as Mikal Gilmore and Todd Leopold have traced the inception of their socio-cultural impact earlier, interpreting even the Beatlemania period, particularly on their first visit to the US, as a key moment in the development of generational awareness. Referring to their appearance on the Ed Sullivan Show Leopold states: "In many ways, the Sullivan appearance marked the beginning of a cultural revolution ... The Beatles were like aliens dropped into the United States of 1964."\n\nIn 1965, Queen Elizabeth II appointed Lennon, McCartney, Harrison and Starr Members of the Order of the British Empire (MBE). The Beatles won the 1971 Academy Award for Best Original Song Score for the film Let It Be (1970). The recipients of seven Grammy Awards and fifteen Ivor Novello Awards, the Beatles have six Diamond albums, as well as 20 Multi-Platinum albums, 16 Platinum albums and six Gold albums in the US. In the UK, the Beatles have four Multi-Platinum albums, four Platinum albums, eight Gold albums and one Silver album. They were inducted into the Rock and Roll Hall of Fame in 1988.\n\nThe best-selling band in history, the Beatles have sold more than 800 million physical and digital albums as of 2013. They have had more number-one albums on the UK charts, fifteen, and sold more singles in the UK, 21.9 million, than any other act. In 2004, Rolling Stone ranked the Beatles as the most significant and influential rock music artists of the last 50 years. They ranked number one on Billboard magazine\'s list of the all-time most successful Hot 100 artists, released in 2008 to celebrate the US singles chart\'s 50th anniversary. As of 2017, they hold the record for most number-one hits on the Billboard Hot 100, with twenty. The Recording Industry Association of America certifies that the Beatles have sold 178 million units in the US, more than any other artist. They were collectively included in Time magazine\'s compilation of the 20th century\'s 100 most influential people. In 2014, they received the Grammy Lifetime Achievement Award.\n\nThere are two holidays celebrated for the Beatles: Global Beatles Day on 25 June each year. On that date in 1967, the band performed "All You Need Is Love" on television. In 2001, UNESCO created World Beatles Day on 16 January each year. This date has direct relation to the opening of The Cavern Club in 1957.\n\nFive asteroids, 4147 Lennon, 4148 McCartney, 4149 Harrison, 4150 Starr and 8749 Beatles are named after the Beatles. <a href="https://www.last.fm/music/The+Beatles">Read more on Last.fm</a>. User-contributed text is available under the Creative Commons By-SA License; additional terms may apply.'

### ----------------- Convertimos el CSV de rock en una lista de tuplas para poder trabajarlo -------------------------------

In [ ]:
df = pd.read_csv("../api_spotify/archivos_csv/df_rock.csv", index_col=0)

In [13]:
df

,Artista,Género,Tipo,Nombre,Año_Lanzamiento,ID_Spotify
0,Five For Fighting,rock,track,Superman (It's Not Easy),2000,3TwtrR1yNLY1PMPsrGQpOp
1,The Smashing Pumpkins,rock,track,Stand Inside Your Love,2000,3RciEQxS7PxtLqMs7OwRsU
2,The Beatles,rock,track,Day Tripper - Remastered 2015,2000,29b2b96jozyD9GPCkOrVLs
3,Deftones,rock,track,Passenger,2000,7IoK6jZBxY7NMoQPoPXZCF
4,Panchiko,rock,track,D>E>A>T>H>M>E>T>A>L,2000,4sIFi8LpJWPvI5xviWFyA6
...,...,...,...,...,...,...
745,Hombres G,rock,track,Qué soy yo para ti,2004,2vnMY0A72GKY9DJey7bzMd
746,Keane,rock,track,Somewhere Only We Know,2004,2slll7iPbwCD4IwdgcZN69
747,Bunbury,rock,track,Canto... el mismo dolor,2004,1boxzAIByOzRhopCsD6PhG
748,Michael McDonald,rock,track,"Stop, Look, Listen (To Your Heart)",2004,6eKRQdKMtSWnlApt4x2aIX
749,Nek,rock,track,Laura no està,2004,5jbG38paHIeVJc57uXUNYt

In [14]:
df['Artista']

0          Five For Fighting
1      The Smashing Pumpkins
2                The Beatles
3                   Deftones
4                   Panchiko
               ...
745                Hombres G
746                    Keane
747                  Bunbury
748         Michael McDonald
749                      Nek
Name: Artista, Length: 750, dtype: object

In [15]:
artista = df['Artista']

In [16]:
artista_unico = set(artista)

In [17]:
artista_unico

{'10cc',
 '3 Doors Down',
 'A Perfect Circle',
 'AC/DC',
 'ASIAN KUNG-FU GENERATION',
 'Aerosmith',
 'Air Supply',
 'Airbag',
 'Al Stewart',
 'Alaska Y Dinarama',
 'Alfredo Pardo- Spanish Pop',
 'Alter Bridge',
 'Alvin Lee',
 'Andrés Calamaro',
 'Arcade Fire',
 'Aterciopelados',
 'Attaque 77',
 'Audioslave',
 'Avenged Sevenfold',
 'Babasonicos',
 'Ben Harper',
 'Benito Kamelas',
 'Bersuit Vergarabat',
 'Billy Joel',
 'Black Rebel Motorcycle Club',
 'Blur',
 'Bon Jovi',
 'Breaking Benjamin',
 'Bruce Springsteen',
 'Bunbury',
 'Bushido',
 'CAKE',
 'Café Tacvba',
 'Callejeros',
 'Calvin Russell',
 'Catupecu Machu',
 'Celso Piña',
 'Charlie Brown Jr.',
 'Charly García',
 'Cheap Trick',
 'Chris de Burgh',
 'Citizen Cope',
 'Cock Robin',
 'Coti',
 'Counting Crows',
 'Crazy Town',
 'Creed',
 'Crossfade',
 'Cypress Hill',
 'Cómplices',
 'Daryl Hall & John Oates',
 'David Bowie',
 'Deftones',
 'Desert Sessions',
 'Design19',
 'Divididos',
 'Dobie Gray',
 'Donavon Frankenreiter',
 'Dover',
 'Drowning Pool',
 'Duncan Dhu',
 'Eagle-Eye Cherry',
 'Electric Six',
 'Elefante',
 'Elvis Presley',
 'Embrace',
 'Engenheiros Do Hawaii',
 'Eric Clapton',
 'Evanescence',
 'Explosions In The Sky',
 'Five For Fighting',
 'Fleetwood Mac',
 'Foo Fighters',
 'Franz Ferdinand',
 'Gary Moore',
 'Green Day',
 'Gustavo Cerati',
 'HALCALI',
 'HIM',
 'Hombres G',
 'Illya Kuryaki & The Valderramas',
 'Incubus',
 'Indio Solari',
 'Inspector',
 'Interpol',
 'Intoxicados',
 'JAY-Z',
 'Jack Johnson',
 'Jaguares',
 'Jarabe De Palo',
 'Jet',
 'Joe Bonamassa',
 'Journey',
 'Juanes',
 'Jóvenes Pordioseros',
 'Keane',
 'Kula Shaker',
 'La Ley',
 'La Mosca',
 'La Renga',
 'La Unión',
 'La Vela Puerca',
 'La-33',
 'Lamp',
 'Las Pelotas',
 'Lenny Kravitz',
 'Libido',
 'Lifehouse',
 'Limp Bizkit',
 'Linkin Park',
 'Lionel Richie',
 'Lordi',
 'Los Abuelos De La Nada',
 'Los Amantes De Lola',
 'Los Animalitos',
 'Los Auténticos Decadentes',
 'Los Caballeros De La Quema',
 'Los Enanitos Verdes',
 'Los Inhumanos',
 'Los Piojos',
 'Los Rodriguez',
 'Los Tipitos',
 'Madrugada',
 'Mancha De Rolando',
 'Manic Street Preachers',
 'Maná',
 'Maria De Los Angeles',
 'Marilyn Manson',
 'Mark Knopfler',
 'Matchbox Twenty',
 'Memphis La Blusera',
 'Metallica',
 'Michael McDonald',
 'Mick Jagger',
 'Miguel Ríos',
 'Modest Mouse',
 'Mogwai',
 'Molotov',
 'Muse',
 'Mägo de Oz',
 'Neil Young',
 'Nek',
 'Nickelback',
 'Nirvana',
 'No Te Va Gustar',
 "O'Funk'illo",
 'Oasis',
 'Orleans',
 'Orquesta Mondragon',
 'Os Paralamas Do Sucesso',
 'Ozzy Osbourne',
 'P.O.D.',
 'PJ Harvey',
 'Panchiko',
 'Papa Roach',
 'Pappo',
 'Patricio Rey y sus Redonditos de Ricota',
 'Pearl Jam',
 'Pedro Suárez-Vértiz',
 'Pepper',
 'Peter Frampton',
 'Phil Collins',
 'Pink Floyd',
 'Pixies',
 'Placebo',
 'Porcupine Tree',
 'Puddle Of Mudd',
 'Queen',
 'Queens of the Stone Age',
 'R.E.M.',
 'Radiohead',
 'Rage Against The Machine',
 'Rata Blanca',
 'Red Hot Chili Peppers',
 'Richard Ashcroft',
 'Robbie Williams',
 'Robert Palmer',
 'Roger Hodgson',
 'Santana',
 'Seether',
 'Semisonic',
 'Serani Poji',
 'Shinedown',
 'Sigur Rós',
 'Silver Mt. Zion',
 'Simon & Garfunkel',
 'Skank',
 'Skay Beilinson',
 'Soda Stereo',
 'Spandau Ballet',
 'Staind',
 'Starsailor',
 'Stone Sour',
 'System Of A Down',
 'TOOL',
 'Talk Talk',
 'Thanya Paredes Aymara',
 'The Arrows and Friends',
 'The Beatles',
 'The Beautiful Girls',
 'The Black Keys',
 'The Cranberries',
 'The Cult',
 'The Cure',
 'The Dandy Warhols',
 'The Darkness',
 'The Goo Goo Dolls',
 'The Greenhornes',
 'The Hellacopters',
 'The Hives',
 'The Killers',
 'The Rolling Stones',
 'The Smashing Pumpkins',
 'The Strokes',
 'The The',
 'The Verve',
 'The Vines',
 'The White Stripes',
 'Thousand Foot Krutch',
 'Three Days Grace',
 'Titãs',
 'Tommy february6',
 'Train',
 'Travis',
 'Turf',
 'U2',
 'Velvet Revolver',
 'Vicentico',
 'Viejas Locas',
 'Vilma Palma e Vampiros',
 'Weezer',
 'Wilco',
 'Zoé'}

In [18]:
len(artista_unico)

233

### ------------- Extraemos la info que necesitamos de la api ---------------------

In [19]:
artistas_a_consultar = artista_unico
lista_artistas = []


for nombre_artista in artistas_a_consultar:
    
    datos_artista = llamar_lastfm_api('artist.getinfo', nombre_artista, cliente)  
    
    
    if datos_artista and 'artist' in datos_artista:
        
        artista_data = datos_artista['artist']
        
        
        oyentes = artista_data.get('stats', {}).get('listeners', 'arista no encontrado') 
        reproducciones = artista_data.get('stats', {}).get('playcount', 'N/D')
        
        bio_content = artista_data.get('bio', {}).get('content', '')
        
        if not bio_content or bio_content.strip() == "":
            bio_resumen = 'biografia no encontrada'
        else:
            bio_resumen = artista_data.get('bio', {}).get('summary')
        
        lista_artistas_dict = {'artista': artista_data.get('name', nombre_artista),'oyentes': oyentes, 'reproducciones': reproducciones, 'bio_resumen': bio_resumen}
        lista_artistas.append(lista_artistas_dict)
        
    
           
    else:
        print(f"No se pudo obtener información de {nombre_artista}")

In [20]:
lista_artistas

[{'artista': 'Patricio Rey y sus Redonditos de Ricota',
  'oyentes': '98653',
  'reproducciones': '10286980',
  'bio_resumen': 'Patricio Rey y sus Redonditos de Ricota was a rock band originally from La Plata, Argentina in 1976. Their tours in the 1980s, 1990s and 2000s drew a cult-like following that mirrored Grateful Dead frenzy in the United States. \n\nThe band\'s strength lies in the semantic power of its lyrics, which discuss different topics such as politics, drugs and women, but always from a philosophical and existential point of view. The band represented a counter-cultural paradigm, reinforced and supported by its truly independent production nature.  <a href="https://www.last.fm/music/Patricio+Rey+y+sus+Redonditos+de+Ricota">Read more on Last.fm</a>'},
 {'artista': 'Hombres G',
  'oyentes': '493105',
  'reproducciones': '9600712',
  'bio_resumen': 'Spanish pop/rock foursome Hombres G was formed by ex-los Residuos guitarist Daniel Mezquita, drummer Javier Molina, and singer/bassist David Summers, soon joined by guitarist Rafael Gutierrez. The band\'s name was based on an American movie called G-Men. Hombres G made its live debut at Madrid\'s Rockola, recording a demo called Milagro En El Congo in 1984. They soon signed up to the independent label Twins to make their debut album, featuring a catchy song called "Devuelveme A Mi Chica," which became their first hit. <a href="https://www.last.fm/music/Hombres+G">Read more on Last.fm</a>'},
 {'artista': 'Airbag',
  'oyentes': '170445',
  'reproducciones': '7705481',
  'bio_resumen': 'There are  at least 9 bands with the same name:\n\n1. Airbag,  from Norway\n2. Airbag, from Spain\n3. Airbag, from Argentina\n4. Airbag, from South Korea.\n5. Airbag, from Bulgaria\n6. Airbag, from the Netherlands\n7. Airbag, from China\n8. Airbag, from Japan\n9. Airbag, from Czech Republic\n\n1 .Airbag is a five member progressive rock group from Norway. The line up (from 2010) is Anders Hovdan - Bass, Asle Tostrup - Vocals, guitar, Bjørn Riis - Guitar, vocals, Henrik Fossum - Drums and Jørgen Hagen - Keyboards. <a href="https://www.last.fm/music/Airbag">Read more on Last.fm</a>'},
 {'artista': 'Thousand Foot Krutch',
  'oyentes': '1138544',
  'reproducciones': '37218183',
  'bio_resumen': 'Thousand Foot Krutch (often abbreviated TFK) is a Canadian Christian rock band from Peterborough, Ontario, Canada. They made their debut in 1995 when Trevor McNevan, Joel Bruyere, and Steve Augustine started putting a praise & worship spin on the nu-metal sound of the time. After building a buzz around Ontario with numerous shows and a strong demo titled That\'s What People Do, Thousand Foot Krutch signed with Diamante and issued their debut LP, Set It Off, in 2000. <a href="https://www.last.fm/music/Thousand+Foot+Krutch">Read more on Last.fm</a>'},
 {'artista': 'Three Days Grace',
  'oyentes': '3710774',
  'reproducciones': '172257837',
  'bio_resumen': 'Three Days Grace is a Canadian rock band, formed under the name Groundswell in Norwood, Ontario, Canada in 1992. After a breakup in 1995, the band reformed in 1997 under its current name and with a line-up consisting of guitarist and lead vocalist Adam Gontier, drummer and backing vocalist Neil Sanderson, and bassist Brad Walst. In 2003, Barry Stock was recruited as the band\'s lead guitarist. The band has released seven studio albums, with a record fourteen #1 hits on Mainstream Rock. <a href="https://www.last.fm/music/Three+Days+Grace">Read more on Last.fm</a>'},
 {'artista': 'Modest Mouse',
  'oyentes': '3338417',
  'reproducciones': '198122770',
  'bio_resumen': 'Modest Mouse is an American alternative rock band which formed in 1993 in Issaquah, Washington, United States. The band\'s original lineup consisted of guitarist Isaac Brock, drummer Jeremiah Green and bassist Eric Judy. Since being signed to Sony\'s Epic Records in 2000, Modest Mouse has attained significant popular success with songs such as "Float On" and "Dashboard."\n\nThe band\'s current configuration is Isaac Brock (vocals, guitar), Tom Peloso (strings, horns, bass, keyboards), Jim Fairchild (guitar), and Eric Judy (bass)). <a href="https://www.last.fm/music/Modest+Mouse">Read more on Last.fm</a>'},
 {'artista': 'The The',
  'oyentes': '679853',
  'reproducciones': '10427433',
  'bio_resumen': 'The The are an English post-punk band. They have been active in various forms since 1979, with singer-songwriter Matt Johnson being the only constant band member. The The achieved critical acclaim and commercial success in the UK, with 15 chart singles (seven reaching the top 40), and their most successful album, Infected (1986), spent 30 weeks on the chart. They followed this with the top ten albums Mind Bomb (1989) and Dusk (1993).\n\nEarly years (1977–1981) <a href="https://www.last.fm/music/The+The">Read more on Last.fm</a>'},
 {'artista': 'Os Paralamas Do Sucesso',
  'oyentes': '478170',
  'reproducciones': '12542860',
  'bio_resumen': 'Three young guys who had in common their love for rock, reggae and ska - Herbert Vianna, Bi Ribeiro and João Barone - formed the group Paralamas at the beginning of the 80’s inspired by the sonority of groups as The Police, The Beat and The Specials, that used to recycle the rhythms created in Jamaica. \n\nStimulated by the talent and the interest in the rising phenomenon of the Brazilian Rock, soon they had recorded their first LP “Cinema Mudo” <a href="https://www.last.fm/music/Os+Paralamas+Do+Sucesso">Read more on Last.fm</a>'},
 {'artista': 'Velvet Revolver',
  'oyentes': '1155293',
  'reproducciones': '20375976',
  'bio_resumen': 'Velvet Revolver was an American hard rock supergroup consisting of Guns N\'Roses members Slash (lead guitar), Duff McKagan (bass, backing vocals) and Matt Sorum (drums, backing vocals), alongside Dave Kushner (rhythm guitar) formerly of punk band Wasted Youth, and Scott Weiland (lead vocalist) formerly of Stone Temple Pilots. The band formed in 2002 and was active until 2008, when Weiland left the band abruptly to rejoin Stone Temple Pilots.\n\nIn 2004, the band achieved commercial success with their debut album, Contraband. <a href="https://www.last.fm/music/Velvet+Revolver">Read more on Last.fm</a>'},
 {'artista': 'Ozzy Osbourne',
  'oyentes': '3003780',
  'reproducciones': '90643775',
  'bio_resumen': 'Ozzy Osbourne (born John Michael Osbourne in Marston Green, Warwickshire, on 3 December 1948; died 22 July 2025) was an English singer, songwriter, and media personality remembered as the lead vocalist of the heavy metal band Black Sabbath, during which period he adopted the nickname "Prince of Darkness". On 5 July 2025, Osbourne performed his final show at the "Back to the Beginning" concert event. \n\nHe was inducted into the Rock and Roll Hall of Fame as a member of Black Sabbath in 2006 and as a solo artist in 2024. <a href="https://www.last.fm/music/Ozzy+Osbourne">Read more on Last.fm</a>'},
 {'artista': 'Embrace',
  'oyentes': '663132',
  'reproducciones': '8808046',
  'bio_resumen': 'Embrace is the name of more than one artist:\n1) an alternative rock band from Brighouse, West Yorkshire, England\n2) a short-lived post-hardcore band from Washington, D.C., USA\n3) a collaboration between dutch trance producers Ferry Corsten and Raz Nitzan\n4) a Gothic Metal band from Toronto, Canada\n\n1) Embrace is a five-piece alternative rock band from Brighouse, West Yorkshire, England, consisting of brothers Danny McNamara (singer) and Richard McNamara (guitarist) as well as Steve Firth (bassist) <a href="https://www.last.fm/music/Embrace">Read more on Last.fm</a>'},
 {'artista': 'Bushido',
  'oyentes': '262008',
  'reproducciones': '15248031',
  'bio_resumen': 'There is more than one artist with this name: a German rapper, a Latin pop act, a post-punk band and a prog rock band from Australia.\n\n1) German rapper Anis Ferchichi who was born on September 28, 1978 in Bonn. His rap is strongly influenced by French Gangsta Rap. He is also known as Sonny Black.\nEarly Life:\nBushido has a Tunisian father and a German mother. However, he was raised in Berlin by his mother and never got to know his father.\n\nMusical Career: <a href="https://www.last.fm/music/Bushido">Read more on Last.fm</a>'},
 {'artista': 'Divididos',
  'oyentes': '129785',
  'reproducciones': '3756470',
  'bio_resumen': 'Divididos ("Divided") is a rock band from Argentina with a significant place in the history of Argentine rock. Formed in 1988 after the death of Luca Prodan and the consequent dissolution of Sumo, Ricardo Mollo (vocals, guitar) and Diego Arnedo (bass guitar) joined drummer Gustavo Collado to form a band named "La División" (The Division), which would be later called "Divididos". (Another band emerged from the ashes of Sumo: Las Pelotas.)\n\nLa Aplanadora del Rock is known for mixing rock with Argentine folk music, and hard-to-get lyrics. <a href="https://www.last.fm/music/Divididos">Read more on Last.fm</a>'},
 {'artista': 'Queens of the Stone Age',
  'oyentes': '3623476',
  'reproducciones': '244886720',
  'bio_resumen': 'Queens of the Stone Age is a rock band from Palm Desert, California, United States. The band is frequently labeled stoner rock, although they reject the label. They developed a style of riff-oriented, heavy music which the band\'s founder and mastermind Josh Homme described as "robot rock", saying that he "wanted to create a heavy sound based on a solid jam, just pound it into your head". Since then, their sound has evolved to incorporate a variety of different styles and influences. <a href="https://www.last.fm/music/Queens+of+the+Stone+Age">Read more on Last.fm</a>'},
 {'artista': 'Indio Solari',
  'oyentes': '28009',
  'reproducciones': '1299564',
  'bio_resumen': 'Indio Solari (born Carlos Solari, c. 1949) is an Argentine singer and musician. He was leader of Patricio Rey y sus Redonditos de Ricota between 1976 and 2002. He got separated from Redondos and then started his first solo work in 2004 called El Tesoro de los Inocentes (Bingo Fuel)), together with his backing band Los Fundamentalistas del Aire Acondicionado. In 2007 he released his second solo album Porco Rex.  <a href="https://www.last.fm/music/Indio+Solari">Read more on Last.fm</a>'},
 {'artista': 'La Vela Puerca',
  'oyentes': '139843',
  'reproducciones': '4257844',
  'bio_resumen': 'La Vela Puerca is "Uruguay\'s most famous ska-rock-band". It was founded 1995 in Montevideo.\n\nIts founders were Sebastián Teysera (lead vocals, frontman and main songwriter), Nicolás Lieutier (bass guitar) and Santiago Butler (guitar) - all three are still part of the band today. The band\'s first appearance as La Vela Puerca was in a montevidean street party in December 24, 1995. By then, several new members had already joined in. In 1996, frontman Sebastián Teysera presented a demo tape to a band contest. <a href="https://www.last.fm/music/La+Vela+Puerca">Read more on Last.fm</a>'},
 {'artista': 'A Perfect Circle',
  'oyentes': '2146828',
  'reproducciones': '111049054',
  'bio_resumen': 'A Perfect Circle is an American alternative rock band formed in Los Angeles, California in 1999 by guitarist Billy Howerdel and Tool vocalist Maynard James Keenan. A Perfect Circle has released four studio albums, the first three during the early 2000s: Mer de Noms, their debut album in 2000, and followed up by Thirteenth Step in 2003; then in 2004, Emotive—an album of radically re-worked cover songs. Shortly after Emotive\'s release, the band went on hiatus; Keenan returned to Tool and started up solo work under the band name Puscifer <a href="https://www.last.fm/music/A+Perfect+Circle">Read more on Last.fm</a>'},
 {'artista': 'Silver Mt. Zion',
  'oyentes': '186773',
  'reproducciones': '3229690',
  'bio_resumen': 'A Silver Mt. Zion is a band formed in 1999, in Montreal, Canada, by Godspeed You! Black Emperor musicians Efrim Menuck, Sophie Trudeau and Thierry Amar. According to an interview with VPRO Radio in The Netherlands, originally the project was for Efrim to learn how to score music, but the idea was soon abandoned as Efrim decided that he preferred music not to be defined by rules, preferring simply what sounds best. Despite this, he continued the project <a href="https://www.last.fm/music/+noredirect/Silver+Mt.+Zion">Read more on Last.fm</a>'},
 {'artista': 'Nirvana',
  'oyentes': '7280628',
  'reproducciones': '549762503',
  'bio_resumen': 'There are multiple artists tracked as "Nirvana" on Last.fm. Following are six, listed in order of prominence:\n\n1) Nirvana was a popular and highly influential American grunge band. The band formed in Aberdeen, Washington in 1987, and it was part of the Seattle grunge scene of the late 80s, alongside bands like Pearl Jam, Alice in Chains and Soundgarden. As their popularity rose, alternative rock became a dominant genre on American and Canadian radio and music television during the early-to-mid \'90s. <a href="https://www.last.fm/music/Nirvana">Read more on Last.fm</a>'},
 {'artista': 'Alfredo Pardo- Spanish Pop',
  'oyentes': '1667',
  'reproducciones': '6491',
  'bio_resumen': 'biografia no encontrada'},
 {'artista': 'Benito Kamelas',
  'oyentes': '16777',
  'reproducciones': '360067',
  'bio_resumen': 'The spanish rock group BENITO KAMELAS se caracteriza por hacer un Rock fresco, cotidiano y divertido pero lo mejor es su puesta en escena. En Diciembre de 1997 graban un Cd con seis cortes (QUE MÁS DA)y empiezan a moverlo sin ningún tipo de apoyo de ninguna compañía, promocionandolo en directo por capitales como Teruel, Zaragoza, Córdoba, Tarragona, Castellón, y Alicante.\nAsombrados por haber vendido 1.500 copias (mano en mano y algún garito) <a href="https://www.last.fm/music/Benito+Kamelas">Read more on Last.fm</a>'},
 {'artista': 'Soda Stereo',
  'oyentes': '688011',
  'reproducciones': '46533412',
  'bio_resumen': 'Soda Stereo was a rock power trio formed in Buenos Aires, Argentina in 1982. Consisting of guitarist and vocalist Gustavo Cerati, bassist Zeta Bosio and drummer Charly Alberti, the band established what would become the template for many other popular Spanish-speaking pop and rock music groups: Clever, often mysterious lyrics, pleasing musical arrangements and an elaborate and glamorous aesthetic image.\n\nThough nominally thought of as a new wave or alternative rock group <a href="https://www.last.fm/music/Soda+Stereo">Read more on Last.fm</a>'},
 {'artista': 'Mogwai',
  'oyentes': '1673333',
  'reproducciones': '90836927',
  'bio_resumen': 'Mogwai is a Scottish post-rock/instrumental band from Glasgow formed in 1995. \nThey compose lengthy, mostly instrumental guitar-based pieces in the style of post-rock, usually focused around the elaboration of a single theme, and are known traditionally for their quiet/loud dynamic, defined bass riffs, and an eminent ambient sound, sometimes dark and sometimes grand. Although frequently referred to as post-rock, the band have revealed in interviews that they despise this categorization <a href="https://www.last.fm/music/Mogwai">Read more on Last.fm</a>'},
 {'artista': 'HALCALI',
  'oyentes': '291522',
  'reproducciones': '6302179',
  'bio_resumen': 'HALCALI is a Japanese rap-pop duo from Tokyo\'s Meguro district. Its two members, Haruka (Halca) and Yukari (Yucali) also comprise the group\'s name; a concatenation of "Haru" and "kari". Haruka, born April 21, 1988 and Yukari, born July 18, 1987 originally met as finalists at a hip-hop audition held in a local school in the Meguro district, where both were born. \n\nAt their inception, the girls were produced by Oshare Track Factory (OTF) comprised of producing artists Rip Slyme <a href="https://www.last.fm/music/HALCALI">Read more on Last.fm</a>'},
 {'artista': 'Breaking Benjamin',
  'oyentes': '2796506',
  'reproducciones': '129779018',
  'bio_resumen': 'Breaking Benjamin is an alternative metal band Formed in Wilkes-Barre, Pennsylvania, USA in 1998 by vocalist Benjamin Burnley and drummer Jeremy Hummel, Breaking Benjamin quickly garnered a strong local following. \n\n1st Studio Album (2002) - Saturate\nThe band signed to Hollywood Records in 2001 after the success of an independently-released, self-titled EP, which sold all 2,000 copies that were manufactured. Hollywood Records released their full-length, major-label debut, Saturate, on August 27, 2002. <a href="https://www.last.fm/music/Breaking+Benjamin">Read more on Last.fm</a>'},
 {'artista': 'The Smashing Pumpkins',
  'oyentes': '4372936',
  'reproducciones': '241159678',
  'bio_resumen': 'The Smashing Pumpkins is an American alternative rock band from Chicago. The band was formed in 1988 by Billy Corgan and James Iha, with bassist D\'arcy Wretzky  and drummer Jimmy Chamberlin joining shortly after. Despite going through many lineup changes, the current lineup is identical to the original, with the exception of Wretzky, who would end up leaving the band just before their initial breakup in 2000.\n\nDisavowing the punk rock roots of many of their alt-rock contemporaries <a href="https://www.last.fm/music/The+Smashing+Pumpkins">Read more on Last.fm</a>'},
 {'artista': 'Mark Knopfler',
  'oyentes': '820691',
  'reproducciones': '24109823',
  'bio_resumen': 'Mark Freuder Knopfler, OBE (born 12 August 1949) is a British singer, guitarist, composer, songwriter, record producer, and film score composer. He was the lead guitarist, lead singer, and songwriter for the rock band Dire Straits, which he co-founded with his younger brother, David Knopfler, in 1977. He was born in Glasgow but raised near Newcastle upon Tyne, England.\n\nSince Dire Straits disbanded in 1995, Knopfler has recorded and produced nine solo albums and, as with his previous band, produced many hit songs. <a href="https://www.last.fm/music/Mark+Knopfler">Read more on Last.fm</a>'},
 {'artista': "O'Funk'illo",
  'oyentes': '39154',
  'reproducciones': '635346',
  'bio_resumen': 'O\'funkillo es un grupo musical sevillano de funky ("Funky andaluz embrutessío" según los propios miembros del grupo). Su nombre proviene de mezclar la expresión sevillana "ojú killo" con el funk, principal estilo de la banda. Aparte del funk, O\'funk\'illo cuenta con una gran variedad de estilos en sus composiciones, desde el metal al flamenco, pasando por el reggae.\n\nLos comienzos de O\'funk\'illo se remontan al año 1997, cuando actuaban bajo el nombre de Motherfunkers, principalmente haciendo versiones. <a href="https://www.last.fm/music/O%27Funk%27illo">Read more on Last.fm</a>'},
 {'artista': 'La Mosca',
  'oyentes': '75029',
  'reproducciones': '456367',
  'bio_resumen': 'Si bien la formación actual del grupo se consolida en marzo de 1995, la historia de la banda se remonta a comienzos de los noventa con "La Reggae & Roll Band", quienes hacían covers y algunos temas propios en la zona de Ramallo. Simultáneamente existían otras bandas entre las que se destacaba "Damas gratis" liderada por Guillermo Novellis.\nTras la disolución de "Damas gratis", Fernando Castro, que era el baterista y uno de los fundadores (de La Reggae)  <a href="https://www.last.fm/music/+noredirect/La+Mosca">Read more on Last.fm</a>'},
 {'artista': 'Rage Against the Machine',
  'oyentes': '4144297',
  'reproducciones': '157574860',
  'bio_resumen': 'Rage Against the Machine was an American rock band from Los Angeles, California. Formed in 1991, the group consisted of vocalist Zack de la Rocha, bassist and backing vocalist Tim Commerford, guitarist Tom Morello, and drummer Brad Wilk. Their songs express revolutionary left-wing political views. As of 2010, they had sold over 16 million records worldwide. In 2023, the band was inducted into the Rock and Roll Hall of Fame.\n\nRage Against the Machine released its eponymous debut album in 1992 to commercial and critical success <a href="https://www.last.fm/music/Rage+Against+the+Machine">Read more on Last.fm</a>'},
 {'artista': 'The Rolling Stones',
  'oyentes': '5668767',
  'reproducciones': '264301481',

### ----Extraemos el país de la biografía por que la api lastfm no nos facilita ese dato-------

In [21]:
# --- 1. DICCIONARIO BASE (PAÍS: GENTILICIO) ---
# Usamos el diccionario que generamos previamente:

PAIS_A_GENTILICIO = {
    "Afghanistan": "Afghan",
    "Albania": "Albanian",
    "Algeria": "Algerian",
    "Argentina": "Argentinian",
    "Australia": "Australian",
    "Austria": "Austrian",
    "Belgium": "Belgian",
    "Bolivia": "Bolivian",
    "Brazil": "Brazilian",
    "Canada": "Canadian",
    "Chile": "Chilean",
    "China": "Chinese",
    "Colombia": "Colombian",
    "Costa Rica": "Costa Rican",
    "Cuba": "Cuban",
    "Denmark": "Dane",
    "Egypt": "Egyptian",
    "France": "French",
    "Germany": "German",
    "Greece": "Greek",
    "India": "Indian",
    "Indonesia": "Indonesian",
    "Ireland": "Irish",
    "Italy": "Italian",
    "Jamaica": "Jamaican",
    "Japan": "Japanese",
    "Mexico": "Mexican",
    "Netherlands": "Dutch",
    "New Zealand": "New Zealander",
    "Nigeria": "Nigerian",
    "Norway": "Norwegian",
    "Peru": "Peruvian",
    "Poland": "Pole",
    "Portugal": "Portuguese",
    "Russia": "Russian",
    "South Korea": "South Korean",
    "Spain": "Spaniard",
    "Sweden": "Swede",
    "Turkey": "Turk",
    "Ukraine": "Ukrainian",
    "United Kingdom": "Briton",
    "United States": "American",
    "United States_adj": "American", 
    "United Kingdom_adj": "British",
    "France_adj": "French",
    "Germany_adj": "German",
    "Spain_adj": "Spanish"}

# --- 2. DICCIONARIO INVERTIDO PARA BÚSQUEDA EFICIENTE ---
# Clave: Gentilicio (lo que busco en la bio), Valor: País
GENTILICIO_A_PAIS = {gentilicio.lower(): pais.replace('_adj', '') 
    for pais, gentilicio in PAIS_A_GENTILICIO.items()}

In [22]:
def extraer_pais_de_biografia(bio_resumen, gentilicio_a_pais_map):
  
    bio_normalizada = bio_resumen.lower()


    for gentilicio, pais in gentilicio_a_pais_map.items():

        # Usamos ' ' + gentilicio + ' ' para buscar la palabra completa y evitar coincidencias parciales
        if f' {gentilicio} ' in bio_normalizada or bio_normalizada.startswith(f'{gentilicio} '):
            return pais
        
        # Caso especial para "is an American rock band" (no tiene espacio antes)
        if bio_normalizada.endswith(gentilicio): 
             return pais

    return ''

#### Agregamos la key "pais" a nuestra lista

In [23]:
for artista_data in lista_artistas:
  
    bio = artista_data['bio_resumen']
    pais_encontrado = extraer_pais_de_biografia(bio, GENTILICIO_A_PAIS)
    
    artista_data['pais'] = pais_encontrado #aqui agregamos la clave pais en nuestro diccionario

In [24]:
lista_artistas

[{'artista': 'Patricio Rey y sus Redonditos de Ricota',
  'oyentes': '98653',
  'reproducciones': '10286980',
  'bio_resumen': 'Patricio Rey y sus Redonditos de Ricota was a rock band originally from La Plata, Argentina in 1976. Their tours in the 1980s, 1990s and 2000s drew a cult-like following that mirrored Grateful Dead frenzy in the United States. \n\nThe band\'s strength lies in the semantic power of its lyrics, which discuss different topics such as politics, drugs and women, but always from a philosophical and existential point of view. The band represented a counter-cultural paradigm, reinforced and supported by its truly independent production nature.  <a href="https://www.last.fm/music/Patricio+Rey+y+sus+Redonditos+de+Ricota">Read more on Last.fm</a>',
  'pais': ''},
 {'artista': 'Hombres G',
  'oyentes': '493105',
  'reproducciones': '9600712',
  'bio_resumen': 'Spanish pop/rock foursome Hombres G was formed by ex-los Residuos guitarist Daniel Mezquita, drummer Javier Molina, and singer/bassist David Summers, soon joined by guitarist Rafael Gutierrez. The band\'s name was based on an American movie called G-Men. Hombres G made its live debut at Madrid\'s Rockola, recording a demo called Milagro En El Congo in 1984. They soon signed up to the independent label Twins to make their debut album, featuring a catchy song called "Devuelveme A Mi Chica," which became their first hit. <a href="https://www.last.fm/music/Hombres+G">Read more on Last.fm</a>',
  'pais': 'United States'},
 {'artista': 'Airbag',
  'oyentes': '170445',
  'reproducciones': '7705481',
  'bio_resumen': 'There are  at least 9 bands with the same name:\n\n1. Airbag,  from Norway\n2. Airbag, from Spain\n3. Airbag, from Argentina\n4. Airbag, from South Korea.\n5. Airbag, from Bulgaria\n6. Airbag, from the Netherlands\n7. Airbag, from China\n8. Airbag, from Japan\n9. Airbag, from Czech Republic\n\n1 .Airbag is a five member progressive rock group from Norway. The line up (from 2010) is Anders Hovdan - Bass, Asle Tostrup - Vocals, guitar, Bjørn Riis - Guitar, vocals, Henrik Fossum - Drums and Jørgen Hagen - Keyboards. <a href="https://www.last.fm/music/Airbag">Read more on Last.fm</a>',
  'pais': ''},
 {'artista': 'Thousand Foot Krutch',
  'oyentes': '1138544',
  'reproducciones': '37218183',
  'bio_resumen': 'Thousand Foot Krutch (often abbreviated TFK) is a Canadian Christian rock band from Peterborough, Ontario, Canada. They made their debut in 1995 when Trevor McNevan, Joel Bruyere, and Steve Augustine started putting a praise & worship spin on the nu-metal sound of the time. After building a buzz around Ontario with numerous shows and a strong demo titled That\'s What People Do, Thousand Foot Krutch signed with Diamante and issued their debut LP, Set It Off, in 2000. <a href="https://www.last.fm/music/Thousand+Foot+Krutch">Read more on Last.fm</a>',
  'pais': 'Canada'},
 {'artista': 'Three Days Grace',
  'oyentes': '3710774',
  'reproducciones': '172257837',
  'bio_resumen': 'Three Days Grace is a Canadian rock band, formed under the name Groundswell in Norwood, Ontario, Canada in 1992. After a breakup in 1995, the band reformed in 1997 under its current name and with a line-up consisting of guitarist and lead vocalist Adam Gontier, drummer and backing vocalist Neil Sanderson, and bassist Brad Walst. In 2003, Barry Stock was recruited as the band\'s lead guitarist. The band has released seven studio albums, with a record fourteen #1 hits on Mainstream Rock. <a href="https://www.last.fm/music/Three+Days+Grace">Read more on Last.fm</a>',
  'pais': 'Canada'},
 {'artista': 'Modest Mouse',
  'oyentes': '3338417',
  'reproducciones': '198122770',
  'bio_resumen': 'Modest Mouse is an American alternative rock band which formed in 1993 in Issaquah, Washington, United States. The band\'s original lineup consisted of guitarist Isaac Brock, drummer Jeremiah Green and bassist Eric Judy. Since being signed to Sony\'s Epic Records in 2000, Modest Mouse has attained significant popular success with songs such as "Float On" and "Dashboard."\n\nThe band\'s current configuration is Isaac Brock (vocals, guitar), Tom Peloso (strings, horns, bass, keyboards), Jim Fairchild (guitar), and Eric Judy (bass)). <a href="https://www.last.fm/music/Modest+Mouse">Read more on Last.fm</a>',
  'pais': 'United States'},
 {'artista': 'The The',
  'oyentes': '679853',
  'reproducciones': '10427433',
  'bio_resumen': 'The The are an English post-punk band. They have been active in various forms since 1979, with singer-songwriter Matt Johnson being the only constant band member. The The achieved critical acclaim and commercial success in the UK, with 15 chart singles (seven reaching the top 40), and their most successful album, Infected (1986), spent 30 weeks on the chart. They followed this with the top ten albums Mind Bomb (1989) and Dusk (1993).\n\nEarly years (1977–1981) <a href="https://www.last.fm/music/The+The">Read more on Last.fm</a>',
  'pais': ''},
 {'artista': 'Os Paralamas Do Sucesso',
  'oyentes': '478170',
  'reproducciones': '12542860',
  'bio_resumen': 'Three young guys who had in common their love for rock, reggae and ska - Herbert Vianna, Bi Ribeiro and João Barone - formed the group Paralamas at the beginning of the 80’s inspired by the sonority of groups as The Police, The Beat and The Specials, that used to recycle the rhythms created in Jamaica. \n\nStimulated by the talent and the interest in the rising phenomenon of the Brazilian Rock, soon they had recorded their first LP “Cinema Mudo” <a href="https://www.last.fm/music/Os+Paralamas+Do+Sucesso">Read more on Last.fm</a>',
  'pais': 'Brazil'},
 {'artista': 'Velvet Revolver',
  'oyentes': '1155293',
  'reproducciones': '20375976',
  'bio_resumen': 'Velvet Revolver was an American hard rock supergroup consisting of Guns N\'Roses members Slash (lead guitar), Duff McKagan (bass, backing vocals) and Matt Sorum (drums, backing vocals), alongside Dave Kushner (rhythm guitar) formerly of punk band Wasted Youth, and Scott Weiland (lead vocalist) formerly of Stone Temple Pilots. The band formed in 2002 and was active until 2008, when Weiland left the band abruptly to rejoin Stone Temple Pilots.\n\nIn 2004, the band achieved commercial success with their debut album, Contraband. <a href="https://www.last.fm/music/Velvet+Revolver">Read more on Last.fm</a>',
  'pais': 'United States'},
 {'artista': 'Ozzy Osbourne',
  'oyentes': '3003780',
  'reproducciones': '90643775',
  'bio_resumen': 'Ozzy Osbourne (born John Michael Osbourne in Marston Green, Warwickshire, on 3 December 1948; died 22 July 2025) was an English singer, songwriter, and media personality remembered as the lead vocalist of the heavy metal band Black Sabbath, during which period he adopted the nickname "Prince of Darkness". On 5 July 2025, Osbourne performed his final show at the "Back to the Beginning" concert event. \n\nHe was inducted into the Rock and Roll Hall of Fame as a member of Black Sabbath in 2006 and as a solo artist in 2024. <a href="https://www.last.fm/music/Ozzy+Osbourne">Read more on Last.fm</a>',
  'pais': ''},
 {'artista': 'Embrace',
  'oyentes': '663132',
  'reproducciones': '8808046',
  'bio_resumen': 'Embrace is the name of more than one artist:\n1) an alternative rock band from Brighouse, West Yorkshire, England\n2) a short-lived post-hardcore band from Washington, D.C., USA\n3) a collaboration between dutch trance producers Ferry Corsten and Raz Nitzan\n4) a Gothic Metal band from Toronto, Canada\n\n1) Embrace is a five-piece alternative rock band from Brighouse, West Yorkshire, England, consisting of brothers Danny McNamara (singer) and Richard McNamara (guitarist) as well as Steve Firth (bassist) <a href="https://www.last.fm/music/Embrace">Read more on Last.fm</a>',
  'pais': 'Netherlands'},
 {'artista': 'Bushido',
  'oyentes': '262008',
  'reproducciones': '15248031',
  'bio_resumen': 'There is more than one artist with this name: a German rapper, a Latin pop act, a post-punk band and a prog rock band from Australia.\n\n1) German rapper Anis Ferchichi who was born on September 28, 1978 in Bonn. His rap is strongly influenced by French Gangsta Rap. He is also known as Sonny Black.\nEarly Life:\nBushido has a Tunisian father and a German mother. However, he was raised in Berlin by his mother and never got to know his father.\n\nMusical Career: <a href="https://www.last.fm/music/Bushido">Read more on Last.fm</a>',
  'pais': 'France'},
 {'artista': 'Divididos',
  'oyentes': '129785',
  'reproducciones': '3756470',
  'bio_resumen': 'Divididos ("Divided") is a rock band from Argentina with a significant place in the history of Argentine rock. Formed in 1988 after the death of Luca Prodan and the consequent dissolution of Sumo, Ricardo Mollo (vocals, guitar) and Diego Arnedo (bass guitar) joined drummer Gustavo Collado to form a band named "La División" (The Division), which would be later called "Divididos". (Another band emerged from the ashes of Sumo: Las Pelotas.)\n\nLa Aplanadora del Rock is known for mixing rock with Argentine folk music, and hard-to-get lyrics. <a href="https://www.last.fm/music/Divididos">Read more on Last.fm</a>',
  'pais': ''},
 {'artista': 'Queens of the Stone Age',
  'oyentes': '3623476',
  'reproducciones': '244886720',
  'bio_resumen': 'Queens of the Stone Age is a rock band from Palm Desert, California, United States. The band is frequently labeled stoner rock, although they reject the label. They developed a style of riff-oriented, heavy music which the band\'s founder and mastermind Josh Homme described as "robot rock", saying that he "wanted to create a heavy sound based on a solid jam, just pound it into your head". Since then, their sound has evolved to incorporate a variety of different styles and influences. <a href="https://www.last.fm/music/Queens+of+the+Stone+Age">Read more on Last.fm</a>',
  'pais': ''},
 {'artista': 'Indio Solari',
  'oyentes': '28009',
  'reproducciones': '1299564',
  'bio_resumen': 'Indio Solari (born Carlos Solari, c. 1949) is an Argentine singer and musician. He was leader of Patricio Rey y sus Redonditos de Ricota between 1976 and 2002. He got separated from Redondos and then started his first solo work in 2004 called El Tesoro de los Inocentes (Bingo Fuel)), together with his backing band Los Fundamentalistas del Aire Acondicionado. In 2007 he released his second solo album Porco Rex.  <a href="https://www.last.fm/music/Indio+Solari">Read more on Last.fm</a>',
  'pais': ''},
 {'artista': 'La Vela Puerca',
  'oyentes': '139843',
  'reproducciones': '4257844',
  'bio_resumen': 'La Vela Puerca is "Uruguay\'s most famous ska-rock-band". It was founded 1995 in Montevideo.\n\nIts founders were Sebastián Teysera (lead vocals, frontman and main songwriter), Nicolás Lieutier (bass guitar) and Santiago Butler (guitar) - all three are still part of the band today. The band\'s first appearance as La Vela Puerca was in a montevidean street party in December 24, 1995. By then, several new members had already joined in. In 1996, frontman Sebastián Teysera presented a demo tape to a band contest. <a href="https://www.last.fm/music/La+Vela+Puerca">Read more on Last.fm</a>',
  'pais': ''},
 {'artista': 'A Perfect Circle',
  'oyentes': '2146828',
  'reproducciones': '111049054',
  'bio_resumen': 'A Perfect Circle is an American alternative rock band formed in Los Angeles, California in 1999 by guitarist Billy Howerdel and Tool vocalist Maynard James Keenan. A Perfect Circle has released four studio albums, the first three during the early 2000s: Mer de Noms, their debut album in 2000, and followed up by Thirteenth Step in 2003; then in 2004, Emotive—an album of radically re-worked cover songs. Shortly after Emotive\'s release, the band went on hiatus; Keenan returned to Tool and started up solo work under the band name Puscifer <a href="https://www.last.fm/music/A+Perfect+Circle">Read more on Last.fm</a>',
  'pais': 'United States'},
 {'artista': 'Silver Mt. Zion',
  'oyentes': '186773',
  'reproducciones': '3229690',
  'bio_resumen': 'A Silver Mt. Zion is a band formed in 1999, in Montreal, Canada, by Godspeed You! Black Emperor musicians Efrim Menuck, Sophie Trudeau and Thierry Amar. According to an interview with VPRO Radio in The Netherlands, originally the project was for Efrim to learn how to score music, but the idea was soon abandoned as Efrim decided that he preferred music not to be defined by rules, preferring simply what sounds best. Despite this, he continued the project <a href="https://www.last.fm/music/+noredirect/Silver+Mt.+Zion">Read more on Last.fm</a>',
  'pais': ''},
 {'artista': 'Nirvana',
  'oyentes': '7280628',
  'reproducciones': '549762503',
  'bio_resumen': 'There are multiple artists tracked as "Nirvana" on Last.fm. Following are six, listed in order of prominence:\n\n1) Nirvana was a popular and highly influential American grunge band. The band formed in Aberdeen, Washington in 1987, and it was part of the Seattle grunge scene of the late 80s, alongside bands like Pearl Jam, Alice in Chains and Soundgarden. As their popularity rose, alternative rock became a dominant genre on American and Canadian radio and music television during the early-to-mid \'90s. <a href="https://www.last.fm/music/Nirvana">Read more on Last.fm</a>',
  'pais': 'Canada'},
 {'artista': 'Alfredo Pardo- Spanish Pop',
  'oyentes': '1667',
  'reproducciones': '6491',
  'bio_resumen': 'biografia no encontrada',
  'pais': ''},
 {'artista': 'Benito Kamelas',
  'oyentes': '16777',
  'reproducciones': '360067',
  'bio_resumen': 'The spanish rock group BENITO KAMELAS se caracteriza por hacer un Rock fresco, cotidiano y divertido pero lo mejor es su puesta en escena. En Diciembre de 1997 graban un Cd con seis cortes (QUE MÁS DA)y empiezan a moverlo sin ningún tipo de apoyo de ninguna compañía, promocionandolo en directo por capitales como Teruel, Zaragoza, Córdoba, Tarragona, Castellón, y Alicante.\nAsombrados por haber vendido 1.500 copias (mano en mano y algún garito) <a href="https://www.last.fm/music/Benito+Kamelas">Read more on Last.fm</a>',
  'pais': 'Spain'},
 {'artista': 'Soda Stereo',
  'oyentes': '688011',
  'reproducciones': '46533412',
  'bio_resumen': 'Soda Stereo was a rock power trio formed in Buenos Aires, Argentina in 1982. Consisting of guitarist and vocalist Gustavo Cerati, bassist Zeta Bosio and drummer Charly Alberti, the band established what would become the template for many other popular Spanish-speaking pop and rock music groups: Clever, often mysterious lyrics, pleasing musical arrangements and an elaborate and glamorous aesthetic image.\n\nThough nominally thought of as a new wave or alternative rock group <a href="https://www.last.fm/music/Soda+Stereo">Read more on Last.fm</a>',
  'pais': ''},
 {'artista': 'Mogwai',
  'oyentes': '1673333',
  'reproducciones': '90836927',
  'bio_resumen': 'Mogwai is a Scottish post-rock/instrumental band from Glasgow formed in 1995. \nThey compose lengthy, mostly instrumental guitar-based pieces in the style of post-rock, usually focused around the elaboration of a single theme, and are known traditionally for their quiet/loud dynamic, defined bass riffs, and an eminent ambient sound, sometimes dark and sometimes grand. Although frequently referred to as post-rock, the band have revealed in interviews that they despise this categorization <a href="https://www.last.fm/music/Mogwai">Read more on Last.fm</a>',
  'pais': ''},
 {'artista': 'HALCALI',
  'oyentes': '291522',
  'reproducciones': '6302179',
  'bio_resumen': 'HALCALI is a Japanese rap-pop duo from Tokyo\'s Meguro district. Its two members, Haruka (Halca) and Yukari (Yucali) also comprise the group\'s name; a concatenation of "Haru" and "kari". Haruka, born April 21, 1988 and Yukari, born July 18, 1987 originally met as finalists at a hip-hop audition held in a local school in the Meguro district, where both were born. \n\nAt their inception, the girls were produced by Oshare Track Factory (OTF) comprised of producing artists Rip Slyme <a href="https://www.last.fm/music/HALCALI">Read more on Last.fm</a>',
  'pais': 'Japan'},
 {'artista': 'Breaking Benjamin',
  'oyentes': '2796506',
  'reproducciones': '129779018',
  'bio_resumen': 'Breaking Benjamin is an alternative metal band Formed in Wilkes-Barre, Pennsylvania, USA in 1998 by vocalist Benjamin Burnley and drummer Jeremy Hummel, Breaking Benjamin quickly garnered a strong local following. \n\n1st Studio Album (2002) - Saturate\nThe band signed to Hollywood Records in 2001 after the success of an independently-released, self-titled EP, which sold all 2,000 copies that were manufactured. Hollywood Records released their full-length, major-label debut, Saturate, on August 27, 2002. <a href="https://www.last.fm/music/Breaking+Benjamin">Read more on Last.fm</a>',
  'pais': ''},
 {'artista': 'The Smashing Pumpkins',
  'oyentes': '4372936',
  'reproducciones': '241159678',
  'bio_resumen': 'The Smashing Pumpkins is an American alternative rock band from Chicago. The band was formed in 1988 by Billy Corgan and James Iha, with bassist D\'arcy Wretzky  and drummer Jimmy Chamberlin joining shortly after. Despite going through many lineup changes, the current lineup is identical to the original, with the exception of Wretzky, who would end up leaving the band just before their initial breakup in 2000.\n\nDisavowing the punk rock roots of many of their alt-rock contemporaries <a href="https://www.last.fm/music/The+Smashing+Pumpkins">Read more on Last.fm</a>',
  'pais': 'United States'},
 {'artista': 'Mark Knopfler',
  'oyentes': '820691',
  'reproducciones': '24109823',
  'bio_resumen': 'Mark Freuder Knopfler, OBE (born 12 August 1949) is a British singer, guitarist, composer, songwriter, record producer, and film score composer. He was the lead guitarist, lead singer, and songwriter for the rock band Dire Straits, which he co-founded with his younger brother, David Knopfler, in 1977. He was born in Glasgow but raised near Newcastle upon Tyne, England.\n\nSince Dire Straits disbanded in 1995, Knopfler has recorded and produced nine solo albums and, as with his previous band, produced many hit songs. <a href="https://www.last.fm/music/Mark+Knopfler">Read more on Last.fm</a>',
  'pais': 'United Kingdom'},
 {'artista': "O'Funk'illo",
  'oyentes': '39154',
  'reproducciones': '635346',
  'bio_resumen': 'O\'funkillo es un grupo musical sevillano de funky ("Funky andaluz embrutessío" según los propios miembros del grupo). Su nombre proviene de mezclar la expresión sevillana "ojú killo" con el funk, principal estilo de la banda. Aparte del funk, O\'funk\'illo cuenta con una gran variedad de estilos en sus composiciones, desde el metal al flamenco, pasando por el reggae.\n\nLos comienzos de O\'funk\'illo se remontan al año 1997, cuando actuaban bajo el nombre de Motherfunkers, principalmente haciendo versiones. <a href="https://www.last.fm/music/O%27Funk%27illo">Read more on Last.fm</a>',
  'pais': ''},
 {'artista': 'La Mosca',
  'oyentes': '75029',
  'reproducciones': '456367',
  'bio_resumen': 'Si bien la formación actual del grupo se consolida en marzo de 1995, la historia de la banda se remonta a comienzos de los noventa con "La Reggae & Roll Band", quienes hacían covers y algunos temas propios en la zona de Ramallo. Simultáneamente existían otras bandas entre las que se destacaba "Damas gratis" liderada por Guillermo Novellis.\nTras la disolución de "Damas gratis", Fernando Castro, que era el baterista y uno de los fundadores (de La Reggae)  <a href="https://www.last.fm/music/+noredirect/La+Mosca">Read more on Last.fm</a>',
  'pais': ''},
 {'artista': 'Rage Against the Machine',
  'oyentes': '4144297',
  'reproducciones': '157574860',

In [25]:
import pandas as pd

In [26]:
df_rock_bio = pd.DataFrame(lista_artistas)

In [27]:
df_rock_bio

,artista,oyentes,reproducciones,bio_resumen,pais
0,Patricio Rey y sus Redonditos de Ricota,98653,10286980,Patricio Rey y sus Redonditos de Ricota was a ...,
1,Hombres G,493105,9600712,Spanish pop/rock foursome Hombres G was formed...,United States
2,Airbag,170445,7705481,There are at least 9 bands with the same name...,
3,Thousand Foot Krutch,1138544,37218183,Thousand Foot Krutch (often abbreviated TFK) i...,Canada
4,Three Days Grace,3710774,172257837,"Three Days Grace is a Canadian rock band, form...",Canada
...,...,...,...,...,...
228,The White Stripes,4723419,194845348,The White Stripes was an alternative rock band...,
229,Five for Fighting,1001944,12457597,Five for Fighting is the stage name of U.S. si...,
230,Gustavo Cerati,497364,37096254,"Gustavo Adrián Cerati Clarke, (Buenos Aires - ...",
231,Robbie Williams,2767784,69627507,Robert Peter Williams (born 13 February 1974) ...,
232,Panchiko,1001231,66524330,Panchiko are an English alternative rock band ...,

In [29]:
df_rock_bio.to_csv("df_rock_bio.csv")