In [1]:
import csv
import requests
import pandas as pd
import os

In [ ]:
#cliente = "clave"
url_api = "http://ws.audioscrobbler.com/2.0/"

In [3]:
#cliente = key de last Fm

In [3]:
def llamar_lastfm_api(method, artist_name, cliente):

        params = {'method': method,'artist': artist_name,'api_key': cliente,'format': 'json'}

        response = requests.get(url_api, params=params)

        if response.status_code == 200:
            return response.json()
        else:
            print(f"Error {response.status_code}: No se pudo obtener la información para el método {method}")
            return

In [4]:

def csv_a_lista_de_tuplas(df_reggae):
    lista_de_tuplas = []
    try:
        print(f"Intentando abrir: {df_reggae}")
        with open(df_reggae, 'r', newline='', encoding='utf-8') as archivo_csv:
            lector_csv = csv.reader(archivo_csv)
            lista_de_tuplas = [tuple(fila) for fila in lector_csv]
        print(f"Leídas {len(lista_de_tuplas)} filas.")
        return lista_de_tuplas
    except FileNotFoundError:
        print(f"Error: El archivo '{df_reggae}' no fue encontrado.")
        return []
    except Exception as e:
        print(f"Ocurrió un error: {e}")
        return []

In [5]:
resultado = csv_a_lista_de_tuplas("df_reggae.csv")
print(resultado[:5])

Intentando abrir: df_reggae.csv
Leídas 751 filas.
[('', 'Artista', 'Género', 'Tipo', 'Nombre', 'Año', 'ID'), ('0', 'Los Rabanes', 'reggae', 'track', 'Señorita a Mi Me Gusta Su Style', '2000', '2jvsbpAxcBkFp6VScarkzT'), ('1', 'Shaggy', 'reggae', 'track', 'Luv Me, Luv Me', '2000', '7hV4x7PMKGC4qD3NWLt2UJ'), ('2', 'Sean Paul', 'reggae', 'track', 'Infiltrate', '2000', '0ru8bc0XnKjUL2O1Fl1k7a'), ('3', 'Ganja', 'reggae', 'track', 'Caminando', '2000', '5hirK8wva1Nh38fVwWdLlc')]

In [6]:
print(os.getcwd())  # muestra el directorio actual
print(os.listdir())  # lista los archivos en esa carpeta

c:\Users\elepf\Desktop\da-project-promo-60-modulo-2-team-1\api_lastfm\archivos_ipynb
['.DS_Store', 'artistas_blues.ipynb', 'artistas_electronica.ipynb', 'artistas_reggae.ipynb', 'artistas_rock_bio.ipynb', 'artista_reggae.csv', 'datos_genero_latin_pop_version1_LAST_FM.ipynb', 'df_latin_pop_LastFm.csv', 'df_reggae.csv']

In [7]:
df = pd.read_csv("df_reggae.csv")

In [8]:
df = pd.DataFrame(df)

df

,Unnamed: 0,Artista,Género,Tipo,Nombre,Año,ID
0,0,Los Rabanes,reggae,track,Señorita a Mi Me Gusta Su Style,2000,2jvsbpAxcBkFp6VScarkzT
1,1,Shaggy,reggae,track,"Luv Me, Luv Me",2000,7hV4x7PMKGC4qD3NWLt2UJ
2,2,Sean Paul,reggae,track,Infiltrate,2000,0ru8bc0XnKjUL2O1Fl1k7a
3,3,Ganja,reggae,track,Caminando,2000,5hirK8wva1Nh38fVwWdLlc
4,4,Sean Paul,reggae,track,Deport Them,2000,5KhypMVGqMI9mgsrrv2lxc
...,...,...,...,...,...,...,...
745,745,Los Fabulosos Cadillacs,reggae,track,Strawberry Fields Forever,2004,62Chy6UjYOxsUO87aCUamR
746,746,Holy Piby,reggae,track,My Time,2004,0A5hoqmtzca09KBqOgz3JX
747,747,Gentleman,reggae,track,Caan Hold Us Down (feat. Barrington Levy & Dad...,2004,3846AQ2m61cbQWFNyjCthl
748,748,Ivete Sangalo,reggae,track,Eva (Eva) / Alô Paixão / Beleza Rara - Ao Vivo,2004,3XFcR5aTojLGMMSsIKeHTx
749,749,Thievery Corporation,reggae,track,The Outernationalist - Rewound By Thievery Cor...,2004,3gSi1BsWjWBY0uD79KzxD1

In [9]:
artistas = df["Artista"]

In [10]:
artistas_unicos = set(artistas)

In [11]:
artistas_unicos

{'10 Ft. Ganja Plant',
 '311',
 'Adriana Lua',
 'Andre Toussaint',
 'Andy and Joey',
 'Anthony B',
 'Antidoping',
 'Aquasky Vs Masterblaster',
 'Ara Ketu',
 'Ardijah',
 'Aswad',
 'Axe Bahia',
 'Banda Bassotti',
 'Banda Beijo',
 'Banda Calypso',
 'Banda Eva',
 'Banda Kebradeira',
 'Bandits Of The Acoustic Revolution',
 'Barry Biggs',
 'Beenie Man',
 'Begoña Bang-Matu',
 'Ben Harper',
 'Beres Hammond',
 'Bernard Lavilliers',
 'Betagarri',
 'Bob Andy',
 'Bob Marley & The Wailers',
 'Bom Balanço',
 'Braga Boys',
 'Brother Culture',
 'Buju Banton',
 'Burning Spear',
 'Busta Rhymes',
 'Capleton',
 'Carlton & The Shoes',
 'Cañaman',
 'Chaka Demus & Pliers',
 'Cheb Mami',
 'Chiclete Com Banana',
 'Chimarruts',
 'Chulito Camacho',
 'Cordel Burrell',
 'Cornell Campbell',
 'Cultura Profética',
 'Culture',
 'Cutty Ranks',
 'Cypress Hill',
 'Dakidarria',
 'Damian Marley',
 'Dancing Mood',
 'Dandy',
 'Dandy Livingstone',
 'Daniela Mercury',
 'Dennis Brown',
 'Derrick Harriott',
 'Dezarie',
 'Dirtsman',
 'Discípulos de Otilia',
 'Discípulos de Otilla',
 'Dobby Dobson',
 'Dr. Calypso',
 'Dr. Ring Ding',
 'Dub Inc',
 'Easy Star All-Stars',
 'Edi Fitzroy',
 'El Gran Silencio',
 'El Roockie',
 'Elephant Man',
 'Ernest Ranglin',
 'Errol Dunkley',
 'Eve',
 'Fishbone',
 'Fly My Pretties',
 'Freddie McGregor',
 'Freddie McKay',
 'Freddie Notes',
 'Ganja',
 'Gecko Turner',
 'Gentleman',
 'Giuliano Palma & The BlueBeaters',
 'Glen Adams',
 'Glen Washington',
 'Goldfinger',
 'Gondwana',
 'Gregory Isaacs',
 'Greyhound',
 'Groundation',
 'Harry Belafonte',
 'Hawkeye',
 'Hepcat',
 'High Tone',
 'Holy Piby',
 'Hopeton Lewis',
 'Horace Andy',
 'Ike Bennett & The Crystalites',
 'Inspector',
 'Intoxicados',
 'Ivete Sangalo',
 'JAHSTA',
 'Jackie Mittoo',
 'Jah Spirit',
 'Jazz Jamaica All Stars',
 'Jennifer Lara',
 'Jimmy Cliff',
 'Jimmy Somerville',
 'Joe Budden',
 'Joe Dukie',
 'Joe Dukie & DJ Fitchie',
 'Johnny Osbourne',
 'Joyce Bond',
 'Judge Dread',
 'Junior Byles',
 'Junior Kelly',
 'Justin Hinds',
 'Kana',
 'Kanka',
 'Keith & Tex',
 'Ken Boothe',
 'Kevin Lyttle',
 'King Chango',
 'La Gran Orquesta Republicana',
 'La Kinky Beat',
 'La Mosca',
 'La Pulquería',
 'La Tremenda Korte',
 'LaMeka55',
 "Le Peuple de L'Herbe",
 'Lee "Scratch" Perry',
 'Lennie Hibbert',
 'Less Than Jake',
 'Lil Jon & The East Side Boyz',
 'Long Beach Dub Allstars',
 'Lord Kossity',
 'Lord Superior',
 'Los Auténticos Decadentes',
 'Los Cafres',
 'Los Calzones',
 'Los De Abajo',
 'Los Fabulosos Cadillacs',
 'Los Pericos',
 'Los Rabanes',
 'Luciano',
 'Lucky Dube',
 'Lutan Fyah',
 'Lynn Taitt',
 'Lyricson',
 'Macka B',
 'Mad Caddies',
 'Mallacán',
 'Manasseh',
 'Manu Chao',
 'Margareth Menezes',
 'Maskavo',
 'Massilia Sound System',
 'Meganoidi',
 'Michael Palmer',
 'Mikey Dread',
 'Misty In Roots',
 'Monsieur Lezard',
 'Morgan Heritage',
 'Morodo',
 'Mr Easy',
 'Mr. Vegas',
 'Nasio',
 'Natiruts',
 'New York Ska-Jazz Ensemble',
 'Nina Sky',
 'No Doubt',
 'Norma Fraser',
 'Notch',
 'Otis Gayle',
 'Panteon Rococo',
 'Patrice',
 'Pepper',
 'Peter Tosh',
 'Phoebe 1',
 'Phyllis Dillon',
 'Planta E Raiz',
 'Prince Buster',
 'Prince Jazzbo',
 'Quique Neira',
 'Rastrillos',
 'Reel Big Fish',
 'Resistencia Suburbana',
 'Rhythm & Sound',
 'Rita Marley',
 'Roots Manuva',
 'Rupee',
 'SOJA',
 'Salida Nula',
 'Salmonella Dub',
 'Salon Victoria',
 'Sasha',
 'Sean Paul',
 'Seeed',
 'Sergent Garcia',
 'Shabba Ranks',
 'Shaggy',
 'Sidney Crooks',
 'Sizzla',
 'Ska Cubano',
 'Ska-P',
 'Skalariak',
 'Skaparapid',
 'Skatalà',
 'Slightly Stoopid',
 'Slim Smith',
 'Streetlight Manifesto',
 'Sugar Daddy',
 'Sugar Minott',
 'Symarip',
 'T.O.K',
 'Talco',
 'Tanto Metro & Devonte',
 'Tanya Stephens',
 'Tapper Zukie',
 'Tchakabum',
 'Terra Samba',
 'Terry Linen',
 'The Aggrolites',
 'The Black Seeds',
 'The Burning Souls',
 'The Expendables',
 'The Gaylads',
 'The Heptones',
 'The Jamaicans',
 'The Limp Twins',
 'The Mighty Mighty Bosstones',
 'The Pioneers',
 'The Skatalites',
 'The Slackers',
 'The Soul Syndicate',
 'The Specials',
 'The Suicide Machines',
 'The Toasters',
 'The Uniques',
 'The Untouchables',
 'The Upsetters',
 'The Wailers',
 'Thievery Corporation',
 'Third World',
 'Tijuana No!',
 'Tiken Jah Fakoly',
 'Toots & The Maytals',
 'Twinset',
 'UB40',
 'Ventania',
 'Vibronics',
 'Wayne Wonder',
 'Winston McAnuff',
 'Wyclef Jean',
 'Zenzile',
 'Ziggy Marley',
 'É O Tchan'}

In [12]:
artistas_unicos
lista_artistas = []
for nombre_artista in artistas_unicos:
    print(f"--- Consultando: {nombre_artista} ---")
    datos_artista = llamar_lastfm_api('artist.getinfo', nombre_artista, cliente)
    if datos_artista and 'artist' in datos_artista:
        artista_data = datos_artista['artist']
        oyentes = artista_data.get('stats', {}).get('listeners', 'arista no encontrado')
        reproducciones = artista_data.get('stats', {}).get('playcount', 'N/D')
        bio_content = artista_data.get('bio', {}).get('content', '')
        if not bio_content or bio_content.strip() == "":
            bio_resumen = 'biografia no encontrada'
        else:
            bio_resumen = artista_data.get('bio', {}).get('summary')
        lista_artistas_dict = {'artista': artista_data.get('name', nombre_artista),'oyentes': oyentes, 'reproducciones': reproducciones, 'bio_resumen': bio_resumen}
        lista_artistas.append(lista_artistas_dict)
        print(f"Datos de {nombre_artista} procesados y guardados.")
    else:
        print(f"No se pudo obtener información de {nombre_artista}")

--- Consultando: Natiruts ---
Datos de Natiruts procesados y guardados.
--- Consultando: Sidney Crooks ---
Datos de Sidney Crooks procesados y guardados.
--- Consultando: Maskavo ---
Datos de Maskavo procesados y guardados.
--- Consultando: Justin Hinds ---
Datos de Justin Hinds procesados y guardados.
--- Consultando: Cordel Burrell ---
Datos de Cordel Burrell procesados y guardados.
--- Consultando: Dobby Dobson ---
Datos de Dobby Dobson procesados y guardados.
--- Consultando: Bob Andy ---
Datos de Bob Andy procesados y guardados.
--- Consultando: Ben Harper ---
Datos de Ben Harper procesados y guardados.
--- Consultando: Phyllis Dillon ---
Datos de Phyllis Dillon procesados y guardados.
--- Consultando: Less Than Jake ---
Datos de Less Than Jake procesados y guardados.
--- Consultando: Salon Victoria ---
Datos de Salon Victoria procesados y guardados.
--- Consultando: The Uniques ---
Datos de The Uniques procesados y guardados.
--- Consultando: Daniela Mercury ---
Datos de Daniela Mercury procesados y guardados.
--- Consultando: Jimmy Cliff ---
Datos de Jimmy Cliff procesados y guardados.
--- Consultando: Lil Jon & The East Side Boyz ---
Datos de Lil Jon & The East Side Boyz procesados y guardados.
--- Consultando: Inspector ---
Datos de Inspector procesados y guardados.
--- Consultando: Chiclete Com Banana ---
Datos de Chiclete Com Banana procesados y guardados.
--- Consultando: Fishbone ---
Datos de Fishbone procesados y guardados.
--- Consultando: Horace Andy ---
Datos de Horace Andy procesados y guardados.
--- Consultando: Patrice ---
Datos de Patrice procesados y guardados.
--- Consultando: Betagarri ---
Datos de Betagarri procesados y guardados.
--- Consultando: Los Auténticos Decadentes ---
Datos de Los Auténticos Decadentes procesados y guardados.
--- Consultando: Seeed ---
Datos de Seeed procesados y guardados.
--- Consultando: La Mosca ---
Datos de La Mosca procesados y guardados.
--- Consultando: Busta Rhymes ---
Datos de Busta Rhymes procesados y guardados.
--- Consultando: Ara Ketu ---
Datos de Ara Ketu procesados y guardados.
--- Consultando: The Specials ---
Datos de The Specials procesados y guardados.
--- Consultando: Mikey Dread ---
Datos de Mikey Dread procesados y guardados.
--- Consultando: Slightly Stoopid ---
Datos de Slightly Stoopid procesados y guardados.
--- Consultando: Barry Biggs ---
Datos de Barry Biggs procesados y guardados.
--- Consultando: New York Ska-Jazz Ensemble ---
Datos de New York Ska-Jazz Ensemble procesados y guardados.
--- Consultando: Banda Beijo ---
Datos de Banda Beijo procesados y guardados.
--- Consultando: The Jamaicans ---
Datos de The Jamaicans procesados y guardados.
--- Consultando: Joe Dukie ---
Datos de Joe Dukie procesados y guardados.
--- Consultando: Dirtsman ---
Datos de Dirtsman procesados y guardados.
--- Consultando: Discípulos de Otilla ---
Datos de Discípulos de Otilla procesados y guardados.
--- Consultando: The Suicide Machines ---
Datos de The Suicide Machines procesados y guardados.
--- Consultando: Luciano ---
Datos de Luciano procesados y guardados.
--- Consultando: Skatalà ---
Datos de Skatalà procesados y guardados.
--- Consultando: Pepper ---
Datos de Pepper procesados y guardados.
--- Consultando: Jah Spirit ---
Datos de Jah Spirit procesados y guardados.
--- Consultando: Judge Dread ---
Datos de Judge Dread procesados y guardados.
--- Consultando: Aquasky Vs Masterblaster ---
Datos de Aquasky Vs Masterblaster procesados y guardados.
--- Consultando: Ken Boothe ---
Datos de Ken Boothe procesados y guardados.
--- Consultando: The Upsetters ---
Datos de The Upsetters procesados y guardados.
--- Consultando: Ventania ---
Datos de Ventania procesados y guardados.
--- Consultando: Shaggy ---
Datos de Shaggy procesados y guardados.
--- Consultando: Monsieur Lezard ---
Datos de Monsieur Lezard procesados y guardados.
--- Consultando: Gecko Turner ---
Datos de Gecko Turner procesados y guardados.
--- Consultando: Vibronics ---
Datos de Vibronics procesados y guardados.
--- Consultando: Lord Kossity ---
Datos de Lord Kossity procesados y guardados.
--- Consultando: Notch ---
Datos de Notch procesados y guardados.
--- Consultando: Lee "Scratch" Perry ---
Datos de Lee "Scratch" Perry procesados y guardados.
--- Consultando: No Doubt ---
Datos de No Doubt procesados y guardados.
--- Consultando: The Toasters ---
Datos de The Toasters procesados y guardados.
--- Consultando: Eve ---
Datos de Eve procesados y guardados.
--- Consultando: Beres Hammond ---
Datos de Beres Hammond procesados y guardados.
--- Consultando: SOJA ---
Datos de SOJA procesados y guardados.
--- Consultando: Groundation ---
Datos de Groundation procesados y guardados.
--- Consultando: Lyricson ---
Datos de Lyricson procesados y guardados.
--- Consultando: Joyce Bond ---
Datos de Joyce Bond procesados y guardados.
--- Consultando: Discípulos de Otilia ---
Datos de Discípulos de Otilia procesados y guardados.
--- Consultando: Chaka Demus & Pliers ---
Datos de Chaka Demus & Pliers procesados y guardados.
--- Consultando: Terry Linen ---
Datos de Terry Linen procesados y guardados.
--- Consultando: Gondwana ---
Datos de Gondwana procesados y guardados.
--- Consultando: Dub Inc ---
Datos de Dub Inc procesados y guardados.
--- Consultando: El Roockie ---
Datos de El Roockie procesados y guardados.
--- Consultando: Carlton & The Shoes ---
Datos de Carlton & The Shoes procesados y guardados.
--- Consultando: Roots Manuva ---
Datos de Roots Manuva procesados y guardados.
--- Consultando: Long Beach Dub Allstars ---
Datos de Long Beach Dub Allstars procesados y guardados.
--- Consultando: Streetlight Manifesto ---
Datos de Streetlight Manifesto procesados y guardados.
--- Consultando: Massilia Sound System ---
Datos de Massilia Sound System procesados y guardados.
--- Consultando: Panteon Rococo ---
Datos de Panteon Rococo procesados y guardados.
--- Consultando: Junior Kelly ---
Datos de Junior Kelly procesados y guardados.
--- Consultando: The Black Seeds ---
Datos de The Black Seeds procesados y guardados.
--- Consultando: Dancing Mood ---
Datos de Dancing Mood procesados y guardados.
--- Consultando: Gentleman ---
Datos de Gentleman procesados y guardados.
--- Consultando: Lucky Dube ---
Datos de Lucky Dube procesados y guardados.
--- Consultando: Meganoidi ---
Datos de Meganoidi procesados y guardados.
--- Consultando: Lord Superior ---
Datos de Lord Superior procesados y guardados.
--- Consultando: The Gaylads ---
Datos de The Gaylads procesados y guardados.
--- Consultando: Fly My Pretties ---
Datos de Fly My Pretties procesados y guardados.
--- Consultando: Ernest Ranglin ---
Datos de Ernest Ranglin procesados y guardados.
--- Consultando: Tchakabum ---
Datos de Tchakabum procesados y guardados.
--- Consultando: The Untouchables ---
Datos de The Untouchables procesados y guardados.
--- Consultando: Rita Marley ---
Datos de Rita Marley procesados y guardados.
--- Consultando: Twinset ---
Datos de Twinset procesados y guardados.
--- Consultando: Rhythm & Sound ---
Datos de Rhythm & Sound procesados y guardados.
--- Consultando: Symarip ---
Datos de Symarip procesados y guardados.
--- Consultando: The Wailers ---
Datos de The Wailers procesados y guardados.
--- Consultando: Prince Jazzbo ---
Datos de Prince Jazzbo procesados y guardados.
--- Consultando: Beenie Man ---
Datos de Beenie Man procesados y guardados.
--- Consultando: Ziggy Marley ---
Datos de Ziggy Marley procesados y guardados.
--- Consultando: Morodo ---
Datos de Morodo procesados y guardados.
--- Consultando: The Expendables ---
Datos de The Expendables procesados y guardados.
--- Consultando: The Heptones ---
Datos de The Heptones procesados y guardados.
--- Consultando: Prince Buster ---
Datos de Prince Buster procesados y guardados.
--- Consultando: Giuliano Palma & The BlueBeaters ---
Datos de Giuliano Palma & The BlueBeaters procesados y guardados.
--- Consultando: Ska Cubano ---
Datos de Ska Cubano procesados y guardados.
--- Consultando: Bernard Lavilliers ---
Datos de Bernard Lavilliers procesados y guardados.
--- Consultando: Manasseh ---
Datos de Manasseh procesados y guardados.
--- Consultando: Macka B ---
Datos de Macka B procesados y guardados.
--- Consultando: Kanka ---
Datos de Kanka procesados y guardados.
--- Consultando: Morgan Heritage ---
Datos de Morgan Heritage procesados y guardados.
--- Consultando: Nasio ---
Datos de Nasio procesados y guardados.
--- Consultando: Otis Gayle ---
Datos de Otis Gayle procesados y guardados.
--- Consultando: Mr. Vegas ---
Datos de Mr. Vegas procesados y guardados.
--- Consultando: Chimarruts ---
Datos de Chimarruts procesados y guardados.
--- Consultando: Antidoping ---
Datos de Antidoping procesados y guardados.
--- Consultando: Reel Big Fish ---
Datos de Reel Big Fish procesados y guardados.
--- Consultando: La Pulquería ---
Datos de La Pulquería procesados y guardados.
--- Consultando: Resistencia Suburbana ---
Datos de Resistencia Suburbana procesados y guardados.
--- Consultando: Junior Byles ---
Datos de Junior Byles procesados y guardados.
--- Consultando: Joe Budden ---
Datos de Joe Budden procesados y guardados.
--- Consultando: Glen Washington ---
Datos de Glen Washington procesados y guardados.
--- Consultando: El Gran Silencio ---
Datos de El Gran Silencio procesados y guardados.
--- Consultando: Tapper Zukie ---
Datos de Tapper Zukie procesados y guardados.
--- Consultando: Ardijah ---
Datos de Ardijah procesados y guardados.
--- Consultando: Zenzile ---
Datos de Zenzile procesados y guardados.
--- Consultando: Kana ---
Datos de Kana procesados y guardados.
--- Consultando: T.O.K ---
Datos de T.O.K procesados y guardados.
--- Consultando: Margareth Menezes ---
Datos de Margareth Menezes procesados y guardados.
--- Consultando: Freddie Notes ---
Datos de Freddie Notes procesados y guardados.
--- Consultando: Thievery Corporation ---
Datos de Thievery Corporation procesados y guardados.
--- Consultando: Los Rabanes ---
Datos de Los Rabanes procesados y guardados.
--- Consultando: Braga Boys ---
Datos de Braga Boys procesados y guardados.
--- Consultando: Shabba Ranks ---
Datos de Shabba Ranks procesados y guardados.
--- Consultando: Rastrillos ---
Datos de Rastrillos procesados y guardados.
--- Consultando: Jimmy Somerville ---
Datos de Jimmy Somerville procesados y guardados.
--- Consultando: Los Calzones ---
Datos de Los Calzones procesados y guardados.
--- Consultando: Kevin Lyttle ---
Datos de Kevin Lyttle procesados y guardados.
--- Consultando: High Tone ---
Datos de High Tone procesados y guardados.
--- Consultando: Ganja ---
Datos de Ganja procesados y guardados.
--- Consultando: Banda Eva ---
Datos de Banda Eva procesados y guardados.
--- Consultando: 311 ---
Datos de 311 procesados y guardados.
--- Consultando: É O Tchan ---
Datos de É O Tchan procesados y guardados.
--- Consultando: Sean Paul ---
Datos de Sean Paul procesados y guardados.
--- Consultando: Terra Samba ---
Datos de Terra Samba procesados y guardados.
--- Consultando: Jazz Jamaica All Stars ---
Datos de Jazz Jamaica All Stars procesados y guardados.
--- Consultando: Sizzla ---
Datos de Sizzla procesados y guardados.
--- Consultando: Planta E Raiz ---
Datos de Planta E Raiz procesados y guardados.
--- Consultando: Capleton ---
Datos de Capleton procesados y guardados.
--- Consultando: Jennifer Lara ---
Datos de Jennifer Lara procesados y guardados.
--- Consultando: Banda Calypso ---
Datos de Banda Calypso procesados y guardados.
--- Consultando: Chulito Camacho ---
Datos de Chulito Camacho procesados y guardados.
--- Consultando: Skalariak ---
Datos de Skalariak procesados y guardados.
--- Consultando: Tiken Jah Fakoly ---
Datos de Tiken Jah Fakoly procesados y guardados.
--- Consultando: Sergent Garcia ---
Datos de Sergent Garcia procesados y guardados.
--- Consultando: Ivete Sangalo ---
Datos de Ivete Sangalo procesados y guardados.
--- Consultando: La Tremenda Korte ---
Datos de La Tremenda Korte procesados y guardados.
--- Consultando: Errol Dunkley ---
Datos de Errol Dunkley procesados y guardados.
--- Consultando: Cornell Campbell ---
Datos de Cornell Campbell procesados y guardados.
--- Consultando: Intoxicados ---
Datos de Intoxicados procesados y guardados.
--- Consultando: Mad Caddies ---
Datos de Mad Caddies procesados y guardados.
--- Consultando: Dandy ---
Datos de Dandy procesados y guardados.
--- Consultando: The Pioneers ---
Datos de The Pioneers procesados y guardados.
--- Consultando: Greyhound ---
Datos de Greyhound procesados y guardados.
--- Consultando: Culture ---
Datos de Culture procesados y guardados.
--- Consultando: Buju Banton ---
Datos de Buju Banton procesados y guardados.
--- Consultando: The Aggrolites ---
Datos de The Aggrolites procesados y guardados.
--- Consultando: Sugar Minott ---
Datos de Sugar Minott procesados y guardados.
--- Consultando: Nina Sky ---
Datos de Nina Sky procesados y guardados.
--- Consultando: Gregory Isaacs ---
Datos de Gregory Isaacs procesados y guardados.
--- Consultando: Manu Chao ---
Datos de Manu Chao procesados y guardados.
--- Consultando: Banda Bassotti ---
Datos de Banda Bassotti procesados y guardados.
--- Consultando: Burning Spear ---
Datos de Burning Spear procesados y guardados.
--- Consultando: Talco ---
Datos de Talco procesados y guardados.
--- Consultando: Aswad ---
Datos de Aswad procesados y guardados.
--- Consultando: Tanya Stephens ---
Datos de Tanya Stephens procesados y guardados.
--- Consultando: Mallacán ---
Datos de Mallacán procesados y guardados.
--- Consultando: Elephant Man ---
Datos de Elephant Man procesados y guardados.
--- Consultando: The Mighty Mighty Bosstones ---
Datos de The Mighty Mighty Bosstones procesados y guardados.
--- Consultando: The Limp Twins ---
Datos de The Limp Twins procesados y guardados.
--- Consultando: Third World ---
Datos de Third World procesados y guardados.
--- Consultando: Cypress Hill ---
Datos de Cypress Hill procesados y guardados.
--- Consultando: Hepcat ---
Datos de Hepcat procesados y guardados.
--- Consultando: Dr. Calypso ---
Datos de Dr. Calypso procesados y guardados.
--- Consultando: Dr. Ring Ding ---
Datos de Dr. Ring Ding procesados y guardados.
--- Consultando: The Skatalites ---
Datos de The Skatalites procesados y guardados.
--- Consultando: Anthony B ---
Datos de Anthony B procesados y guardados.
--- Consultando: Dandy Livingstone ---
Datos de Dandy Livingstone procesados y guardados.
--- Consultando: Glen Adams ---
Datos de Glen Adams procesados y guardados.
--- Consultando: Rupee ---
Datos de Rupee procesados y guardados.
--- Consultando: Tanto Metro & Devonte ---
Datos de Tanto Metro & Devonte procesados y guardados.
--- Consultando: UB40 ---
Datos de UB40 procesados y guardados.
--- Consultando: La Kinky Beat ---
Datos de La Kinky Beat procesados y guardados.
--- Consultando: Skaparapid ---
Datos de Skaparapid procesados y guardados.
--- Consultando: Quique Neira ---
Datos de Quique Neira procesados y guardados.
--- Consultando: Lutan Fyah ---
Datos de Lutan Fyah procesados y guardados.
--- Consultando: Toots & The Maytals ---
Datos de Toots & The Maytals procesados y guardados.
--- Consultando: Easy Star All-Stars ---
Datos de Easy Star All-Stars procesados y guardados.
--- Consultando: Lennie Hibbert ---
Datos de Lennie Hibbert procesados y guardados.
--- Consultando: Edi Fitzroy ---
Datos de Edi Fitzroy procesados y guardados.
--- Consultando: Dakidarria ---
Datos de Dakidarria procesados y guardados.
--- Consultando: Wyclef Jean ---
Datos de Wyclef Jean procesados y guardados.
--- Consultando: Michael Palmer ---
Datos de Michael Palmer procesados y guardados.
--- Consultando: The Slackers ---
Datos de The Slackers procesados y guardados.
--- Consultando: Ska-P ---
Datos de Ska-P procesados y guardados.
--- Consultando: Cañaman ---
Datos de Cañaman procesados y guardados.
--- Consultando: Winston McAnuff ---
Datos de Winston McAnuff procesados y guardados.
--- Consultando: Cutty Ranks ---
Datos de Cutty Ranks procesados y guardados.
--- Consultando: Norma Fraser ---
Datos de Norma Fraser procesados y guardados.
--- Consultando: Goldfinger ---
Datos de Goldfinger procesados y guardados.
--- Consultando: Begoña Bang-Matu ---
Datos de Begoña Bang-Matu procesados y guardados.
--- Consultando: Andre Toussaint ---
Datos de Andre Toussaint procesados y guardados.
--- Consultando: Ike Bennett & The Crystalites ---
Datos de Ike Bennett & The Crystalites procesados y guardados.
--- Consultando: Harry Belafonte ---
Datos de Harry Belafonte procesados y guardados.
--- Consultando: Los Pericos ---
Datos de Los Pericos procesados y guardados.
--- Consultando: Freddie McGregor ---
Datos de Freddie McGregor procesados y guardados.
--- Consultando: Tijuana No! ---
Datos de Tijuana No! procesados y guardados.
--- Consultando: Johnny Osbourne ---
Datos de Johnny Osbourne procesados y guardados.
--- Consultando: Sasha ---
Datos de Sasha procesados y guardados.
--- Consultando: Damian Marley ---
Datos de Damian Marley procesados y guardados.
--- Consultando: Wayne Wonder ---
Datos de Wayne Wonder procesados y guardados.
--- Consultando: Hopeton Lewis ---
Datos de Hopeton Lewis procesados y guardados.
--- Consultando: Dezarie ---
Datos de Dezarie procesados y guardados.
--- Consultando: Andy and Joey ---
Datos de Andy and Joey procesados y guardados.
--- Consultando: Bob Marley & The Wailers ---
Datos de Bob Marley & The Wailers procesados y guardados.
--- Consultando: Salmonella Dub ---
Datos de Salmonella Dub procesados y guardados.
--- Consultando: Axe Bahia ---
Datos de Axe Bahia procesados y guardados.
--- Consultando: Los Cafres ---
Datos de Los Cafres procesados y guardados.
--- Consultando: Keith & Tex ---
Datos de Keith & Tex procesados y guardados.
--- Consultando: Hawkeye ---
Datos de Hawkeye procesados y guardados.
--- Consultando: Lynn Taitt ---
Datos de Lynn Taitt procesados y guardados.
--- Consultando: Sugar Daddy ---
Datos de Sugar Daddy procesados y guardados.
--- Consultando: Phoebe 1 ---
Datos de Phoebe 1 procesados y guardados.
--- Consultando: Adriana Lua ---
Datos de Adriana Lua procesados y guardados.
--- Consultando: Banda Kebradeira ---
Datos de Banda Kebradeira procesados y guardados.
--- Consultando: Holy Piby ---
Datos de Holy Piby procesados y guardados.
--- Consultando: Cultura Profética ---
Datos de Cultura Profética procesados y guardados.
--- Consultando: King Chango ---
Datos de King Chango procesados y guardados.
--- Consultando: Peter Tosh ---
Datos de Peter Tosh procesados y guardados.
--- Consultando: Jackie Mittoo ---
Datos de Jackie Mittoo procesados y guardados.
--- Consultando: Salida Nula ---
Datos de Salida Nula procesados y guardados.
--- Consultando: The Soul Syndicate ---
Datos de The Soul Syndicate procesados y guardados.
--- Consultando: Brother Culture ---
Datos de Brother Culture procesados y guardados.
--- Consultando: Dennis Brown ---
Datos de Dennis Brown procesados y guardados.
--- Consultando: Slim Smith ---
Datos de Slim Smith procesados y guardados.
--- Consultando: Le Peuple de L'Herbe ---
Datos de Le Peuple de L'Herbe procesados y guardados.
--- Consultando: Bom Balanço ---
Datos de Bom Balanço procesados y guardados.
--- Consultando: LaMeka55 ---
Datos de LaMeka55 procesados y guardados.
--- Consultando: Los Fabulosos Cadillacs ---
Datos de Los Fabulosos Cadillacs procesados y guardados.
--- Consultando: La Gran Orquesta Republicana ---
Datos de La Gran Orquesta Republicana procesados y guardados.
--- Consultando: Derrick Harriott ---
Datos de Derrick Harriott procesados y guardados.
--- Consultando: The Burning Souls ---
Datos de The Burning Souls procesados y guardados.
--- Consultando: Joe Dukie & DJ Fitchie ---
Datos de Joe Dukie & DJ Fitchie procesados y guardados.
--- Consultando: 10 Ft. Ganja Plant ---
Datos de 10 Ft. Ganja Plant procesados y guardados.
--- Consultando: Los De Abajo ---
Datos de Los De Abajo procesados y guardados.
--- Consultando: Freddie McKay ---

In [13]:
lista_artistas

[{'artista': 'Natiruts',
  'oyentes': '493615',
  'reproducciones': '16384113',
  'bio_resumen': 'Natiruts are a popular reggae band formed in Brasília, Brazil in 1996. Alexandre Carlo invited his soccer friends from Brasilia city in order to begin a new band in Brazil\'s capital. They are Luis Mauricio (bass) and Bruno Dourado (percussion). Later, the group \'enlisted\' some new members: Izabella Rocha (backing vocals) and Kiko Peres (solo electric guitar). The first album (Nativus) was released in 1997.\n\nOn the following albums (Verbalize - 2001 and Quatro - 2002) Tonho Gebara participated (solo electric guitar). <a href="https://www.last.fm/music/Natiruts">Read more on Last.fm</a>'},
 {'artista': 'Sidney Crooks',
  'oyentes': '2041',
  'reproducciones': '4453',
  'bio_resumen': 'biografia no encontrada'},
 {'artista': 'Maskavo',
  'oyentes': '132327',
  'reproducciones': '1303007',
  'bio_resumen': 'Maskavo is a brazilian reggae band formed in 2000. The group is a union of other three reggae band: Maskavo Roots, Leões de Judah and Os The Everaldos. BAND MEMBERS: Marceleza - vocals,\nBruno Prieto - bass and vocals, Prata - guitar, Naná - drums <a href="https://www.last.fm/music/Maskavo">Read more on Last.fm</a>'},
 {'artista': 'Justin Hinds',
  'oyentes': '37386',
  'reproducciones': '174965',
  'bio_resumen': 'Justin Hinds (May 7, 1942 - March 16, 2005) is best known as a Jamaican ska vocalist, with his backing singers the Dominoes. He is best known for his work with Duke Reid\'s Treasure Isle Records, where his most notable song, "Carry Go Bring Come" recorded in late 1963, went to number one in Jamaica. He recorded seventy singles between 1964 and 1966, and was the most popular artist on the record label.\nHinds died of lung cancer in March, 2005, at the age of 62. <a href="https://www.last.fm/music/Justin+Hinds">Read more on Last.fm</a>'},
 {'artista': 'Cordel Burrell',
  'oyentes': '524',
  'reproducciones': '1374',
  'bio_resumen': 'biografia no encontrada'},
 {'artista': 'Dobby Dobson',
  'oyentes': '22137',
  'reproducciones': '78534',
  'bio_resumen': 'Legendary singer Dobby Dobson, born Highland Ralph Dobson, began singing in the early 1950s. Though his career started in his native home, Jamaica he is now renowned worldwide. He has appeared all over the Caribbean, South, Central and North Americas, Canada and The United Kingdom. This talented performer has become famous for his stirring performances that always leave the audience begging for more and make the ladies scream with delight. Dobby’s talents knows no boundaries <a href="https://www.last.fm/music/Dobby+Dobson">Read more on Last.fm</a>'},
 {'artista': 'Bob Andy',
  'oyentes': '120880',
  'reproducciones': '643432',
  'bio_resumen': 'Bob Andy CD (born Keith Anderson in Kingston, Jamaica, on 28 October 1944; died 27 March 2020) was a Jamaican reggae musician widely regarded as one of reggae\'s most influential songwriters. As well as solo recordings, he was a founding member of The Paragons and was in Bob & Marcia.\n\nHe emerged as a solo star in 1966 with the smash hit "I\'ve Got to Go Back Home", a song which has become a much-loved anthem for Jamaicans. He had served his singing and songwriting apprenticeship with the legendary vocal group THE PARAGONS <a href="https://www.last.fm/music/Bob+Andy">Read more on Last.fm</a>'},
 {'artista': 'Ben Harper',
  'oyentes': '1549835',
  'reproducciones': '30776136',
  'bio_resumen': 'Ben Harper (born in Pomona, CA, on 28 October 1969) is an American  Grammy-winning singer and songwriter. As well as solo albums, he has recorded as Ben Harper and Tom Freund, Ben Harper & The Innocent Criminals, Ben Harper And The Blind Boys Of Alabama, Ben Harper and Relentless7, Ben Harper & Charlie Musselwhite, and Ben & Ellen Harper. \n\nHarper grew up listening to blues, folk, soul, RnB, and reggae. Harper\'s blend of groove-laden funky soul and <a href="https://www.last.fm/music/Ben+Harper">Read more on Last.fm</a>'},
 {'artista': 'Phyllis Dillon',
  'oyentes': '141617',
  'reproducciones': '1193285',
  'bio_resumen': 'Phyllis Dillon (27 December 1944 — 15 April 2004) was a Jamaican ska and reggae singer who recorded for Duke Reid\'s lucrative Treasure Isle record label in the late 1960s and early 1970s.\n\nDillon was born in 1944 in Linstead, St. Catherine, Jamaica.[1] Influenced by American singers Connie Francis, Patti Page and Dionne Warwick, she began singing in talent contests. It was during a performance at the Glass Bucket Club in Kingston, Jamaica with the group The Vulcans, that Duke Reid\'s session guitarist Lynn Taitt discovered Dillon.[1] <a href="https://www.last.fm/music/Phyllis+Dillon">Read more on Last.fm</a>'},
 {'artista': 'Less Than Jake',
  'oyentes': '858718',
  'reproducciones': '33816646',
  'bio_resumen': 'Less Than Jake is a ska punk band formed in 1992 in Gainesville, USA. Their current line-up consists of Chris DeMakes (vocals, guitar), Roger Lima (vocals, bass), Matt Yonker (drums), Buddy Schaub (trombone) and Peter "JR" Wasilewski (saxophone).\n\nThe band\'s name derives from a dog Vinnie had while growing up, which was treated better than the rest of the family. It\'s also a reference to the phrase "everything is jake," which is an old phrase meaning everything is cool. <a href="https://www.last.fm/music/Less+Than+Jake">Read more on Last.fm</a>'},
 {'artista': 'Salon Victoria',
  'oyentes': '32448',
  'reproducciones': '452896',
  'bio_resumen': 'biografia no encontrada'},
 {'artista': 'The Uniques',
  'oyentes': '83566',
  'reproducciones': '451215',
  'bio_resumen': 'The Uniques is the name of more than one band:\n1) Jamaican rocksteady 2) 60s US garage band 3) Doo Wop 4) Slovak electroclash\n\n1)  The Uniques were a Jamaican rocksteady and reggae vocal group, formed in 1966 and active with varying line-ups until the late 1970s.\nThe Uniques originally formed as a vocal harmony trio of Roy Shirley, Slim Smith, and Franklyn White, (the latter two from The Techniques) releasing a few singles in 1966 including the R&B influenced "Do Me Good" for Ken Lack\'s (Keith Calneck) Caltone imprint. <a href="https://www.last.fm/music/The+Uniques">Read more on Last.fm</a>'},
 {'artista': 'Daniela Mercury',
  'oyentes': '183484',
  'reproducciones': '3280924',
  'bio_resumen': 'Daniela Mercuri de Almeida Verçosa (born July 28, 1965 in Salvador, Bahia, Brazil), best known as Daniela Mercury, is a Brazilian axé, samba-reggae and MPB singer, songwriter, dancer, actress, entrepeneur, producer, poet, philanthropist and activist for LGBTQ+ rights. For her pioneering of the axé genre, she is also known as the "Queen of Axé."\n\nSince her breakthrough, Mercury has become one of the best known Brazilian female singers, selling over 20 million albums worldwide. <a href="https://www.last.fm/music/Daniela+Mercury">Read more on Last.fm</a>'},
 {'artista': 'Jimmy Cliff',
  'oyentes': '929041',
  'reproducciones': '8388840',
  'bio_resumen': 'Jimmy Cliff OM (Jamaican Order of Merit) born as James Chambers (1 April 1948, St. Catherine, Jamaica) is a Jamaican reggae musician. He is best known among mainstream audiences for songs like "Sittin\' in Limbo", "You Can Get It If You Really Want," "Many Rivers to Cross" and the title track from The Harder They Come, a film soundtrack which helped popularise reggae across the world.\n\nCliff moved to Kingston in 1962. After he released two singles that failed to make much of an impression <a href="https://www.last.fm/music/Jimmy+Cliff">Read more on Last.fm</a>'},
 {'artista': 'Lil Jon & The East Side Boyz',
  'oyentes': '904536',
  'reproducciones': '5760936',
  'bio_resumen': 'Smith took the stage name Lil Jon and formed musical group Lil Jon & the East Side Boyz with rappers Big Sam (born Sammie Dernard Norris) and Lil\' Bo (born Wendell Maurice Neal). The group signed to the Atlanta-based Mirror Image Records and were distributed by Ichiban Records. In 1997, Lil Jon & the East Side Boyz debuted with Get Crunk, Who U Wit: Da Album. It included singles "Who U Wit?" and "Shawty Freak a Lil\' Sumthin\'", the latter of which came out in 1998. <a href="https://www.last.fm/music/Lil+Jon+&+The+East+Side+Boyz">Read more on Last.fm</a>'},
 {'artista': 'Inspector',
  'oyentes': '133233',
  'reproducciones': '2258621',
  'bio_resumen': 'There are 2 bands with this name:\n\n1. Mexican ska revival ensemble Inspector comprises singer Javier Sánchez aka Big Javi, drummer David Martínez aka Tribi, bassist Arnoldo Ortega aka Lolo, sax players Jaime González aka Jimmy and Jesús Arriaga aka Padrino, guitarist Alejandro Ortega aka Güero, keyboardist Homero Ontiveros aka Marango and trumpeter Jesús Lemo. The band debuted in 1995 with the independently produced Misión Ska, featuring five original songs. <a href="https://www.last.fm/music/Inspector">Read more on Last.fm</a>'},
 {'artista': 'Chiclete Com Banana',
  'oyentes': '136991',
  'reproducciones': '1819795',
  'bio_resumen': 'Chiclete com Banana is an Axé music band consisting of Bell Marques, Wadinho Marques, Rey, Waltinho Cruz and Deny. They released their first album, called "Traz os montes", in 1982.\n\nNowadays, they are one of the most successful axé music bands in Brazil. Their abadás are the most expensive on Salvador Carnival. They usually have anywhere from 200.000 to 500.000 people walking along their sound truck Trio Elétrico as it is known. <a href="https://www.last.fm/music/Chiclete+Com+Banana">Read more on Last.fm</a>'},
 {'artista': 'Fishbone',
  'oyentes': '247832',
  'reproducciones': '3009233',
  'bio_resumen': 'Fishbone is an American rock band formed in 1979 in Los Angeles, California, which plays a fusion of ska, punk, funk, heavy metal, reggae, and soul. AllMusic has described the group as "one of the most distinctive and eclectic alternative rock bands of the late \'80s. With their hyperactive, self-conscious diversity, goofy sense of humor, and sharp social commentary, the group gained a sizable cult following yet they were never able to earn a mainstream audience." <a href="https://www.last.fm/music/Fishbone">Read more on Last.fm</a>'},
 {'artista': 'Horace Andy',
  'oyentes': '333982',
  'reproducciones': '3485513',
  'bio_resumen': 'Horace Andy, or Horace Hinds ( ⋆ 19 Feb 1951 in  Kingston, Jamaica) is legendary reggae  artist and roots reggae singer and songwriter. He is also Rastafarian. His first single, "This is a Black Man\'s Country," was released 1967 Andy is one of the most respected and influential singers in Jamaica, known for his distinctive falsetto vocal style and songs as Skylarking, Government Land, Angel, Five Man Army and for his work with English Massive Attack. <a href="https://www.last.fm/music/Horace+Andy">Read more on Last.fm</a>'},
 {'artista': 'Patrice',
  'oyentes': '389726',
  'reproducciones': '7691370',
  'bio_resumen': 'Patrice (Patrice Bart-Williams) is an Afro-German reggae artist. His music is influenced by Jimi Hendrix and Bob Marley.\nEffortlessly combining folk, reggae, soul and blues, the singer/songwriter/guitarist , Patrice, exploded onto the music scene with his phenomenal testimonial debut Lions E.P in 1999 aged just 18. With the deep lyrical content and social conscience resonating within his work, Patrice alludes to his late father (a Sierra Leonian political activist and poet) and Bob Marley as the greatest influences on his music. <a href="https://www.last.fm/music/Patrice">Read more on Last.fm</a>'},
 {'artista': 'Betagarri',
  'oyentes': '33294',
  'reproducciones': '468151',
  'bio_resumen': 'Betagarri is a basque skaband from Vitoria-Gasteiz. Their sound seems to be a mix of ska, reggae and rock but are also influenced by latin and punk. Most texts are written and sung in basque language and largely deal with social- and globalisation critical issues. \n\nBetagarri consists of eight musicans who are Iñaki Ortiz de Villalba (voice), Aitor Ruiz de Arbulo (guitar) and Pablo Rodríguez (bass) who are the only remaining founder members from 1992 and Iker Uriarte (drumset) <a href="https://www.last.fm/music/Betagarri">Read more on Last.fm</a>'},
 {'artista': 'Los Auténticos Decadentes',
  'oyentes': '247206',
  'reproducciones': '4635288',
  'bio_resumen': 'Los Auténticos Decadentes (Spanish for "The Authentic Decadents") is an Argentine band that mixes ska with Latin American rhythms. The band was formed around 1986 by Cucho and Nito, who invited Gastón to join them.\n\nTheir first hit was Veni Raquel, which set the tone for their later lyrics\' irreverence and ironic humor. Many of their songs are classic anthems of Argentinian nightlife, such as Corazón, Loco (Tu Forma de Ser), Entregá el Marrón, La Guitarra, Los Piratas, and El Murguero. <a href="https://www.last.fm/music/+noredirect/Los+Aut%C3%A9nticos+Decadentes">Read more on Last.fm</a>'},
 {'artista': 'Seeed',
  'oyentes': '542318',
  'reproducciones': '16391290',
  'bio_resumen': 'Seeed, formed in 1998 in Berlin, Germany, plays  dancehall,  reggae, and hip hop. \n\nThe group currently consists of 10 people:\nEnuff aka Peter Fox aka Pierre Baigorry (vocals)\nEased aka Dellé aka Frank A. Dellé (vocals)\nAlfi Trowers (percussions)\nBased (drums)\nMoritz Delgado (sax)\nDJ Luke (DJ) - (since 2005)\nJerome "Tchamp" Bugnon (trombone)\n"Dubmaster" Reibold (keyboard)\n"Rudeboy" Rudy (guitar)\nTobsen Cordes (bass)\n\nFormer members:\nEar aka Boundzound aka Demba Nabé (vocals) - (1998-2018, deceased) <a href="https://www.last.fm/music/Seeed">Read more on Last.fm</a>'},
 {'artista': 'La Mosca',
  'oyentes': '75882',
  'reproducciones': '464821',
  'bio_resumen': 'Si bien la formación actual del grupo se consolida en marzo de 1995, la historia de la banda se remonta a comienzos de los noventa con "La Reggae & Roll Band", quienes hacían covers y algunos temas propios en la zona de Ramallo. Simultáneamente existían otras bandas entre las que se destacaba "Damas gratis" liderada por Guillermo Novellis.\nTras la disolución de "Damas gratis", Fernando Castro, que era el baterista y uno de los fundadores (de La Reggae)  <a href="https://www.last.fm/music/+noredirect/La+Mosca">Read more on Last.fm</a>'},
 {'artista': 'Busta Rhymes',
  'oyentes': '2108448',
  'reproducciones': '26483535',
  'bio_resumen': 'Trevor George Smith Jr. (born May 20, 1972 in Brooklyn, New York), better known by his stage name Busta Rhymes, is an American rapper and actor signed to Universal Motown. He began his rap career in the group Leaders of the New School, and had his breakout moment when they featured on A Tribe Called Quest\'s hit, Scenario. Busta then released his debut album, The Coming, in 1996. He has since released 1997\'s When Disaster Strikes, 1998\'s E.L.E. (Extinction Level Event): The Final World Front <a href="https://www.last.fm/music/Busta+Rhymes">Read more on Last.fm</a>'},
 {'artista': 'Ara Ketu',
  'oyentes': '78787',
  'reproducciones': '676060',
  'bio_resumen': 'The band Ara Ketu derived from the Carnival bloco of the same name and was founded in 1980. Before reaching success in Brazil, they became popular in Europe with an entertaining mix of Afro-Bahian percussive grooves with electronic paraphernalia and performing in colorful outfits. The group also added a vocalist (Tatau) and a horn section, counting up to 12 members. Since its beginning, the group developed a work of research on traditional African music keeping in perspective Brazilian and international pop music... <a href="https://www.last.fm/music/Ara+Ketu">Read more on Last.fm</a>'},
 {'artista': 'The Specials',
  'oyentes': '1109937',
  'reproducciones': '19418769',
  'bio_resumen': 'The Specials is an English “2 Tone” ska revival band  formed in 1977 in Coventry, Warwickshire. Their music combines a danceable ska beat with punk’s energy, underpinned by an informed political and social stance. \n\nThe group was formed by songwriter/keyboardist Jerry Dammers, with Terry Hall (vocals), Lynval Golding (guitar, vocals) and a rhythm section featuring Horace Panter (bass) and John Bradbury (drums; born 16 February 1953, died 28 December 2015). <a href="https://www.last.fm/music/The+Specials">Read more on Last.fm</a>'},
 {'artista': 'Mikey Dread',
  'oyentes': '112886',
  'reproducciones': '849205',
  'bio_resumen': 'Michael Campbell (1954-2008), better known as Mikey Dread, was a multi-talented Jamaican singer, producer, and broadcaster. During his long career, he brought dub music to the cultural fore in not only Jamaica but internationally, courageously fused dub with punk via work with The Clash, spread a global message of racial unity, and played a seminal role as a forefather of the now popular and very commercial dancehall and even reggaeton styles with popular dub cuts like Roots and Culture.  <a href="https://www.last.fm/music/Mikey+Dread">Read more on Last.fm</a>'},
 {'artista': 'Slightly Stoopid',
  'oyentes': '836799',
  'reproducciones': '18601421',
  'bio_resumen': 'While it’s a rare commodity for a band to tour as consistently as Slightly Stoopid, the group’s diligent commitment to live music provides some insight into their loyal fan base and unique creative metamorphosis throughout their extensive existence. Though it\'s been a couple of years since the release of their last studio album, Top Of The World (August 14, 2012), the Ocean Beach, California-based group—led by co-founders and multi-instrumentalists <a href="https://www.last.fm/music/Slightly+Stoopid">Read more on Last.fm</a>'},
 {'artista': 'Barry Biggs',
  'oyentes': '48636',
  'reproducciones': '234305',
  'bio_resumen': 'Barry Biggs (born 1947, although some accounts list 1953;[1] St. Andrew, Jamaica) is a reggae singer, best known in the UK for his cover of the Blue Magic song, "Sideshow", which got to #3 in the UK Singles Chart in 1977\n\nBiggs worked as an recording engineer and cameraman with the Jamaican Broadcasting Company, and also spent time as a member of the band the Astronauts, before becoming the lead singer for Byron Lee\'s Dragonaires.[1][3]\nIt was at <a href="https://www.last.fm/music/Barry+Biggs">Read more on Last.fm</a>'},
 {'artista': 'New York Ska-Jazz Ensemble',
  'oyentes': '76000',
  'reproducciones': '1193064',
  'bio_resumen': 'New York Ska-Jazz Ensemble is a group of New York ska musicians linking together ska and jazz music. \n\nMembers:\nFreddie Reiter (saxophone, flute, vocals),Mark Paquin (trombone, vocals)\nYao Dinizulu (drums), Alberto Tarin (guitar), Earl Appleton (keyboards)\n\nADDITIONAL MUSICIANS\n\nMitch Margold (keyboards),Cary Brown (keyboards), Gregg Leventhal (bass)\nLee Archibald(guitar, bass, vocals), Chris Weigers (bass)\n\nPAST MEMBERS\n\nJohnnathan McCain (drums <a href="https://www.last.fm/music/New+York+Ska-Jazz+Ensemble">Read more on Last.fm</a>'},
 {'artista': 'Banda Beijo',
  'oyentes': '46829',
  'reproducciones': '259906',
  'bio_resumen': 'Banda Beijo foi uma banda brasileira de axé music. Teve sua origem no Bloco Beijo e foi formada em 1988, tendo em seu auge como vocalista o cantor Netinho, que também fazia parte do bloco, e logo após sua saída da banda, a cantora Gilmelândia.\n\nApesar de ser uma banda de Axé Music, não restringe seu repertório a tal estilo. Incluindo desde Tim Maia até The Police, saiu de seu reduto original, o carnaval baiano, e teve seu sucesso expandido por todo o Brasil. <a href="https://www.last.fm/music/Banda+Beijo">Read more on Last.fm</a>'},
 {'artista': 'The Jamaicans',
  'oyentes': '71187',
  'reproducciones': '302030',

In [14]:
len(lista_artistas)

254

In [15]:
artista_reggae = pd.DataFrame(lista_artistas)
artista_reggae

,artista,oyentes,reproducciones,bio_resumen
0,Natiruts,493615,16384113,Natiruts are a popular reggae band formed in B...
1,Sidney Crooks,2041,4453,biografia no encontrada
2,Maskavo,132327,1303007,Maskavo is a brazilian reggae band formed in 2...
3,Justin Hinds,37386,174965,"Justin Hinds (May 7, 1942 - March 16, 2005) is..."
4,Cordel Burrell,524,1374,biografia no encontrada
...,...,...,...,...
249,Cheb Mami,79343,712599,Romanized spelling of شاب مامي (Cheb Mami).\nC...
250,Bandits of the Acoustic Revolution,132915,1562933,Bandits of the Acoustic Revolution (commonly a...
251,Mr Easy,15076,56365,Mr Easy is a man over-flowing with music and m...
252,Misty In Roots,60130,562138,"Roots reggae band formed 1975 in Southall, Lon..."
253,Jahsta,12038,112213,"a reggae band of Zaragoza <a href=""https://www..."

In [16]:
artista_reggae.to_csv("artista_reggae.csv", index = False)

In [17]:
PAIS_A_GENTILICIO = {
    "Afghanistan": "Afghan",
    "Albania": "Albanian",
    "Algeria": "Algerian",
    "Argentina": "Argentinian",
    "Australia": "Australian",
    "Austria": "Austrian",
    "Belgium": "Belgian",
    "Bolivia": "Bolivian",
    "Brazil": "Brazilian",
    "Canada": "Canadian",
    "Chile": "Chilean",
    "China": "Chinese",
    "Colombia": "Colombian",
    "Costa Rica": "Costa Rican",
    "Cuba": "Cuban",
    "Denmark": "Dane",
    "Egypt": "Egyptian",
    "France": "French",
    "Germany": "German",
    "Greece": "Greek",
    "India": "Indian",
    "Indonesia": "Indonesian",
    "Ireland": "Irish",
    "Italy": "Italian",
    "Jamaica": "Jamaican",
    "Japan": "Japanese",
    "Mexico": "Mexican",
    "Netherlands": "Dutch",
    "New Zealand": "New Zealander",
    "Nigeria": "Nigerian",
    "Norway": "Norwegian",
    "Peru": "Peruvian",
    "Poland": "Pole",
    "Portugal": "Portuguese",
    "Russia": "Russian",
    "South Korea": "South Korean",
    "Spain": "Spaniard",
    "Sweden": "Swede",
    "Turkey": "Turk",
    "Ukraine": "Ukrainian",
    "United Kingdom": "Briton",
    "United States": "American",
    "United States_adj": "American",
    "United Kingdom_adj": "British",
    "France_adj": "French",
    "Germany_adj": "German",
    "Spain_adj": "Spanish"}

In [18]:
# DICCIONARIO INVERTIDO PARA BÚSQUEDA EFICIENTE
# Clave: Gentilicio (lo que busco en la bio), Valor: País
GENTILICIO_A_PAIS = {gentilicio.lower(): pais.replace('_adj', '')
    for pais, gentilicio in PAIS_A_GENTILICIO.items()}

In [19]:
def extraer_pais_de_biografia(bio_resumen, gentilicio_a_pais_map):
    bio_normalizada = bio_resumen.lower()
    for gentilicio, pais in gentilicio_a_pais_map.items():
        # Usamos ' ' + gentilicio + ' ' para buscar la palabra completa y evitar coincidencias parciales
        if f' {gentilicio} ' in bio_normalizada or bio_normalizada.startswith(f'{gentilicio} '):
            return pais
        
        if bio_normalizada.endswith(gentilicio):
             return pais
    return ''

for artista_data in lista_artistas:
    bio = artista_data['bio_resumen']
    pais_encontrado = extraer_pais_de_biografia(bio, GENTILICIO_A_PAIS)
    artista_data['pais'] = pais_encontrado #aqui agregamos la clave pais en nuestro diccionario
print(lista_artistas)

[{'artista': 'Natiruts', 'oyentes': '493615', 'reproducciones': '16384113', 'bio_resumen': 'Natiruts are a popular reggae band formed in Brasília, Brazil in 1996. Alexandre Carlo invited his soccer friends from Brasilia city in order to begin a new band in Brazil\'s capital. They are Luis Mauricio (bass) and Bruno Dourado (percussion). Later, the group \'enlisted\' some new members: Izabella Rocha (backing vocals) and Kiko Peres (solo electric guitar). The first album (Nativus) was released in 1997.\n\nOn the following albums (Verbalize - 2001 and Quatro - 2002) Tonho Gebara participated (solo electric guitar). <a href="https://www.last.fm/music/Natiruts">Read more on Last.fm</a>', 'pais': ''}, {'artista': 'Sidney Crooks', 'oyentes': '2041', 'reproducciones': '4453', 'bio_resumen': 'biografia no encontrada', 'pais': ''}, {'artista': 'Maskavo', 'oyentes': '132327', 'reproducciones': '1303007', 'bio_resumen': 'Maskavo is a brazilian reggae band formed in 2000. The group is a union of other three reggae band: Maskavo Roots, Leões de Judah and Os The Everaldos. BAND MEMBERS: Marceleza - vocals,\nBruno Prieto - bass and vocals, Prata - guitar, Naná - drums <a href="https://www.last.fm/music/Maskavo">Read more on Last.fm</a>', 'pais': 'Brazil'}, {'artista': 'Justin Hinds', 'oyentes': '37386', 'reproducciones': '174965', 'bio_resumen': 'Justin Hinds (May 7, 1942 - March 16, 2005) is best known as a Jamaican ska vocalist, with his backing singers the Dominoes. He is best known for his work with Duke Reid\'s Treasure Isle Records, where his most notable song, "Carry Go Bring Come" recorded in late 1963, went to number one in Jamaica. He recorded seventy singles between 1964 and 1966, and was the most popular artist on the record label.\nHinds died of lung cancer in March, 2005, at the age of 62. <a href="https://www.last.fm/music/Justin+Hinds">Read more on Last.fm</a>', 'pais': 'Jamaica'}, {'artista': 'Cordel Burrell', 'oyentes': '524', 'reproducciones': '1374', 'bio_resumen': 'biografia no encontrada', 'pais': ''}, {'artista': 'Dobby Dobson', 'oyentes': '22137', 'reproducciones': '78534', 'bio_resumen': 'Legendary singer Dobby Dobson, born Highland Ralph Dobson, began singing in the early 1950s. Though his career started in his native home, Jamaica he is now renowned worldwide. He has appeared all over the Caribbean, South, Central and North Americas, Canada and The United Kingdom. This talented performer has become famous for his stirring performances that always leave the audience begging for more and make the ladies scream with delight. Dobby’s talents knows no boundaries <a href="https://www.last.fm/music/Dobby+Dobson">Read more on Last.fm</a>', 'pais': ''}, {'artista': 'Bob Andy', 'oyentes': '120880', 'reproducciones': '643432', 'bio_resumen': 'Bob Andy CD (born Keith Anderson in Kingston, Jamaica, on 28 October 1944; died 27 March 2020) was a Jamaican reggae musician widely regarded as one of reggae\'s most influential songwriters. As well as solo recordings, he was a founding member of The Paragons and was in Bob & Marcia.\n\nHe emerged as a solo star in 1966 with the smash hit "I\'ve Got to Go Back Home", a song which has become a much-loved anthem for Jamaicans. He had served his singing and songwriting apprenticeship with the legendary vocal group THE PARAGONS <a href="https://www.last.fm/music/Bob+Andy">Read more on Last.fm</a>', 'pais': 'Jamaica'}, {'artista': 'Ben Harper', 'oyentes': '1549835', 'reproducciones': '30776136', 'bio_resumen': 'Ben Harper (born in Pomona, CA, on 28 October 1969) is an American  Grammy-winning singer and songwriter. As well as solo albums, he has recorded as Ben Harper and Tom Freund, Ben Harper & The Innocent Criminals, Ben Harper And The Blind Boys Of Alabama, Ben Harper and Relentless7, Ben Harper & Charlie Musselwhite, and Ben & Ellen Harper. \n\nHarper grew up listening to blues, folk, soul, RnB, and reggae. Harper\'s blend of groove-laden funky soul and <a href="https://www.last.fm/music/Ben+Harper">Read more on Last.fm</a>', 'pais': 'United States'}, {'artista': 'Phyllis Dillon', 'oyentes': '141617', 'reproducciones': '1193285', 'bio_resumen': 'Phyllis Dillon (27 December 1944 — 15 April 2004) was a Jamaican ska and reggae singer who recorded for Duke Reid\'s lucrative Treasure Isle record label in the late 1960s and early 1970s.\n\nDillon was born in 1944 in Linstead, St. Catherine, Jamaica.[1] Influenced by American singers Connie Francis, Patti Page and Dionne Warwick, she began singing in talent contests. It was during a performance at the Glass Bucket Club in Kingston, Jamaica with the group The Vulcans, that Duke Reid\'s session guitarist Lynn Taitt discovered Dillon.[1] <a href="https://www.last.fm/music/Phyllis+Dillon">Read more on Last.fm</a>', 'pais': 'Jamaica'}, {'artista': 'Less Than Jake', 'oyentes': '858718', 'reproducciones': '33816646', 'bio_resumen': 'Less Than Jake is a ska punk band formed in 1992 in Gainesville, USA. Their current line-up consists of Chris DeMakes (vocals, guitar), Roger Lima (vocals, bass), Matt Yonker (drums), Buddy Schaub (trombone) and Peter "JR" Wasilewski (saxophone).\n\nThe band\'s name derives from a dog Vinnie had while growing up, which was treated better than the rest of the family. It\'s also a reference to the phrase "everything is jake," which is an old phrase meaning everything is cool. <a href="https://www.last.fm/music/Less+Than+Jake">Read more on Last.fm</a>', 'pais': ''}, {'artista': 'Salon Victoria', 'oyentes': '32448', 'reproducciones': '452896', 'bio_resumen': 'biografia no encontrada', 'pais': ''}, {'artista': 'The Uniques', 'oyentes': '83566', 'reproducciones': '451215', 'bio_resumen': 'The Uniques is the name of more than one band:\n1) Jamaican rocksteady 2) 60s US garage band 3) Doo Wop 4) Slovak electroclash\n\n1)  The Uniques were a Jamaican rocksteady and reggae vocal group, formed in 1966 and active with varying line-ups until the late 1970s.\nThe Uniques originally formed as a vocal harmony trio of Roy Shirley, Slim Smith, and Franklyn White, (the latter two from The Techniques) releasing a few singles in 1966 including the R&B influenced "Do Me Good" for Ken Lack\'s (Keith Calneck) Caltone imprint. <a href="https://www.last.fm/music/The+Uniques">Read more on Last.fm</a>', 'pais': 'Jamaica'}, {'artista': 'Daniela Mercury', 'oyentes': '183484', 'reproducciones': '3280924', 'bio_resumen': 'Daniela Mercuri de Almeida Verçosa (born July 28, 1965 in Salvador, Bahia, Brazil), best known as Daniela Mercury, is a Brazilian axé, samba-reggae and MPB singer, songwriter, dancer, actress, entrepeneur, producer, poet, philanthropist and activist for LGBTQ+ rights. For her pioneering of the axé genre, she is also known as the "Queen of Axé."\n\nSince her breakthrough, Mercury has become one of the best known Brazilian female singers, selling over 20 million albums worldwide. <a href="https://www.last.fm/music/Daniela+Mercury">Read more on Last.fm</a>', 'pais': 'Brazil'}, {'artista': 'Jimmy Cliff', 'oyentes': '929041', 'reproducciones': '8388840', 'bio_resumen': 'Jimmy Cliff OM (Jamaican Order of Merit) born as James Chambers (1 April 1948, St. Catherine, Jamaica) is a Jamaican reggae musician. He is best known among mainstream audiences for songs like "Sittin\' in Limbo", "You Can Get It If You Really Want," "Many Rivers to Cross" and the title track from The Harder They Come, a film soundtrack which helped popularise reggae across the world.\n\nCliff moved to Kingston in 1962. After he released two singles that failed to make much of an impression <a href="https://www.last.fm/music/Jimmy+Cliff">Read more on Last.fm</a>', 'pais': 'Jamaica'}, {'artista': 'Lil Jon & The East Side Boyz', 'oyentes': '904536', 'reproducciones': '5760936', 'bio_resumen': 'Smith took the stage name Lil Jon and formed musical group Lil Jon & the East Side Boyz with rappers Big Sam (born Sammie Dernard Norris) and Lil\' Bo (born Wendell Maurice Neal). The group signed to the Atlanta-based Mirror Image Records and were distributed by Ichiban Records. In 1997, Lil Jon & the East Side Boyz debuted with Get Crunk, Who U Wit: Da Album. It included singles "Who U Wit?" and "Shawty Freak a Lil\' Sumthin\'", the latter of which came out in 1998. <a href="https://www.last.fm/music/Lil+Jon+&+The+East+Side+Boyz">Read more on Last.fm</a>', 'pais': ''}, {'artista': 'Inspector', 'oyentes': '133233', 'reproducciones': '2258621', 'bio_resumen': 'There are 2 bands with this name:\n\n1. Mexican ska revival ensemble Inspector comprises singer Javier Sánchez aka Big Javi, drummer David Martínez aka Tribi, bassist Arnoldo Ortega aka Lolo, sax players Jaime González aka Jimmy and Jesús Arriaga aka Padrino, guitarist Alejandro Ortega aka Güero, keyboardist Homero Ontiveros aka Marango and trumpeter Jesús Lemo. The band debuted in 1995 with the independently produced Misión Ska, featuring five original songs. <a href="https://www.last.fm/music/Inspector">Read more on Last.fm</a>', 'pais': 'Mexico'}, {'artista': 'Chiclete Com Banana', 'oyentes': '136991', 'reproducciones': '1819795', 'bio_resumen': 'Chiclete com Banana is an Axé music band consisting of Bell Marques, Wadinho Marques, Rey, Waltinho Cruz and Deny. They released their first album, called "Traz os montes", in 1982.\n\nNowadays, they are one of the most successful axé music bands in Brazil. Their abadás are the most expensive on Salvador Carnival. They usually have anywhere from 200.000 to 500.000 people walking along their sound truck Trio Elétrico as it is known. <a href="https://www.last.fm/music/Chiclete+Com+Banana">Read more on Last.fm</a>', 'pais': ''}, {'artista': 'Fishbone', 'oyentes': '247832', 'reproducciones': '3009233', 'bio_resumen': 'Fishbone is an American rock band formed in 1979 in Los Angeles, California, which plays a fusion of ska, punk, funk, heavy metal, reggae, and soul. AllMusic has described the group as "one of the most distinctive and eclectic alternative rock bands of the late \'80s. With their hyperactive, self-conscious diversity, goofy sense of humor, and sharp social commentary, the group gained a sizable cult following yet they were never able to earn a mainstream audience." <a href="https://www.last.fm/music/Fishbone">Read more on Last.fm</a>', 'pais': 'United States'}, {'artista': 'Horace Andy', 'oyentes': '333982', 'reproducciones': '3485513', 'bio_resumen': 'Horace Andy, or Horace Hinds ( ⋆ 19 Feb 1951 in  Kingston, Jamaica) is legendary reggae  artist and roots reggae singer and songwriter. He is also Rastafarian. His first single, "This is a Black Man\'s Country," was released 1967 Andy is one of the most respected and influential singers in Jamaica, known for his distinctive falsetto vocal style and songs as Skylarking, Government Land, Angel, Five Man Army and for his work with English Massive Attack. <a href="https://www.last.fm/music/Horace+Andy">Read more on Last.fm</a>', 'pais': ''}, {'artista': 'Patrice', 'oyentes': '389726', 'reproducciones': '7691370', 'bio_resumen': 'Patrice (Patrice Bart-Williams) is an Afro-German reggae artist. His music is influenced by Jimi Hendrix and Bob Marley.\nEffortlessly combining folk, reggae, soul and blues, the singer/songwriter/guitarist , Patrice, exploded onto the music scene with his phenomenal testimonial debut Lions E.P in 1999 aged just 18. With the deep lyrical content and social conscience resonating within his work, Patrice alludes to his late father (a Sierra Leonian political activist and poet) and Bob Marley as the greatest influences on his music. <a href="https://www.last.fm/music/Patrice">Read more on Last.fm</a>', 'pais': ''}, {'artista': 'Betagarri', 'oyentes': '33294', 'reproducciones': '468151', 'bio_resumen': 'Betagarri is a basque skaband from Vitoria-Gasteiz. Their sound seems to be a mix of ska, reggae and rock but are also influenced by latin and punk. Most texts are written and sung in basque language and largely deal with social- and globalisation critical issues. \n\nBetagarri consists of eight musicans who are Iñaki Ortiz de Villalba (voice), Aitor Ruiz de Arbulo (guitar) and Pablo Rodríguez (bass) who are the only remaining founder members from 1992 and Iker Uriarte (drumset) <a href="https://www.last.fm/music/Betagarri">Read more on Last.fm</a>', 'pais': ''}, {'artista': 'Los Auténticos Decadentes', 'oyentes': '247206', 'reproducciones': '4635288', 'bio_resumen': 'Los Auténticos Decadentes (Spanish for "The Authentic Decadents") is an Argentine band that mixes ska with Latin American rhythms. The band was formed around 1986 by Cucho and Nito, who invited Gastón to join them.\n\nTheir first hit was Veni Raquel, which set the tone for their later lyrics\' irreverence and ironic humor. Many of their songs are classic anthems of Argentinian nightlife, such as Corazón, Loco (Tu Forma de Ser), Entregá el Marrón, La Guitarra, Los Piratas, and El Murguero. <a href="https://www.last.fm/music/+noredirect/Los+Aut%C3%A9nticos+Decadentes">Read more on Last.fm</a>', 'pais': 'Argentina'}, {'artista': 'Seeed', 'oyentes': '542318', 'reproducciones': '16391290', 'bio_resumen': 'Seeed, formed in 1998 in Berlin, Germany, plays  dancehall,  reggae, and hip hop. \n\nThe group currently consists of 10 people:\nEnuff aka Peter Fox aka Pierre Baigorry (vocals)\nEased aka Dellé aka Frank A. Dellé (vocals)\nAlfi Trowers (percussions)\nBased (drums)\nMoritz Delgado (sax)\nDJ Luke (DJ) - (since 2005)\nJerome "Tchamp" Bugnon (trombone)\n"Dubmaster" Reibold (keyboard)\n"Rudeboy" Rudy (guitar)\nTobsen Cordes (bass)\n\nFormer members:\nEar aka Boundzound aka Demba Nabé (vocals) - (1998-2018, deceased) <a href="https://www.last.fm/music/Seeed">Read more on Last.fm</a>', 'pais': ''}, {'artista': 'La Mosca', 'oyentes': '75882', 'reproducciones': '464821', 'bio_resumen': 'Si bien la formación actual del grupo se consolida en marzo de 1995, la historia de la banda se remonta a comienzos de los noventa con "La Reggae & Roll Band", quienes hacían covers y algunos temas propios en la zona de Ramallo. Simultáneamente existían otras bandas entre las que se destacaba "Damas gratis" liderada por Guillermo Novellis.\nTras la disolución de "Damas gratis", Fernando Castro, que era el baterista y uno de los fundadores (de La Reggae)  <a href="https://www.last.fm/music/+noredirect/La+Mosca">Read more on Last.fm</a>', 'pais': ''}, {'artista': 'Busta Rhymes', 'oyentes': '2108448', 'reproducciones': '26483535', 'bio_resumen': 'Trevor George Smith Jr. (born May 20, 1972 in Brooklyn, New York), better known by his stage name Busta Rhymes, is an American rapper and actor signed to Universal Motown. He began his rap career in the group Leaders of the New School, and had his breakout moment when they featured on A Tribe Called Quest\'s hit, Scenario. Busta then released his debut album, The Coming, in 1996. He has since released 1997\'s When Disaster Strikes, 1998\'s E.L.E. (Extinction Level Event): The Final World Front <a href="https://www.last.fm/music/Busta+Rhymes">Read more on Last.fm</a>', 'pais': 'United States'}, {'artista': 'Ara Ketu', 'oyentes': '78787', 'reproducciones': '676060', 'bio_resumen': 'The band Ara Ketu derived from the Carnival bloco of the same name and was founded in 1980. Before reaching success in Brazil, they became popular in Europe with an entertaining mix of Afro-Bahian percussive grooves with electronic paraphernalia and performing in colorful outfits. The group also added a vocalist (Tatau) and a horn section, counting up to 12 members. Since its beginning, the group developed a work of research on traditional African music keeping in perspective Brazilian and international pop music... <a href="https://www.last.fm/music/Ara+Ketu">Read more on Last.fm</a>', 'pais': 'Brazil'}, {'artista': 'The Specials', 'oyentes': '1109937', 'reproducciones': '19418769', 'bio_resumen': 'The Specials is an English “2 Tone” ska revival band  formed in 1977 in Coventry, Warwickshire. Their music combines a danceable ska beat with punk’s energy, underpinned by an informed political and social stance. \n\nThe group was formed by songwriter/keyboardist Jerry Dammers, with Terry Hall (vocals), Lynval Golding (guitar, vocals) and a rhythm section featuring Horace Panter (bass) and John Bradbury (drums; born 16 February 1953, died 28 December 2015). <a href="https://www.last.fm/music/The+Specials">Read more on Last.fm</a>', 'pais': ''}, {'artista': 'Mikey Dread', 'oyentes': '112886', 'reproducciones': '849205', 'bio_resumen': 'Michael Campbell (1954-2008), better known as Mikey Dread, was a multi-talented Jamaican singer, producer, and broadcaster. During his long career, he brought dub music to the cultural fore in not only Jamaica but internationally, courageously fused dub with punk via work with The Clash, spread a global message of racial unity, and played a seminal role as a forefather of the now popular and very commercial dancehall and even reggaeton styles with popular dub cuts like Roots and Culture.  <a href="https://www.last.fm/music/Mikey+Dread">Read more on Last.fm</a>', 'pais': 'Jamaica'}, {'artista': 'Slightly Stoopid', 'oyentes': '836799', 'reproducciones': '18601421', 'bio_resumen': 'While it’s a rare commodity for a band to tour as consistently as Slightly Stoopid, the group’s diligent commitment to live music provides some insight into their loyal fan base and unique creative metamorphosis throughout their extensive existence. Though it\'s been a couple of years since the release of their last studio album, Top Of The World (August 14, 2012), the Ocean Beach, California-based group—led by co-founders and multi-instrumentalists <a href="https://www.last.fm/music/Slightly+Stoopid">Read more on Last.fm</a>', 'pais': ''}, {'artista': 'Barry Biggs', 'oyentes': '48636', 'reproducciones': '234305', 'bio_resumen': 'Barry Biggs (born 1947, although some accounts list 1953;[1] St. Andrew, Jamaica) is a reggae singer, best known in the UK for his cover of the Blue Magic song, "Sideshow", which got to #3 in the UK Singles Chart in 1977\n\nBiggs worked as an recording engineer and cameraman with the Jamaican Broadcasting Company, and also spent time as a member of the band the Astronauts, before becoming the lead singer for Byron Lee\'s Dragonaires.[1][3]\nIt was at <a href="https://www.last.fm/music/Barry+Biggs">Read more on Last.fm</a>', 'pais': 'Jamaica'}, {'artista': 'New York Ska-Jazz Ensemble', 'oyentes': '76000', 'reproducciones': '1193064', 'bio_resumen': 'New York Ska-Jazz Ensemble is a group of New York ska musicians linking together ska and jazz music. \n\nMembers:\nFreddie Reiter (saxophone, flute, vocals),Mark Paquin (trombone, vocals)\nYao Dinizulu (drums), Alberto Tarin (guitar), Earl Appleton (keyboards)\n\nADDITIONAL MUSICIANS\n\nMitch Margold (keyboards),Cary Brown (keyboards), Gregg Leventhal (bass)\nLee Archibald(guitar, bass, vocals), Chris Weigers (bass)\n\nPAST MEMBERS\n\nJohnnathan McCain (drums <a href="https://www.last.fm/music/New+York+Ska-Jazz+Ensemble">Read more on Last.fm</a>', 'pais': ''}, {'artista': 'Banda Beijo', 'oyentes': '46829', 'reproducciones': '259906', 'bio_resumen': 'Banda Beijo foi uma banda brasileira de axé music. Teve sua origem no Bloco Beijo e foi formada em 1988, tendo em seu auge como vocalista o cantor Netinho, que também fazia parte do bloco, e logo após sua saída da banda, a cantora Gilmelândia.\n\nApesar de ser uma banda de Axé Music, não restringe seu repertório a tal estilo. Incluindo desde Tim Maia até The Police, saiu de seu reduto original, o carnaval baiano, e teve seu sucesso expandido por todo o Brasil. <a href="https://www.last.fm/music/Banda+Beijo">Read more on Last.fm</a>', 'pais': ''}, {'artista': 'The Jamaicans', 'oyentes': '71187', 'reproducciones': '302030', 'bio_resumen': 'The Jamaicans were a Jamaican rocksteady vocal group formed in 1967 and disbanded in 1972. Mostly known for the songs "Ba Ba Boom" (that won the Island\'s Festival Song Contest in 1967) and "Things You S

In [20]:
df_artistas_reggae_LastFm = pd.DataFrame(lista_artistas)

In [21]:
df_artistas_reggae_LastFm

,artista,oyentes,reproducciones,bio_resumen,pais
0,Natiruts,493615,16384113,Natiruts are a popular reggae band formed in B...,
1,Sidney Crooks,2041,4453,biografia no encontrada,
2,Maskavo,132327,1303007,Maskavo is a brazilian reggae band formed in 2...,Brazil
3,Justin Hinds,37386,174965,"Justin Hinds (May 7, 1942 - March 16, 2005) is...",Jamaica
4,Cordel Burrell,524,1374,biografia no encontrada,
...,...,...,...,...,...
249,Cheb Mami,79343,712599,Romanized spelling of شاب مامي (Cheb Mami).\nC...,Algeria
250,Bandits of the Acoustic Revolution,132915,1562933,Bandits of the Acoustic Revolution (commonly a...,
251,Mr Easy,15076,56365,Mr Easy is a man over-flowing with music and m...,Jamaica
252,Misty In Roots,60130,562138,"Roots reggae band formed 1975 in Southall, Lon...",
253,Jahsta,12038,112213,"a reggae band of Zaragoza <a href=""https://www...",

In [24]:
df_artistas_reggae_LastFm.to_csv("artista_reggae.csv", index=False, encoding="utf-8")